src/MetaCompilation/MetaCompilation/MetaCompilation.Test/UnitTests.cs
src/MetaCompilation/MetaCompilation/MetaCompilation/CodeFixProvider.cs

@jepetty @zoepetard @tmeschter 
Fixes #16 
Fixes #23 
Fixes #171

Refactor code fixes

---

src/MetaCompilation/MetaCompilation/MetaCompilation.Test/UnitTests.cs
src/MetaCompilation/MetaCompilation/MetaCompilation/CodeFixProvider.cs
src/MetaCompilation/MetaCompilation/MetaCompilation/DiagnosticAnalyzer.cs

Fix the code fix for an incorrect accessor return in the variable declaration form
@jepetty  @daking2014

Accessor return code fix

---

src/MetaCompilation/MetaCompilation/MetaCompilation.Test/UnitTests.cs

Fixes problems with build.
@tmeschter  @zoepetard @daking2014

Rename new variables to match new naming conventions. 

---

NewAnalyzerTemplate/NewAnalyzerTemplate/NewAnalyzerTemplate/DiagnosticAnalyzer.cs
NewAnalyzerTemplate/NewAnalyzerTemplate/NewAnalyzerTemplate/README.md

Response to Issue #230 @daking2014  @jepetty

Edit to Readme from Alex Turner's feedback

---

src/MetaCompilation/MetaCompilation/MetaCompilation.Test/UnitTests.cs
src/MetaCompilation/MetaCompilation/MetaCompilation/CodeFixProvider.cs

@jepetty @zoepetard @tmeschter 
Fixes #227

Spaces between lines

---

SyntaxNodeAnalyzer/SyntaxNodeAnalyzer/SyntaxNodeAnalyzer/DiagnosticAnalyzer.cs
src/MetaCompilation/MetaCompilation/MetaCompilation.Test/UnitTests.cs
src/MetaCompilation/MetaCompilation/MetaCompilation/CodeFixProvider.cs

Add comments to trailing trivia checks
@daking2014  @jepetty 
Fixes #234

Trailing trivia comments

---

NewAnalyzerTemplate/NewAnalyzerTemplate/NewAnalyzerTemplate/README.md
src/MetaCompilation/MetaCompilation/MetaCompilation.Test/UnitTests.cs
src/MetaCompilation/MetaCompilation/MetaCompilation/DiagnosticAnalyzer.cs
src/MetaCompilation/MetaCompilation/MetaCompilation/ReadMe.md

Fix Issue #248 
@daking2014  @jepetty

Clarify what to do after finishing tutorial

---

SyntaxNodeAnalyzer/SyntaxNodeAnalyzer/SyntaxNodeAnalyzer/DiagnosticAnalyzer.cs
src/MetaCompilation/MetaCompilation/MetaCompilation.Test/UnitTests.cs
src/MetaCompilation/MetaCompilation/MetaCompilation/CodeFixProvider.cs

New comments in Initialize and before analyze if statement
@daking2014  @jepetty

Clarify analyze if

---

src/MetaCompilation/MetaCompilation/MetaCompilation.Test/UnitTests.cs
src/MetaCompilation/MetaCompilation/MetaCompilation/CodeFixProvider.cs
src/MetaCompilation/MetaCompilation/MetaCompilation/DiagnosticAnalyzer.cs

@jepetty @zoepetard @tmeschter 
Fixes #231

Rule defaults

---

build/Scripts/PostBuild.ps1
build/Scripts/PreBuild.ps1
src/.nuget/NuGetRestore.ps1

Add pre- and post-build scripts for use in official builds.

Add build scripts

---

README.md

@zoepetard @jepetty merging because its just changing a capital letter

Fix link to instructions

---

src/AnalyzerPowerPack/Core/Usage/SerializationRulesDiagnosticAnalyzer.cs
src/AnalyzerPowerPack/Test/Usage/CA2235Tests.cs

Fixed issue 3801 in the roslyn project:
https://github.com/dotnet/roslyn/issues/3801
Moved pull request here

Issue 3801 from Roslyn project

---

build/Targets/Analyzers.Versions.targets

Update the AnalyzerPowerPack version number from 1.0.1 to 1.0.2. We
have already shipped 1.0.1.

Update AnalyzerPowerPack version number

---

src/AnalyzerPowerPack/Test/Design/CodeFixes/CA1033FixerTests.cs

Unskip a few unit tests now that the underlying issues have been fixed.
@srivatsn @mavasani @genlu Please review.

Unskip tests

---

src/Roslyn/Core/ApiDesign/DeclarePublicAPIAnalyzer.cs
src/Roslyn/Core/RoslynDiagnosticsResources.Designer.cs
src/Roslyn/Core/RoslynDiagnosticsResources.resx
src/Roslyn/Microsoft.Net.RoslynDiagnostics.md

@tmeschter @michaelcfanning @lgolding

Fix DiagnosticDescriptor of RS0024

---

src/Roslyn/Microsoft.Net.RoslynDiagnostics.md
src/Roslyn/VisualBasic/Usage/BasicUseSiteDiagnosticsCheckEnforcerAnalyzer.vb

Telemetry tag was taken as description.
@tmeschter @michaelcfanning @lgolding

Fix the DiagnosticDescriptor of RS0004

---

src/Tools/FileIssues/Program.cs
src/Tools/FileIssues/Resources.Designer.cs
src/Tools/FileIssues/Resources.resx

@srivatsn @nguerrera @michaelcfanning @mavasani - FYI, merging

Add "Area-" labels for all issues in spreadsheet

---

src/Tools/FileIssues/Program.cs

@srivatsn @nguerrera @michaelcfanning @mavasani - FYI, merging

Bug fix: Don't remove a label we just added

---

build/Targets/Analyzers.Imports.targets

Fix building if your enlistment root contains a space

---

src/Desktop.Analyzers/Core/DoNotUseInsecureCryptographicAlgorithms.cs
src/Desktop.Analyzers/Desktop.Analyzers.md
src/Microsoft.ApiDesignGuidelines.Analyzers/Microsoft.ApiDesignGuidelines.Analyzers.md
src/Microsoft.Maintainability.Analyzers/Microsoft.Maintainability.Analyzers.md
src/Microsoft.QualityGuidelines.Analyzers/Microsoft.QualityGuidelines.Analyzers.md
src/System.Runtime.Analyzers/System.Runtime.Analyzers.md

Also update the markdown files of package description. This fixes #733 
@rigotek @srivatsn @mavasani

Add helper link to CA5350 and CA5351

---

Porting FxCop Rules to Roslyn.md

@michaelcfanning @srivatsn @nguerrera @bricelam

Address feedback from @michaelcfanning

---

src/Microsoft.ApiDesignGuidelines.Analyzers/Core/OperatorOverloadsHaveNamedAlternates.Fixer.cs

Addresses feedback from #772.
Tagging @heejaechang

make task running better and use the correct cancellation token

---

src/Microsoft.ApiDesignGuidelines.Analyzers/CSharp/CSharpImplementStandardExceptionConstructors.cs
src/Microsoft.ApiDesignGuidelines.Analyzers/Core/ImplementStandardExceptionConstructors.cs
src/Microsoft.ApiDesignGuidelines.Analyzers/UnitTests/ImplementStandardExceptionConstructorsTests.cs
src/Microsoft.ApiDesignGuidelines.Analyzers/VisualBasic/BasicImplementStandardExceptionConstructors.vb

Complete Analyzer. Will do Fixer tomorrow

Ported analyzer for CA1032: Implement standard exception constructors

---

src/Microsoft.ApiDesignGuidelines.Analyzers/Core/OverrideEqualsAndOperatorEqualsOnValueTypes.cs
src/System.Runtime.Analyzers/Core/DisposableTypesShouldDeclareFinalizer.cs

These are the two rules I implemented over the last few days. Per our discussion yesterday, rules are enabled by default as we implement them.
@srivatsn @nguerrera @michaelcfanning @genlu @heejaechang

CA1815, CA2216: isEnabledByDefault = true

---

src/Desktop.Analyzers/UnitTests/MarkAllNonSerializableFieldsTests.cs

CA2235: Create skipped unit test demonstrating roslyn/3898

---

src/Microsoft.Maintainability.Analyzers/UnitTests/ReviewUnusedParametersTests.cs

See https://github.com/dotnet/roslyn/issues/8884
@dotnet/roslyn-analysis

Add skipped test for Roslyn IOperation bug

---

src/Microsoft.Maintainability.Analyzers/UnitTests/ReviewUnusedParametersTests.cs

See https://github.com/dotnet/roslyn/issues/8884#issuecomment-185982523
@dotnet/roslyn-analysis

Add more skipped tests for https://github.com/dotnet/roslyn/issues/8884

---

src/Desktop.Analyzers/Desktop.Analyzers.md
src/Microsoft.ApiDesignGuidelines.Analyzers/Microsoft.ApiDesignGuidelines.Analyzers.md
src/Microsoft.Maintainability.Analyzers/Microsoft.Maintainability.Analyzers.md
src/Microsoft.QualityGuidelines.Analyzers/Microsoft.QualityGuidelines.Analyzers.md
src/Roslyn.Diagnostics.Analyzers/Roslyn.Diagnostics.Analyzers.md
src/System.Resources.Analyzers/System.Resources.Analyzers.md
src/System.Runtime.Analyzers/System.Runtime.Analyzers.md

Update mark down files for rule description

---

README.md

Update badges to new job locations

---

src/Microsoft.ApiDesignGuidelines.Analyzers/CSharp/CSharpEnumStorageShouldBeInt32.Fixer.cs
src/Microsoft.ApiDesignGuidelines.Analyzers/Core/EnumStorageShouldBeInt32.Fixer.cs
src/Microsoft.ApiDesignGuidelines.Analyzers/UnitTests/EnumStorageShouldBeInt32Tests.Fixer.cs
src/Microsoft.ApiDesignGuidelines.Analyzers/VisualBasic/BasicEnumStorageShouldBeInt32.Fixer.vb

CA1028: EnumStorageShouldBeInt32 Fixer

---

src/Test/Utilities/DiagnosticAnalyzerTestBase.cs

This is a follow-up to address some PR #891 comments
@dotnet/roslyn-analysis Could someone review this please?

Address PR refactoring

---

src/System.Runtime.Analyzers/Core/AvoidZeroLengthArrayAllocations.cs
src/System.Runtime.Analyzers/UnitTests/AvoidZeroLengthArrayAllocationsTests.cs

See https://github.com/dotnet/roslyn/issues/10214 for more context.

Apply a workaround in CA1825 for bailing out on compiler generated code

---

src/System.Runtime.Analyzers/Core/SpecifyCultureInfo.cs
src/System.Runtime.Analyzers/Core/SpecifyIFormatProvider.cs
src/System.Runtime.Analyzers/Core/SystemRuntimeAnalyzersResources.Designer.cs
src/System.Runtime.Analyzers/Core/SystemRuntimeAnalyzersResources.resx
src/System.Runtime.Analyzers/UnitTests/SpecifyCultureInfoTests.cs

Change the diagnostic message for CA1035 and cover some corner cases in
CA1304
Tagging @dotnet/roslyn-analysis for review

Cleanup CA1305 CA1304

---

src/Microsoft.QualityGuidelines.Analyzers/Core/MarkMembersAsStatic.cs

* Replaced `\` by `/`
* Relocated comment about CA1000 to the statement it applies to

Corrections in comments

---

src/Analyzer.Utilities/Extensions/IMethodSymbolExtensions.cs
src/Microsoft.ApiDesignGuidelines.Analyzers/Core/IdentifiersShouldNotContainUnderscores.cs
src/Microsoft.ApiDesignGuidelines.Analyzers/UnitTests/IdentifiersShouldNotContainUnderscoresTests.cs

Fix IdentifiersShouldNotContainUnderscores (CA1707) reports on operators

---

src/.nuget/NuGetRestore.ps1

Fix NugetRestore.ps1 to not look for packages.config

---

cibuild.cmd

Also replace the fixed path to VS Cmd prompt to Environment variable
Tagging @dotnet/roslyn-analysis  @srivatsn @mavasani @heejaechang  for review

Turn echo off  partially

---

src/Desktop.Analyzers/Core/ImplementSerializationConstructors.Fixer.cs
src/Microsoft.ApiDesignGuidelines.Analyzers/Core/UriParametersShouldNotBeStrings.Fixer.cs

Replaces usages of Generator.DottedName with Generator.TypeExpression

---

src/System.Runtime.Analyzers/Core/ProvideCorrectArgumentsToFormattingMethods.cs

Replaced TODO with comment

---

src/Microsoft.ApiDesignGuidelines.Analyzers/Core/IdentifiersShouldNotMatchKeywords.cs

This fixes #1012.
After eliminating the race condition, https://github.com/dotnet/roslyn-analyzers/blob/master/src/Microsoft.ApiDesignGuidelines.Analyzers/UnitTests/IdentifiersShouldNotMatchKeywordsNamespaceRuleTests.cs#L101 started to fail. This test expects unique warnings based on the combination of namespace and keyword. But the `HashSet` only tracked namespaces, so it reported once instead of twice.
To solve this, I've changed the `HashSet` to store the combination of namespace and keyword.

CA1716: Fixes race condition in reporting namespace warnings

---

src/System.Runtime.Analyzers/Core/AvoidZeroLengthArrayAllocations.cs

The IArgument.ArgumentKind property is going to be removed, so this analyzer cannot continue to refer to it.
As a side effect, this change set fixes a bug--the last argument local was being tested against null after it was dereferenced.
@dotnet/roslyn-analysis @srivatsn @mavasani @genlu

Avoid use of to-be-removed IArgument.ArgumentKind property.

---

src/Microsoft.ApiDesignGuidelines.Analyzers/UnitTests/ImplementIDisposableCorrectlyTests.cs

Fixing errors in #1011. Hopefully this time I got them all.

Fix compile errors in test input VB code for CA1063 ImplementDisposableCorrectly tests

---

src/Microsoft.QualityGuidelines.Analyzers/UnitTests/UseLiteralsWhereAppropriateTests.cs

Fixes compile error in test

---

src/Microsoft.ApiDesignGuidelines.Analyzers/UnitTests/EnumsShouldHaveZeroValueTests.Fixer.cs
src/Microsoft.ApiDesignGuidelines.Analyzers/UnitTests/EnumsShouldHaveZeroValueTests.cs

Fixed broken code

---

src/Microsoft.QualityGuidelines.Analyzers/UnitTests/RethrowToPreserveStackDetailsTests.cs

* Renamed tests to make their purpose easier to understand
* Merged separate test sets for CS/VB into single tests that contain both languages
* Re-enabled skipped test with compile errors
Fixes #1016.

Cleanup tests for CA2200 (RethrowToPreserveStackDetails)

---

src/Microsoft.ApiDesignGuidelines.Analyzers/Core/DefineAccessorsForAttributeArguments.Fixer.cs
src/Microsoft.ApiDesignGuidelines.Analyzers/UnitTests/DefineAccessorsForAttributeArgumentsTests.Fixer.cs

Generate throwing getter instead of auto-property for non-auto setter

---

src/System.Runtime.Analyzers/CSharp/CSharpTestForNaNCorrectly.Fixer.cs
src/System.Runtime.Analyzers/Core/TestForNaNCorrectly.Fixer.cs
src/System.Runtime.Analyzers/UnitTests/TestForNaNCorrectlyTests.Fixer.cs
src/System.Runtime.Analyzers/UnitTests/TestForNaNCorrectlyTests.cs
src/System.Runtime.Analyzers/VisualBasic/BasicTestForNaNCorrectly.Fixer.vb

CodeFixProvider for CA2242

---

src/Desktop.Analyzers/Core/DoNotUseInsecureDtdProcessing.cs
src/Desktop.Analyzers/UnitTests/DoNotUseInsecureDtdProcessingXmlTextReaderConstructedWithNoSecureResolutionTests.cs

Fix: NRE on static properties

---

src/.nuget/NuGet.Config
src/ApiReview.Analyzers/Setup/source.extension.vsixmanifest
src/Desktop.Analyzers/Setup/source.extension.vsixmanifest
src/MetaCompilation.Analyzers/Setup/source.extension.vsixmanifest
src/Microsoft.ApiDesignGuidelines.Analyzers/Setup/source.extension.vsixmanifest
src/Microsoft.CodeAnalysis.Analyzers/Setup/source.extension.vsixmanifest
src/Microsoft.Composition.Analyzers/Setup/source.extension.vsixmanifest
src/Microsoft.Maintainability.Analyzers/Setup/source.extension.vsixmanifest
src/Microsoft.QualityGuidelines.Analyzers/Setup/source.extension.vsixmanifest
src/Roslyn.Diagnostics.Analyzers/Setup/source.extension.vsixmanifest
src/System.Collections.Immutable.Analyzers/Setup/source.extension.vsixmanifest
src/System.Resources.Analyzers/Setup/source.extension.vsixmanifest
src/System.Runtime.Analyzers/Setup/source.extension.vsixmanifest
src/System.Runtime.InteropServices.Analyzers/Setup/source.extension.vsixmanifest
src/System.Security.Cryptography.Hashing.Algorithms.Analyzers/Setup/source.extension.vsixmanifest
src/System.Threading.Tasks.Analyzers/Setup/source.extension.vsixmanifest
src/Text.Analyzers/Setup/source.extension.vsixmanifest
src/XmlDocumentationComments.Analyzers/Setup/source.extension.vsixmanifest

Done as part of E2E day assessment work item [371916](https://devdiv.visualstudio.com/DevDiv/_workitems?id=371916)

Move the repo forward to VSIX V3 extension format

---

src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/PropertyNamesShouldNotMatchGetMethods.cs
src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/PropertyNamesShouldNotMatchGetMethodsTests.cs

Did a decent amount of refactoring as well. What's the deal with the bad unit test names?

Fix #1088 CA1721 does not consider method/property accessibility

---

src/Microsoft.NetCore.Analyzers/Core/System.Runtime.Analyzers/ProvideCorrectArgumentsToFormattingMethods.cs
src/Microsoft.NetCore.Analyzers/UnitTests/System.Runtime.Analyzers/ProvideCorrectArgumentsToFormattingMethodsTests.cs

Count unique placeholder numbers, rather than just the number of placeholders
This resolves issue #1109

Improve CA2241 format string placeholder counting

---

BuildAndTest.proj
README.md
RoslynAnalyzers.sln
src/MetaCompilation.Analyzers/Core/ReadMe.md

Move solution file to the repo root

---

src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/MarkAttributesWithAttributeUsageTests.cs

Fixes #1161. Tagging @dotnet/roslyn-analysis @sharwell for review.

Added missing tests to ca1018

---

src/Microsoft.CodeQuality.Analyzers/CSharp/QualityGuidelines/CSharpUseLiteralsWhereAppropriate.Fixer.cs
src/Microsoft.CodeQuality.Analyzers/Core/QualityGuidelines/MicrosoftQualityGuidelinesAnalyzersResources.Designer.cs
src/Microsoft.CodeQuality.Analyzers/Core/QualityGuidelines/MicrosoftQualityGuidelinesAnalyzersResources.resx
src/Microsoft.CodeQuality.Analyzers/Core/QualityGuidelines/UseLiteralsWhereAppropriate.Fixer.cs
src/Microsoft.CodeQuality.Analyzers/Core/QualityGuidelines/UseLiteralsWhereAppropriate.cs
src/Microsoft.CodeQuality.Analyzers/UnitTests/QualityGuidelines/UseLiteralsWhereAppropriateTests.Fixer.cs
src/Microsoft.CodeQuality.Analyzers/UnitTests/QualityGuidelines/UseLiteralsWhereAppropriateTests.cs
src/Microsoft.CodeQuality.Analyzers/VisualBasic/QualityGuidelines/BasicUseLiteralsWhereAppropriate.Fixer.vb

Fixer for CA1802: UseLiteralsWhereAppropriate

---

src/Microsoft.CodeAnalysis.Analyzers/UnitTests/InternalImplementationOnlyTests.cs

Added tests to prevent implementing IOperation

---

RoslynAnalyzers.sln

Put CPS guid in sln to bypass selector

---

src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/AvoidUninstantiatedInternalClasses.cs
src/Microsoft.CodeQuality.Analyzers/UnitTests/Maintainability/AvoidUninstantiatedInternalClassesTests.cs

Tagging @mavasani @dotnet/roslyn-analysis for review. Fixes #1154.

Fixed ca1812 to work for generic classes.

---

src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/TypeNamesShouldNotMatchNamespaces.cs

Revert generated code analysis workaround

---

RoslynAnalyzers.sln
src/FxCopAnalyzersSetup/FxCopAnalyzersSetup/FxCopAnalyzersSetup.csproj
src/FxCopAnalyzersSetup/FxCopAnalyzersSetup/Properties/launchSettings.json
src/FxCopAnalyzersSetup/FxCopAnalyzersSetup/source.extension.vsixmanifest
src/Microsoft.NetCore.Analyzers/Setup/source.extension.vsixmanifest

This is essentially a packaging VSIX which contains the underlying VSIXes for different analyzer packages.

Add a new VSIX project for Microsoft.CodeAnalysis.FxCopAnalyzers

---

build/Targets/Versions.props

@jinujoseph @mavasani  for review.

Fixed analyzer dependency version

---

netci.groovy

Need to change this first to update Jenkins.

Update netci.groovy to new infra

---

netci.groovy

Tagging @dotnet/roslyn-analysis @tmat for review.

Update archive settings to only archive on failure

---

src/Common/Test/App.config
src/Directory.Build.props

Another attempt to fix microbuild, previous was not successful.

Use app.config to configure tests instead of .json

---

src/Directory.Build.props

Always OSS sign

---

build/build.ps1
src/Analyzer.Utilities/Extensions/IOperationExtensions.cs
src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/PassSystemUriObjectsInsteadOfStrings.cs
src/Microsoft.NetCore.Analyzers/Core/ImmutableCollections/DoNotCallToImmutableArrayOnAnImmutableArrayValue.cs
src/Microsoft.NetCore.Analyzers/Core/Runtime/NormalizeStringsToUppercase.cs
src/Microsoft.NetCore.Analyzers/Core/Tasks/DoNotCreateTasksWithoutPassingATaskScheduler.cs

Tagging @dotnet/roslyn-analysis. Fixes https://github.com/dotnet/roslyn-analyzers/issues/1272.

Removed use of IsInvalid for performance optimization.

---

src/Analyzer.Utilities/Extensions/IOperationExtensions.cs
src/Microsoft.NetCore.Analyzers/Core/Runtime/AvoidZeroLengthArrayAllocations.cs
src/Microsoft.NetCore.Analyzers/Core/Runtime/ProvideCorrectArgumentsToFormattingMethods.cs
src/Microsoft.NetCore.Analyzers/Core/Runtime/TestForNaNCorrectly.cs

Analyzer changes for removed API IArrayCreationExpression.ElementType

---

src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/IdentifiersShouldNotContainUnderscores.cs
src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/IdentifiersShouldNotContainUnderscoresTests.cs

Fixes https://github.com/dotnet/roslyn-analyzers/issues/1319
CC: @kentcb

False positive on custom operator 

---

src/Microsoft.NetFramework.Analyzers/Core/SerializationRulesDiagnosticAnalyzer.cs
src/Microsoft.NetFramework.Analyzers/UnitTests/MarkISerializableTypesWithSerializableTests.cs

Bail out early for delegates and interfaces in serialization analyzer

---

README.md
src/Microsoft.CodeQuality.Analyzers/Microsoft.CodeQuality.Analyzers.md

Also update the hyperlink in the repo's README.md.
Fixes #1285

Add back Microsoft.CodeQuality.Analyzers.md

---

build/SignToolData.json
build/Versions.props
src/Directory.Build.targets

Fixes the VSIX deployment among other changes.

RepoToolset 57

---

src/Analyzer.Utilities/Extensions/IOperationExtensions.cs
src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/InterfaceMethodsShouldBeCallableByChildTypes.Fixer.cs
src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/InterfaceMethodsShouldBeCallableByChildTypes.cs
src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/InterfaceMethodsShouldBeCallableByChildTypesTests.Fixer.cs
src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/InterfaceMethodsShouldBeCallableByChildTypesTests.cs

Reenabled all tests pertaining to CA1033. Also fixed a few bugs revealed by these skipped tests. Fixes #1008.

Reenabled skipped CA1033 Tests

---

src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/PropertyNamesShouldNotMatchGetMethods.cs
src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/PropertyNamesShouldNotMatchGetMethodsTests.cs

Ignore GetType in CA1721 checks.

---

src/Analyzer.Utilities/Extensions/IMethodSymbolExtensions.cs
src/Microsoft.NetCore.Analyzers/UnitTests/Runtime/CallGCSuppressFinalizeCorrectlyTests.cs

Fix issues with explicitly implementing IDisposable.Dispose.

---

src/Microsoft.CodeAnalysis.Analyzers/Core/FixAnalyzers/FixerWithFixAllAnalyzer.cs

RS1011 now accounts for base code action types defined in different compilation. Writing a unit test for this case is blocked due to #1416, but I have verified it manually.
Fixes #1413

Handle another case for RS1011 false report

---

src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/ImplementIDisposableCorrectly.cs
src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/ReviewUnusedParameters.cs
src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/ImplementIDisposableCorrectlyTests.cs
src/Microsoft.CodeQuality.Analyzers/UnitTests/Maintainability/ReviewUnusedParametersTests.cs
src/Utilities/Extensions/IOperationExtensions.cs

Handle attribute operation blocks in operation block analyzers

---

docs/FxCopPort/Proposed FxCop rule changes in Roslyn.md

Additional arguments for ruling reversal

Update Proposed FxCop rule changes in Roslyn.md

---

src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/IdentifiersShouldNotContainUnderscoresTests.cs
src/Microsoft.CodeQuality.Analyzers/UnitTests/Maintainability/AvoidUninstantiatedInternalClassesTests.cs
src/Roslyn.Diagnostics.Analyzers/UnitTests/DeclarePublicAPIAnalyzerTests.cs
src/Test.Utilities/DiagnosticAnalyzerTestBase.cs

Fix and unskip tests blocked by #881

---

Directory.Build.props
build/Toolset.proj
build/Versions.props
build/build.ps1

Update RepoToolset to 1.0.0-beta-62412-03

---

src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/CollectionPropertiesShouldBeReadOnly.cs
src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/MicrosoftApiDesignGuidelinesAnalyzersResources.resx
src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.cs.xlf
src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.de.xlf
src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.es.xlf
src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.fr.xlf
src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.it.xlf
src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.ja.xlf
src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.ko.xlf
src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.pl.xlf
src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.pt-BR.xlf
src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.ru.xlf
src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.tr.xlf
src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.zh-Hans.xlf
src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.zh-Hant.xlf
src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/CollectionPropertiesShouldBeReadOnlyTests.cs

Change analyzer message for CA2227

---

src/Microsoft.CodeQuality.Analyzers/UnitTests/Maintainability/AvoidUnusedPrivateFieldsTests.Fixer.cs
src/Test.Utilities/CodeFixRunner.cs
src/Test.Utilities/CodeFixTestBase.cs
src/Test.Utilities/CodeFixTests.Extensions.cs
src/Test.Utilities/DiagnosticAnalyzerTestBase.cs
src/Utilities/Analyzer.Utilities.projitems
src/Utilities/SolutionChangeAction.cs

Need to support tests for #459

Extend test infrastructure to support multiple test files

---

src/Microsoft.NetCore.Analyzers/Core/Runtime/TestForEmptyStringsUsingStringLength.cs
src/Microsoft.NetCore.Analyzers/UnitTests/Runtime/TestForEmptyStringsUsingStringLengthTests.cs

Fixes https://github.com/dotnet/roslyn-analyzers/issues/1081.

Remove binary operation analysis from CA1309.

---

src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/DoNotIgnoreMethodResults.cs
src/Microsoft.CodeQuality.Analyzers/UnitTests/Maintainability/DoNotIgnoreMethodResultsTests.cs
src/Microsoft.NetCore.Analyzers/UnitTests/ImmutableCollections/DoNotCallToImmutableCollectionOnAnImmutableCollectionValueTests.cs
src/Test.Utilities/MinimalImplementations/ImmutableCollectionsSource.cs
src/Test.Utilities/MinimalImplementations/MSTestExpectedExceptionAttribute.cs
src/Test.Utilities/MinimalImplementations/NUnitAssert.cs
src/Test.Utilities/MinimalImplementations/XunitAssert.cs
src/Utilities/Extensions/IOperationExtensions.cs
src/Utilities/WellKnownTypes.cs

Fixes https://github.com/dotnet/roslyn-analyzers/issues/1369.

Skip lambda arguments for Throws variants in CA1806

---

src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/MicrosoftApiDesignGuidelinesAnalyzersResources.resx
src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/OverrideMethodsOnComparableTypes.cs
src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.cs.xlf
src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.de.xlf
src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.es.xlf
src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.fr.xlf
src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.it.xlf
src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.ja.xlf
src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.ko.xlf
src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.pl.xlf
src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.pt-BR.xlf
src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.ru.xlf
src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.tr.xlf
src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.zh-Hans.xlf
src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.zh-Hant.xlf
src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/OverrideMethodsOnComparableTypesTests.cs

Fixes https://github.com/dotnet/roslyn-analyzers/issues/1396. Tagging @mavasani @ivanbasov for review.

Update CA1036 messaging.

---

build/Versions.props

Sets algorithm used to calculate source file checksums stored in PDB to SHA256.

Update RepoToolset to 1.0.0-beta-62614-04

---

src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Analysis/DisposeAnalysis/DisposeAnalysis.DisposeDataFlowOperationVisitor.cs
src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAnalysis.PointsToDataFlowOperationVisitor.cs
src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Framework/DataFlow/AnalysisEntityFactory.cs
src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs
src/Microsoft.CodeQuality.Analyzers.Exp/Core/Security/ReviewSqlQueriesForSecurityVulnerabilities.cs
src/Microsoft.CodeQuality.Analyzers.Exp/UnitTests/Reliability/DisposeObjectsBeforeLosingScopeTests.cs
src/Microsoft.CodeQuality.Analyzers.Exp/UnitTests/Security/ReviewSQLQueriesForSecurityVulnerabilitiesTests.cs
src/Test.Utilities/DiagnosticAnalyzerTestBase.cs

1. Fix NRE in ReviewSQLQueriesForSecurityVulnerabilities while computing well known types.
2. Fix NRE in PointsToDataFlowOperationVisitor for null type for an IMethodReferenceOperation

Fix couple of NREs in newly added rules

---

build/Analyzers_NonShippingRules.ruleset
src/MetaCompilation.Analyzers/Core/CodeFixProvider.cs
src/MetaCompilation.Analyzers/Core/DiagnosticAnalyzer.cs
src/Test.Utilities/CodeFixTestBase.cs

 Fix violations of CA1801 (Review unused parameters)

---

build/build.ps1

Fixes a failure to download vswhere from GitHub

Update the build script to use TLS 1.2

---

src/Microsoft.CodeQuality.Analyzers.Exp/Core/Security/ReviewSqlQueriesForSecurityVulnerabilities.cs
src/Microsoft.CodeQuality.Analyzers.Exp/UnitTests/Security/ReviewSQLQueriesForSecurityVulnerabilitiesTests.cs
src/Utilities/Extensions/ISymbolExtensions.cs

Ensure that we also check for overrides of IDbCommand.CommandText

---

netci.groovy

This is a prerequisite for #1614.

Add CODECOV_TOKEN to the build definition

---

src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/DoNotDeclareVisibleInstanceFields.cs
src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/DoNotDeclareVisibleInstanceFieldsTests.cs

Trigger CA1051 for protected and protected internal/friend fields from DoNotDeclareVisibleInstanceFieldsAnalyzer.  Addresses #919.

Trigger CA1051 for protected fields.

---

src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/EnumWithFlagsAttribute.cs
src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/EnumWithFlagsAttributeTests.Fixer.cs
src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/EnumWithFlagsAttributeTests.cs

Fixed false positives of CA2217, enum values don't have to be there.

---

src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/OverrideMethodsOnComparableTypes.cs
src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/OverrideMethodsOnComparableTypesTests.cs

Fixes #1671
This change matches the FxCop behavior

Do not report CA1036 on sub-types of comparable types

---

RoslynAnalyzers.sln
src/Tools/Metrics.csproj
src/Tools/MetricsOutputWriter.cs
src/Tools/Program.cs

Addresses part of #1741
Addresses VSFeedback requests to port this tool:
1. https://developercommunity.visualstudio.com/content/problem/142328/code-metrics-powertool-missing-for-vs2017.html
2. https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/33459643--netcore-code-metrics
Note that majority of the options and report format have been ported from the old binary analysis based Metrics.exe that shipped from VS2010 to VS2015. Old tool worked on assemblies, while this one uses source based code metrics computation.
**TODO:** ~~File an issue to add unit tests for this console application.~~ https://github.com/dotnet/roslyn-analyzers/issues/1755
**Testing:** Manual verification has been done on RoslynAnalyzers.sln.
Example:
**Source:**
```
using System;
namespace …
```

Add console app Metrics.exe to generate code metrics report

---

src/Microsoft.CodeAnalysis.Analyzers/CSharp/MetaAnalyzers/CSharpReportDiagnosticAnalyzer.cs
src/Microsoft.CodeAnalysis.Analyzers/UnitTests/MetaAnalyzers/InvalidReportDiagnosticRuleTests.cs
src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/IdentifiersShouldNotMatchKeywords.cs
src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/IdentifiersShouldNotMatchKeywordsNamespaceRuleTests.cs

Handle property initializers in RS1005

---

src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/DoNotHideBaseClassMethods.Fixer.cs

Fix not implemented exception from DoNotHideBaseClassMethods.Fixer

---

src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/IdentifiersShouldNotMatchKeywords.cs
src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/IdentifiersShouldNotMatchKeywordsNamespaceRuleTests.cs

Report CA1716 for namespaces with namespace location

---

src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/DiagnosticAnalyzerAPIUsageAnalyzer.cs
src/Microsoft.CodeAnalysis.Analyzers/UnitTests/MetaAnalyzers/DiagnosticAnalyzerApiUsageAnalyzerTests.cs

Handle error type arguments in DiagnosticAnalyzerAPIUsageAnalyzer

---

src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/AvoidDeadConditionalCode.cs
src/Microsoft.CodeQuality.Analyzers/UnitTests/Maintainability/AvoidDeadConditionalCode_NullAnalysis.cs
src/Microsoft.CodeQuality.Analyzers/UnitTests/Maintainability/AvoidDeadConditionalCode_StringContentAnalysis.cs
src/Utilities/Extensions/IOperationExtensions.cs
src/Utilities/FlowAnalysis/Analysis/CopyAnalysis/CopyAnalysis.CopyDataFlowOperationVisitor.cs
src/Utilities/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAnalysis.CorePointsToAnalysisDataDomain.cs
src/Utilities/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAnalysis.PointsToDataFlowOperationVisitor.cs
src/Utilities/FlowAnalysis/Framework/DataFlow/DataFlowAnalysis.cs
src/Utilities/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs
src/Utilities/WellKnownTypeProvider.cs
src/Utilities/WellKnownTypes.cs

Fixes #1650
While fixing this I ran into other bugs related to flow analysis, which have been fixed as well.

Enable flow analysis based rules for non-method body executable code

---

src/Microsoft.NetFramework.Analyzers/Core/MarkVerbHandlersWithValidateAntiforgeryTokenAnalyzer.cs
src/Microsoft.NetFramework.Analyzers/UnitTests/Security/MarkVerbHandlersWithValidateAntiforgeryTokenTests.cs

and unit test for documentation samples.

Help link for CA3147

---

global.json

Arcade 18476.3

---

src/Microsoft.CodeQuality.Analyzers/UnitTests/QualityGuidelines/ValidateArgumentsOfPublicMethodsTests.cs
src/Test.Utilities/DiagnosticAnalyzerTestBase.cs
src/Utilities/FlowAnalysis/Analysis/CopyAnalysis/CopyAnalysisData.cs
src/Utilities/FlowAnalysis/Analysis/PointsToAnalysis/DefaultPointsToValueGenerator.cs
src/Utilities/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAnalysis.PointsToDataFlowOperationVisitor.cs
src/Utilities/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAnalysis.cs
src/Utilities/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAnalysisData.cs
src/Utilities/FlowAnalysis/Analysis/PointsToAnalysis/PointsToBlockAnalysisResult.cs
src/Utilities/FlowAnalysis/Analysis/ValueContentAnalysis/ValueContentAnalysis.ValueContentDataFlowOperationVisitor.cs
src/Utilities/FlowAnalysis/Framework/DataFlow/AnalysisEntityBasedPredicateAnalysisData.cs
src/Utilities/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs

Fix assert for interprocedural PointsToAnalysis and add more asserts

---

src/Roslyn.Diagnostics.Analyzers/Core/SymbolDeclaredEventMustBeGeneratedForSourceSymbols.cs

We might end up not finding some expected symbols for broken compilation.
Fixes VSO [729456](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/729456)

Relax the assert in the analyzer for error cases

---

src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/DoNotHideBaseClassMethods.cs
src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/DoNotHideBaseClassMethodsTests.cs

CA1061 shouldn't apply to contructors

---

src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/CancellationTokenParametersMustComeLast.cs
src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/CancellationTokenParametersMustComeLastTests.cs

CA1068 permits multiple CancellationToken at end of parameter list

---

src/Roslyn.Diagnostics.Analyzers/Core/SymbolIsBannedAnalyzer.cs

Compilation end actions are not invoked unless FSA is enabled, for performance reasons.
Without this change, users may see diagnostics from compilation that then disappear in the IDE's editor.
Follows #1781.
See also dotnet/roslyn#11750, dotnet/roslyn#27094.
Thanks @mavasani for help in diagnosing the cause of this problem.

Refactor banned API to not use compilation end action

---

src/Microsoft.NetCore.Analyzers/Core/Security/MicrosoftNetCoreSecurityResources.resx
src/Microsoft.NetCore.Analyzers/Core/Security/ReviewCodeForInformationDisclosureVulnerabilities.cs
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.cs.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.de.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.es.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.fr.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.it.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.ja.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.ko.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.pl.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.pt-BR.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.ru.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.tr.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.zh-Hans.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.zh-Hant.xlf
src/Microsoft.NetCore.Analyzers/UnitTests/Security/ReviewCodeForInformationDisclosureVulnerabilitiesTests.cs
src/Utilities/Analyzer.Utilities.projitems
src/Utilities/Extensions/ImmutableHashSetBuilderExtensions.cs
src/Utilities/FlowAnalysis/Analysis/TaintedDataAnalysis/DllSinks.cs
src/Utilities/FlowAnalysis/Analysis/TaintedDataAnalysis/InformationDisclosureSources.cs
src/Utilities/FlowAnalysis/Analysis/TaintedDataAnalysis/SinkInfo.cs
src/Utilities/FlowAnalysis/Analysis/TaintedDataAnalysis/SinkKind.cs
src/Utilities/FlowAnalysis/Analysis/TaintedDataAnalysis/SqlSinks.cs
src/Utilities/FlowAnalysis/Analysis/TaintedDataAnalysis/TaintedDataAnalysis.TaintedDataOperationVisitor.cs
src/Utilities/FlowAnalysis/Analysis/TaintedDataAnalysis/TaintedDataConfig.cs
src/Utilities/FlowAnalysis/Analysis/TaintedDataAnalysis/WebInputSources.cs
src/Utilities/FlowAnalysis/Analysis/TaintedDataAnalysis/WebOutputSinks.cs
src/Utilities/WellKnownTypes.cs

- Now SinkInfos can be for multiple SinkKinds
- Hard coded sources and sinks (from FxCop, minus the enum value sinks) for information disclosure
- Smoke tests for tainted data DFA information disclosure

Information disclosure tainted data DFA

---

src/Microsoft.CodeQuality.Analyzers/UnitTests/QualityGuidelines/ValidateArgumentsOfPublicMethodsTests.cs
src/Utilities/Extensions/IOperationExtensions.cs
src/Utilities/Extensions/ISymbolExtensions.cs

Fix an incorrect assert when comparing lambda methods

---

src/Microsoft.CodeQuality.Analyzers/CSharp/QualityGuidelines/CSharpRemoveEmptyFinalizersAnalyzer.cs
src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/ImplementIDisposableCorrectly.cs
src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/ImplementIDisposableCorrectlyTests.cs
src/Microsoft.CodeQuality.Analyzers/UnitTests/QualityGuidelines/RemoveEmptyFinalizersTests.cs

Fix CA1063 and CA1821 to handle expression bodied finalizers

---

src/Microsoft.NetFramework.Analyzers/Core/SerializationRulesDiagnosticAnalyzer.cs
src/Microsoft.NetFramework.Analyzers/UnitTests/MarkAllNonSerializableFieldsTests.cs

Fixes #1970 
I verified the test failed for both languages before implementing the fix.

Prevent CA2235 when type implements ISerializable

---

THIRD-PARTY-NOTICES.txt
eng/Versions.props
src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/EnumsShouldHavePluralNames.cs
src/Microsoft.CodeQuality.Analyzers/Core/Microsoft.CodeQuality.Analyzers.csproj
src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/EnumsShouldHavePluralNamesTests.cs
src/Test.Utilities/Test.Utilities.csproj
src/Utilities/Extensions/StringExtensions.cs

Fixes #1323
Fixes #950
~~TODO: Pending approval to consume humanizer~~ Confirmed we have approval for version 2.2.0 of Humanizer and also added Third Party Notices document.

Use humanizer for plural word detection in CA1714 and CA1717

---

src/Microsoft.NetCore.Analyzers/Core/Security/MicrosoftNetCoreSecurityResources.resx
src/Microsoft.NetCore.Analyzers/Core/Security/ReviewCodeForFilePathInjectionVulnerabilities.cs
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.cs.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.de.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.es.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.fr.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.it.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.ja.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.ko.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.pl.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.pt-BR.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.ru.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.tr.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.zh-Hans.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.zh-Hant.xlf
src/Microsoft.NetCore.Analyzers/UnitTests/Security/ReviewCodeForFileCanonicalizationVulnerabilitiesTests.cs
src/Utilities/Analyzer.Utilities.projitems
src/Utilities/FlowAnalysis/Analysis/TaintedDataAnalysis/FilePathInjectionSinks.cs
src/Utilities/FlowAnalysis/Analysis/TaintedDataAnalysis/SinkKind.cs
src/Utilities/FlowAnalysis/Analysis/TaintedDataAnalysis/TaintedDataConfig.cs
src/Utilities/WellKnownTypes.cs

- Tainted sinks hardcoded from FxCop.
- Fixed a bug in TaintedDataConfig.
- Smoke tests for file path injection.

File path injection tainted data DFA

---

docs/Analyzer Configuration.md
src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/DoNotDirectlyAwaitATask.cs
src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/AvoidEmptyInterfacesTests.cs
src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/DoNotDirectlyAwaitATaskTests.cs
src/Test.Utilities/DiagnosticAnalyzerTestBase.cs
src/Utilities/Analyzer.Utilities.projitems
src/Utilities/Options/AnalyzerOptionsExtensions.cs
src/Utilities/Options/CategorizedAnalyzerConfigOptions.cs
src/Utilities/Options/EditorConfigOptionNames.cs

Add editorconfig based configuration for CA2007 (DoNotDirectlyAwaitATask)

---

src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/DoNotDirectlyAwaitATask.Fixer.cs
src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/MicrosoftApiDesignGuidelinesAnalyzersResources.resx
src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.cs.xlf
src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.de.xlf
src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.es.xlf
src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.fr.xlf
src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.it.xlf
src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.ja.xlf
src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.ko.xlf
src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.pl.xlf
src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.pt-BR.xlf
src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.ru.xlf
src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.tr.xlf
src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.zh-Hans.xlf
src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.zh-Hant.xlf
src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/DoNotDirectlyAwaitATaskTests.Fixer.cs

Code fix to Append .ConfigureAwait(true) for CA2007

---

src/Microsoft.NetCore.Analyzers/Core/Security/DoNotUseInsecureDeserializerBinaryFormatterMethods.cs
src/Microsoft.NetCore.Analyzers/Core/Security/DoNotUseInsecureDeserializerBinaryFormatterWithoutBinder.cs
src/Microsoft.NetCore.Analyzers/Core/Security/DoNotUseInsecureDeserializerLosFormatter.cs
src/Microsoft.NetCore.Analyzers/Core/Security/DoNotUseInsecureDeserializerMethodsBase.cs
src/Microsoft.NetCore.Analyzers/Core/Security/MicrosoftNetCoreSecurityResources.resx
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.cs.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.de.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.es.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.fr.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.it.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.ja.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.ko.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.pl.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.pt-BR.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.ru.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.tr.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.zh-Hans.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.zh-Hant.xlf
src/Microsoft.NetCore.Analyzers/UnitTests/Security/DoNotUseInsecureDeserializationLosFormatterTests.cs
src/Microsoft.NetCore.Analyzers/UnitTests/Security/DoNotUseInsecureDeserializerBinaryFormatterMethodsTests.cs

- Old CA2300 and CA2301 -> New CA2300
- Old CA2302 -> New CA2301
- Old CA2303 -> New CA2302
- Old CA2310 and CA2311 -> New CA2305

Consolidating rule IDs for invoking and referencing insecure deserialization, and a little bit of renumbering

---

src/Microsoft.NetCore.Analyzers/Core/Security/MicrosoftNetCoreSecurityResources.resx
src/Microsoft.NetCore.Analyzers/Core/Security/ReviewCodeForCommandExecutionVulnerabilities.cs
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.cs.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.de.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.es.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.fr.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.it.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.ja.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.ko.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.pl.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.pt-BR.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.ru.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.tr.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.zh-Hans.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.zh-Hant.xlf
src/Microsoft.NetCore.Analyzers/UnitTests/Security/ReviewCodeForCommandExecutionVulnerabilitiesTests.cs
src/Utilities/Analyzer.Utilities.projitems
src/Utilities/FlowAnalysis/Analysis/TaintedDataAnalysis/ProcessCommandSinks.cs
src/Utilities/FlowAnalysis/Analysis/TaintedDataAnalysis/SinkKind.cs
src/Utilities/FlowAnalysis/Analysis/TaintedDataAnalysis/TaintedDataConfig.cs
src/Utilities/WellKnownTypes.cs

- Tainted sinks hardcoded from FxCop.
- Smoke tests for process command injection.

Process command injection tainted data DFA

---

src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/DiagnosticDescriptorCreationAnalyzer.cs
src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/ReportDiagnosticAnalyzer.cs
src/Microsoft.CodeQuality.Analyzers.Exp/Core/Microsoft.CodeQuality.Analyzers.Exp.csproj
src/Microsoft.CodeQuality.Analyzers/CSharp/Maintainability/CSharpUseNameofInPlaceOfString.Fixer.cs
src/Microsoft.NetFramework.Analyzers/Core/MarkVerbHandlersWithValidateAntiforgeryTokenAnalyzer.MvcAttributeSymbols.cs
src/Roslyn.Diagnostics.Analyzers/Core/DeclarePublicAPIAnalyzer.cs
src/Test.Utilities/TestAdditionalDocument.cs
src/Test.Utilities/WorkItemAttribute.cs
src/Utilities/Extensions/IMethodSymbolExtensions.cs
src/Utilities/Extensions/IOperationExtensions.cs
src/Utilities/Extensions/ObjectExtensions.cs

Cleans up the remaining messages in the error list

Fix IDE0034 violations (use default literal)

---

src/Utilities/Compiler/WellKnownTypeNames.cs
src/Utilities/Compiler/WellKnownTypes.cs

Moving constants to WellKnownTypeNames.

Finishing WellKnownTypeNames in features/dataflow

---

nuget/PerformanceSensitive.Analyzers/Microsoft.PerformanceSensitive.Analyzers.targets

Fix #2124 
@tmat @sharwell @mavasani

Embed PerformanceSensitiveAttribute source in PDB

---

docs/Analyzer Configuration.md
src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/DoNotDirectlyAwaitATask.cs
src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/IdentifiersShouldHaveCorrectPrefix.cs
src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/DoNotDirectlyAwaitATaskTests.cs
src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/IdentifiersShouldHaveCorrectPrefixTests.cs
src/Utilities/Compiler/Options/EditorConfigOptionNames.cs

Change editorconfig option names for couple of recently added options

---

eng/Analyzers_ShippingRules.ruleset
eng/Versions.props
src/Directory.Build.props
src/DotNetAnalyzers/Core/PublicApiAnalyzer/DeclarePublicAPIAnalyzer.Impl.cs
src/MetaCompilation.Analyzers/UnitTests/Helpers/DiagnosticVerifier.Helper.cs
src/Microsoft.CodeAnalysis.FlowAnalysis.Utilities/Microsoft.CodeAnalysis.FlowAnalysis.Utilities.csproj
src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/TypeNamesShouldNotMatchNamespaces.cs
src/Microsoft.NetFramework.Analyzers/Core/DoNotUseInsecureDtdProcessingInApiDesign.cs
src/Microsoft.NetFramework.Analyzers/VisualBasic/Helpers/SyntaxNodeHelper.vb
src/Test.Utilities/AdditionalMetadataReferences.cs
src/Test.Utilities/CodeMetricsTestsBase.cs
src/Test.Utilities/DiagnosticAnalyzerTestBase.cs
src/Test.Utilities/DiagnosticExtensions.cs
src/Test.Utilities/MarkupTestFile.cs
src/Tools/Program.cs
src/Utilities.UnitTests/FlowAnalysis/Analysis/PropertySetAnalysis/PropertySetAnalysisTests.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PropertySetAnalysis/PropertySetAnalysis.PropertySetDataFlowOperationVisitor.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/ValueContentAnalysis/ValueContentAbstractValue.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/ValueContentAnalysis/ValueContentAnalysis.CoreAnalysisDataDomain.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/PredicatedAnalysisData.cs

I have also filed issues for the reported false positives.

Dogfood the flow-analysis based analyzers in features/dataflow branch

---

README.md
docs/Analyzer Configuration.md
src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/DoNotDirectlyAwaitATask.cs
src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/IdentifiersShouldHaveCorrectPrefix.cs
src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/DoNotDirectlyAwaitATaskTests.cs
src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/IdentifiersShouldHaveCorrectPrefixTests.cs
src/Microsoft.NetCore.Analyzers/CSharp/Runtime/CSharpTestForEmptyStringsUsingStringLength.Fixer.cs
src/Microsoft.NetCore.Analyzers/Core/Runtime/InstantiateArgumentExceptionsCorrectly.cs
src/Microsoft.NetCore.Analyzers/Core/Runtime/TestForEmptyStringsUsingStringLength.Fixer.cs
src/Microsoft.NetCore.Analyzers/Core/Security/DoNotReferSelfInSerializableClass.cs
src/Microsoft.NetCore.Analyzers/Core/Security/SystemSecurityCryptographyResources.resx
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/SystemSecurityCryptographyResources.cs.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/SystemSecurityCryptographyResources.de.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/SystemSecurityCryptographyResources.es.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/SystemSecurityCryptographyResources.fr.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/SystemSecurityCryptographyResources.it.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/SystemSecurityCryptographyResources.ja.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/SystemSecurityCryptographyResources.ko.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/SystemSecurityCryptographyResources.pl.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/SystemSecurityCryptographyResources.pt-BR.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/SystemSecurityCryptographyResources.ru.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/SystemSecurityCryptographyResources.tr.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/SystemSecurityCryptographyResources.zh-Hans.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/SystemSecurityCryptographyResources.zh-Hant.xlf
src/Microsoft.NetCore.Analyzers/UnitTests/Runtime/InstantiateArgumentExceptionsCorrectlyTests.cs
src/Microsoft.NetCore.Analyzers/UnitTests/Runtime/TestForEmptyStringsUsingStringLengthTests.Fixer.cs
src/Microsoft.NetCore.Analyzers/UnitTests/Security/DoNotReferSelfInSerializableClassTests.cs
src/Microsoft.NetCore.Analyzers/VisualBasic/Runtime/BasicTestForEmptyStringsUsingStringLength.Fixer.vb
src/Utilities/Compiler/Options/EditorConfigOptionNames.cs

FYI @dotpaul - I will create a PR for RI after this is merged.

FI master to features/dataflow

---

src/Microsoft.NetCore.Analyzers/UnitTests/Runtime/DisposableFieldsShouldBeDisposedTests.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/DisposeAnalysis/DisposeAnalysis.DisposeDataFlowOperationVisitor.cs

Ensure that disposable fields are tracked during dispose analysis on all control flow paths
Fixes #2182

Fix CA2213 (DisposableFieldsShouldBeDisposed) false positive

---

src/Microsoft.NetCore.Analyzers/CSharp/Runtime/CSharpDoNotUseEnumerableMethodsOnIndexableCollectionsInsteadUseTheCollectionDirectly.Fixer.cs
src/Microsoft.NetCore.Analyzers/UnitTests/Runtime/DoNotUseEnumerableMethodsOnIndexableCollectionsInsteadUseTheCollectionDirectlyTests.Fixer.cs

This PR fixes the formatting problem introduced by the previous PR - https://github.com/dotnet/roslyn-analyzers/pull/2173
The both relate to this issue - https://github.com/dotnet/roslyn-analyzers/issues/1932

CA1826 formatting related trivia fix

---

README.md
src/Microsoft.CodeAnalysis.BannedApiAnalyzers/Microsoft.CodeAnalysis.BannedApiAnalyzers.md
src/PublicApiAnalyzers/Microsoft.CodeAnalysis.PublicApiAnalyzers.md

https://github.com/dotnet/roslyn-analyzers/issues/2198
#2199

Update repo's Readme for bannedAPI and publicAPI analyzers

---

src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/DefineAccessorsForAttributeArgumentsTests.Fixer.cs
src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/ImplementStandardExceptionConstructorsTests.Fixer.cs
src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/InterfaceMethodsShouldBeCallableByChildTypesTests.Fixer.cs
src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/ParameterNamesShouldMatchBaseDeclarationTests.Fixer.cs
src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/UriParametersShouldNotBeStringsTests.Fixer.cs
src/Microsoft.CodeQuality.Analyzers/UnitTests/Maintainability/ReviewUnusedParametersTests.Fixer.cs
src/Test.Utilities/CodeFixTestBase.cs

Addesses the issue - https://github.com/dotnet/roslyn-analyzers/issues/2233

Fix for false positive unit tests

---

src/Microsoft.CodeQuality.Analyzers/CSharp/QualityGuidelines/CSharpRethrowToPreserveStackDetails.cs
src/Microsoft.CodeQuality.Analyzers/UnitTests/QualityGuidelines/RethrowToPreserveStackDetailsTests.cs
src/Microsoft.CodeQuality.Analyzers/VisualBasic/QualityGuidelines/BasicRethrowToPreserveStackDetails.vb

Fix NRE in RethrowToPreserveStackDetailsAnalyzer

---

eng/Versions.props

Bump version to 2.9.1

---

src/Microsoft.NetCore.Analyzers/Core/Security/DoNotUseInsecureDeserializerBinaryFormatterMethods.cs
src/Microsoft.NetCore.Analyzers/Core/Security/DoNotUseInsecureDeserializerBinaryFormatterWithoutBinder.cs
src/Microsoft.NetCore.Analyzers/Core/Security/DoNotUseInsecureDeserializerNetDataContractSerializerWithoutBinder.cs

I'll only merge this if the docs get published first.

Help links for BinaryFormatter rules

---

src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/IdentifiersShouldHaveCorrectSuffix.cs

Utilizing the new goodness in the language

CA1710 code style fix - using new tuple syntax

---

src/Directory.Build.props
src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/IdentifiersShouldNotHaveIncorrectSuffixTests.cs
src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/ImplementStandardExceptionConstructorsTests.cs

Fix xUnit warnings

---

src/Microsoft.CodeQuality.Analyzers/UnitTests/QualityGuidelines/RemoveEmptyFinalizersTests.cs
src/Microsoft.NetCore.Analyzers/UnitTests/Runtime/DisposeMethodsShouldCallBaseClassDisposeTests.cs
src/Microsoft.NetCore.Analyzers/UnitTests/Runtime/ProvideCorrectArgumentsToFormattingMethodsTests.cs
src/Microsoft.NetCore.Analyzers/UnitTests/Runtime/TestForNaNCorrectlyTests.cs
src/Microsoft.NetCore.Analyzers/UnitTests/Security/ReviewCodeForSqlInjectionVulnerabilitiesTests.cs
src/Roslyn.Diagnostics.Analyzers/UnitTests/SpecializedEnumerableCreationAnalyzerTests.cs

Closes #1654
Closes #1788
Closes #1891

Enable tests which were skipped but now work

---

src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/OperatorOverloadsHaveNamedAlternates.Fixer.cs
src/Microsoft.NetCore.Analyzers/UnitTests/Security/TaintedDataAnalyzerTestBase.cs
src/Test.Utilities/DiagnosticAnalyzerTestBase.cs
src/Test.Utilities/MarkupTestFile.cs

Utilizing the new language goodness even more.
Closes #2320

Updated codebase to use new tuple syntax

---

src/Microsoft.NetCore.Analyzers/Core/Runtime/AvoidZeroLengthArrayAllocations.Fixer.cs
src/Microsoft.NetCore.Analyzers/Core/Runtime/UseOrdinalStringComparison.Fixer.cs
src/Microsoft.NetCore.Analyzers/UnitTests/Runtime/AvoidZeroLengthArrayAllocationsTests.cs
src/Microsoft.NetCore.Analyzers/UnitTests/Runtime/UseOrdinalStringComparisonTests.Fixer.cs
src/Utilities/Workspaces/SyntaxGeneratorExtensions.cs

Generate MemberAccessExpression instead of QualifiedName

---

src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/CompareSymbolsCorrectlyAnalyzer.cs
src/Microsoft.CodeAnalysis.Analyzers/UnitTests/MetaAnalyzers/CompareSymbolsCorrectlyTests.cs

Fix RS1024 (Compare symbols correctly) false positives

---

src/Microsoft.CodeQuality.Analyzers/UnitTests/QualityGuidelines/ValidateArgumentsOfPublicMethodsTests.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/ParameterValidationAnalysis/ParameterValidationAnalysis.ParameterValidationDataFlowOperationVisitor.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/ThrownExceptionInfo.cs

Fix a bunch of false positives from [CA1062](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1062-validate-arguments-of-public-methods?view=vs-2019) (Validate arguments of public methods)
Fixes #2275
Fixes #2276
Fixes #2277
Fixes #2280
Fixes #2327
Fixes #2339

Fix CA1062 false positive bugs

---

src/PerformanceSensitiveAnalyzers/UnitTests/ExplicitAllocationAnalyzerTests.cs
src/PerformanceSensitiveAnalyzers/UnitTests/VisualBasicPerformanceCodeFixVerifier`2+Test.cs
src/PerformanceSensitiveAnalyzers/UnitTests/VisualBasicPerformanceCodeFixVerifier`2.cs

Add ExplicitAllocationAnalyzerTests for Visual Basic

---

src/Test.Utilities/AdditionalMetadataReferences.cs
src/Test.Utilities/CodeFixRunner.cs
src/Test.Utilities/DiagnosticAnalyzerTestBase.cs
src/Test.Utilities/DiagnosticExtensions.cs
src/Test.Utilities/MarkupTestFile.cs
src/Test.Utilities/Test.Utilities.csproj

Fixes #1225
See dotnet/roslyn#35102

Remove dependencies on IVTs from dotnet/roslyn

---

nuget/PerformanceSensitiveAnalyzers/Microsoft.CodeAnalysis.PerformanceSensitiveAnalyzers.targets
nuget/PerformanceSensitiveAnalyzers/PerformanceSensitiveAttribute.cs
nuget/PerformanceSensitiveAnalyzers/PerformanceSensitiveAttribute.vb

Fixes #2372 
Fixes #2373 
Fixes #2374 
Fixes #2375

Fix issues with PerformanceSensitiveAttribute

---

src/Roslyn.Diagnostics.Analyzers/Core/ExportedPartsShouldHaveImportingConstructor.cs
src/Roslyn.Diagnostics.Analyzers/UnitTests/ExportedPartsShouldHaveImportingConstructorTests.cs

Found while dogfooding on Roslyn.

Update RS0034 to ignore static constructors

---

src/Roslyn.Diagnostics.Analyzers/Core/ExportedPartsShouldHaveImportingConstructorCodeFixProvider.cs

Found while dogfooding on Roslyn.

Fix code fix for creating importing constructors from custom export attributes

---

src/Roslyn.Diagnostics.Analyzers/Core/ExportedPartsShouldHaveImportingConstructorCodeFixProvider.cs
src/Roslyn.Diagnostics.Analyzers/UnitTests/ExportedPartsShouldHaveImportingConstructorTests.cs

Found while dogfooding on Roslyn.

Place generated constructor after fields

---

src/Microsoft.NetCore.Analyzers/Core/Security/DoNotAddSchemaByURL.cs
src/Microsoft.NetCore.Analyzers/Core/Security/DoNotDisableHttpHeaderChecking.cs
src/Microsoft.NetCore.Analyzers/Core/Security/SetViewStateUserKey.cs

Re-enabling temporarily disabled rules

---

src/Microsoft.CodeAnalysis.Analyzers/Core/InternalImplementationOnlyAnalyzer.cs
src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/DiagnosticAnalyzerAttributeAnalyzer.cs
src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/DiagnosticAnalyzerCorrectnessAnalyzer.DiagnosticAnalyzerSymbolAnalyzer.cs
src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/DiagnosticAnalyzerFieldsAnalyzer.cs
src/Roslyn.Diagnostics.Analyzers/Core/DoNotMixAttributesFromDifferentVersionsOfMEF.cs
src/Roslyn.Diagnostics.Analyzers/Core/ExportedPartsShouldHaveImportingConstructor.cs
src/Roslyn.Diagnostics.Analyzers/Core/ImportingConstructorShouldBeObsolete.cs
src/Roslyn.Diagnostics.Analyzers/Core/PartsExportedWithMEFv2MustBeMarkedAsShared.cs
src/Roslyn.Diagnostics.Analyzers/Core/TestExportsShouldNotBeDiscoverable.cs
src/Roslyn.Diagnostics.Analyzers/UnitTests/ExportedPartsShouldHaveImportingConstructorTests.cs
src/Utilities/Compiler/Extensions/ITypeSymbolExtensions.cs

Found while dogfooding on Roslyn.

Update GetApplicableAttributes to check inheritance

---

src/Microsoft.CodeQuality.Analyzers/UnitTests/QualityGuidelines/MarkMembersAsStaticTests.cs
src/Utilities/Compiler/Extensions/OperationBlockAnalysisContextExtension.cs

Handle error case of throw operation with no exception

---

src/Microsoft.NetCore.Analyzers/Core/Security/DoNotUseInsecureDeserializerJavascriptSerializerWithSimpleTypeResolver.cs

Will merge once links are live, so I can check that they're correct.

Adding help links for CA2321 and CA2322

---

eng/common/build.ps1

It didn't work for me because I didn't have the VS SDK installed.

Error message when running the CI build without necessary Visual Studio components

---

src/Microsoft.NetCore.Analyzers/Core/Security/DoNotInstallRootCert.cs
src/Microsoft.NetCore.Analyzers/UnitTests/Security/DoNotInstallRootCertTests.cs
src/Utilities.UnitTests/FlowAnalysis/Analysis/PropertySetAnalysis/PropertySetAnalysisTests.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PropertySetAnalysis/PropertySetAnalysis.cs

Hopefully this will using PropertySetAnalysis with ValueContentAnalysis a little easier.

Helper method for mapping ValueContentAbstractValues to PropertySetAbstractValueKinds

---

src/Microsoft.CodeQuality.Analyzers/UnitTests/Maintainability/AvoidDeadConditionalCode_NullAnalysis.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAnalysis.PointsToDataFlowOperationVisitor.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs

Fix an NRE in dataflow analysis for erroroneous code

---

src/Microsoft.NetCore.Analyzers/Core/Runtime/DisposeObjectsBeforeLosingScope.cs
src/Microsoft.NetCore.Analyzers/UnitTests/Runtime/DisposeObjectsBeforeLosingScopeTests.cs

Fix CA2000 false positive for disposable creations in catch clause

---

src/Microsoft.NetCore.Analyzers/UnitTests/Runtime/DisposeObjectsBeforeLosingScopeTests.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs

Handle erroroneous branch value in flow analysis

---

src/Microsoft.CodeAnalysis.FlowAnalysis.Utilities/PublicAPI.Unshipped.txt
src/Microsoft.NetCore.Analyzers/Core/Security/DoNotSetSwitch.cs
src/Microsoft.NetCore.Analyzers/UnitTests/Security/DoNotDisableSchUseStrongCryptoTests.cs
src/Microsoft.NetCore.Analyzers/UnitTests/Security/DoNotDisableUsingServicePointManagerSecurityProtocolsTests.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/ValueContentAnalysis/ValueContentAbstractValue.cs

Reverts dotnet/roslyn-analyzers#2492

Revert "A pinch of ValueContentAnalysis for DoNotSetSwitch"

---

src/Microsoft.NetCore.Analyzers/Core/Runtime/DisposeObjectsBeforeLosingScope.cs
src/Microsoft.NetCore.Analyzers/UnitTests/Runtime/DisposeObjectsBeforeLosingScopeTests.cs

Do not report CA2000 diagnostic with multiline argument

---

src/Microsoft.NetCore.Analyzers/Core/Security/SetViewStateUserKey.cs
src/Microsoft.NetCore.Analyzers/Core/Security/SystemSecurityCryptographyResources.resx
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/SystemSecurityCryptographyResources.cs.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/SystemSecurityCryptographyResources.de.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/SystemSecurityCryptographyResources.es.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/SystemSecurityCryptographyResources.fr.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/SystemSecurityCryptographyResources.it.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/SystemSecurityCryptographyResources.ja.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/SystemSecurityCryptographyResources.ko.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/SystemSecurityCryptographyResources.pl.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/SystemSecurityCryptographyResources.pt-BR.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/SystemSecurityCryptographyResources.ru.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/SystemSecurityCryptographyResources.tr.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/SystemSecurityCryptographyResources.zh-Hans.xlf
src/Microsoft.NetCore.Analyzers/Core/Security/xlf/SystemSecurityCryptographyResources.zh-Hant.xlf
src/Microsoft.NetCore.Analyzers/UnitTests/Security/SetViewStateUserKeyTests.cs

Extend CA5368 to support Page.ViewStateUserKey.

Fix a bug for ca5368

---

src/Microsoft.CodeQuality.Analyzers/UnitTests/QualityGuidelines/ValidateArgumentsOfPublicMethodsTests.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/AbstractLocationDataFlowOperationVisitor.cs

Fixes https://github.com/dotnet/roslyn-analyzers/issues/2525#issuecomment-503180297

Fix a follow up false positive in CA1062 from #2525

---

src/Microsoft.NetCore.Analyzers/Core/Runtime/DoNotPassLiteralsAsLocalizedParameters.cs
src/Microsoft.NetCore.Analyzers/UnitTests/Runtime/DoNotPassLiteralsAsLocalizedParametersTests.cs

Fix NRE in DoNotPassLiteralsAsLocalizedParameters analyzer (CA1303)

---

src/GenerateAnalyzerRulesets/Program.cs
src/MetaCompilation.Analyzers/MetaCompilation.Analyzers.sarif
src/Microsoft.CodeAnalysis.Analyzers/Microsoft.CodeAnalysis.Analyzers.sarif
src/Microsoft.CodeAnalysis.FxCopAnalyzers/Microsoft.CodeAnalysis.FxCopAnalyzers.sarif
src/Microsoft.CodeQuality.Analyzers/Microsoft.CodeQuality.Analyzers.sarif
src/Microsoft.NetCore.Analyzers/Microsoft.NetCore.Analyzers.sarif
src/Microsoft.NetFramework.Analyzers/Microsoft.NetFramework.Analyzers.sarif
src/PerformanceSensitiveAnalyzers/Microsoft.CodeAnalysis.PerformanceSensitiveAnalyzers.sarif
src/PublicApiAnalyzers/Microsoft.CodeAnalysis.PublicApiAnalyzers.sarif
src/Roslyn.Diagnostics.Analyzers/Roslyn.Diagnostics.Analyzers.sarif

Fix SRAIF fullDescription for the case where the description is null or empty.
/cc @mavasani

Fix SRAIF fullDescription

---

src/Microsoft.CodeQuality.Analyzers/Core/QualityGuidelines/AvoidPropertySelfAssignment.cs
src/Microsoft.CodeQuality.Analyzers/UnitTests/QualityGuidelines/AvoidPropertySelfAssignmentTests.cs

Found false positives during dogfooding

Handle indexers in CA2245 (AvoidPropertySelfAssignment)

---

src/Microsoft.CodeQuality.Analyzers/UnitTests/QualityGuidelines/ValidateArgumentsOfPublicMethodsTests.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/ParameterValidationAnalysis/ParameterValidationAnalysis.ParameterValidationDataFlowOperationVisitor.cs

Handle IsType checks in conditional expressions

---

src/PublicApiAnalyzers/Core/Analyzers/DeclarePublicApiAnalyzer.cs
src/PublicApiAnalyzers/UnitTests/DeclarePublicApiAnalyzerTests.cs
src/Roslyn.Diagnostics.Analyzers/Core/RoslynDiagnosticIds.cs

#2622 tracks a better approach that enables code fix based experience

Revert recently added PublicApiFilesMissing diagnostic

---

docs/Analyzer Configuration.md
src/Microsoft.CodeQuality.Analyzers/UnitTests/QualityGuidelines/ValidateArgumentsOfPublicMethodsTests.cs
src/Microsoft.NetCore.Analyzers/Core/Runtime/DoNotPassLiteralsAsLocalizedParameters.cs
src/Microsoft.NetCore.Analyzers/UnitTests/Runtime/DoNotPassLiteralsAsLocalizedParametersTests.cs
src/Utilities/Compiler/Analyzer.Utilities.projitems
src/Utilities/Compiler/Extensions/ISymbolExtensions.cs
src/Utilities/Compiler/Options/AnalyzerOptionsExtensions.cs
src/Utilities/Compiler/Options/EditorConfigOptionNames.cs
src/Utilities/Compiler/Options/SymbolNamesOption.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/ParameterValidationAnalysis/ParameterValidationAnalysis.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/ParameterValidationAnalysis/ParameterValidationAnalysisContext.cs

Add editorconfig option to CA1303 to exclude method/constructors

---

src/Microsoft.CodeAnalysis.Analyzers/Core/FixAnalyzers/FixerWithFixAllAnalyzer.cs
src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/DiagnosticAnalyzerAttributeAnalyzer.cs
src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/DiagnosticAnalyzerFieldsAnalyzer.cs
src/Microsoft.CodeAnalysis.Analyzers/Core/UpgradeMSBuildWorkspaceAnalyzer.cs

Fixes #2040 
Fixes #2043 
Partially addresses #2042

Enable concurrency for additional analyzers

---

src/Utilities/Compiler/Extensions/ITypeSymbolExtensions.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/ValueContentAnalysis/ValueContentAbstractValue.cs

Fixes #1775 for NetCore projects.

Fix CA2235 (Serializable fields) for string type fields

---

eng/GenerateAnalyzerNuspec.targets

Ensure that we mark analyzer packages as a development dependency

---

src/Microsoft.NetFramework.Analyzers/UnitTests/DoNotUseInsecureXSLTScriptExecutionXslCompiledTransformLoadInsecureConstructedSettingsTests.cs
src/Microsoft.NetFramework.Analyzers/VisualBasic/Helpers/SyntaxNodeHelper.vb

Handling 'As New' in VB when getting constructor arguments

---

src/Microsoft.NetCore.Analyzers/Core/MicrosoftNetCoreAnalyzersResources.resx
src/Microsoft.NetCore.Analyzers/Core/Security/SslProtocolsAnalyzer.cs
src/Microsoft.NetCore.Analyzers/Core/xlf/MicrosoftNetCoreAnalyzersResources.cs.xlf
src/Microsoft.NetCore.Analyzers/Core/xlf/MicrosoftNetCoreAnalyzersResources.de.xlf
src/Microsoft.NetCore.Analyzers/Core/xlf/MicrosoftNetCoreAnalyzersResources.es.xlf
src/Microsoft.NetCore.Analyzers/Core/xlf/MicrosoftNetCoreAnalyzersResources.fr.xlf
src/Microsoft.NetCore.Analyzers/Core/xlf/MicrosoftNetCoreAnalyzersResources.it.xlf
src/Microsoft.NetCore.Analyzers/Core/xlf/MicrosoftNetCoreAnalyzersResources.ja.xlf
src/Microsoft.NetCore.Analyzers/Core/xlf/MicrosoftNetCoreAnalyzersResources.ko.xlf
src/Microsoft.NetCore.Analyzers/Core/xlf/MicrosoftNetCoreAnalyzersResources.pl.xlf
src/Microsoft.NetCore.Analyzers/Core/xlf/MicrosoftNetCoreAnalyzersResources.pt-BR.xlf
src/Microsoft.NetCore.Analyzers/Core/xlf/MicrosoftNetCoreAnalyzersResources.ru.xlf
src/Microsoft.NetCore.Analyzers/Core/xlf/MicrosoftNetCoreAnalyzersResources.tr.xlf
src/Microsoft.NetCore.Analyzers/Core/xlf/MicrosoftNetCoreAnalyzersResources.zh-Hans.xlf
src/Microsoft.NetCore.Analyzers/Core/xlf/MicrosoftNetCoreAnalyzersResources.zh-Hant.xlf
src/Microsoft.NetCore.Analyzers/UnitTests/Security/SslProtocolsAnalyzerTests.cs
src/Utilities/Compiler/WellKnownTypeNames.cs

Similar to the existing DoNotUseDeprecatedSecurityProtocols analyzer.

Analyzer for deprecated/hardcoded SslProtocols enum values

---

src/Microsoft.NetFramework.Analyzers/Core/DoNotUseInsecureDtdProcessing.cs
src/Microsoft.NetFramework.Analyzers/UnitTests/DoNotUseInsecureDtdProcessingXmlDocumentSetInsecureResolverTests.cs

Fixing NullReferenceException in CA3075

---

src/Microsoft.NetCore.Analyzers/Core/MicrosoftNetCoreAnalyzersResources.resx
src/Microsoft.NetCore.Analyzers/Core/xlf/MicrosoftNetCoreAnalyzersResources.cs.xlf
src/Microsoft.NetCore.Analyzers/Core/xlf/MicrosoftNetCoreAnalyzersResources.de.xlf
src/Microsoft.NetCore.Analyzers/Core/xlf/MicrosoftNetCoreAnalyzersResources.es.xlf
src/Microsoft.NetCore.Analyzers/Core/xlf/MicrosoftNetCoreAnalyzersResources.fr.xlf
src/Microsoft.NetCore.Analyzers/Core/xlf/MicrosoftNetCoreAnalyzersResources.it.xlf
src/Microsoft.NetCore.Analyzers/Core/xlf/MicrosoftNetCoreAnalyzersResources.ja.xlf
src/Microsoft.NetCore.Analyzers/Core/xlf/MicrosoftNetCoreAnalyzersResources.ko.xlf
src/Microsoft.NetCore.Analyzers/Core/xlf/MicrosoftNetCoreAnalyzersResources.pl.xlf
src/Microsoft.NetCore.Analyzers/Core/xlf/MicrosoftNetCoreAnalyzersResources.pt-BR.xlf
src/Microsoft.NetCore.Analyzers/Core/xlf/MicrosoftNetCoreAnalyzersResources.ru.xlf
src/Microsoft.NetCore.Analyzers/Core/xlf/MicrosoftNetCoreAnalyzersResources.tr.xlf
src/Microsoft.NetCore.Analyzers/Core/xlf/MicrosoftNetCoreAnalyzersResources.zh-Hans.xlf
src/Microsoft.NetCore.Analyzers/Core/xlf/MicrosoftNetCoreAnalyzersResources.zh-Hant.xlf

Operating System, not Operation System

Fixing text in message

---

src/Microsoft.NetCore.Analyzers/UnitTests/Runtime/DisposeObjectsBeforeLosingScopeTests.cs

This reverts commit 3c65eada546d8b5f0b7142d21ae18a277eef4d39.
Follow-up to https://github.com/dotnet/roslyn-analyzers/pull/2806

Revert "Revert "Unit tests for ??= operator""

---

GuidelinesForNewRules.md
README.md

Based on the questions from #2811

Add documentation for guidance on contributing a new CA rule to the repo

---

src/Microsoft.NetCore.Analyzers/Core/Runtime/SerializationRulesDiagnosticAnalyzer.cs

Bail out from CA2235 for NetStandard assemblies

---

Directory.Build.targets
THIRD-PARTY-NOTICES.txt
assets/ThirdPartyNotices.rtf
eng/GenerateAnalyzerNuspec.csx
src/MetaCompilation.Analyzers/Setup/source.extension.vsixmanifest
src/Microsoft.CodeAnalysis.Analyzers/Setup/source.extension.vsixmanifest
src/Microsoft.CodeAnalysis.BannedApiAnalyzers/Setup/source.extension.vsixmanifest
src/Microsoft.CodeQuality.Analyzers/Setup/source.extension.vsixmanifest
src/Microsoft.NetCore.Analyzers/Setup/source.extension.vsixmanifest
src/Microsoft.NetFramework.Analyzers/Setup/source.extension.vsixmanifest
src/PerformanceSensitiveAnalyzers/Setup/source.extension.vsixmanifest
src/PublicApiAnalyzers/Setup/source.extension.vsixmanifest
src/Roslyn.Diagnostics.Analyzers/Setup/source.extension.vsixmanifest
src/Text.Analyzers/Setup/source.extension.vsixmanifest

updating TPN and adding TPN/EULA to Nuget/VSIX

---

src/Microsoft.NetCore.Analyzers/Core/xlf/MicrosoftNetCoreAnalyzersResources.cs.xlf
src/Microsoft.NetCore.Analyzers/Core/xlf/MicrosoftNetCoreAnalyzersResources.de.xlf
src/Microsoft.NetCore.Analyzers/Core/xlf/MicrosoftNetCoreAnalyzersResources.es.xlf
src/Microsoft.NetCore.Analyzers/Core/xlf/MicrosoftNetCoreAnalyzersResources.fr.xlf
src/Microsoft.NetCore.Analyzers/Core/xlf/MicrosoftNetCoreAnalyzersResources.it.xlf
src/Microsoft.NetCore.Analyzers/Core/xlf/MicrosoftNetCoreAnalyzersResources.ja.xlf
src/Microsoft.NetCore.Analyzers/Core/xlf/MicrosoftNetCoreAnalyzersResources.ko.xlf
src/Microsoft.NetCore.Analyzers/Core/xlf/MicrosoftNetCoreAnalyzersResources.pl.xlf
src/Microsoft.NetCore.Analyzers/Core/xlf/MicrosoftNetCoreAnalyzersResources.pt-BR.xlf
src/Microsoft.NetCore.Analyzers/Core/xlf/MicrosoftNetCoreAnalyzersResources.ru.xlf
src/Microsoft.NetCore.Analyzers/Core/xlf/MicrosoftNetCoreAnalyzersResources.tr.xlf
src/Microsoft.NetCore.Analyzers/Core/xlf/MicrosoftNetCoreAnalyzersResources.zh-Hans.xlf
src/Microsoft.NetCore.Analyzers/Core/xlf/MicrosoftNetCoreAnalyzersResources.zh-Hant.xlf
src/Tools/Scripts/SortXlfTransUnits.ps1

Hopefully makes automerge to master PRs easier in the future (maybe).

Sorting NetCore XLFs

---

src/Microsoft.NetCore.Analyzers/UnitTests/Security/DoNotUseInsecureDeserializerBinaryFormatterWithoutBinderTests.cs
src/Microsoft.NetCore.Analyzers/UnitTests/Security/UseXmlReaderForSchemaReadTests.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PropertySetAnalysis/PropertySetAnalysis.PropertySetDataFlowOperationVisitor.cs

And also a doc sample and demonstrating some behavior that needs to be investigated.

PropertySetAnalysis: Handling assignments to flow captures when tracking properties

---

src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/OverrideEqualsAndOperatorEqualsOnValueTypes.cs
src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/OverrideEqualsAndOperatorEqualsOnValueTypesTests.cs

CA1815: Do not report on ref struct

---

src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/EquatableAnalyzer.cs
src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/EquatableAnalyzerTests.cs

CA1066: Do not report on ref struct

---

src/Microsoft.NetCore.Analyzers/Core/Runtime/TestForNaNCorrectly.cs
src/Microsoft.NetCore.Analyzers/UnitTests/Runtime/TestForNaNCorrectlyTests.Fixer.cs

Update CA2242: do not report in generated code

---

src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/CancellationTokenParametersMustComeLast.cs
src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/CancellationTokenParametersMustComeLastTests.cs
src/Utilities/Compiler/WellKnownTypeNames.cs

CA1068: Do not report when last argument is of type IProgress<T>

---

src/Microsoft.NetCore.Analyzers/Core/Runtime/DoNotUseEnumerableMethodsOnIndexableCollectionsInsteadUseTheCollectionDirectly.Fixer.cs
src/Microsoft.NetCore.Analyzers/UnitTests/Runtime/DoNotUseEnumerableMethodsOnIndexableCollectionsInsteadUseTheCollectionDirectlyTests.Fixer.cs
src/Utilities/Compiler/Extensions/ITypeSymbolExtensions.cs
src/Utilities/Compiler/Extensions/ReportDiagnosticExtensions.cs

Add 2 more code fixes for CA1826.
Relates to #1932

CA1826: Add codefix for .Last() and .Count()

---

eng/Versions.props
src/Microsoft.CodeQuality.Analyzers/UnitTests/Maintainability/ReviewUnusedParametersTests.cs
src/Test.Utilities/AdditionalMetadataReferences.cs

Update Microsoft.CodeAnalysis.Testing to 1.0.1-beta1.19557.2

---

src/PublicApiAnalyzers/Core/Analyzers/PublicApiAnalyzerResources.resx
src/PublicApiAnalyzers/Core/Analyzers/xlf/PublicApiAnalyzerResources.cs.xlf
src/PublicApiAnalyzers/Core/Analyzers/xlf/PublicApiAnalyzerResources.de.xlf
src/PublicApiAnalyzers/Core/Analyzers/xlf/PublicApiAnalyzerResources.es.xlf
src/PublicApiAnalyzers/Core/Analyzers/xlf/PublicApiAnalyzerResources.fr.xlf
src/PublicApiAnalyzers/Core/Analyzers/xlf/PublicApiAnalyzerResources.it.xlf
src/PublicApiAnalyzers/Core/Analyzers/xlf/PublicApiAnalyzerResources.ja.xlf
src/PublicApiAnalyzers/Core/Analyzers/xlf/PublicApiAnalyzerResources.ko.xlf
src/PublicApiAnalyzers/Core/Analyzers/xlf/PublicApiAnalyzerResources.pl.xlf
src/PublicApiAnalyzers/Core/Analyzers/xlf/PublicApiAnalyzerResources.pt-BR.xlf
src/PublicApiAnalyzers/Core/Analyzers/xlf/PublicApiAnalyzerResources.ru.xlf
src/PublicApiAnalyzers/Core/Analyzers/xlf/PublicApiAnalyzerResources.tr.xlf
src/PublicApiAnalyzers/Core/Analyzers/xlf/PublicApiAnalyzerResources.zh-Hans.xlf
src/PublicApiAnalyzers/Core/Analyzers/xlf/PublicApiAnalyzerResources.zh-Hant.xlf
src/PublicApiAnalyzers/Core/CodeFixes/DeclarePublicApiFix.cs

Provide 3 new resource entries to replace hardcoded titles for Public API fixes.
Fix #2976

Add resources for the 3 fix titles

---

src/Microsoft.NetCore.Analyzers/Core/Runtime/DoNotLockOnObjectsWithWeakIdentity.cs
src/Microsoft.NetCore.Analyzers/UnitTests/Runtime/DoNotLockOnObjectsWithWeakIdentityTests.cs

Update CA2002 to handle Monitor.Enter and Monitor.TryEnter

---

src/Microsoft.CodeQuality.Analyzers/Core/MicrosoftCodeQualityAnalyzersResources.resx
src/Microsoft.CodeQuality.Analyzers/Core/QualityGuidelines/AvoidInfiniteRecursion.cs
src/Microsoft.CodeQuality.Analyzers/Core/xlf/MicrosoftCodeQualityAnalyzersResources.cs.xlf
src/Microsoft.CodeQuality.Analyzers/Core/xlf/MicrosoftCodeQualityAnalyzersResources.de.xlf
src/Microsoft.CodeQuality.Analyzers/Core/xlf/MicrosoftCodeQualityAnalyzersResources.es.xlf
src/Microsoft.CodeQuality.Analyzers/Core/xlf/MicrosoftCodeQualityAnalyzersResources.fr.xlf
src/Microsoft.CodeQuality.Analyzers/Core/xlf/MicrosoftCodeQualityAnalyzersResources.it.xlf
src/Microsoft.CodeQuality.Analyzers/Core/xlf/MicrosoftCodeQualityAnalyzersResources.ja.xlf
src/Microsoft.CodeQuality.Analyzers/Core/xlf/MicrosoftCodeQualityAnalyzersResources.ko.xlf
src/Microsoft.CodeQuality.Analyzers/Core/xlf/MicrosoftCodeQualityAnalyzersResources.pl.xlf
src/Microsoft.CodeQuality.Analyzers/Core/xlf/MicrosoftCodeQualityAnalyzersResources.pt-BR.xlf
src/Microsoft.CodeQuality.Analyzers/Core/xlf/MicrosoftCodeQualityAnalyzersResources.ru.xlf
src/Microsoft.CodeQuality.Analyzers/Core/xlf/MicrosoftCodeQualityAnalyzersResources.tr.xlf
src/Microsoft.CodeQuality.Analyzers/Core/xlf/MicrosoftCodeQualityAnalyzersResources.zh-Hans.xlf
src/Microsoft.CodeQuality.Analyzers/Core/xlf/MicrosoftCodeQualityAnalyzersResources.zh-Hant.xlf
src/Microsoft.CodeQuality.Analyzers/UnitTests/QualityGuidelines/AvoidInfiniteRecursionTests.cs

Add a new rule to detect infinite recursive setter.
Fix #777

Rule CA2011: Avoid infinite recursion

---

src/Microsoft.CodeQuality.Analyzers/CSharp/ApiDesignGuidelines/CSharpTypesThatOwnDisposableFieldsShouldBeDisposable.cs
src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/TypesThatOwnDisposableFieldsShouldBeDisposable.cs
src/Microsoft.CodeQuality.Analyzers/VisualBasic/ApiDesignGuidelines/BasicTypesThatOwnDisposableFieldsShouldBeDisposable.vb
src/Microsoft.NetCore.Analyzers/Core/Runtime/DisposableFieldsShouldBeDisposed.cs
src/Microsoft.NetCore.Analyzers/Core/Runtime/DisposeMethodsShouldCallBaseClassDispose.cs
src/Microsoft.NetCore.Analyzers/UnitTests/Runtime/DisposableFieldsShouldBeDisposedTests.cs
src/Microsoft.NetCore.Analyzers/UnitTests/Runtime/DisposeObjectsBeforeLosingScopeTests.cs
src/Test.Utilities/MinimalImplementations/IAsyncDisposable.cs
src/Utilities/Compiler/Extensions/IMethodSymbolExtensions.cs
src/Utilities/Compiler/Extensions/ITypeSymbolExtensions.cs
src/Utilities/Compiler/WellKnownTypeNames.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/DisposeAnalysis/DisposeAnalysis.DisposeDataFlowOperationVisitor.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/DisposeAnalysis/DisposeAnalysisHelper.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAnalysis.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs

Add support for IAsyncDisposable in dispose analysis

---

src/Microsoft.NetCore.Analyzers/UnitTests/Runtime/DisposeObjectsBeforeLosingScopeTests.cs
src/Utilities/Compiler/Extensions/IMethodSymbolExtensions.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAnalysis.PointsToDataFlowOperationVisitor.cs

Update the collection add heuristic for escaped objects

---

src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/IdentifiersShouldNotContainUnderscores.cs
src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/IdentifiersShouldNotContainUnderscoresTests.cs

Update CA1707 to not report on discard symbol

---

src/Microsoft.CodeAnalysis.Analyzers/Core/CodeAnalysisDiagnosticsResources.resx
src/Microsoft.CodeAnalysis.Analyzers/Core/DiagnosticIds.cs
src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/DiagnosticDescriptorCreationAnalyzer.cs
src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.cs.xlf
src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.de.xlf
src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.es.xlf
src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.fr.xlf
src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.it.xlf
src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.ja.xlf
src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.ko.xlf
src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.pl.xlf
src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.pt-BR.xlf
src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.ru.xlf
src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.tr.xlf
src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.zh-Hans.xlf
src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.zh-Hant.xlf
src/Microsoft.CodeAnalysis.Analyzers/UnitTests/MetaAnalyzers/DiagnosticDescriptorCreationAnalyzerTests.cs

Supersedes #3090 and fixes #1501

Rule RS1028: Provide customTags argument in Diagnostic Descriptor

---

src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/AvoidUninstantiatedInternalClasses.cs
src/Microsoft.CodeQuality.Analyzers/UnitTests/Maintainability/AvoidUninstantiatedInternalClassesTests.cs
src/Utilities/Compiler/WellKnownTypeNames.cs

Update CA1812: Handled types declared in DesignerAttribute

---

src/Utilities/Compiler/DiagnosticCategoryAndIdRanges.txt

Fix category for ID CA2210 in DiagnosticCategoryAndIdRanges.txt

---

src/Microsoft.CodeAnalysis.Analyzers/UnitTests/FixAnalyzers/FixerWithFixAllAnalyzerTests.cs
src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/DoNotDirectlyAwaitATaskTests.cs
src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/DoNotHideBaseClassMethodsTests.cs
src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/EquatableAnalyzerTests.cs
src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/OperatorsShouldHaveSymmetricalOverloadsTests.cs
src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/OverrideEqualsAndOperatorEqualsOnValueTypesTests.cs
src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/ParameterNamesShouldMatchBaseDeclarationTests.cs
src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/StaticHolderTypeTests.cs
src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/UsePropertiesWhereAppropriateTests.cs
src/Microsoft.CodeQuality.Analyzers/UnitTests/Maintainability/AvoidUninstantiatedInternalClassesTests.cs
src/Microsoft.CodeQuality.Analyzers/UnitTests/Maintainability/AvoidUnusedPrivateFieldsTests.cs
src/Microsoft.CodeQuality.Analyzers/UnitTests/Maintainability/DoNotIgnoreMethodResultsTests.cs
src/Microsoft.CodeQuality.Analyzers/UnitTests/Maintainability/ReviewUnusedParametersTests.cs
src/Microsoft.CodeQuality.Analyzers/UnitTests/Maintainability/UseNameOfInPlaceOfStringTests.cs
src/Microsoft.CodeQuality.Analyzers/UnitTests/QualityGuidelines/AssigningSymbolAndItsMemberInSameStatementTests.cs
src/Microsoft.CodeQuality.Analyzers/UnitTests/QualityGuidelines/RemoveEmptyFinalizersTests.cs
src/Microsoft.CodeQuality.Analyzers/UnitTests/QualityGuidelines/RethrowToPreserveStackDetailsTests.cs
src/Microsoft.CodeQuality.Analyzers/UnitTests/QualityGuidelines/ValidateArgumentsOfPublicMethodsTests.cs
src/Test.Utilities/CSharpCodeFixVerifier`2.cs
src/Test.Utilities/VisualBasicCodeFixVerifier`2.cs

Fixes #2995 and supersedes #3005

Prefer expected diagnostics over CompilerDiagnostics.None

---

src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/ParameterNamesShouldMatchBaseDeclaration.Fixer.cs
src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/ParameterNamesShouldMatchBaseDeclarationTests.Fixer.cs

Update CA1725 fixer to really fix all instances of the diagnostic

---

src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/OverloadOperatorEqualsOnOverridingValueTypeEqualsTests.Fixer.cs

Fix #1381 
Please let me know if this test isn't the proper way to test the fix-all.

CA2231: Add test for fix-all

---

src/Microsoft.CodeAnalysis.Analyzers/Core/CodeAnalysisDiagnosticsResources.resx
src/Microsoft.CodeAnalysis.Analyzers/Core/DiagnosticIds.cs
src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/DiagnosticDescriptorCreationAnalyzer.cs
src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.cs.xlf
src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.de.xlf
src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.es.xlf
src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.fr.xlf
src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.it.xlf
src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.ja.xlf
src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.ko.xlf
src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.pl.xlf
src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.pt-BR.xlf
src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.ru.xlf
src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.tr.xlf
src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.zh-Hans.xlf
src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.zh-Hant.xlf
src/Microsoft.CodeAnalysis.Analyzers/UnitTests/MetaAnalyzers/DiagnosticDescriptorCreationAnalyzerTests.cs

RS1029: Do not use reserved diagnostic IDs

---

src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/ReviewUnusedParameters.cs
src/Microsoft.CodeQuality.Analyzers/UnitTests/Maintainability/ReviewUnusedParametersTests.cs

Update CA1801 to losen event handler recognition for UWP

---

src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/IdentifiersShouldNotContainUnderscores.cs
src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/IdentifiersShouldNotContainUnderscoresTests.cs
src/Utilities/Compiler/WellKnownTypeNames.cs

Fix #3121 
Following comment is still open https://github.com/dotnet/roslyn-analyzers/issues/3121#issuecomment-571537124

Update CA1707 to ignore global.asax special methods

---

src/Microsoft.NetCore.Analyzers/Core/Runtime/InstantiateArgumentExceptionsCorrectly.cs
src/Microsoft.NetCore.Analyzers/UnitTests/Runtime/InstantiateArgumentExceptionsCorrectlyTests.cs

Fix intermittent test failure for Spanish queue

---

README.md

Add VS install instructions to Getting Started section

---

src/NetAnalyzers/Core/Microsoft.NetFramework.Analyzers/DoNotUseInsecureDtdProcessing.cs
src/NetAnalyzers/UnitTests/Microsoft.NetFramework.Analyzers/DoNotUseInsecureDtdProcessingDoNotUseLoadXmlTests.cs
src/NetAnalyzers/UnitTests/Microsoft.NetFramework.Analyzers/DoNotUseInsecureDtdProcessingDoNotUseSetInnerXmlTests.cs
src/NetAnalyzers/UnitTests/Microsoft.NetFramework.Analyzers/DoNotUseInsecureDtdProcessingReviewDataViewCollectionStringTests.cs
src/NetAnalyzers/UnitTests/Microsoft.NetFramework.Analyzers/DoNotUseInsecureDtdProcessingUseXmlReaderForDataSetReadXmlSchemaTests.cs
src/NetAnalyzers/UnitTests/Microsoft.NetFramework.Analyzers/DoNotUseInsecureDtdProcessingUseXmlReaderForDataSetReadXmlTests.cs
src/NetAnalyzers/UnitTests/Microsoft.NetFramework.Analyzers/DoNotUseInsecureDtdProcessingUseXmlReaderForDataTableReadXmlSchemaTests.cs
src/NetAnalyzers/UnitTests/Microsoft.NetFramework.Analyzers/DoNotUseInsecureDtdProcessingUseXmlReaderForDataTableReadXmlTests.cs
src/NetAnalyzers/UnitTests/Microsoft.NetFramework.Analyzers/DoNotUseInsecureDtdProcessingUseXmlReaderForDeserializeTests.cs
src/NetAnalyzers/UnitTests/Microsoft.NetFramework.Analyzers/DoNotUseInsecureDtdProcessingUseXmlReaderForLoadTests.cs
src/NetAnalyzers/UnitTests/Microsoft.NetFramework.Analyzers/DoNotUseInsecureDtdProcessingUseXmlReaderForSchemaReadTests.cs
src/NetAnalyzers/UnitTests/Microsoft.NetFramework.Analyzers/DoNotUseInsecureDtdProcessingUseXmlReaderForXPathDocumentTests.cs
src/NetAnalyzers/UnitTests/Microsoft.NetFramework.Analyzers/DoNotUseInsecureDtdProcessingXmlDocumentConstructedWithNoSecureResolverTests.cs
src/NetAnalyzers/UnitTests/Microsoft.NetFramework.Analyzers/DoNotUseInsecureDtdProcessingXmlReaderCreateWrongOverloadTests.cs
src/NetAnalyzers/UnitTests/Microsoft.NetFramework.Analyzers/DoNotUseInsecureDtdProcessingXmlTextReaderConstructedWithNoSecureResolutionTests.cs
src/NetAnalyzers/UnitTests/Microsoft.NetFramework.Analyzers/DoNotUseInsecureDtdProcessingXmlTextReaderSetInsecureResolutionTests.cs
src/NetAnalyzers/UnitTests/Microsoft.NetFramework.Analyzers/Security/MarkVerbHandlersWithValidateAntiforgeryTokenTests.cs

Extracted from #3207 
tagging @dotpaul

[Security] Cleanup tests after test framework migration

---

src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/DisposableFieldsShouldBeDisposed.cs

Use appropriate cancellation token

---

src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/DisposeObjectsBeforeLosingScopeTests.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/DisposeAnalysis/DisposeAnalysis.DisposeDataFlowOperationVisitor.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/DisposeAnalysis/DisposeAnalysis.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/DisposeAnalysis/DisposeAnalysisContext.cs

Update CA2000 to exclude some types

---

src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Security/DoNotAddArchiveItemPathToTheTargetFileSystemPathTests.cs
src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Security/TaintedDataAnalyzerTestBase.cs
src/Test.Utilities/AdditionalMetadataReferences.cs
src/Utilities.UnitTests/FlowAnalysis/Analysis/PropertySetAnalysis/PropertySetAnalysisTests.cs

Remove DiagnosticAnalyzerTestBase

---

src/Roslyn.Diagnostics.Analyzers/UnitTests/DoNotMixAttributesFromDifferentVersionsOfMEFTests.cs
src/Roslyn.Diagnostics.Analyzers/UnitTests/PartsExportedWithMEFv2MustBeMarkedAsSharedTests.cs
src/Test.Utilities/AdditionalMetadataReferences.cs

Fix #3206 thanks to @sharwell 's comment.

Convert last tests to use Test.Utilities.CSharpCodeFixVerifier

---

src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Security/DoNotDisableHttpClientCRLCheck.cs
src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Security/DoNotDisableHttpClientCRLCheckTests.cs
src/Utilities/Compiler/WellKnownTypeNames.cs

Removing CurlHandler from CA5399/CA5400

---

src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Security/ReviewCodeForXmlInjectionVulnerabilitiesTests.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/TaintedDataAnalysis/XmlSanitizers.cs

Fix #3301 and overrides #3302 
Tagging @dotpaul

Update CA3009 to handle AntiXssEncoder

---

src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/IdentifiersShouldNotContainTypeNames.cs
src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/IdentifiersShouldNotContainTypeNamesTests.cs

Update CA1720: Do not report on identifier 'obj'

---

src/PerformanceSensitiveAnalyzers/CSharp/CallSiteImplicitAllocationAnalyzer.cs
src/PerformanceSensitiveAnalyzers/UnitTests/CSharpPerformanceCodeFixVerifier`2.cs
src/PerformanceSensitiveAnalyzers/UnitTests/CallSiteImplicitAllocationAnalyzerTests.cs

Fix #3272
@sharwell is it what you were expecting?

HAA0101 add unit test for empty 'params' in net45

---

src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/NestedTypesShouldNotBeVisible.cs
src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/NestedTypesShouldNotBeVisibleTests.cs

Update CA1034 to allow builder pattern

---

src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/PropertyNamesShouldNotMatchGetMethods.cs
src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/PropertyNamesShouldNotMatchGetMethodsTests.cs

Update CA1721 to exclude obsolete members

---

src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/CollectionPropertiesShouldBeReadOnly.cs
src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/CollectionPropertiesShouldBeReadOnlyTests.cs
src/Utilities/Compiler/WellKnownTypeNames.cs

Update CA2227: Exclude readonly collections

---

src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/Maintainability/CodeMetricsAnalyzer.cs
src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/Maintainability/CodeMetricsAnalyzerTests.cs
src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/Maintainability/CodeMetricsComputationTests.cs
src/Test.Utilities/CodeMetricsTestsBase.cs
src/Utilities/Compiler/CodeMetrics/CodeAnalysisMetricData.AssemblyMetricData.cs
src/Utilities/Compiler/CodeMetrics/CodeAnalysisMetricData.EventMetricData.cs
src/Utilities/Compiler/CodeMetrics/CodeAnalysisMetricData.FieldMetricData.cs
src/Utilities/Compiler/CodeMetrics/CodeAnalysisMetricData.MethodMetricData.cs
src/Utilities/Compiler/CodeMetrics/CodeAnalysisMetricData.NamedTypeMetricData.cs
src/Utilities/Compiler/CodeMetrics/CodeAnalysisMetricData.NamespaceMetricData.cs
src/Utilities/Compiler/CodeMetrics/CodeAnalysisMetricData.PropertyMetricData.cs
src/Utilities/Compiler/CodeMetrics/MetricsHelper.cs
src/Utilities/Compiler/WellKnownTypeNames.cs

Update CA1506: Ignore compiler generated types

---

src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/RemoveEmptyFinalizersTests.cs

Fix unit test and skip it until code is also fixed

---

src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/SpecifyIFormatProvider.cs
src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/SpecifyIFormatProviderTests.cs

Update CA1305 to not report on Guid ToString

---

src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/MicrosoftNetCoreAnalyzersResources.resx
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.cs.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.de.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.es.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.fr.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.it.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ja.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ko.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.pl.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.pt-BR.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ru.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.tr.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.zh-Hans.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.zh-Hant.xlf

TODO: Come up with a nice way to pull localizations from master back into 2.9.x.

Renaming CA5358 to more appropriately reflect its recommendation

---

src/Microsoft.CodeAnalysis.BannedApiAnalyzers/Core/SymbolIsBannedAnalyzer.cs
src/Microsoft.CodeAnalysis.BannedApiAnalyzers/UnitTests/SymbolIsBannedAnalyzerTests.cs

Update RS0030 to report on usage of overriden banned APIs

---

src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/Maintainability/ReviewUnusedParametersTests.cs
src/Utilities/Compiler/Extensions/OperationBlockAnalysisContextExtension.cs

Update CA1801 to handle arrowed methods throwing

---

src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/Maintainability/AvoidDeadConditionalCode.cs
src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/Maintainability/AvoidDeadConditionalCode_NullAnalysis.cs

Update CA1508 to avoid FP with variable declarator in using

---

src/Roslyn.Diagnostics.Analyzers/CSharp/PreferNullLiteral.cs
src/Roslyn.Diagnostics.Analyzers/CSharp/PreferNullLiteralCodeFixProvider.cs
src/Roslyn.Diagnostics.Analyzers/UnitTests/PreferNullLiteralTests.cs

* Support pointer types
* Support `default(T)` in nullable contexts

Improve analysis and fix for default→null

---

src/PublicApiAnalyzers/PublicApiAnalyzers.Help.md

Refine PublicApiAnalyzers multitargeting instructions

---

docs/Analyzer Configuration.md

@mavasani This will make our lives easier :)

Update Analyzer Configuration to simplify merge

---

src/Roslyn.Diagnostics.Analyzers/Core/RoslynDiagnosticsAnalyzersResources.resx
src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.cs.xlf
src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.de.xlf
src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.es.xlf
src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.fr.xlf
src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.it.xlf
src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.ja.xlf
src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.ko.xlf
src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.pl.xlf
src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.pt-BR.xlf
src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.ru.xlf
src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.tr.xlf
src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.zh-Hans.xlf
src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.zh-Hant.xlf

This fires against reference and nullable value types.

Use "nullable" instead of "reference"

---

src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Security/DoNotCallDangerousMethodsInDeserialization.cs
src/Utilities/Compiler/WellKnownTypeNames.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/TaintedDataAnalysis/FilePathInjectionSinks.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/TaintedDataAnalysis/HardcodedCertificateSources.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/TaintedDataAnalysis/ZipSlipSinks.cs

Keeping it consistent.
Targeting 2.9.x.

Fix name of WellKnownTypeNames.SystemIOFile

---

src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Security/DoNotCallDangerousMethodsInDeserialization.cs
src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Security/DoNotCallDangerousMethodsInDeserializationTests.cs

Handle local functions in DoNotCallDangerousMethodsInDeserialization

---

src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/DoNotPassLiteralsAsLocalizedParameters.cs

#3429 caused a build break as its PR validation completed before #3493 was merged in, which has a conflicting API change

Fix build break

---

src/NetAnalyzers/Core/AnalyzerReleases.Unshipped.md
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/MicrosoftNetCoreAnalyzersResources.resx
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Tasks/DoNotCreateTaskCompletionSourceWithWrongArguments.Fixer.cs
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Tasks/DoNotCreateTaskCompletionSourceWithWrongArguments.cs
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.cs.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.de.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.es.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.fr.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.it.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ja.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ko.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.pl.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.pt-BR.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ru.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.tr.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.zh-Hans.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.zh-Hant.xlf
src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Tasks/DoNotCreateTaskCompletionSourceWithWrongArgumentsTests.cs
src/Utilities/Compiler/WellKnownTypeNames.cs

New analyzer for TaskCompletionSource constructor arguments as detailed in dotnet/runtime#30740

Added analyzer for TaskCompletionSource constructor arguments

---

src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/MicrosoftCodeQualityAnalyzersResources.resx
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.cs.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.de.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.es.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.fr.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.it.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.ja.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.ko.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.pl.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.pt-BR.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.ru.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.tr.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.zh-Hans.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.zh-Hant.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Performance/DoNotUseCountWhenAnyCanBeUsed.Fixer.cs
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Performance/DoNotUseCountWhenAnyCanBeUsed.cs

1. Fix the code fix title for CA1827
2. Fix title and resource strings for CA1066. Fixes #3551

Simple fixes

---

src/PublicApiAnalyzers/Core/CodeFixes/DeclarePublicApiFix.cs
src/PublicApiAnalyzers/UnitTests/DeclarePublicApiAnalyzerTests.cs

Fix PublicAPI code fix to avoid duplicate entries from FixAll operations

---

src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/OperatorOverloadsHaveNamedAlternates.cs
src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/DisposeObjectsBeforeLosingScopeTests.cs
src/Text.Analyzers/Core/IdentifiersShouldBeSpelledCorrectly.cs
src/Utilities/Compiler/Options/EditorConfigOptionNames.cs

Some comments still have old links to docs

Fix URLs in comments

---

src/PublicApiAnalyzers/PublicApiAnalyzers.Help.md

FYI @RussKie (thanks for the dogfooding and feedback)

More details on tracking nullability

---

src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/DiagnosticDescriptorCreationAnalyzer.cs
src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/DiagnosticDescriptorCreationAnalyzer_IdRangeAndCategoryValidation.cs
src/Microsoft.CodeAnalysis.Analyzers/UnitTests/MetaAnalyzers/DiagnosticDescriptorCreationAnalyzerTests.cs

Recommended review strategy is commit-by-commit.

Improve maintainability of DiagnosticDescriptorCreationAnalyzerTests

---

src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Tasks/UseValueTasksCorrectly.cs
src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Tasks/UseValueTaskCorrectlyTests.cs

Report a more specific diagnostic message.
Fixes https://github.com/dotnet/roslyn-analyzers/issues/3573

Fix UseValueTasksCorrectly message for discards

---

docs/Analyzer Configuration.md

Clarify package version for .editorconfig support

Update Analyzer Configuration.md

---

README.md
docs/Analyzer Configuration.md
docs/NetCore_GettingStarted.md

These are the steps suggested from Rolsyn devs, learned by our experiences integrated into this page for the future .Net Core devs who wants to implement an analyzer/fixers for this repo first time. Not sure if we want to add the `tips` section of the notes cc @carlossanlop 
Thank you for your contribution @bartonjs @carlossanlop @jeffhandley @mavasani @pgovind @stephentoub  and please review

Getting started page for .Net Core developers

---

src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Data/ReviewSqlQueriesForSecurityVulnerabilities.cs
src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Data/ReviewSQLQueriesForSecurityVulnerabilitiesTests.cs
src/Utilities/Compiler/Options/AnalyzerOptionsExtensions.cs
src/Utilities/FlowAnalysis/Options/AnalyzerOptionsExtensions_FlowAnalysis.cs

Gracefully handle requests to compute options for unsupported symbol kinds
Fixes #3613

Fix NRE in AnalyzerConfigOptions computation

---

azure-pipelines-microbuild.yml

depends on [#3618](https://github.com/dotnet/roslyn-analyzers/pull/3618)

publish nuget packages to a dnceng channel

---

eng/Versions.props

Update coverlet to 2.8.1
Update codecov to 1.10.0

Update code coverage dependencies

---

src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/MicrosoftCodeQualityAnalyzersResources.resx
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.cs.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.de.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.es.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.fr.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.it.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.ja.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.ko.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.pl.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.pt-BR.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.ru.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.tr.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.zh-Hans.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.zh-Hant.xlf

Relates to #3565 
Tagging @mavasani

Update message + desc for CA1710

---

src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/UseIntegralOrStringArgumentForIndexers.cs

CA1043: Perf - Use ImmutableArray instead of ImmutableHashSet

---

src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/PreferJaggedArraysOverMultidimensional.cs
src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/PreferJaggedArraysOverMultidimensionalTests.cs

Update CA1814 to not report on interface member implementation

---

src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/TypeNamesShouldNotMatchNamespaces.cs

The issue in the comment is fixed. It should be okay to re-enable CA1508 for that line.

Enable CA1508

---

src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStatic.Fixer.cs
src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStaticTests.Fixer.cs

Fix CA1822 code fix (Make member static)

---

src/Microsoft.CodeAnalysis.Analyzers/Core/AnalyzerReleases.Unshipped.md
src/Microsoft.CodeAnalysis.Analyzers/Core/CodeAnalysisDiagnosticsResources.resx
src/Microsoft.CodeAnalysis.Analyzers/Core/DiagnosticIds.cs
src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/DiagnosticDescriptorCreationAnalyzer.cs
src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.cs.xlf
src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.de.xlf
src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.es.xlf
src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.fr.xlf
src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.it.xlf
src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.ja.xlf
src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.ko.xlf
src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.pl.xlf
src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.pt-BR.xlf
src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.ru.xlf
src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.tr.xlf
src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.zh-Hans.xlf
src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.zh-Hant.xlf
src/Microsoft.CodeAnalysis.Analyzers/UnitTests/MetaAnalyzers/DiagnosticDescriptorCreationAnalyzerTests.cs

Fix #3575, fix #3576 and fix #3577

Analyze diagnostic title, message and description

---

Directory.Build.props

 Re-enable nullable warning CS8717

---

src/NetAnalyzers/UnitTests/Microsoft.NetFramework.Analyzers/DoNotUseInsecureDtdProcessingAnalyzerTests.cs
src/NetAnalyzers/UnitTests/Microsoft.NetFramework.Analyzers/DoNotUseInsecureDtdProcessingXmlReaderCreateUsingInsecureConstructedXmlReaderSettingsTests.cs
src/NetAnalyzers/UnitTests/Microsoft.NetFramework.Analyzers/DoNotUseInsecureDtdProcessingXmlTextReaderConstructedWithNoSecureResolutionTests.cs

Make unit tests that target a framework version target a framework version

---

src/Microsoft.CodeAnalysis.Analyzers/VisualBasic/VisualBasicUpgradeMSBuildWorkspaceAnalyzer.vb
src/NetAnalyzers/VisualBasic/Microsoft.CodeQuality.Analyzers/QualityGuidelines/BasicRethrowToPreserveStackDetails.vb
src/NetAnalyzers/VisualBasic/Microsoft.NetCore.Analyzers/Runtime/BasicUseOrdinalStringComparison.Fixer.vb
src/Roslyn.Diagnostics.Analyzers/CSharp/CSharpSpecializedEnumerableCreationAnalyzer.cs
src/Roslyn.Diagnostics.Analyzers/Core/SpecializedEnumerableCreationAnalyzer.cs
src/Roslyn.Diagnostics.Analyzers/VisualBasic/BasicSpecializedEnumerableCreationAnalyzer.vb

By manually going through the code, I found there are places where CancellationToken can be used but not actually used. There are more places than this PR, I opened this to get a review on whether I should continue on that or not.

Use CancellationToken whenever possible

---

src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/DiagnosticDescriptorCreationAnalyzer.cs
src/Microsoft.CodeAnalysis.BannedApiAnalyzers/Core/SymbolIsBannedAnalyzer.cs
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/AvoidOutParameters.cs
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/Maintainability/CodeMetricsAnalyzer.cs
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/AvoidZeroLengthArrayAllocations.cs
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/DoNotPassLiteralsAsLocalizedParameters.cs
src/PerformanceSensitiveAnalyzers/CSharp/CallSiteImplicitAllocationAnalyzer.cs
src/PublicApiAnalyzers/Core/CodeFixes/DeclarePublicApiFix.cs
src/Roslyn.Diagnostics.Analyzers/Core/NumberCommentslRefactoring.cs
src/Utilities/Compiler/Analyzer.Utilities.projitems
src/Utilities/Compiler/Index.cs
src/Utilities/Compiler/Options/AnalyzerOptionsExtensions.cs
src/Utilities/Compiler/Options/SymbolNamesWithValueOption.cs
src/Utilities/Compiler/Range.cs
src/Utilities/FlowAnalysis/Extensions/BasicBlockExtensions.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/DisposeAnalysis/DisposeAnalysis.DisposeDataFlowOperationVisitor.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowAnalysis.cs

Define and use Index and Range

---

src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/Maintainability/CodeMetricsAnalyzerTests.cs
src/Utilities/Compiler/Options/SymbolNamesWithValueOption.cs

Fix handling of error types in code metrics

---

src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/IdentifiersShouldHaveCorrectSuffixTests.cs
src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/Maintainability/CodeMetricsAnalyzerTests.cs
src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/AvoidZeroLengthArrayAllocationsTests.cs
src/Tools/RulesetToEditorconfigConverter/Source/RulesetToEditorconfigConverter.csproj
src/Utilities.UnitTests/FlowAnalysis/Analysis/PropertySetAnalysis/PropertySetAnalysisTests.cs
src/Utilities/Compiler/Analyzer.Utilities.projitems
src/Utilities/Compiler/Extensions/StringCompatExtensions.cs
src/Utilities/Compiler/Options/AnalyzerOptionsExtensions.cs
src/Utilities/Compiler/Options/SymbolNamesWithValueOption.cs
src/Utilities/Compiler/RulesetToEditorconfigConverter.cs

Use string APIs from .NET Core

---

src/Utilities.UnitTests/Lightup/LightupHelpersTests.cs
src/Utilities/Compiler/Extensions/IEnumerableExtensions.cs
src/Utilities/Compiler/Lightup/LightupHelpers.cs
src/Utilities/Compiler/Options/SymbolNamesWithValueOption.cs
src/Utilities/Compiler/Options/Unit.cs

Updated nullability annotations

---

src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Performance/DoNotUseCountWhenAnyCanBeUsedTests.Code.cs
src/PublicApiAnalyzers/Core/Analyzers/DeclarePublicApiAnalyzer.cs
src/Roslyn.Diagnostics.Analyzers/Core/NumberCommentslRefactoring.cs
src/Utilities/Compiler/CodeMetrics/CodeAnalysisMetricData.AssemblyMetricData.cs
src/Utilities/Compiler/CodeMetrics/CodeAnalysisMetricData.EventMetricData.cs
src/Utilities/Compiler/CodeMetrics/CodeAnalysisMetricData.NamespaceMetricData.cs
src/Utilities/Compiler/CodeMetrics/CodeAnalysisMetricData.PropertyMetricData.cs
src/Utilities/Compiler/CodeMetrics/CodeAnalysisMetricData.cs
src/Utilities/Compiler/Extensions/IMethodSymbolExtensions.cs
src/Utilities/Compiler/Extensions/IOperationExtensions.cs
src/Utilities/Compiler/Extensions/ISymbolExtensions.cs
src/Utilities/Compiler/Options/CompilationCategorizedAnalyzerConfigOptions.cs
src/Utilities/Compiler/Options/SymbolNamesWithValueOption.cs
src/Utilities/Compiler/PooledObjects/PooledConcurrentDictionary.cs

Should be a straightforward review.

Fix warnings reported by recently added analyzers 

---

README.md

Recommended Visual Studio Version: **Visual Studio 2019 16.0 RTW or later**

Corrected Recommended Visual Studio Version:

---

src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/DisposeObjectsBeforeLosingScope.cs
src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/DisposeObjectsBeforeLosingScopeTests.cs
src/Utilities/FlowAnalysis/Extensions/BasicBlockExtensions.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/DisposeAnalysis/DisposeAnalysis.DisposeDataFlowOperationVisitor.cs

Remove hack in DisposeAnalysis

---

src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/ValidateArgumentsOfPublicMethodsTests.cs
src/Utilities/Compiler/Extensions/IOperationExtensions.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs

Fixes #3716
Also handle the new discard and recursive patterns correctly.
Fixes #2185

Fix dataflow predicate analysis for pattern operations

---

.editorconfig
eng/Versions.props
nuget.config
src/MetaCompilation.Analyzers/Core/CodeFixProvider.cs
src/Microsoft.CodeAnalysis.Analyzers/Core/FixAnalyzers/FixerWithFixAllAnalyzer.Fixer.cs
src/Microsoft.CodeAnalysis.BannedApiAnalyzers/Core/SymbolIsBannedAnalyzer.cs
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/ImplementStandardExceptionConstructors.Fixer.cs
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/TypesThatOwnDisposableFieldsShouldBeDisposable.Fixer.cs
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/UriParametersShouldNotBeStrings.Fixer.cs
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/Maintainability/AvoidUninstantiatedInternalClasses.cs
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/Maintainability/ReviewUnusedParameters.Fixer.cs
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Resources/MarkAssembliesWithNeutralResourcesLanguage.cs
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/DisposableFieldsShouldBeDisposed.cs
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/DoNotPassLiteralsAsLocalizedParameters.cs
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Security/DoNotSerializeTypeWithPointerFields.cs
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Security/PotentialReferenceCycleInDeserializedObjectGraph.cs
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Security/SetViewStateUserKey.cs
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Security/UseAutoValidateAntiforgeryToken.cs
src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Performance/DoNotUseCountWhenAnyCanBeUsedTests.Code.cs
src/NetAnalyzers/VisualBasic/Microsoft.NetCore.Analyzers/Runtime/BasicUseOrdinalStringComparison.Fixer.vb
src/Utilities/Compiler/CodeMetrics/MetricsHelper.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/CopyAnalysis/CopyAnalysis.CopyDataFlowOperationVisitor.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/DisposeAnalysis/DisposeAnalysisHelper.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAnalysis.PointsToDataFlowOperationVisitor.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/TaintedDataAnalysis/TaintedDataAnalysis.TaintedDataOperationVisitor.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/ValueContentAnalysis/ValueContentAnalysis.ValueContentDataFlowOperationVisitor.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/AnalysisEntityBasedPredicateAnalysisData.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DictionaryAnalysisData.cs

FYI: All the nullability related changes are just backports from master branch.

Update analyzer packages and compiler toolset for 2.9.x branch

---

src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/ForwardCancellationTokenToInvocations.Analyzer.cs
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/ForwardCancellationTokenToInvocations.Fixer.cs
src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/ForwardCancellationTokenToInvocationsTests.cs

Fixes https://github.com/dotnet/roslyn-analyzers/issues/3786

Fix CA2016 bugs - diagnostic triggered in edge cases

---

src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/InteropServices/RuntimePlatformCheckAnalyzer.cs
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/MicrosoftNetCoreAnalyzersResources.resx
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.cs.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.de.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.es.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.fr.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.it.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ja.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ko.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.pl.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.pt-BR.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ru.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.tr.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.zh-Hans.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.zh-Hant.xlf

Remote temporary resource strings for RuntimePlatformCheckAnalyzer

---

src/Roslyn.Diagnostics.Analyzers/CSharp/CSharpAvoidOptSuffixForNullableEnableCode.cs
src/Roslyn.Diagnostics.Analyzers/UnitTests/CSharpAvoidOptSuffixForNullableEnableCodeTests.cs

Update RS0046: ignore interface implementation and overrides

---

src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/Maintainability/AvoidDeadConditionalCode.cs

Update CA1508: Explicitly declare second descriptor

---

src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/Maintainability/AvoidDeadConditionalCode_NullAnalysis.cs

CA1508: Add failing tests for string.IsNullXXX

---

src/NetAnalyzers/CSharp/Microsoft.NetCore.Analyzers/Runtime/CSharpForwardCancellationTokenToInvocations.Fixer.cs
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/ForwardCancellationTokenToInvocations.Fixer.cs
src/NetAnalyzers/VisualBasic/Microsoft.NetCore.Analyzers/Runtime/BasicForwardCancellationTokenToInvocations.Fixer.vb

Avoid capturing a mutable list in code action application lambda

---

docs/Analyzer Configuration.md
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStatic.cs
src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStaticTests.cs
src/Utilities/Compiler/Extensions/CompilationExtensions.cs
src/Utilities/Compiler/Options/AbstractCategorizedAnalyzerConfigOptions.cs
src/Utilities/Compiler/Options/AggregateCategorizedAnalyzerConfigOptions.cs
src/Utilities/Compiler/Options/AnalyzerOptionsExtensions.cs
src/Utilities/Compiler/Options/ICategorizedAnalyzerConfigOptions.cs
src/Utilities/Compiler/Options/MSBuildPropertyOptionNames.cs

Do not report CA1812 (Make static) on public APIs for web projects

---

src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Performance/UseCountProperly.cs
src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Performance/PreferIsEmptyOverCountTests.cs

Fixes https://github.com/dotnet/roslyn-analyzers/issues/3810
cc @jeffhandley, @sharwell.

Disallow Span and Memory from CA1836

---

eng/Analyzers_ShippingRules.ruleset

Enable some diagnostics for shipping code

---

src/NetAnalyzers/Core/AnalyzerReleases.Unshipped.md
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/InteropServices/DoNotUseOutAttributeStringPInvokeParameters.cs
src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/InteropServices/DoNotUseOutAttributeStringPInvokeParametersTests.cs

Fix casing of DoNotUseOutAttributeStringPInvokeParametersAnalyzer class name

---

src/Roslyn.Diagnostics.Analyzers/CSharp/CSharpAvoidOptSuffixForNullableEnableCode.cs
src/Roslyn.Diagnostics.Analyzers/UnitTests/CSharpAvoidOptSuffixForNullableEnableCodeTests.cs

Update RS0046 to also report on properties

---

src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Security/ReviewCodeForCommandExecutionVulnerabilitiesTests.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/TaintedDataAnalysis/TaintedDataAnalysis.TaintedDataOperationVisitor.cs

Don't track parameter as a source even if it was tainted if it doesn't flow into a sink argument

---

global.json

allow roll-forward

---

src/NetAnalyzers/Core/AnalyzerReleases.Unshipped.md

I put the publish rules in their own table because they're a bit different from normal analyzers

Fix AnalyzerReleases.Unshipped.md

---

src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/MicrosoftCodeQualityAnalyzersResources.resx
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.cs.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.de.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.es.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.fr.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.it.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.ja.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.ko.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.pl.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.pt-BR.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.ru.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.tr.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.zh-Hans.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.zh-Hant.xlf

Update CA1054, CA1055 and CA1056 resources

---

src/Microsoft.CodeAnalysis.Analyzers/Microsoft.CodeAnalysis.Analyzers.md
src/Microsoft.CodeAnalysis.Analyzers/Microsoft.CodeAnalysis.Analyzers.sarif
src/Microsoft.CodeAnalysis.BannedApiAnalyzers/Microsoft.CodeAnalysis.BannedApiAnalyzers.md
src/Microsoft.CodeAnalysis.FxCopAnalyzers/Microsoft.CodeAnalysis.FxCopAnalyzers.md
src/Microsoft.CodeAnalysis.FxCopAnalyzers/Microsoft.CodeAnalysis.FxCopAnalyzers.sarif
src/Microsoft.CodeAnalysis.VersionCheckAnalyzer/Microsoft.CodeAnalysis.VersionCheckAnalyzer.md
src/Microsoft.CodeQuality.Analyzers/Microsoft.CodeQuality.Analyzers.md
src/Microsoft.CodeQuality.Analyzers/Microsoft.CodeQuality.Analyzers.sarif
src/Microsoft.NetCore.Analyzers/Microsoft.NetCore.Analyzers.md
src/Microsoft.NetCore.Analyzers/Microsoft.NetCore.Analyzers.sarif
src/Microsoft.NetFramework.Analyzers/Microsoft.NetFramework.Analyzers.md
src/Microsoft.NetFramework.Analyzers/Microsoft.NetFramework.Analyzers.sarif
src/NetAnalyzers/Microsoft.CodeAnalysis.NetAnalyzers.md
src/NetAnalyzers/Microsoft.CodeAnalysis.NetAnalyzers.sarif
src/PerformanceSensitiveAnalyzers/Microsoft.CodeAnalysis.PerformanceSensitiveAnalyzers.md
src/PerformanceSensitiveAnalyzers/Microsoft.CodeAnalysis.PerformanceSensitiveAnalyzers.sarif
src/PublicApiAnalyzers/Microsoft.CodeAnalysis.PublicApiAnalyzers.md
src/Roslyn.Diagnostics.Analyzers/Roslyn.Diagnostics.Analyzers.md
src/Tools/GenerateDocumentationAndConfigFiles/Program.cs

Fix #3460
Tagging @Andrew-Webb

Update rules documentation template

---

src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Performance/UseCountProperly.cs
src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Performance/PreferIsEmptyOverCountTests.cs
src/Utilities/Compiler/WellKnownTypeNames.cs

Fixes https://github.com/dotnet/roslyn-analyzers/issues/3954
cc @jeffhandley

CA1836 - Switch to allow list that only specifies concurrent collections

---

src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Security/ReviewCodeForSqlInjectionVulnerabilitiesTests.cs
src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Security/ReviewCodeForXssVulnerabilitiesTests.cs
src/Test.Utilities/SharedTestCode.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/TaintedDataAnalysis/PooledHashSetExtensions.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/TaintedDataAnalysis/SanitizerInfo.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/TaintedDataAnalysis/TaintedDataAnalysis.TaintedDataOperationVisitor.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/TaintedDataAnalysis/TaintedDataSymbolMapExtensions.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/TaintedDataAnalysis/WebInputSources.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/TaintedDataAnalysis/XssSanitizers.cs

#3951 PR retargeted to 2.9.x branch

Support sanitizers that write the sanitized value into output parameter

---

src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/MicrosoftNetCoreAnalyzersResources.resx
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.cs.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.de.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.es.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.fr.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.it.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ja.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ko.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.pl.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.pt-BR.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ru.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.tr.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.zh-Hans.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.zh-Hant.xlf

Update message for CA1838

---

src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/Maintainability/ReviewUnusedParameters.cs
src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/Maintainability/ReviewUnusedParametersTests.cs

Don't report unnamed parameters

---

src/NetAnalyzers/Core/AnalyzerReleases.Shipped.md
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/SpecifyStringComparison.cs

https://github.com/dotnet/roslyn-analyzers/pull/4047 for details

Disable CA1307 by default

---

README.md

See https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md029---ordered-list-item-prefix

Fix code block indentation

---

src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatabilityAnalyzer.cs
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Security/UseContainerLevelAccessPolicy.cs
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Security/UseSharedAccessProtocolHttpsOnly.cs
src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatabilityAnalyzerTests.GuardedCallsTests.cs
src/Utilities/Compiler/Extensions/IOperationExtensions.cs
src/Utilities/FlowAnalysis/Extensions/OperationBlocksExtensions.cs

Fixes #4105
Verified added unit tests for NoDiagnostic cases fail before the fix.

Fix up GetControlFlowGraph extension method for property initializers

---

src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/MicrosoftNetCoreAnalyzersResources.resx
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.cs.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.de.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.es.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.fr.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.it.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ja.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ko.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.pl.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.pt-BR.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ru.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.tr.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.zh-Hans.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.zh-Hant.xlf

Fix CA1309 message

---

src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatabilityAnalyzer.cs

Fixes https://github.com/dotnet/roslyn-analyzers/issues/4117

Fix NRE found in platform compat analyzer

---

src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/MicrosoftNetCoreAnalyzersResources.resx
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/PreferStringContainsOverIndexOf.Fixer.cs
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.cs.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.de.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.es.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.fr.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.it.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ja.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ko.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.pl.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.pt-BR.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ru.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.tr.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.zh-Hans.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.zh-Hant.xlf

CA2249: Rename code fix title

---

src/NetAnalyzers/Core/AnalyzerReleases.Shipped.md
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzer.Data.cs
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzer.OperationVisitor.cs
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzer.Value.cs
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzer.cs
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/MicrosoftNetCoreAnalyzersResources.resx
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.cs.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.de.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.es.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.fr.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.it.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ja.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ko.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.pl.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.pt-BR.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ru.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.tr.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.zh-Hans.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.zh-Hant.xlf
src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzerTests.GuardedCallsTests.cs
src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzerTests.cs

Fix typos, rename analyzer name accordingly

---

src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/MicrosoftCodeQualityAnalyzersResources.resx
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.cs.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.de.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.es.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.fr.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.it.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.ja.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.ko.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.pl.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.pt-BR.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.ru.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.tr.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.zh-Hans.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.zh-Hant.xlf

Fixes #4132
Do I need a parallel doc PR?

CA2231: Update message for clarity

---

src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/DoNotDeclareVisibleInstanceFields.cs
src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/DoNotDeclareVisibleInstanceFieldsTests.cs

Update CA1051 to not report on types marked with StructLayoutAttribute

---

src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/MicrosoftNetCoreAnalyzersResources.resx
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.cs.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.de.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.es.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.fr.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.it.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ja.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ko.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.pl.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.pt-BR.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ru.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.tr.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.zh-Hans.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.zh-Hant.xlf

Clarifying titles / messages

---

docs/Analyzer Configuration.md
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/DoNotDeclareVisibleInstanceFields.cs
src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/DoNotDeclareVisibleInstanceFieldsTests.cs
src/Utilities/Compiler/Options/EditorConfigOptionNames.cs

Update CA1051 to allow user-option to disable struct analysis

---

src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/OperatorOverloadsHaveNamedAlternates.cs
src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/OperatorOverloadsHaveNamedAlternatesTests.cs
src/Utilities/Compiler/Extensions/DiagnosticExtensions.cs

CA2225: array types for implicit and explicit conversions

---

src/Tools/GenerateDocumentationAndConfigFiles/Program.cs
src/Tools/GenerateGlobalAnalyzerConfigs/Program.cs

Respect CodeAnalysisTreatWarningsAsErrors for IDE design-time builds

---

src/NetAnalyzers/CSharp/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/CSharpTypesThatOwnDisposableFieldsShouldBeDisposable.cs
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/TypesThatOwnDisposableFieldsShouldBeDisposable.cs
src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/TypesThatOwnDisposableFieldsShouldBeDisposableTests.cs
src/NetAnalyzers/VisualBasic/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/BasicTypesThatOwnDisposableFieldsShouldBeDisposable.vb

Update CA1001 to display correct list of disposable fields

---

src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Usage/ProvideCorrectArgumentToEnumHasFlag.cs
src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Usage/ProvideCorrectArgumentToEnumHasFlagTests.cs

Update CA2248 to fix issues with generic enum types

---

src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/DoNotCallOverridableMethodsInConstructors.cs
src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/DoNotCallOverridableMethodsInConstructorsTests.cs

Update CA2214 to handle local func

---

src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzerTests.GuardedCallsTests.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs

Default the Visit method to return the value for the operand. Fixes #4190

Fix DataflowOperationVisitor.VisitUnaryOperator

---

src/Directory.Build.props

Enable IDE0055 for vbnet

---

azure-pipelines-microbuild.yml
eng/Publishing.props

V3 publishing 
with default channel : https://dnceng.visualstudio.com/internal/_build/results?buildId=826687&view=results
without default channel : https://dnceng.visualstudio.com/internal/_build/results?buildId=826493&view=results

V3 publishing 

---

docs/Analyzer Configuration.md
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/DoNotUseEnumerableMethodsOnIndexableCollectionsInsteadUseTheCollectionDirectly.cs
src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/DoNotUseEnumerableMethodsOnIndexableCollectionsInsteadUseTheCollectionDirectlyTests.cs
src/Utilities/Compiler/Options/EditorConfigOptionNames.cs

Update CA1826 to add user option to exclude OrDefault methods

---

src/Microsoft.CodeAnalysis.Analyzers/CSharp/MetaAnalyzers/Fixers/CSharpConfigureGeneratedCodeAnalysisFix.cs
src/Microsoft.CodeAnalysis.Analyzers/CSharp/MetaAnalyzers/Fixers/CSharpEnableConcurrentExecutionFix.cs
src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/Fixers/ConfigureGeneratedCodeAnalysisFix.cs
src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/Fixers/EnableConcurrentExecutionFix.cs
src/Microsoft.CodeAnalysis.Analyzers/UnitTests/MetaAnalyzers/ConfigureGeneratedCodeAnalysisAnalyzerTests.cs
src/Microsoft.CodeAnalysis.Analyzers/UnitTests/MetaAnalyzers/EnableConcurrentExecutionAnalyzerTests.cs
src/Microsoft.CodeAnalysis.Analyzers/VisualBasic/MetaAnalyzers/Fixers/BasicConfigureGeneratedCodeAnalysisFix.vb
src/Microsoft.CodeAnalysis.Analyzers/VisualBasic/MetaAnalyzers/Fixers/BasicEnableConcurrentExecutionFix.vb

Handle expression-bodied method in code-fixes for RS1025 and RS1026

---

src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/RethrowToPreserveStackDetailsTests.cs

Improve test coverage for RethrowToPreserveStackDetailsAnalyzer

---

src/Microsoft.CodeAnalysis.Analyzers/CSharp/MetaAnalyzers/CSharpDiagnosticAnalyzerFieldsAnalyzer.cs
src/Microsoft.CodeAnalysis.Analyzers/CSharp/MetaAnalyzers/CSharpReportDiagnosticAnalyzer.cs
src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/DiagnosticAnalyzerCorrectnessAnalyzer.SyntaxNodeWithinAnalyzerTypeCompilationAnalyzer.cs
src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/DiagnosticAnalyzerFieldsAnalyzer.cs
src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/ReportDiagnosticAnalyzer.cs
src/Microsoft.CodeAnalysis.Analyzers/UnitTests/MetaAnalyzers/DoNotStorePerCompilationDataOntoFieldsRuleTests.cs
src/Microsoft.CodeAnalysis.Analyzers/VisualBasic/MetaAnalyzers/BasicDiagnosticAnalyzerFieldsAnalyzer.vb
src/Microsoft.CodeAnalysis.Analyzers/VisualBasic/MetaAnalyzers/BasicReportDiagnosticAnalyzer.vb

Update RS1008 to stop reporting on nested struct

---

src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/ValidateArgumentsOfPublicMethodsTests.cs

CA1062: Add tests for is null or not null patterns

---

src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/ValidateArgumentsOfPublicMethodsTests.cs
src/Utilities/Compiler/WellKnownTypeNames.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/ParameterValidationAnalysis/ParameterValidationAnalysis.ParameterValidationDataFlowOperationVisitor.cs

Update CA1062 to handle NotNullAttribute

---

src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/PredicatedAnalysisData.cs

The linked issue is closed, so I expect the false positive to be fixed.

Remove CA2213 suppression

---

src/Microsoft.CodeAnalysis.BannedApiAnalyzers/UnitTests/RestrictedInternalsVisibleToAnalyzerTests.cs
src/Microsoft.CodeAnalysis.BannedApiAnalyzers/UnitTests/SymbolIsBannedAnalyzerTests.cs

Refactor BannedAnalyzer tests to use markup and span instead of location

---

src/Microsoft.CodeAnalysis.Analyzers/Core/FixAnalyzers/FixerWithFixAllAnalyzer.cs
src/Microsoft.CodeAnalysis.Analyzers/UnitTests/FixAnalyzers/FixerWithFixAllAnalyzerTests.cs

Update RS1010 to not report on overload with nestedActions

---

src/Microsoft.CodeAnalysis.FxCopAnalyzers/Microsoft.CodeAnalysis.FxCopAnalyzers.md
src/Microsoft.CodeAnalysis.FxCopAnalyzers/Microsoft.CodeAnalysis.FxCopAnalyzers.sarif
src/Microsoft.CodeAnalysis.FxCopAnalyzers/RulesMissingDocumentation.md
src/Microsoft.CodeQuality.Analyzers/Microsoft.CodeQuality.Analyzers.md
src/Microsoft.CodeQuality.Analyzers/Microsoft.CodeQuality.Analyzers.sarif
src/Microsoft.CodeQuality.Analyzers/RulesMissingDocumentation.md
src/Microsoft.NetCore.Analyzers/Microsoft.NetCore.Analyzers.md
src/Microsoft.NetCore.Analyzers/Microsoft.NetCore.Analyzers.sarif
src/Microsoft.NetCore.Analyzers/RulesMissingDocumentation.md
src/Microsoft.NetFramework.Analyzers/Microsoft.NetFramework.Analyzers.md
src/Microsoft.NetFramework.Analyzers/Microsoft.NetFramework.Analyzers.sarif
src/NetAnalyzers/Microsoft.CodeAnalysis.NetAnalyzers.md
src/NetAnalyzers/Microsoft.CodeAnalysis.NetAnalyzers.sarif
src/NetAnalyzers/RulesMissingDocumentation.md
src/Utilities/Compiler/DiagnosticDescriptorHelper.cs

Update CA doc links to point to dotnet docs repo

---

src/PerformanceSensitiveAnalyzers/PerformanceSensitiveAnalyzers.md

Add doc on how to resolve the issue in #2371
@sharwell

Add doc for resolving conflict with IVT

---

src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStaticTests.cs

CA1822: Add test for custom SkippableFactAttribute

---

src/Microsoft.CodeAnalysis.Analyzers/UnitTests/MetaAnalyzers/DoNotStorePerCompilationDataOntoFieldsRuleTests.cs

RS1008: Add test for nested struct

---

src/NetAnalyzers/Core/Microsoft.NetFramework.Analyzers/DoNotUseInsecureDtdProcessing.cs
src/NetAnalyzers/UnitTests/Microsoft.NetFramework.Analyzers/DoNotUseInsecureDtdProcessingXmlReaderCreateWrongOverloadTests.cs

Remove more false positives from CA3075

---

src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/CallGCSuppressFinalizeCorrectly.cs
src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/CallGCSuppressFinalizeCorrectlyTests.cs
src/Utilities/Compiler/Extensions/IMethodSymbolExtensions.cs

Fixes #3675
I'm not familiar with the code base here, so I'm not sure if that's a correct fix.

CA1816 shouldn't warn for IAsyncDisposable.DisposeAsync

---

src/Microsoft.CodeAnalysis.Analyzers/CSharp/MetaAnalyzers/CSharpDiagnosticAnalyzerAPIUsageAnalyzer.cs

I'm not sure if this changes behavior or not.

Add RecordDeclaration to IsNamedTypeDeclarationBlock

---

src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/AttributeStringLiteralsShouldParseCorrectly.cs
src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/AttributeStringLiteralsShouldParseCorrectlyTests.cs

CA2243: Update the rule to exclude ObsoleteAttribute.UrlFormat

---

eng/Version.Details.xml
eng/Versions.props
src/Utilities/Compiler/Options/SymbolNamesWithValueOption.cs

This will remove the override of the version of roslyn used to build this repo

Remove explicit dependency on roslyn used to build

---

src/Microsoft.CodeAnalysis.FxCopAnalyzers/RulesMissingDocumentation.md
src/Microsoft.CodeQuality.Analyzers/RulesMissingDocumentation.md
src/NetAnalyzers/Core/AnalyzerReleases.Shipped.md
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/DoNotInitializeUnnecessarily.cs
src/NetAnalyzers/Microsoft.CodeAnalysis.NetAnalyzers.md
src/NetAnalyzers/Microsoft.CodeAnalysis.NetAnalyzers.sarif
src/NetAnalyzers/RulesMissingDocumentation.md

See https://github.com/dotnet/docs/issues/21181 and https://github.com/dotnet/docs/issues/21137 for context

Switch CA1805 from Info to Hidden based on user feedback

---

src/Roslyn.Diagnostics.Analyzers/Core/AbstractDoNotCopyValue.cs
src/Roslyn.Diagnostics.Analyzers/UnitTests/DoNotCopyValueTests.cs

Commit-by-commit is recommended; tests added for each case.

More non-copyable analysis cases

---

src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzerTests.GuardedCallsTests.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/GlobalFlowStateAnalysis/GlobalFlowStateDataFlowOperationVisitor.cs

Handle multiple analyses passes of the visitor

---

.devcontainer/devcontainer.json
.devcontainer/devinit.json

add devcontainer

---

src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/Maintainability/AvoidDeadConditionalCode.cs
src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/Maintainability/AvoidDeadConditionalCode_NullAnalysis.cs
src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/Maintainability/AvoidDeadConditionalCode_ValueContentAnalysis.cs
src/Utilities/FlowAnalysis/Extensions/BasicBlockExtensions.cs
src/Utilities/FlowAnalysis/Extensions/ControlFlowRegionExtensions.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAnalysis.PointsToDataFlowOperationVisitor.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/ValueContentAnalysis/ValueContentAnalysis.ValueContentDataFlowOperationVisitor.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/AnalysisEntityFactory.cs

Recommend reviewing with whitespaces removed: https://github.com/dotnet/roslyn-analyzers/pull/4358/files?diff=unified&w=1
Fixes #4327
Fixes #4382
Fixes #4383
Fixes #4411
Fixes #4415
Fixes #4387

Fix CA1508 bugs

---

docs/Analyzer Configuration.md
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/TypesThatOwnDisposableFieldsShouldBeDisposable.cs
src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/TypesThatOwnDisposableFieldsShouldBeDisposableTests.cs

Update CA1001 to support excluded_symbol_names option

---

src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/Maintainability/AvoidUninstantiatedInternalClasses.cs
src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/Maintainability/AvoidUninstantiatedInternalClassesTests.cs

AvoidUninstantiatedInternalClasses: Don't report on static classes

---

src/Microsoft.CodeAnalysis.FxCopAnalyzers/Microsoft.CodeAnalysis.FxCopAnalyzers.md
src/Microsoft.CodeAnalysis.FxCopAnalyzers/Microsoft.CodeAnalysis.FxCopAnalyzers.sarif
src/Microsoft.NetCore.Analyzers/Microsoft.NetCore.Analyzers.md
src/Microsoft.NetCore.Analyzers/Microsoft.NetCore.Analyzers.sarif
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/MicrosoftNetCoreAnalyzersResources.resx
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.cs.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.de.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.es.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.fr.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.it.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ja.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ko.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.pl.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.pt-BR.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ru.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.tr.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.zh-Hans.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.zh-Hant.xlf
src/NetAnalyzers/Microsoft.CodeAnalysis.NetAnalyzers.md
src/NetAnalyzers/Microsoft.CodeAnalysis.NetAnalyzers.sarif

Converting `Visual?Basic` to `Visual Basic`.

Remove questionable question mark

---

src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/Maintainability/AvoidDeadConditionalCode_NullAnalysis.cs
src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/ValidateArgumentsOfPublicMethodsTests.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAnalysis.PointsToDataFlowOperationVisitor.cs

Fixes #3845. This regressed with c5dd3e42f2ede6888f15b88c310b091a57cd35b6.

Param array parameters can be null

---

src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/Maintainability/AvoidDeadConditionalCode_NullAnalysis.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs

Fix predicate analysis for IsNullOrXXX method calls

---

src/Tools/GenerateGlobalAnalyzerConfigs/Program.cs

- Changing the message from using the, grammatically incorrect, `then` to use `than`
- Changing the message from using passive voice to active voice

Updating package upgrade message

---

src/Tools/GenerateAnalyzerNuspec/Program.cs

Fixes #4441
~~I'll most likely re-write the commit history to ease review, so no need to review while it's still draft.~~ Done.

Fix disabled warnings in GenerateAnalyzerNuspec

---

src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/CollectionPropertiesShouldBeReadOnly.cs
src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/CollectionPropertiesShouldBeReadOnlyTests.cs
src/Utilities/Compiler/Analyzer.Utilities.projitems
src/Utilities/Compiler/Lightup/IMethodSymbolExtensions.cs

Update CA2227 to not report on init only property

---

src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/SealMethodsThatSatisfyPrivateInterfaces.cs
src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/SealMethodsThatSatisfyPrivateInterfacesTests.cs

CA2119: Fix false negative with extended interface

---

docs/Analyzer Configuration.md
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/CancellationTokenParametersMustComeLast.cs
src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/CancellationTokenParametersMustComeLastTests.cs

Update CA1068 to handle api_surface option

---

src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/CompareSymbolsCorrectlyAnalyzer.cs
src/Microsoft.CodeAnalysis.Analyzers/UnitTests/MetaAnalyzers/CompareSymbolsCorrectlyTests.cs

Fix NRE in RS1024

---

src/Utilities/Compiler/BoundedCache.cs

Remove unnecessary suppression

---

docs/Analyzer Configuration.md

Update doc links in Analyzer Configuration.md

---

docs/Analyzer Configuration.md

Fix and unify markdown usage in 'Analyzer Configuration.md'

---

src/Tools/GenerateDocumentationAndConfigFiles/Program.cs

Follow-up to https://github.com/dotnet/sdk/pull/14833 towards addressing part of https://github.com/dotnet/roslyn/issues/49250#issuecomment-736879786
Apart from reading `AnalysisLevelSuffix`, we also support reading the `AnalysisMode` property for back compat and also allow additional property values `Minimum` and `Recommended`.

Add support for reading AnalysisLevelSuffix

---

src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/Maintainability/AvoidDeadConditionalCode_NullAnalysis.cs
src/Utilities/Compiler/Lightup/ITypeSymbolExtensions.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PointsToAnalysis/DefaultPointsToValueGenerator.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAnalysis.PointsToDataFlowOperationVisitor.cs

Recommend to review by commit-by-commit
Fixes #4509
Fixes #4548

Couple of fixes for CA1508

---

src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/MicrosoftNetCoreAnalyzersResources.resx
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Usage/ProvideCorrectArgumentToEnumHasFlag.cs
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.cs.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.de.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.es.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.fr.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.it.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ja.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ko.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.pl.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.pt-BR.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ru.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.tr.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.zh-Hans.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.zh-Hant.xlf
src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Usage/ProvideCorrectArgumentToEnumHasFlagTests.cs

Remove second descriptor because of FP rate

---

src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/CompareSymbolsCorrectlyAnalyzer.cs
src/Microsoft.CodeAnalysis.Analyzers/UnitTests/MetaAnalyzers/CompareSymbolsCorrectlyTests.cs

RS1024: fix false positive on object creation

---

src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/DisposeObjectsBeforeLosingScopeTests.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/AnalysisEntityFactory.cs

Remove workaround in AnalysisEntityFactory for a possible IOperation bug

---

src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Security/DoNotDisableCertificateValidation.cs

Fixes #2009 and overrides #4594

[2.9.x] Remove stale TODO comment

---

src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/MicrosoftNetCoreAnalyzersResources.resx
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.cs.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.de.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.es.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.fr.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.it.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ja.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ko.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.pl.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.pt-BR.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ru.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.tr.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.zh-Hans.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.zh-Hant.xlf
src/NetAnalyzers/Microsoft.CodeAnalysis.NetAnalyzers.md
src/NetAnalyzers/Microsoft.CodeAnalysis.NetAnalyzers.sarif

Fix CA2016 message

---

src/Microsoft.CodeAnalysis.Analyzers/CSharp/MetaAnalyzers/CSharpDiagnosticAnalyzerAPIUsageAnalyzer.cs
src/Microsoft.CodeAnalysis.Analyzers/UnitTests/MetaAnalyzers/StartActionWithNoRegisteredActionsRuleTests.cs
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/DoNotRaiseExceptionsInUnexpectedLocations.cs
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/ImplementIDisposableCorrectly.cs
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/OperatorOverloadsHaveNamedAlternates.cs
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/Maintainability/CodeMetricsAnalyzer.cs
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/DoNotLockOnObjectsWithWeakIdentity.cs
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/DoNotUseEnumerableMethodsOnIndexableCollectionsInsteadUseTheCollectionDirectly.cs
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/SerializationRulesDiagnosticAnalyzer.cs
src/PublicApiAnalyzers/Core/Analyzers/DeclarePublicApiAnalyzer.Impl.cs
src/Roslyn.Diagnostics.Analyzers/CSharp/CSharpSpecializedEnumerableCreationAnalyzer.cs
src/Utilities/Compiler/CodeMetrics/MetricsHelper.cs
src/Utilities/Compiler/Extensions/IMethodSymbolExtensions.cs
src/Utilities/Compiler/Extensions/IOperationExtensions.cs
src/Utilities/Compiler/Extensions/ITypeSymbolExtensions.cs
src/Utilities/Compiler/WellKnownTypeProvider.cs
src/Utilities/Compiler/WordParser.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/CopyAnalysis/CopyAbstractValueKind.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAnalysis.PointsToDataFlowOperationVisitor.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/AnalysisEntity.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/MapAbstractDomain.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/PredicatedAnalysisData.cs
src/Utilities/FlowAnalysis/Options/DisposeAnalysisKind.cs

Merge 2.9.x to master

---

src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.de.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.es.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.fr.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.it.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.ja.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.ko.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.pl.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.pt-BR.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.ru.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.tr.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.zh-Hans.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.zh-Hant.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.cs.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.de.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.es.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.fr.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.it.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ja.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ko.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.pl.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.pt-BR.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ru.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.tr.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.zh-Hans.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.zh-Hant.xlf
src/PublicApiAnalyzers/Core/Analyzers/xlf/PublicApiAnalyzerResources.pt-BR.xlf

[Loc] Latest translations

---

eng/Versions.props
src/Microsoft.CodeAnalysis.Analyzers/UnitTests/InternalImplementationOnlyTests.cs
src/Microsoft.CodeAnalysis.BannedApiAnalyzers/UnitTests/RestrictedInternalsVisibleToAnalyzerTests.cs
src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/IdentifiersShouldNotContainTypeNamesTests.cs
src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/Maintainability/AvoidUninstantiatedInternalClassesTests.cs
src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/Maintainability/ReviewUnusedParametersTests.cs
src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Security/DoNotDisableCertificateValidationTests.cs

* Update to Microsoft.CodeAnalysis.Testing 1.0.1-beta1.20623.3
* Simplify code using `SolutionTransforms` to set `OutputKind`
* Simplify code using `SolutionTransforms` to create additional projects

Update to Microsoft.CodeAnalysis.Testing 1.0.1-beta1.20623.3

---

src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStatic.cs
src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStaticTests.cs

MarkMembersAsStatic: Exclude indexers

---

.github/ISSUE_TEMPLATE/bug-report.md
PostReleaseActivities.md
VERSIONING.md
eng/Versions.props
src/NetAnalyzers/Microsoft.CodeAnalysis.NetAnalyzers.sarif

https://github.com/dotnet/roslyn-analyzers/releases/tag/5.0.3

Post release activities for NetAnalyzers release 5.0.3

---

src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/UsePropertiesWhereAppropriate.cs
src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/UsePropertiesWhereAppropriateTests.cs

Exclude GetPinnableReference from CA1024 analysis

---

src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/AvoidZeroLengthArrayAllocations.cs
src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/AvoidZeroLengthArrayAllocationsTests.cs

CA1825: Bail-out for expression trees

---

src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/OverrideGetHashCodeOnOverridingEqualsTests.cs

Delete unneeded skipped tests

---

src/NetAnalyzers/Core/Microsoft.NetFramework.Analyzers/DoNotUseInsecureXSLTScriptExecution.cs
src/NetAnalyzers/UnitTests/Microsoft.NetFramework.Analyzers/DoNotUseInsecureXSLTScriptExecutionXslCompiledTransformLoadInsecureConstructedSettingsTests.cs

Fix NRE in CA3076

---

src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/CollectionPropertiesShouldBeReadOnly.cs
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/EnumStorageShouldBeInt32.cs
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/EnumWithFlagsAttribute.cs
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/EnumsShouldHaveZeroValue.cs
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/MarkAttributesWithAttributeUsage.cs
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/UseGenericEventHandlerInstances.cs
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/Maintainability/DoNotIgnoreMethodResults.cs
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStatic.cs
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/SerializationRulesDiagnosticAnalyzer.cs
src/Text.Analyzers/Core/EnumsShouldHavePluralNames.cs

Simplify code to use HasAttribute extension method

---

src/Roslyn.Diagnostics.Analyzers/CSharp/CSharpApplyTraitToClass.cs
src/Roslyn.Diagnostics.Analyzers/Core/AbstractApplyTraitToClass`1.cs
src/Roslyn.Diagnostics.Analyzers/Core/RoslynDiagnosticsAnalyzersResources.resx
src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.cs.xlf
src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.de.xlf
src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.es.xlf
src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.fr.xlf
src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.it.xlf
src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.ja.xlf
src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.ko.xlf
src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.pl.xlf
src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.pt-BR.xlf
src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.ru.xlf
src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.tr.xlf
src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.zh-Hans.xlf
src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.zh-Hant.xlf
src/Roslyn.Diagnostics.Analyzers/UnitTests/ApplyTraitToClassTests.cs
src/Roslyn.Diagnostics.Analyzers/VisualBasic/VisualBasicApplyTraitToClass.vb
src/Utilities/Compiler/Analyzer.Utilities.projitems
src/Utilities/Compiler/IsExternalInit.cs
src/Utilities/Compiler/WellKnownTypeNames.cs

Implement 'Apply trait to class' refactoring

---

src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/Fixers/AnalyzerReleaseTrackingFix.cs
src/Microsoft.CodeAnalysis.Analyzers/ReleaseTrackingAnalyzers.Help.md
src/Microsoft.CodeAnalysis.Analyzers/UnitTests/MetaAnalyzers/ReleaseTrackingAnalyzerTests.cs

Fixes #4131
@mavasani this PR could be considered as a breaking-change so we probably don't want to target master but I am not sure which of the preview branch to target.

Update the release analyzer fixer to add a blank line after headers

---

src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/OperatorOverloadsHaveNamedAlternates.Fixer.cs
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/MicrosoftCodeQualityAnalyzersResources.resx
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.cs.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.de.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.es.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.fr.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.it.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.ja.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.ko.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.pl.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.pt-BR.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.ru.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.tr.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.zh-Hans.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.zh-Hant.xlf

Add new resource key for CA2225 fixer

---

README.md

Add build badges for Ubuntu

---

src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/MicrosoftCodeQualityAnalyzersResources.resx
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.cs.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.de.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.es.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.fr.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.it.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.ja.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.ko.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.pl.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.pt-BR.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.ru.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.tr.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.zh-Hans.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.zh-Hant.xlf

@Evangelink @sharwell This will probably make the other PR shorter and easier to review.

Delete unused resources

---

README.md

Update latest pre-release link for Microsoft.CodeAnalysis.Analyzers

---

src/PublicApiAnalyzers/Core/CodeFixes/AnnotatePublicApiFix.cs
src/PublicApiAnalyzers/Core/CodeFixes/DeclarePublicApiFix.cs
src/PublicApiAnalyzers/Core/CodeFixes/NullableEnablePublicApiFix.cs
src/PublicApiAnalyzers/Core/CodeFixes/PublicApiFixHelpers.cs
src/PublicApiAnalyzers/UnitTests/DeclarePublicApiAnalyzerTests.cs

Fix line endings for public api fixers

---

src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/MicrosoftNetCoreAnalyzersResources.resx
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Security/DoNotCallDangerousMethodsInDeserialization.cs
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.cs.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.de.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.es.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.fr.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.it.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ja.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ko.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.pl.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.pt-BR.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ru.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.tr.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.zh-Hans.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.zh-Hant.xlf
src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Security/DoNotCallDangerousMethodsInDeserializationTests.cs
src/Utilities/Compiler/SymbolDisplayStringCache.cs

CA5360: Show potential invocations to reach potentially dangerous method

---

eng/Analyzers_ShippingRules.ruleset
eng/Versions.props

Disable rules which cause severe build-time overhead.

Faster build

---

eng/Versions.props
src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzerTests.cs

Add regression test for PlatformCompatabilityAnalyzer timely termination

---

.github/ISSUE_TEMPLATE/bug-report.md

I noticed some issues being reported that were already fixed in the latest NuGet package, but hasn't yet shipped into the SDK.
Hoping this note can eliminate the number of these reports.

Add note to bug-report template

---

src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/DoNotDirectlyAwaitATask.Fixer.cs
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/DoNotDirectlyAwaitATask.cs
src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/DoNotDirectlyAwaitATaskTests.cs
src/Utilities/Compiler/Analyzer.Utilities.projitems
src/Utilities/Compiler/Lightup/IOperationWrapper.cs
src/Utilities/Compiler/Lightup/IUsingDeclarationOperationWrapper.cs
src/Utilities/Compiler/Lightup/IUsingOperationExtensions.cs
src/Utilities/Compiler/Lightup/LightupHelpers.cs
src/Utilities/Compiler/Lightup/OperationKindEx.cs
src/Utilities/Compiler/Lightup/OperationWrapperHelper.cs
src/Utilities/Compiler/WellKnownTypeNames.cs
src/Utilities/Workspaces/DocumentBasedFixAllProvider.cs
src/Utilities/Workspaces/FixAllContextHelper.cs
src/Utilities/Workspaces/Workspaces.Utilities.projitems

Support 'await using' in CA2007 (DoNotDirectlyAwaitATask)

---

src/Microsoft.CodeAnalysis.Analyzers/CSharp/MetaAnalyzers/Fixers/CSharpPreferIsKindFix.cs
src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/PreferIsKindAnalyzer.cs
src/Microsoft.CodeAnalysis.Analyzers/UnitTests/MetaAnalyzers/PreferIsKindAnalyzerTests.cs
src/Microsoft.CodeAnalysis.Analyzers/VisualBasic/MetaAnalyzers/Fixers/BasicPreferIsKindFix.vb

Handle conditional access in PreferIsKind analyzer

---

src/Microsoft.CodeAnalysis.Analyzers/Setup/Microsoft.CodeAnalysis.Analyzers.Setup.csproj
src/Microsoft.CodeAnalysis.BannedApiAnalyzers/Setup/Microsoft.CodeAnalysis.BannedApiAnalyzers.Setup.csproj
src/NetAnalyzers/Setup/Microsoft.CodeAnalysis.NetAnalyzers.Setup.csproj
src/PerformanceSensitiveAnalyzers/Setup/Microsoft.CodeAnalysis.PerformanceSensitiveAnalyzers.Setup.csproj
src/PublicApiAnalyzers/Setup/Microsoft.CodeAnalysis.PublicApiAnalyzers.Setup.csproj
src/Roslyn.Diagnostics.Analyzers/Setup/Roslyn.Diagnostics.Analyzers.Setup.csproj
src/Text.Analyzers/Setup/Text.Analyzers.Setup.csproj

This independent change was extracted from features/source-build.

Remove unused build properties

---

eng/GenerateAnalyzerNuspec.targets
src/Tools/GenerateAnalyzerNuspec/GenerateAnalyzerNuspec.csproj
src/Tools/GenerateDocumentationAndConfigFiles/GenerateDocumentationAndConfigFiles.csproj
src/Tools/GenerateDocumentationAndConfigFiles/Program.cs

This independent change was extracted from features/source-build.

Build private tools with net5.0

---

eng/Versions.props
src/Microsoft.CodeAnalysis.ResxSourceGenerator/Microsoft.CodeAnalysis.ResxSourceGenerator.UnitTests/ResxGeneratorTests.cs
src/Microsoft.CodeAnalysis.ResxSourceGenerator/Microsoft.CodeAnalysis.ResxSourceGenerator.UnitTests/Verifiers/CSharpSourceGeneratorVerifier`1+Test.cs
src/Test.Utilities/CSharpCodeFixVerifier`2+Test.cs
src/Test.Utilities/CSharpCodeRefactoringVerifier`1+Test.cs
src/Test.Utilities/CSharpSecurityCodeFixVerifier`2+Test.cs
src/Test.Utilities/VisualBasicCodeFixVerifier`2+Test.cs
src/Test.Utilities/VisualBasicCodeRefactoringVerifier`1+Test.cs
src/Test.Utilities/VisualBasicSecurityCodeFixVerifier`2+Test.cs

* Simplify application of compilation and parse options
* Update to Microsoft.CodeAnalysis.Testing 1.0.1-beta1.21202.2

Update to Microsoft.CodeAnalysis.Testing 1.0.1-beta1.21202.2

---

Directory.Build.props

Enable strict mode

---

src/PublicApiAnalyzers/Core/Analyzers/DeclarePublicApiAnalyzer.Impl.cs
src/PublicApiAnalyzers/UnitTests/DeclarePublicApiAnalyzerTests.cs

Fixes https://github.com/dotnet/roslyn-analyzers/issues/1192

Handle open generics forwarded types in public api analyzers

---

Directory.Build.props
nuget/Microsoft.CodeAnalysis.AnalyzerUtilities/Microsoft.CodeAnalysis.AnalyzerUtilities.Package.csproj
nuget/Microsoft.CodeAnalysis.Analyzers/Microsoft.CodeAnalysis.Analyzers.Package.csproj
nuget/Microsoft.CodeAnalysis.BannedApiAnalyzers/Microsoft.CodeAnalysis.BannedApiAnalyzers.Package.csproj
nuget/Microsoft.CodeAnalysis.Metrics/Microsoft.CodeAnalysis.Metrics.Package.csproj
nuget/Microsoft.CodeAnalysis.RulesetToEditorconfigConverter/Microsoft.CodeAnalysis.RulesetToEditorconfigConverter.Package.csproj
nuget/NetAnalyzers/Microsoft.CodeAnalysis.NetAnalyzers.Package.csproj
nuget/PublicApiAnalyzers/Microsoft.CodeAnalysis.PublicApiAnalyzers.Package.csproj
nuget/Roslyn.Diagnostics.Analyzers/Roslyn.Diagnostics.Analyzers.Package.csproj
nuget/Text.Analyzers/Text.Analyzers.Package.csproj

@mavasani what is the set of nuget packages that we ship on nuget? What else needs to be included here?

mark packages as shipping/not shipping

---

azure-pipelines.yml

Ubuntu 16.04 queue will be turned off.

Move to Ubuntu 18.04 queue

---

src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/Maintainability/UseNameofInPlaceOfString.cs
src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/Maintainability/UseNameOfInPlaceOfStringTests.cs

Closes #3023
Closes #3115 (they look like an exact dupe)

Remove dead condition

---

Directory.Build.props
eng/GenerateAnalyzerNuspec.targets
src/Tools/GenerateAnalyzerNuspec/Program.cs

Fixes https://github.com/dotnet/roslyn-analyzers/issues/5054

iconUrl -> icon

---

src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/IdentifiersShouldHaveCorrectSuffix.cs
src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/IdentifiersShouldHaveCorrectSuffixTests.cs

Fixes https://github.com/dotnet/roslyn-analyzers/issues/5035

Correctly give higher priority to user's suffix map

---

src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/DoNotRaiseExceptionsInUnexpectedLocations.cs
src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/DoNotRaiseExceptionsInUnexpectedLocationsTests.cs

#5021 CA1065 Enhancement: Report on more operators

---

src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/ReportDiagnosticAnalyzer.cs
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Security/DoNotCallDangerousMethodsInDeserialization.cs
src/Tools/Metrics/Program.cs
src/Utilities/FlowAnalysis/Extensions/ControlFlowBranchExtensions.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs

Hello,
This pull request is _very simple_ and aims to reduce the technical debt. It specifically targets the following rules:
SonarQube:
- "IEnumerable LINQs should be simplified" [rule](https://rules.sonarsource.com/csharp/RSPEC-2971)
ReSharper:
- "Merge sequential checks in && or || expressions" [rule](https://www.jetbrains.com/help/resharper/MergeSequentialChecks.html)
- "Replace if statement with null-propagating code" [rule](https://www.jetbrains.com/help/resharper/UseNullPropagation.html)

Refactors code to reduce technical debt

---

azure-pipelines-microbuild.yml

Fixes #5136
@jmarolf - I think this is all that is necessary to address #5136.  Is it alright to queue a test build?  If so please provide any special instructions I should follow.

Add source build leg to official build

---

src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Tasks/DoNotCreateTaskCompletionSourceWithWrongArguments.cs
src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Tasks/DoNotCreateTaskCompletionSourceWithWrongArgumentsTests.cs

Fixes https://github.com/dotnet/roslyn-analyzers/issues/5135

Fix CA2247 handling of base(TaskContinuationOptions)

---

azure-pipelines-microbuild.yml

Turns on automated localization PRs from OneLocBuild. See documentation [here](https://github.com/dotnet/arcade/blob/main/Documentation/OneLocBuild.md).
cc/ @sharwell @jmarolf

Turn on loc PRs

---

src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStatic.cs
src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStaticTests.Fixer.cs

Fix CA1822 false positive with partial methods

---

azure-pipelines-perf.yml
eng/perf/CIPerf.cmd
eng/perf/ComparePerfResults.ps1
eng/perf/DiffPerfToBaseLine.ps1
eng/perf/PerfCore.ps1
eng/perf/RunPerfTests.ps1
eng/perf/baseline.json
global.json
src/Tools/PerfDiff/BDN/BenchmarkDotNetDiffer.cs
src/Tools/PerfDiff/PerfDiff.cs
src/Tools/PerfDiff/Program.cs

small script fixes and adding yaml file

adding perf yaml file

---

eng/perf/ComparePerfResults.ps1
eng/perf/DiffPerfToBaseLine.ps1
eng/perf/PerfCore.ps1
eng/perf/RunPerfTests.ps1
src/Tools/PerfDiff/BDN/BenchmarkDotNetDiffer.cs
src/Tools/PerfDiff/PerfDiff.cs
src/Tools/PerfDiff/Program.cs

add return code logging

---

src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/EnumShouldNotHaveDuplicatedValues.cs

Remove dead code in CA1069 analyzer

---

src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.zh-Hans.xlf

Loc/zh-hans: 过载 -> 重载

---

src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStaticTests.cs

Refactor tests to use non-obsolete location API

---

src/NetAnalyzers/Core/Microsoft.NetFramework.Analyzers/DoNotUseInsecureDtdProcessing.cs

Refactor or conditions in DoNotUseInsecureDtdProcessingAnalyzer

---

src/Microsoft.CodeAnalysis.BannedApiAnalyzers/UnitTests/SymbolIsBannedAnalyzerTests.cs

I have updated a part of the BannedApiAnalyzer test code.
I think this code makes the part about Location more explicit.

[refactor] test's location

---

azure-pipelines-perf.yml
eng/perf/baseline.json
src/PerformanceTests/Tests/Enabled/CSharp_CA2255.cs

updating baseline to include new tests
fixes https://github.com/dotnet/roslyn-analyzers/issues/5381

reset perf baseline

---

src/Tools/GenerateDocumentationAndConfigFiles/Program.cs

fix casing on unix

---

src/PublicApiAnalyzers/Core/Analyzers/PublicApiAnalyzerResources.resx
src/PublicApiAnalyzers/Core/Analyzers/xlf/PublicApiAnalyzerResources.cs.xlf
src/PublicApiAnalyzers/Core/Analyzers/xlf/PublicApiAnalyzerResources.de.xlf
src/PublicApiAnalyzers/Core/Analyzers/xlf/PublicApiAnalyzerResources.es.xlf
src/PublicApiAnalyzers/Core/Analyzers/xlf/PublicApiAnalyzerResources.fr.xlf
src/PublicApiAnalyzers/Core/Analyzers/xlf/PublicApiAnalyzerResources.it.xlf
src/PublicApiAnalyzers/Core/Analyzers/xlf/PublicApiAnalyzerResources.ja.xlf
src/PublicApiAnalyzers/Core/Analyzers/xlf/PublicApiAnalyzerResources.ko.xlf
src/PublicApiAnalyzers/Core/Analyzers/xlf/PublicApiAnalyzerResources.pl.xlf
src/PublicApiAnalyzers/Core/Analyzers/xlf/PublicApiAnalyzerResources.pt-BR.xlf
src/PublicApiAnalyzers/Core/Analyzers/xlf/PublicApiAnalyzerResources.ru.xlf
src/PublicApiAnalyzers/Core/Analyzers/xlf/PublicApiAnalyzerResources.tr.xlf
src/PublicApiAnalyzers/Core/Analyzers/xlf/PublicApiAnalyzerResources.zh-Hans.xlf
src/PublicApiAnalyzers/Core/Analyzers/xlf/PublicApiAnalyzerResources.zh-Hant.xlf
src/PublicApiAnalyzers/Microsoft.CodeAnalysis.PublicApiAnalyzers.md
src/PublicApiAnalyzers/Microsoft.CodeAnalysis.PublicApiAnalyzers.sarif

Update docs on how to record removed API

---

src/NetAnalyzers/Core/AnalyzerReleases.Shipped.md
src/NetAnalyzers/VisualBasic/AnalyzerReleases.Shipped.md
src/Tools/GenerateDocumentationAndConfigFiles/Program.cs

looks like these markdown pages were never updated

support analysis level 6

---

azure-pipelines-microbuild.yml

adding required variable groups

---

src/Tools/PerfDiff/BDN/BenchmarkDotNetDiffer.cs

getting reports of false positives so I am increasing the noise threshold

increase noise threshold to 35% to reduce probability of a false positive

---

src/Tools/GenerateDocumentationAndConfigFiles/Program.cs

Escape asterisks when generating markdown doc files

---

src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/DetectPreviewFeatureAnalyzer.cs
src/NetAnalyzers/Microsoft.CodeAnalysis.NetAnalyzers.md
src/NetAnalyzers/Microsoft.CodeAnalysis.NetAnalyzers.sarif
src/NetAnalyzers/RulesMissingDocumentation.md

This will round out the initial development of CA2252.

Make CA2252 an error

---

src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/ValidateArgumentsOfPublicMethodsTests.cs

Add test for ??= operator

---

nuget/Microsoft.CodeAnalysis.Metrics/Microsoft.CodeAnalysis.Metrics.targets

[Code Metrics] Add quotes to project and out argument

---

src/PerformanceTests/Utilities/ReferenceAssemblies/ReferenceAssemblies.csproj
src/Test.Utilities/Test.Utilities.csproj
src/TestReferenceAssembly/TestReferenceAssembly.csproj
src/Utilities.UnitTests/Analyzer.Utilities.UnitTests.csproj

Exclude test projects from source-build

---

src/Microsoft.CodeAnalysis.BannedApiAnalyzers/UnitTests/SymbolIsBannedAnalyzerTests.cs

Deleted the unused System using from BannedApiAnalyzer's Unit test.

[delete] unused using directive

---

src/Tools/GenerateAnalyzerNuspec/Program.cs

Remove Eula.rtf from NuGet packages

---

src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Security/DoNotAlwaysSkipTokenValidationInDelegates.cs

Remove dead code from `DoNotAlwaysSkipTokenValidationInDelegates`

---

src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/DisposableTypesShouldDeclareFinalizer.cs

This was discussed recently on Discord.

Remove unneeded `Shared` attribute

---

src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/SpecifyIFormatProvider.cs
src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/SpecifyIFormatProviderTests.cs

porting https://github.com/dotnet/roslyn-analyzers/pull/5374 to rc2

Add support for CA1305 suppression.

---

src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/DoNotCallOverridableMethodsInConstructors.cs
src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/DoNotCallOverridableMethodsInConstructorsTests.cs

Fixes https://github.com/dotnet/roslyn-analyzers/issues/5286

Fix false positive for calling virtual member of other instance

---

.github/workflows/milestone-tracking.yml

Implements the following rule, but does not enable the mutation at this point.

Add milestone tracking automation (mutation disabled)

---

.github/workflows/milestone-tracking.yml

Fix expected repository name

---

.github/workflows/milestone-tracking.yml

Fixes the error which occurred here:
https://github.com/dotnet/roslyn-analyzers/actions/runs/1285213404

Pass GITHUB_TOKEN to automation workflow

---

.github/workflows/milestone-tracking.yml

* Pass milestone name to `jq` since environment variables do not expand within single-quoted strings
* Enable mutation to assign milestone

Enable release tracking

---

.github/workflows/community-pr.yml

Label community pull requests

---

.github/workflows/community-pr.yml

Fix query and filter logic for labeling community PRs

---

src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.cs.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.de.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.es.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.fr.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.it.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.ja.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.ko.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.pl.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.pt-BR.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.ru.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.tr.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.zh-Hans.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.zh-Hant.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.cs.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.de.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.es.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.fr.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.it.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ja.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ko.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.pl.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.pt-BR.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ru.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.tr.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.zh-Hans.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.zh-Hant.xlf

A few loc strings got missed. Will need to ask permission to merge these in tactics

Update Loc strings for .NET Analyzers

---

src/Tools/GenerateDocumentationAndConfigFiles/Program.cs

Follow up to dotnet/source-build#2483 (comment)

ensure globalconfig files are lowercase (.NET 6 RTM)

---

src/Tools/GenerateDocumentationAndConfigFiles/Program.cs

Follow up to https://github.com/dotnet/source-build/issues/2483#issuecomment-934501469

ensure globalconfig files are lowercase

---

src/NetAnalyzers/CSharp/Microsoft.CodeQuality.Analyzers/QualityGuidelines/CSharpDoNotInitializeUnnecessarily.Fixer.cs
src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/DoNotInitializeUnnecessarilyTests.cs

Fixes https://github.com/dotnet/roslyn-analyzers/issues/5412

Fix CA1805 missing trivia

---

src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/PreferDictionaryContainsMethods.cs
src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/PreferDictionaryContainsMethodsTests.cs

Fix #5718
I have added only one test, let me know if you want me to add the various tests I did on this PR #4522

CA1841: do not report on expression tree contexts

---

NuGet.config
azure-pipelines-microbuild.yml
azure-pipelines.yml

Per https://github.com/dotnet/core-eng/issues/14276.

Switch to 1ES servicing pools on release/5.0.3xx

---

src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Performance/UseCountProperly.cs
src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Performance/UsePropertyInsteadOfCountMethodWhenAvailableTests.cs

CA1827 CA1829 CA1836: Do not report within expression tree

---

Directory.Build.props
azure-pipelines.yml
eng/Testing.props
eng/Versions.props

initial step to track down flakyness in the CI pipline

Blame hangs and crashes

---

src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/InteropServices/DynamicInterfaceCastableImplementation.Fixer.cs

this fixes some test failure flakyness

do not break in tests

---

src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/Maintainability/AvoidDeadConditionalCode_ValueContentAnalysis.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs

Fixes https://github.com/dotnet/roslyn-analyzers/issues/5747
Fixes https://github.com/dotnet/roslyn-analyzers/issues/5154
@mavasani Can you review please?

Handle var pattern correctly in data flow analysis

---

eng/Versions.props

Update version of `coverlet.msbuild`, this should help reducing chance of flaky ci.

Update coverlet.msbuild version

---

docs/NetCore_GettingStarted.md

Some doc updates needed for testing a new analyzer in runtime / roslyn-analyzers repo

Update doc part: testing the new analyzer in runtime/roslyn-analyzers repo

---

src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/AvoidOutParameters.cs
src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/AvoidOutParametersTests.cs

Don't report CA1021 (Avoid out parameter) for overrides and interface implementations

---

src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/AvoidOutParameters.cs
src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/AvoidOutParametersTests.cs

Use api_surface = all for CA1021 tests

---

azure-pipelines-richnav.yml

Test Run: https://dev.azure.com/dnceng/public/_build/results?buildId=1614379&view=logs&j=67047ecc-22cf-5e69-553e-e3e9198dea49

Fix RichNav image

---

azure-pipelines-perf.yml
eng/Versions.props
src/PerformanceTests/Tests/Enabled/CSharp_CA2252.cs
src/PerformanceTests/Utilities/ReferenceAssemblies/Generated.targets
src/PerformanceTests/Utilities/ReferenceAssemblies/Net60.cs
src/PerformanceTests/Utilities/ReferenceAssemblies/Net60Resources.cs

Add CA2252 benchmark

---

src/Roslyn.Diagnostics.Analyzers/CSharp/CSharpRunIterations.cs
src/Roslyn.Diagnostics.Analyzers/Core/AbstractRunIterations`1.cs
src/Roslyn.Diagnostics.Analyzers/Core/RoslynDiagnosticsAnalyzersResources.resx
src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.cs.xlf
src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.de.xlf
src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.es.xlf
src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.fr.xlf
src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.it.xlf
src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.ja.xlf
src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.ko.xlf
src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.pl.xlf
src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.pt-BR.xlf
src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.ru.xlf
src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.tr.xlf
src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.zh-Hans.xlf
src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.zh-Hant.xlf
src/Roslyn.Diagnostics.Analyzers/UnitTests/RunIterationsTests.cs
src/Roslyn.Diagnostics.Analyzers/VisualBasic/VisualBasicRunIterations.vb
src/Utilities/Compiler/WellKnownTypeNames.cs

Simplifies the process of converting a test to run multiple iterations.

Add "Run iterations" refactoring

---

src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/MicrosoftCodeQualityAnalyzersResources.resx
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/AvoidMultipleEnumerations/AvoidMultipleEnumerations.cs
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/AvoidMultipleEnumerations/AvoidMultipleEnumerationsHelpers.cs
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.cs.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.de.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.es.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.fr.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.it.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.ja.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.ko.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.pl.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.pt-BR.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.ru.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.tr.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.zh-Hans.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.zh-Hant.xlf
src/NetAnalyzers/Microsoft.CodeAnalysis.NetAnalyzers.md
src/NetAnalyzers/Microsoft.CodeAnalysis.NetAnalyzers.sarif
src/NetAnalyzers/RulesMissingDocumentation.md

Address the comments in this PR
https://github.com/dotnet/roslyn-analyzers/pull/5907

Address some remaining nits

---

src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/MicrosoftCodeQualityAnalyzersResources.resx
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/AvoidMultipleEnumerations/AvoidMultipleEnumerations.cs
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.cs.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.de.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.es.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.fr.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.it.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.ja.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.ko.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.pl.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.pt-BR.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.ru.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.tr.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.zh-Hans.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.zh-Hant.xlf
src/NetAnalyzers/Microsoft.CodeAnalysis.NetAnalyzers.md
src/NetAnalyzers/Microsoft.CodeAnalysis.NetAnalyzers.sarif
src/NetAnalyzers/RulesMissingDocumentation.md

Address https://github.com/dotnet/roslyn-analyzers/pull/5907#discussion_r825181565

Add message title back

---

src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzer.cs
src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzerTests.GuardedCallsTests.cs

Contributes to https://github.com/dotnet/roslyn-analyzers/issues/5938, fixes Case 2:
```cs
public class Test
{
[SupportedOSPlatform("ios")]
public void M1()
{
[|M2()|];
if(OperatingSystem.IsIOS() && !OperatingSystem.IsIOSVersionAtLeast(13, 0))
{
M2();
return;
}
M3(); // should not warn as ios 13.0 or below case returns within above contions
}
[SupportedOSPlatform("ios")]
[UnsupportedOSPlatform("ios13.0")]
[SupportedOSPlatform("tvos")]
[UnsupportedOSPlatform("tvos13.0")]
public void M2() { }
[SupportedOSPlatform("ios13.0")]
[SupportedOSPlatform("tvos13.0")]
public void M3() { }
}
```
The `if(OperatingSystem.IsIOS() && !OperatingSystem.IsIOSVersionAtLeast(13, 0))` condition could be false if current platform is not iOS, and the warning on `M3()` call would be valid. But the call site (`M1`) …

Fix false positive case: 2 mentioned in #5938

---

src/Microsoft.CodeAnalysis.Analyzers/Core/AnalyzerReleases.Shipped.md

Order releases in AnalyzerReleases.Shippsed.md

---

src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/ForwardCancellationTokenToInvocations.Analyzer.cs
src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/ForwardCancellationTokenToInvocationsTests.cs

Fixes #5965
I originally had this as part of the blocked PR #5865.
I'll revise #5865 to see if there are any other bugs it revealed and fix them separately.

Fix NRE for __arglist

---

src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/MarkAssembliesWithAttributesDiagnosticAnalyzer.cs
src/NetAnalyzers/Microsoft.CodeAnalysis.NetAnalyzers.sarif

See https://github.com/dotnet/runtime/issues/44194 for more details

Disable CA1014 for AllEnabledByDefault analysis mode

---

README.md

Update pre-release links

---

src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/UsePropertiesWhereAppropriate.cs
src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/UsePropertiesWhereAppropriateTests.cs

Do not report on members marked as extern

---

docs/Analyzer Configuration.md
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/UriParametersShouldNotBeStrings.cs
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/UriPropertiesShouldNotBeStrings.cs
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/UriReturnValuesShouldNotBeStrings.cs
src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/UriParametersShouldNotBeStringsTests.cs
src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/UriPropertiesShouldNotBeStringsTests.cs
src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/UriReturnValuesShouldNotBeStringsTests.cs

CA1054: CA1055: CA1056: Allow excluded_symbol_names option

---

src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/IdentifiersShouldHaveCorrectSuffix.cs

Cleanup of PR 4619

---

src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/MicrosoftCodeQualityAnalyzersResources.resx
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.cs.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.de.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.es.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.fr.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.it.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.ja.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.ko.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.pl.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.pt-BR.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.ru.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.tr.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.zh-Hans.xlf
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.zh-Hant.xlf

CA1812: Update message

---

src/Roslyn.Diagnostics.Analyzers/Core/RoslynDiagnosticsAnalyzersResources.resx
src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.cs.xlf
src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.de.xlf
src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.es.xlf
src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.fr.xlf
src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.it.xlf
src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.ja.xlf
src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.ko.xlf
src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.pl.xlf
src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.pt-BR.xlf
src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.ru.xlf
src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.tr.xlf
src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.zh-Hans.xlf
src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.zh-Hant.xlf
src/Roslyn.Diagnostics.Analyzers/Roslyn.Diagnostics.Analyzers.md
src/Roslyn.Diagnostics.Analyzers/Roslyn.Diagnostics.Analyzers.sarif
src/Roslyn.Diagnostics.Analyzers/RulesMissingDocumentation.md

Refine RS0034 diagnostic title and message to describe public visibility requirement

---

azure-pipelines-perf.yml
eng/Versions.props

Addresses [compliance issue](https://dnceng.visualstudio.com/internal/_componentGovernance/dotnet-roslyn-analyzers/alert/7073665?typeId=6250578) (microsoft)

Update Newtonsoft.Json version to 13.0.1

---

src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/AvoidPropertySelfAssignment.cs

Remove IDE0055 (fix formatting) suppression

---

eng/Versions.props
src/Tools/Metrics/Metrics.Legacy.csproj
src/Tools/Metrics/Metrics.csproj

See https://github.com/dotnet/roslyn-analyzers/issues/6150 for details.

Fix metrics

---

src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/DisposableFieldsShouldBeDisposedTests.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/DisposeAnalysis/DisposeAnalysis.DisposeDataFlowOperationVisitor.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/DisposeAnalysis/DisposeAnalysis.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/DisposeAnalysis/DisposeAnalysisContext.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/DisposeAnalysis/DisposeAnalysisHelper.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs

CA2213: Fix false positive on disposable field

---

src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/DisposeObjectsBeforeLosingScopeTests.cs
src/Utilities/Compiler/Analyzer.Utilities.projitems
src/Utilities/Compiler/Lightup/INegatedPatternOperationWrapper.cs
src/Utilities/Compiler/Lightup/OperationWrapperHelper.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs

Issue 4981: Add support for 'is not null'

---

azure-pipelines.yml

Follow internal recommendations and switch build image.
cc @mavasani (this is following some internal email).

Update name of build image

---

azure-pipelines.yml

Reverts dotnet/roslyn-analyzers#6210

Revert "Update name of build image"

---

eng/Versions.props
global.json
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/DoNotRaiseReservedExceptionTypes.cs
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/PreferDictionaryContainsMethods.cs
src/NetAnalyzers/Core/Microsoft.NetFramework.Analyzers/Helpers/SyntaxNodeHelper.cs
src/PerformanceTests/Utilities/ReferenceAssemblies/ResourceLoader.cs
src/PublicApiAnalyzers/Core/Analyzers/DeclarePublicApiAnalyzer.cs
src/Tools/GenerateDocumentationAndConfigFiles/JsonWriter.cs
src/Utilities.UnitTests/FlowAnalysis/Analysis/PropertySetAnalysis/PropertySetAnalysisTests.cs
src/Utilities/Compiler/Extensions/IOperationExtensions.cs
src/Utilities/Compiler/WordParser.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PropertySetAnalysis/PropertySetAnalysis.PropertySetDataFlowOperationVisitor.TrackedAssignmentData.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PropertySetAnalysis/PropertySetAnalysis.PropertySetDataFlowOperationVisitor.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PropertySetAnalysis/PropertySetAnalysis.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/TaintedDataAnalysis/TaintedDataAnalysis.TaintedDataOperationVisitor.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/TaintedDataAnalysis/TaintedDataSymbolMapExtensions.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/AnalysisEntityDataFlowOperationVisitor.cs
src/Utilities/FlowAnalysis/SingleThreadedConcurrentDictionary.cs

Move from .NET 7 RC1 to .NET 7.0.101

---

eng/Versions.props

Dogfood latest 7.0.0 analyzers

---

README.md

Fixes https://github.com/dotnet/roslyn-analyzers/issues/6107

Update "Getting Started" section with VS 2022 requirement

---

src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Performance/DoNotGuardDictionaryRemoveByContainsKey.cs

Use `WalkDownParentheses` to simplify code

---

README.md

Update README.md for .NET 8 SDK update

---

src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/UseAsyncMethodInAsyncContext.cs

Refactor UseAsyncMethodInAsyncContext

---

docs/NetCore_GettingStarted.md

Cleans up Getting Started docs and adds some msbuild binary log information for future developers.

Update Getting Started docs

---

src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/UseExceptionThrowHelpers.cs
src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/UseExceptionThrowHelpersTests.cs

Contributes to https://github.com/dotnet/runtime/issues/82667

Update CA1512 for new ThrowIfEqual and ThrowIfNotEqual methods

---

src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/MicrosoftNetCoreAnalyzersResources.resx
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.cs.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.de.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.es.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.fr.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.it.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ja.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ko.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.pl.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.pt-BR.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ru.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.tr.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.zh-Hans.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.zh-Hant.xlf
src/NetAnalyzers/Microsoft.CodeAnalysis.NetAnalyzers.md
src/NetAnalyzers/Microsoft.CodeAnalysis.NetAnalyzers.sarif
src/NetAnalyzers/RulesMissingDocumentation.md

Improve message for CA2013

---

eng/Versions.props
src/NetAnalyzers/Microsoft.CodeAnalysis.NetAnalyzers.sarif

The version for new `release/7.0.3xx` branch needs to be bumped up, please let me know if anything else needs update

Update version for release/7.0.3xx branch

---

.editorconfig
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/IdentifiersShouldHaveCorrectPrefix.cs
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/MarkAttributesWithAttributeUsage.cs
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/MovePInvokesToNativeMethodsClass.cs
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStatic.cs
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/InteropServices/UseValidPlatformString.cs
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/DoNotDefineFinalizersForTypesDerivedFromMemoryManager.cs
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/ForwardCancellationTokenToInvocations.Analyzer.cs
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/PreferAsSpanOverSubstring.cs
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/PreferStringContainsOverIndexOfAnalyzer.cs
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/TestForEmptyStringsUsingStringLength.cs
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/UseSpanBasedStringConcat.cs
src/NetAnalyzers/Core/Microsoft.NetFramework.Analyzers/DoNotUseInsecureXSLTScriptExecution.cs
src/Utilities/Compiler/Analyzer.Utilities.projitems
src/Utilities/Compiler/Extensions/IEnumerableOfIMethodSymbolExtensions.cs
src/Utilities/Compiler/Extensions/ISymbolExtensions.cs
src/Utilities/Compiler/Options/AbstractCategorizedAnalyzerConfigOptions.cs
src/Utilities/Compiler/Options/AggregateCategorizedAnalyzerConfigOptions.cs
src/Utilities/Compiler/Options/AnalyzerOptionsExtensions.cs
src/Utilities/Compiler/Options/ICategorizedAnalyzerConfigOptions.cs
src/Utilities/Compiler/PooledObjects/TemporaryDictionary`2.cs
src/Utilities/Compiler/PooledObjects/TemporarySet`1.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAbstractValue.cs

Addresses several allocation issues observed in AB#1815692

Allocation optimizations from feedback ticket

---

eng/Versions.props
src/NetAnalyzers/Microsoft.CodeAnalysis.NetAnalyzers.sarif

The version for new release/7.0.4xx branch needs to be bumped up

Update the version of new release/7.0.4xx branch

---

src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/OperatorOverloadsHaveNamedAlternates.cs
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/UseLiteralsWhereAppropriate.cs
src/NetAnalyzers/VisualBasic/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/BasicOverrideEqualsOnOverloadingOperatorEquals.vb

Address remaining feedback from #6690

Address remaining feedback from #6690

---

src/NetAnalyzers/CSharp/Microsoft.NetCore.Analyzers/Runtime/CSharpDoNotUseStackallocInLoops.cs
src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/DoNotUseStackallocInLoopsTests.cs

Don't emit CA2014 when stackalloc is in loop initializer

---

src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/TypesThatOwnDisposableFieldsShouldBeDisposable.cs
src/Utilities/Compiler/PooledObjects/TemporarySet`1.cs

Fix race condition in CA1001 analyzer

---

src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/Maintainability/AvoidDeadConditionalCode_ValueContentAnalysis.cs
src/Utilities/Compiler/Extensions/ITypeSymbolExtensions.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAnalysis.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/ValueContentAnalysis/ValueContentAnalysis.ValueContentDataFlowOperationVisitor.cs

Handle default expression value properly in Value content analysis

---

src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/Maintainability/AvoidDeadConditionalCode_NullAnalysis.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAnalysis.PointsToDataFlowOperationVisitor.cs

Bail out from conversion inference for user-defined conversions

---

src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/Maintainability/AvoidDeadConditionalCode_NullAnalysis.cs

Add test for fixed CA1508 issue

---

src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/Maintainability/AvoidDeadConditionalCode_ValueContentAnalysis.cs

Closes #6483
Verified that the issue repros on slightly older NetAnalyzers Nuget package, but is fixed in the main branch.

Add test for fixed CA1508 false positive

---

src/NetAnalyzers/CSharp/Microsoft.CodeQuality.Analyzers/Maintainability/CSharpAvoidDeadConditionalCode.cs
src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/Maintainability/AvoidDeadConditionalCode.cs
src/NetAnalyzers/Microsoft.CodeAnalysis.NetAnalyzers.sarif
src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/Maintainability/AvoidDeadConditionalCode_NullAnalysis.cs
src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/Maintainability/AvoidDeadConditionalCode_ValueContentAnalysis.cs
src/NetAnalyzers/VisualBasic/Microsoft.CodeQuality.Analyzers/Maintainability/BasicAvoidDeadConditionalCode.vb

Handle lowered IsPattern operation generated for switch expression arms

---

src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/AvoidMultipleEnumerationsTests.cs
src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzerTests.GuardedCallsTests.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/GlobalFlowStateAnalysis/GlobalFlowStateDataFlowOperationVisitor.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowAnalysis.cs
src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs

Skip exceptions path analysis post pass for global flow analysis

---

nuget/Microsoft.CodeAnalysis.Analyzers/Microsoft.CodeAnalysis.Analyzers.Package.csproj
src/Microsoft.CodeAnalysis.Analyzers/readme.md

Add README file to Microsoft.CodeAnalysis.Analyzers NuGet package

---

docs/NetCore_GettingStarted.md
docs/Performance.md

This pull request addresses and corrects several grammatical errors found throughout the codebase.
The changes include fixing typos, punctuation, and ensuring proper sentence structure for improved readability and clarity.
No functional changes have been made; this is purely a maintenance update.

docs(grammatical): correct typos

---

src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/MicrosoftNetCoreAnalyzersResources.resx
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.cs.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.de.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.es.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.fr.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.it.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ja.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ko.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.pl.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.pt-BR.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ru.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.tr.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.zh-Hans.xlf
src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.zh-Hant.xlf
src/NetAnalyzers/Microsoft.CodeAnalysis.NetAnalyzers.sarif

Remove an extra space in the title of the rule CA5402.

Remove extra space

---

src/NetAnalyzers/CSharp/Microsoft.NetCore.Analyzers/Performance/CSharpPreferDictionaryTryMethodsOverContainsKeyGuardFixer.cs
src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Performance/PreferDictionaryTryGetValueMethodsTests.cs

Preserve code style during fix

---

Directory.Build.props
eng/GenerateAnalyzerNuspec.targets
eng/Versions.props
src/Directory.Build.props
src/Directory.Build.targets
src/Microsoft.CodeAnalysis.Analyzers/UnitTests/Microsoft.CodeAnalysis.Analyzers.UnitTests.csproj
src/NetAnalyzers/UnitTests/Microsoft.CodeAnalysis.NetAnalyzers.UnitTests.csproj
src/PerformanceTests/Utilities/CSharp/CSharpPerfUtilities.csproj
src/PerformanceTests/Utilities/Common/CommonPerfUtilities.csproj
src/PerformanceTests/Utilities/ReferenceAssemblies/ReferenceAssemblies.csproj
src/PerformanceTests/Utilities/VisualBasic/VisualBasicPerfUtilities.csproj
src/Roslyn.Diagnostics.Analyzers/UnitTests/Roslyn.Diagnostics.Analyzers.UnitTests.csproj
src/Test.Utilities/Test.Utilities.csproj
src/Text.Analyzers/UnitTests/Text.Analyzers.UnitTests.csproj
src/Tools/GenerateDocumentationAndConfigFiles/GenerateDocumentationAndConfigFiles.csproj
src/Tools/GenerateDocumentationAndConfigFilesForBrokenRuntime/GenerateDocumentationAndConfigFilesForBrokenRuntime.csproj
src/Tools/Metrics/Metrics.Legacy.csproj
src/Tools/Metrics/Metrics.csproj
src/Tools/ReleaseNotesUtil/ReleaseNotesUtil.csproj
src/Tools/RulesetToEditorconfigConverter/Source/RulesetToEditorconfigConverter.csproj

This repo only required a straight port from A->B

Unified Build control update

---

eng/GenerateAnalyzerNuspec.targets

We were only doing this for source-build before but it makes sense to turn this on for any VMR build.

Use offline validation for any kind of VMR build

---

azure-pipelines-microbuild.yml

Official build run: https://dnceng.visualstudio.com/internal/_build/results?buildId=2431322&view=results

Replace deprecated CI image

---

azure-pipelines-microbuild.yml

Add policheck to official pipelines

Add policheck enablement

---

eng/TSAConfig.gdntsa

Turns on TSA reporting for this repository

Enable TSA reporting
