- BuildAndTest.proj
Don't deploy VS extensions when running BuildAndTest.proj. Since we only run
unit tests, there's no need to do this step.
This also avoids issues when the extension can't be updated for whatever reason.
> Don't deploy extensions during BuildAndTest

- src/Test/Utilities/DiagnosticsTestUtilities.csproj
- src/Test/Utilities/packages.config
Fix test failure caused by improperly signed Microsoft.CodeAnalysis.Test.Resources.Proprietary.dll
on machine not skipping SN verification.
@tmeschter @srivatsn
> Update reference to NuGet package

- src/MetaCompilation/MetaCompilation/MetaCompilation.Test/UnitTests.cs
- src/MetaCompilation/MetaCompilation/MetaCompilation/CodeFixProvider.cs
- src/MetaCompilation/MetaCompilation/MetaCompilation/DiagnosticAnalyzer.cs
Fix issue #233 
Any code fix that creates immutable array also inserts rule arguments
EXCEPT if the invocation expression itself is wrong eg
"ImmutableArary.Equals()"
@daking2014  @jepetty
> Code fix that creates immutable array also inserts rule arguments

- src/FxCop/Desktop.Analyzers/Core/DesktopAnalyzers.csproj
- src/FxCop/Desktop.Analyzers/Core/DesktopAnalyzers.nuspec
- src/FxCop/Desktop.Analyzers/Core/ThirdPartyNotices.rtf
- src/FxCop/Desktop.Analyzers/Core/install.ps1
- src/FxCop/Desktop.Analyzers/Core/uninstall.ps1
- src/FxCop/Desktop.Analyzers/NuGet/DesktopAnalyzers.NuGet.proj
- src/FxCop/System.Runtime.Analyzers/Core/SystemRuntimeAnalyzers.nuspec
- src/Packaging/Packaging.proj
- Make content of existing nuspec files identical to their counterpart in dotnet/roslyn repo.
- Add Nuget authoring to Desktop.Analyzers.
@tmeschter @srivatsn @mavasani @lgolding
> Fix issues of NuGet arthoring projects in FxCop analyzers

- build/Targets/Analyzers.Imports.targets
Add support for signing files.
If a file has been delay-signed and we're real-signing the build, we
create a <FilesToSign> item pointing at the output binary. The Microsoft
build systems will use this to sign the appropriate binaries at the end
of a project build.
Note that this currently only supports signing .dll and .exe binaries;
it does not yet support signing .vsix files.
> Add support for signing files

- build/Targets/Analyzers.Imports.targets
Fix how we compute the signed file name.
Right now we're computing a property, OutputExtension, based on
OutputType. We're also using another property, OutputName, which doesn't
actually exist as it turns out.
Instead, use TargetFileName.
> Fix signed file name

- build/Targets/Analyzers.Imports.targets
Fix Authenticode signing. The wrong item metadata was being set to
indicate the certificate to use. We need to set the `<Authenticode>`
metadata, not `<AuthenticodeCertficateName>`.
> Fix Authenticode signing

- src/Roslyn/Core/ApiDesign/DeclarePublicAPIAnalyzer.Impl.cs
- src/Roslyn/Core/ApiDesign/DeclarePublicAPIAnalyzer.cs
- src/Roslyn/Test/ApiDesign/DeclarePublicAPIAnalyzerTests.cs
- src/Test/Utilities/DiagnosticAnalyzerTestBase.cs
The logic for detecting a removed API in the unshipped API text was
comparing against the full entry.  This meant it compared the calculated
name to the stored name + the removed prefix.  Updated to compare
against the correct name.
There was a unit test to catch this case but the unit tests themselves
weren't functioning correctly.  They didn't include the error because it
was in an additional document.  Updated the unit test to report this
type of error.
> Correct removed api logic

- src/AnalyzerPowerPack/Core/Design/CA1052DiagnosticAnalyzer.cs
- src/AnalyzerPowerPack/Test/Design/CA1052Tests.cs
CA1053 behavior differs from original FxCop version: if a class has a base class it is still qualified as a static holder, while the original FxCop's version leaves this class be:
public class C23Base
{ }
public class C23 : C23Base
{
public static void Foo()
{ }
}
> CA1052: class with a base class shouldn't be considered static holder.

- src/Roslyn/Core/Documentation/DoNotUseVerbatimCrefsAnalyzer.cs
> Check if the syntax list has any elements before calling .First()

- src/FxCop/System.Runtime.Analyzers/Test/Performance/AvoidUnsealedAttributesTests.Fixer.cs
Unskip a unit test. The underlying issue was fixed long ago, though
the test itself needed a little fixing up.
> Unskip a unit test

- src/FxCop/System.Runtime.Analyzers/CSharp/CSharpSystemRuntimeAnalyzers.csproj
- src/FxCop/System.Runtime.Analyzers/CSharp/Design/TypesThatOwnDisposableFieldsShouldBeDisposable.cs
- src/FxCop/System.Runtime.Analyzers/Core/Design/TypesThatOwnDisposableFieldsShouldBeDisposable.Fixer.cs
- src/FxCop/System.Runtime.Analyzers/Core/Design/TypesThatOwnDisposableFieldsShouldBeDisposable.cs
- src/FxCop/System.Runtime.Analyzers/Test/Design/TypesThatOwnDisposableFieldsShouldBeDisposableTests.Fixer.cs
- src/FxCop/System.Runtime.Analyzers/Test/Design/TypesThatOwnDisposableFieldsShouldBeDisposableTests.cs
- src/FxCop/System.Runtime.Analyzers/VisualBasic/BasicSystemRuntimeAnalyzers.vbproj
- src/FxCop/System.Runtime.Analyzers/VisualBasic/Design/TypesThatOwnDisposableFieldsShouldBeDisposable.vb
CA1001 analyzer was triggering on non-disposable type declarations with any field that implements
`IDisposable`. This fix changes this behavior to resemble its FxCop counterpart, which only fires a warning if the disposable field member is created within the type definition (i.e. either initialized when field
is declared or an object is created by a `new` oprator and assigned to the field in this type's methods). Also modify fixer tests due to this change.
This fix partially addresses https://github.com/dotnet/roslyn-analyzers/issues/281.
@srivatsn @tmeschter @lgolding @mavasani
> Fix false positive on CA1001 analyzer

- README.md
- src/AnalyzerPowerPack/AnalyzerPowerPack.md
- src/AsyncPackage/AsyncPackage.md
- src/CodeAnalysis/Microsoft.CodeAnalysis.Analyzers.md
- src/FxCop/Desktop.Analyzers/Desktop.Analyzers.md
- src/FxCop/System.Runtime.Analyzers/System.Runtime.Analyzers.md
- src/FxCop/System.Runtime.InteropServices.Analyzers/System.Runtime.InteropServices.Analyzers.md
- src/Roslyn/Microsoft.Net.RoslynDiagnostics.md
Add project-specific documentation. At the moment this documentation
is just a list of diagnostics produced by a set of analyzers with
some basic information--ID, title, description, etc. A simple tool
was created to produce this documentation in Markdown format.
The main README.md has been updated to point to this information.
> Add project-specific docs

- src/AnalyzerPowerPack/AnalyzerPowerPack.md
- src/AsyncPackage/AsyncPackage.md
- src/CodeAnalysis/Microsoft.CodeAnalysis.Analyzers.md
- src/FxCop/Desktop.Analyzers/Desktop.Analyzers.md
- src/FxCop/System.Runtime.Analyzers/System.Runtime.Analyzers.md
- src/FxCop/System.Runtime.InteropServices.Analyzers/System.Runtime.InteropServices.Analyzers.md
- src/Roslyn/Microsoft.Net.RoslynDiagnostics.md
Fix project docs. Right now the "Category" and "Severity" lines display
on the same line when viewed on GitHub.com. Fix this by adding a blank
link between them so they render as separate paragraphs.
> Fix project docs

- src/MetaCompilation/MetaCompilation/MetaCompilation/ReadMe.md
Github is escaping "\\." which in turn renders as an incorrect as the path should be src\\.nuget\NuGetRestore.ps1 and not src.nuget\NuGetRestore.ps1
> Updated readme instructions

- src/Roslyn/Core/ApiDesign/DeclarePublicAPIAnalyzer.cs
- src/Roslyn/Core/RoslynDiagnosticIds.cs
- src/Roslyn/Core/RoslynDiagnosticsResources.Designer.cs
- src/Roslyn/Core/RoslynDiagnosticsResources.resx
- src/Roslyn/Test/ApiDesign/DeclarePublicAPIAnalyzerTests.cs
- src/Test/Utilities/DiagnosticAnalyzerTests.Extensions.cs
Currently, the DeclarePublicAPIAnalyzer does not expect the same symbol
to occur more than once, either within a public API file or across
files. If this happens the analyzer throws an exception in its
compilation start action and fails to actually check the API.
This change updates the analyzer to look out for duplicated symbols and
create a diagnostic to bring the issue to the attention of the user.
Fixes #312.
> Look for duplicated symbols in public API files

- src/FxCop/Desktop.Analyzers/Core/DesktopAnalyzersResources.Designer.cs
- src/FxCop/Desktop.Analyzers/Core/DesktopAnalyzersResources.resx
- src/FxCop/Desktop.Analyzers/Core/Security/CompilationSecurityTypes.cs
- src/FxCop/Desktop.Analyzers/Core/Security/DoNotUseInsecureCryptographicAlgorithmsAnalyzer.cs
- src/FxCop/Desktop.Analyzers/Core/Security/SecurityTypes.cs
- src/FxCop/Desktop.Analyzers/Test/Security/DoNotUseInsecureCryptographicAlgorithmsTests.cs
Remove Rijndael according to security development adviser. The algorithm is not absolutely insecure. We will revisit it and need to collect more info to make a diagnostic.
> Remove Rijndael according to security development adviser

- PortFxCop/src/Analyzer.Utilities/Analyzer.Utilities.csproj
It was referring to target files used by existing projects.
@heejaechang
> Fix the location of target files used by shared analyzer utility project

- PortFxCop/src/Microsoft.ApiDesignGuidelines.Analyzers/Core/MicrosoftApiDesignGuidelinesAnalyzersResources.Designer.cs
- PortFxCop/src/Microsoft.ApiDesignGuidelines.Analyzers/Core/MicrosoftApiDesignGuidelinesAnalyzersResources.resx
- PortFxCop/src/Microsoft.ApiDesignGuidelines.Analyzers/UnitTests/OverloadOperatorEqualsOnOverridingValueTypeEqualsTests.cs
- PortFxCop/src/Microsoft.ApiDesignGuidelines.Analyzers/UnitTests/OverrideMethodsOnComparableTypesTests.cs
My previous change where I had simply copied files over broke some tests because the tests had hardcoded the message of the diagnostic to test instead of reading from the resource file. The stub generator created resource files with the original strings from FxCop and those are different from what the analyzers had implemented. Most tests are fine because they read the expected value from the resx files as well, expect for some tests below.
There was one more case where the number of holes in the strings differed between the FxCop string and the analyzer. I've restored it to the original analyzer's string
> Fixing up some resource strings that were hardcoded

- src/FxCop/Desktop.Analyzers/Core/DesktopAnalyzersResources.Designer.cs
- src/FxCop/Desktop.Analyzers/Core/DesktopAnalyzersResources.resx
- src/FxCop/Desktop.Analyzers/Core/Security/DoNotCatchCorruptedStateExceptionsAnalyzer.cs
- src/FxCop/Desktop.Analyzers/Core/Security/DoNotUseInsecureCryptographicAlgorithmsAnalyzer.cs
- src/FxCop/Desktop.Analyzers/Core/Shared/DiagnosticHelpers.cs
- src/FxCop/Desktop.Analyzers/Test/Security/DoNotUseInsecureCryptographicAlgorithmsTests.cs
@genlu @srivatsn 
This is the pull request to update the crypto rules' (CA5350, CA5351) message strings so that all algorithms have a same user-facing string pattern.
And also updated help link of CA2153.
See https://microsoft.sharepoint.com/teams/CESecEngineering/SecDevTools/_layouts/15/WopiFrame2.aspx?sourcedoc={3b7b7554-5f75-4db3-8a52-fa37d9a3713b}&action=edit&wd=target%28Crypto%2Eone%7C9ACEC449-841F-4EF2-A460-F4A5E6760B69%2F%29
> Update the crypto rules strings and help links

- PortFxCop/src/Analyzer.Utilities/Extensions/DiagnosticExtensions.cs
- src/AnalyzerPowerPack/Core/Shared/Extensions/DiagnosticExtensions.cs
(Replaces #606, re-targeted at FxCop branch.)
We're experimenting with running symbol analysis against binaries and there were a couple of places in analyzer helpers that were assuming there was always a source location, which would cause some rules to crash just as they were reporting a diagnostic.
I've followed the precedent set by  CreateDiagnostic(Location, DiagnosticDescriptor, object[])  which coerces the location to null when it's not in source and done the same when the  IEnumerable<Location>  variant gets a sequence where none of the locations are in source. We probably want to think about letting metadata locations through, but I'm starting with the least invasive change.
@srivatsn @michaelcfanning
> Tolerate non-source locations in DiagnosticExtensions

- .gitignore
@srivatsn  This file shows up in git status after running cibuild.cmd so I thought it would be nice to add it to gitignore to avoid accidental check-in...
> Add TestResults.xml to .gitignore

- PortFxCop/src/Tools/FileIssues/Program.cs
- PortFxCop/src/Tools/FileIssues/Resources.Designer.cs
- PortFxCop/src/Tools/FileIssues/Resources.resx
* The logic for adding and removing labels from existing issues was wrong. It should only add a label if the label does not already exist on the issue. Instead, it was adding a label if the label did not already exist *in the list of labels to add* -- which was always!
The `--dry-run` feature caught this.
* Wrap the "if dry run" test directly around the calls to the GitHub API, not around our helper methods. In dry runs, we were losing logging information about label changes and issue state changes.
The `--dry-run` feature also caught this.
@srivatsn @nguerrera @mavasani @michaelcfanning
> Fix label updates and improve logging in dry runs

- src/Tools/AnalyzersStatusGenerator/AnalyzersStatusGenerator.csproj
If you did `git clean -xdf` followed by `cibuild.cmd`, you would get a build break in the `AnalyzersStatusGenerator` project, because MSBuild couldn't resolve the reference to the assembly `System.Composition.AttributedModel`.
The problem was that the `.csproj` file specified a `HintPath` for this assembly in `..\packages`, but actually the packages directory is three levels up (`..\..\..\packages`). Several other assembly references in this project file had the same problem, but those assemblies weren't actually needed.
So I corrected the `HintPath` for `System.Composition.AttributedModel`, and removed the unncessary assembly references. All the remaining assembly references in this project file correctly specified `..\..\..\packages`.
The odd thing is that if you built a second time, …
> Fix build break in AnalyzersStatusGenerator tool

- build/Targets/Analyzers.NuGet.Settings.targets
Fix the link in the generated .nuspec file. Fix up the release notes and tags while we're at it.
@srivatsn @tmeschter
> Fix #359: "Project site" link on NuGet.org is wrong

- src/Microsoft.ApiDesignGuidelines.Analyzers/Core/NestedTypesShouldNotBeVisible.cs
- src/Microsoft.ApiDesignGuidelines.Analyzers/UnitTests/NestedTypesShouldNotBeVisibleTests.cs
Fixes a bug in my implementation of CA1304 noted by @nguerrera.
@nguerrera @srivatsn
> CA1304: Only complain if nested type is visible outside assembly

- src/System.Runtime.Analyzers/CSharp/CSharpUseOrdinalStringComparison.cs
- src/System.Runtime.Analyzers/Core/UseOrdinalStringComparison.cs
- src/System.Runtime.Analyzers/VisualBasic/BasicUseOrdinalStringComparison.vb
This one is interesting. The analysis that was duplicated for C#\VB can be combined by analyzing operation nodes. However, the original analyzer was being very specific in the location of the diagnostics. For something like `a.Equals(b)`, it was squiggling just the Equals identifier instead of the whole invocation expression to point out that the overload of Equals is wrong. While analyzing operation nodes, we only have the invocation operation and therefore the invocation syntax. To go any finer than that I have to dive into syntax which is language specific. 
So I have a couple of abstract methods to get the locations for each language but all other analysis is common.
> Change CA1309 to analyze operation nodes.

- src/Microsoft.ApiDesignGuidelines.Analyzers/Core/IdentifiersShouldNotMatchKeywords.cs
- src/Microsoft.ApiDesignGuidelines.Analyzers/UnitTests/IdentifiersShouldNotMatchKeywordsMemberParameterRuleTests.cs
- src/Microsoft.ApiDesignGuidelines.Analyzers/UnitTests/IdentifiersShouldNotMatchKeywordsMemberRuleTests.cs
- src/Microsoft.ApiDesignGuidelines.Analyzers/UnitTests/IdentifiersShouldNotMatchKeywordsTests.cs
- src/Microsoft.ApiDesignGuidelines.Analyzers/UnitTests/IdentifiersShouldNotMatchKeywordsTypeRuleTests.cs
- src/Microsoft.ApiDesignGuidelines.Analyzers/UnitTests/Microsoft.ApiDesignGuidelines.Analyzers.UnitTests.csproj
We add the implementation of the type name rule.
Also:
* Refactor: Place the code that applies to all the partial test classes in a separate file.
* Remove using declarations that become unnecessary once the common code is moved to the separate file.
* Remove unnecessary base class declarations from all but one of the partial classes.
* Add missing copyright notice to one file.
* Rename one misnamed test.
@srivatsn @nguerrera @michaelcfanning @dotnet/roslyn-analysis
> Partial #451: CA1716: IdentifiersShouldNotMatchKeywords (type names)

- src/Microsoft.ApiDesignGuidelines.Analyzers/Core/IdentifiersShouldNotMatchKeywords.cs
- src/Microsoft.ApiDesignGuidelines.Analyzers/UnitTests/IdentifiersShouldNotMatchKeywordsMemberParameterRuleTests.cs
- src/Microsoft.ApiDesignGuidelines.Analyzers/UnitTests/IdentifiersShouldNotMatchKeywordsMemberRuleTests.cs
- src/Microsoft.ApiDesignGuidelines.Analyzers/UnitTests/IdentifiersShouldNotMatchKeywordsTypeRuleTests.cs
Per suggestion from @nguerrera, add unit tests for nested types to ensure that nobody accidentally "simplifies" the code by replacing the usage of `GetResultantVisibility` with `DeclaredVisibility`.
Adding these tests revealed a bug, namely that in the TypeRule, I was not properly formatting the type name for nested classes; that is, I was displaying "D" instead of "C.D".
@nguerrera @dotnet/roslyn-analysis
> CA1716: Test nested types

- src/Microsoft.ApiDesignGuidelines.Analyzers/Core/IdentifiersShouldNotMatchKeywords.cs
- src/Microsoft.ApiDesignGuidelines.Analyzers/UnitTests/IdentifiersShouldNotMatchKeywordsNamespaceRuleTests.cs
- src/Microsoft.ApiDesignGuidelines.Analyzers/UnitTests/Microsoft.ApiDesignGuidelines.Analyzers.UnitTests.csproj
Conclude the odyssey by implementing the rule that namespaces names should not match keyword names.
Per discussion with @srivatsn, we don't report a location for this rule. The reason is that you can open a namespace in multiple locations. We only want to report a violation for a given namespace once, so we keep track of which namespaces we've reported. But which of the multiple occurrences the analyzer will find first, and report, is not deterministic.
Why does that matter? Suppose the namespace occurs in both A.cs and B.cs. Suppose the compiler reports the violation in A.cs, and the user suppresses it. In contrast to the way it treats partial classes, Roslyn does _not_ suppress a namespace-scoped diagnostic across all occurrences
of the namespace. So if, in a future compilation, the …
> Fix #451: CA1716: IdentifiersShouldNotMatchKeywords (namespace rule)

- src/Desktop.Analyzers/Core/TypesShouldNotExtendCertainBaseTypes.cs
- src/Microsoft.ApiDesignGuidelines.Analyzers/Core/ExceptionsShouldBePublic.cs
- src/Microsoft.ApiDesignGuidelines.Analyzers/Core/MovePInvokesToNativeMethodsClass.cs
- src/Microsoft.ApiDesignGuidelines.Analyzers/Core/StaticHolderTypes.cs
- src/System.Runtime.InteropServices.Analyzers/Core/PInvokeDiagnosticAnalyzer.cs
1. Do not assume type.BaseType != null. This is not the
case for System.Object itself.
2. Use CreateDiagnostic from analyzer utilities to get
source location for diagnostic without crashing if there
is none.
@srivatsn @lgolding @dotnet/roslyn-analysis
> Fix issues identified during binary analysis prototyping

- src/Microsoft.ApiDesignGuidelines.Analyzers/Core/EquatableAnalyzer.cs
- src/Microsoft.ApiDesignGuidelines.Analyzers/Core/MicrosoftApiDesignGuidelinesAnalyzersResources.Designer.cs
- src/Microsoft.ApiDesignGuidelines.Analyzers/Core/MicrosoftApiDesignGuidelinesAnalyzersResources.resx
In preparation for this change, I did the following:
* Added a document "Documenting your analyzers", containing guidance for creating analyzer reference pages, to the docs directory.
* Added a template for the analyzer reference pages to docs directory of the repo https://github.com/Microsoft/sarif-sdk.
* Wrote reference pages for CA1066 and CA1067.
Then, with this change, I:
* Set the helpLinkUris of the two DiagnosticDescriptors in this analyzer to the new reference pages, using stable URIs.
* Populated the Description properties of the two DiagnosticDescriptors with information taken from the reference pages.
@srivatsn @nguerrera @michaelcfanning 
cc: @dotnet/roslyn-analysis
> Fix #865: EquatableAnalyzer does not have help URL(s)

- src/Test/Utilities/DiagnosticAnalyzerTestBase.cs
- src/Test/Utilities/DiagnosticAnalyzerTests.Extensions.cs
This change adds a helper to Test base to pretty print the actual diagnostics when the test assertion fails.
This will be helpfully to write unittest cases fast.
Working:
1. The user writes a testcase with empty(or any failing expected) diagnostics
2. Set PrintActualDiagnosticsOnFailure to true
3. Run the testcase
4. The console will display the actual diagnostics that were generated in a format that can pasted into the testcase with minimal change
5. Care should be taken by the user to verify if the values reported at accurate
There is also an option for the user to mention a template for diagnostics display. The format which will take 3 arguments.
Arg1 : Line number
Arg2 : Column number
Arg3 : Message of the diagnostics
This can be used like below,
ExpectedDiagnosticsAssertionTemplate = …
> Pretty print Actual Diagnostics on Test failure

- src/Desktop.Analyzers/Core/Desktop.Analyzers.props
- src/Microsoft.ApiDesignGuidelines.Analyzers/CSharp/Microsoft.ApiDesignGuidelines.CSharp.Analyzers.props
- src/Microsoft.ApiDesignGuidelines.Analyzers/Core/IdentifiersShouldNotContainTypeNames.cs
- src/Microsoft.ApiDesignGuidelines.Analyzers/Core/Microsoft.ApiDesignGuidelines.Analyzers.props
- src/Microsoft.ApiDesignGuidelines.Analyzers/Core/PropertyNamesShouldNotMatchGetMethods.cs
- src/Microsoft.ApiDesignGuidelines.Analyzers/Core/UseIntegralOrStringArgumentForIndexers.cs
- src/Microsoft.ApiDesignGuidelines.Analyzers/VisualBasic/Microsoft.ApiDesignGuidelines.VisualBasic.Analyzers.props
- src/Microsoft.Maintainability.Analyzers/Core/Microsoft.Maintainability.Analyzers.props
- src/Microsoft.Maintainability.Analyzers/VisualBasic/Microsoft.Maintainability.VisualBasic.Analyzers.props
- src/Microsoft.QualityGuidelines.Analyzers/CSharp/Microsoft.QualityGuidelines.CSharp.Analyzers.props
- src/Microsoft.QualityGuidelines.Analyzers/Core/Microsoft.QualityGuidelines.Analyzers.props
- src/Microsoft.QualityGuidelines.Analyzers/VisualBasic/Microsoft.QualityGuidelines.VisualBasic.Analyzers.props
- src/System.Resources.Analyzers/CSharp/System.Resources.CSharp.Analyzers.props
- src/System.Resources.Analyzers/Core/System.Resources.Analyzers.props
- src/System.Resources.Analyzers/VisualBasic/System.Resources.VisualBasic.Analyzers.props
- src/System.Runtime.Analyzers/CSharp/System.Runtime.CSharp.Analyzers.props
- src/System.Runtime.Analyzers/Core/System.Runtime.Analyzers.props
- src/System.Runtime.Analyzers/VisualBasic/System.Runtime.VisualBasic.Analyzers.props
All of the analyzer packages have a props file that turns off the FxCop implementation of the rules implemented by that package so that issues are not reported twice in VS. Updating that list with all the rules that have been implemented so far. I modified the a2md tool to spit out the lines that go into the file. 
If there are any rules that are disabled in the props file that FxCop doesn't understand then it complains. Verified by installing all the packages that all the rules mentioned in the props files do exist in FxCop. (We've added some new ones that I had to remove).
Fixes #306 
@dotnet/roslyn-analysis @mavasani
> Updating the fxcop props files with all the newly implemented rules.

- src/System.Runtime.InteropServices.Analyzers/Core/PInvokeDiagnosticAnalyzer.cs
- src/System.Runtime.InteropServices.Analyzers/UnitTests/PInvokeDiagnosticAnalyzerTests.cs
Fixes https://github.com/dotnet/roslyn-analyzers/issues/792
@dotnet/roslyn-analysis
> Fix CA1401 to look at resultant visibility instead of declared visibility

- src/Microsoft.ApiDesignGuidelines.Analyzers/Core/UseIntegralOrStringArgumentForIndexers.cs
- src/Microsoft.ApiDesignGuidelines.Analyzers/UnitTests/UseIntegralOrStringArgumentForIndexersTests.cs
While testing something unrelated I noticed that indexer with generic parameters were being flagged as incorrect (CA1043 says Indexers should have either integer or string parameters). The FxCop implementation excludes type parameters and for enums it checks the underlying type. I've made both those changes in this PR.
@dotnet/roslyn-analysis
> Fix CA1043 to not report in a couple of cases

- src/Microsoft.ApiDesignGuidelines.Analyzers/Core/DoNotDecreaseInheritedMemberVisibility.cs
- src/Microsoft.ApiDesignGuidelines.Analyzers/Core/TypeNamesShouldNotMatchNamespaces.cs
- src/Microsoft.ApiDesignGuidelines.Analyzers/UnitTests/DoNotDecreaseInheritedMemberVisibilityTests.cs
1. Fix DoNotDecreaseInheritedMemberVisibilityAnalyzer to match few more cases with binary FxCop 
Fixes #940
2. Fix TypeNamesShouldNotMatchNamespacesAnalyzer to not report analyze/report diagnostics on generated code.
Fixes #949
Seems like invoking `analysisContext.ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags.Analyze)`, which should suppress all diagnostics on generated code, still allows the analyzer to report compilation end diagnostics on generated code. I'll file a separate bug on roslyn repo to fix the driver.
> Fix couple of analyzer bugs

- src/Microsoft.ApiDesignGuidelines.Analyzers/Core/IdentifiersShouldHaveCorrectPrefix.cs
- src/Microsoft.ApiDesignGuidelines.Analyzers/UnitTests/IdentifiersShouldHaveCorrectPrefixTests.cs
> Allow type parameter names with single letter, for example Foo<K, V>

- src/Analyzer.Utilities/Extensions/ITypeSymbolExtensions.cs
- src/Microsoft.ApiDesignGuidelines.Analyzers/Core/IdentifiersShouldNotHaveIncorrectSuffix.cs
- src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/DiagnosticAnalyzerAttributeAnalyzer.cs
1. commit https://github.com/dotnet/roslyn-analyzers/commit/1d64947f23c8fb361df77b1228390778ea75a75b -   Add a null check in ITypeSymbolExtensions.DerivesFrom. Fixes #939 
2. commit https://github.com/dotnet/roslyn-analyzers/commit/47610b093d65bde9f0a1366de55a6e346e153c17 -   Fix NRE in DiagnosticAnalyzerAttributeAnalyzer. Fixes #847 
3. commit https://github.com/dotnet/roslyn-analyzers/commit/e1560b49ef7ef28d2cd1c79dea8c64f2aef7a1a5 - Fix NRE in IdentifiersShouldNotHaveIncorrectSuffixAnalyzer encountered during dogfooding.
Handle null well-known types in compilation. No bug.
> Misc analyzer NRE bug fixes

- src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/DiagnosticAnalyzerFieldsAnalyzer.cs
- src/Microsoft.CodeAnalysis.Analyzers/Test/MetaAnalyzers/DoNotStorePerCompilationDataOntoFieldsRuleTests.cs
As suggested in https://github.com/dotnet/roslyn-analyzers/issues/845#issuecomment-218457931.
> Added check for IOperation fields (similar to ISymbol)

- src/Microsoft.ApiDesignGuidelines.Analyzers/Core/AbstractTypesShouldNotHaveConstructors.cs
Using `GetResultantVisibility` returns non-public when any of the outer types is non-public. Even in that case, this diagnostic should be reported.
For example:
```csharp
internal class C
{
public abstract class D
{
public D() { }
}
}
```
Therefore I believe `GetResultantVisibility` should not be used here and the TODO can be removed.
> Resolved TODO

- src/ApiReview.Analyzers/UnitTests/ApiReview.Analyzers.UnitTests.csproj
- src/Desktop.Analyzers/UnitTests/Desktop.Analyzers.UnitTests.csproj
- src/MetaCompilation/MetaCompilation/MetaCompilation.Test/MetaCompilation.Test.csproj
- src/Microsoft.ApiDesignGuidelines.Analyzers/UnitTests/Microsoft.ApiDesignGuidelines.Analyzers.UnitTests.csproj
- src/Microsoft.CodeAnalysis.Analyzers/Test/CodeAnalysisDiagnosticAnalyzersTest.csproj
- src/Microsoft.Composition.Analyzers/UnitTests/Microsoft.Composition.Analyzers.UnitTests.csproj
- src/Microsoft.Maintainability.Analyzers/UnitTests/Microsoft.Maintainability.Analyzers.UnitTests.csproj
- src/Microsoft.QualityGuidelines.Analyzers/UnitTests/Microsoft.QualityGuidelines.Analyzers.UnitTests.csproj
- src/Roslyn.Diagnostics.Analyzers/UnitTests/Roslyn.Diagnostics.Analyzers.UnitTests.csproj
- src/System.Collections.Immutable.Analyzers/UnitTests/System.Collections.Immutable.Analyzers.UnitTests.csproj
- src/System.Resources.Analyzers/UnitTests/System.Resources.Analyzers.UnitTests.csproj
- src/System.Runtime.Analyzers/UnitTests/System.Runtime.Analyzers.UnitTests.csproj
- src/System.Runtime.InteropServices.Analyzers/UnitTests/System.Runtime.InteropServices.Analyzers.UnitTests.csproj
- src/System.Security.Cryptography.Hashing.Algorithms.Analyzers/UnitTests/System.Security.Cryptography.Hashing.Algorithms.Analyzers.UnitTests.csproj
- src/System.Threading.Tasks.Analyzers/UnitTests/System.Threading.Tasks.Analyzers.UnitTests.csproj
- src/Text.Analyzers/UnitTests/Text.Analyzers.UnitTests.csproj
- src/Tools/AnalyzerCodeGenerator/template/src/REPLACE.ME/UnitTests/REPLACE.ME.Analyzers.UnitTests.csproj
- src/Unfactored/AsyncPackage/AsyncPackage.Test/AsyncPackage.Test.csproj
- src/Unfactored/Roslyn/Test/RoslynDiagnosticAnalyzersTest.csproj
- src/XmlDocumentationComments.Analyzers/UnitTests/XmlDocumentationComments.Analyzers.UnitTests.csproj
After a fresh clone, the `.\packages` folder containing `xunit.console.x86.exe` no longer existed, which caused F5 on UnitTest projects to fail.
Since the `cibuild` still worked, I updated project files to use the same location for `xunit.console.x86.exe`.
> Fixed running unittests from within VS

- src/Analyzer.Utilities/Extensions/IMethodSymbolExtensions.cs
- src/Roslyn.Diagnostics.Analyzers/Core/DeclarePublicAPIAnalyzer.Impl.cs
- src/Roslyn.Diagnostics.Analyzers/Core/DeclarePublicAPIAnalyzer.cs
- src/Roslyn.Diagnostics.Analyzers/Core/RoslynDiagnosticIds.cs
- src/Roslyn.Diagnostics.Analyzers/Core/RoslynDiagnosticsAnalyzersResources.Designer.cs
- src/Roslyn.Diagnostics.Analyzers/Core/RoslynDiagnosticsAnalyzersResources.resx
- src/Roslyn.Diagnostics.Analyzers/UnitTests/DeclarePublicAPIAnalyzerTests.cs
See https://github.com/dotnet/roslyn/blob/master/docs/Adding%20Optional%20Parameters%20in%20Public%20API.md for backcompat requirements.
This change flags the following 2 cases:
1) Unshipped public API with optional parameters, if it has any other public API overloads with optional parameters.
2) Public API with optional parameters (shipped or unshipped), if it does not have more pamareters than any other unshipped public API overload without optional parameters.
> Public API Analyzer: Add support for catching compat break due to optional parameters in public API

- src/Microsoft.ApiDesignGuidelines.Analyzers/Core/OverrideEqualsAndOperatorEqualsOnValueTypes.cs
- src/Microsoft.ApiDesignGuidelines.Analyzers/UnitTests/OverrideEqualsAndOperatorEqualsOnValueTypesTests.cs
- src/Microsoft.QualityGuidelines.Analyzers/Core/MicrosoftQualityGuidelinesAnalyzersResources.Designer.cs
- src/Microsoft.QualityGuidelines.Analyzers/Core/MicrosoftQualityGuidelinesAnalyzersResources.resx
- src/Microsoft.QualityGuidelines.Analyzers/Core/UseLiteralsWhereAppropriate.cs
- src/Microsoft.QualityGuidelines.Analyzers/UnitTests/UseLiteralsWhereAppropriateTests.cs
1. commit https://github.com/dotnet/roslyn-analyzers/commit/9180eaba61c505b3ef15488ac5626cbe5b7ef9db: Ensure that we don't report CA1815 for types assignable to IEnumerator (FxCop compat)
Fixes #899.
2. commit https://github.com/dotnet/roslyn-analyzers/commit/872592c991407491681114df1834dcf23658ccfd: Don't display the constant value in the diagnostic message for CA1802 - this can be extremely large string.
See #936 for an example.
Fixes #936
> Couple of analyzer bug fixes

- src/Roslyn.Diagnostics.Analyzers/Core/DeclarePublicAPIAnalyzer.Impl.cs
- src/Roslyn.Diagnostics.Analyzers/Core/RoslynDiagnosticsAnalyzersResources.Designer.cs
- src/Roslyn.Diagnostics.Analyzers/Core/RoslynDiagnosticsAnalyzersResources.resx
- src/Roslyn.Diagnostics.Analyzers/UnitTests/DeclarePublicAPIAnalyzerTests.cs
1. When computing stale sibling symbol entries to remove in public API text (e.g. signature change of unshipped public API), handle generic type with same name as a non-generic sibling.
2. Fix error message name for code fix to add public API entry for implicit constructor to use containging symbol's name.
> Couple of fixes to DeclarePublicAPI analyzer

- src/Microsoft.QualityGuidelines.Analyzers/UnitTests/DoNotCallOverridableMethodsInConstructorsTests.cs
- src/Microsoft.QualityGuidelines.Analyzers/UnitTests/MarkMembersAsStaticTests.cs
- src/Microsoft.QualityGuidelines.Analyzers/UnitTests/PreferJaggedArraysOverMultidimensionalTests.cs
- src/Microsoft.QualityGuidelines.Analyzers/UnitTests/SealMethodsThatSatisfyPrivateInterfacesTests.cs
- src/Microsoft.QualityGuidelines.Analyzers/UnitTests/UseLiteralsWhereAppropriateTests.cs
Overview of typical issues in unittest code fragments:
* Missing namespace imports
* Missing `abstract`/`MustInherit` on class definition that contains abstract members
* Missing return type in method signatures
* Incorrectly escaped string values
* Missing VB end markers, such as `End Class`
> Fixed compiler errors in Microsoft.QualityGuidelines.Analyzers.UnitTests

- src/Roslyn.Diagnostics.Analyzers/UnitTests/DeclarePublicAPIAnalyzerTests.cs
- src/Roslyn.Diagnostics.Analyzers/UnitTests/SpecializedEnumerableCreationAnalyzerTests.cs
Overview of typical issues in unittest code fragments:
* Duplicate parameter names
* Non-void method must return a value or throw
* Mismatch between VB array size and number of elements
> Fixed compiler errors in Roslyn.Diagnostics.Analyzers.UnitTests

- src/System.Collections.Immutable.Analyzers/UnitTests/DoNotCallToImmutableArrayOnAnImmutableArrayValueTests.cs
Overview of issues in unittest code fragments:
* Extension methods must be in static class/module
* Unconstrained generic cannot be `null`
> Fixed compiler errors in Collections.Immutable.Analyzers.UnitTests

- src/Microsoft.Maintainability.Analyzers/UnitTests/AvoidUnusedPrivateFieldsTests.cs
- src/Microsoft.Maintainability.Analyzers/UnitTests/DoNotIgnoreMethodResultsTests.cs
- src/Microsoft.Maintainability.Analyzers/UnitTests/RemoveUnusedLocalsTests.cs
- src/Microsoft.Maintainability.Analyzers/UnitTests/ReviewUnusedParametersTests.cs
Overview of typical issues in unittest code fragments:
* Copy/paste errors
* Missing imports
* Scoping errors (use private type in public signature)
* Poor translations from C# to VB
* `out` variables not assigned
> Fixed compiler errors in Microsoft.Maintainability.Analyzers.UnitTests

- src/System.Security.Cryptography.Hashing.Algorithms.Analyzers/Core/DoNotUseInsecureCryptographicAlgorithms.cs
I don't see any shared state in this analyzer, so it looks like this is already thread-safe as-is. Am I missing something?
> Enable concurrent execution for CA5350/CA5351

- src/System.Runtime.Analyzers/UnitTests/AvoidUnsealedAttributesTests.cs
- src/System.Runtime.Analyzers/UnitTests/AvoidZeroLengthArrayAllocationsTests.cs
- src/System.Runtime.Analyzers/UnitTests/CallGCSuppressFinalizeCorrectlyTests.cs
- src/System.Runtime.Analyzers/UnitTests/DisposableTypesShouldDeclareFinalizerTests.cs
- src/System.Runtime.Analyzers/UnitTests/DoNotLockOnObjectsWithWeakIdentityTests.cs
- src/System.Runtime.Analyzers/UnitTests/InitializeStaticFieldsInlineTests.cs
- src/System.Runtime.Analyzers/UnitTests/InstantiateArgumentExceptionsCorrectlyTests.cs
- src/System.Runtime.Analyzers/UnitTests/NormalizeStringsToUppercaseTests.cs
- src/System.Runtime.Analyzers/UnitTests/ProvideCorrectArgumentsToFormattingMethodsTests.cs
- src/System.Runtime.Analyzers/UnitTests/SpecifyIFormatProviderTests.cs
- src/System.Runtime.Analyzers/UnitTests/TestForEmptyStringsUsingStringLengthTests.cs
- src/System.Runtime.Analyzers/UnitTests/TestForNaNCorrectlyTests.cs
- src/System.Runtime.Analyzers/UnitTests/UseOrdinalStringComparisonTests.Fixer.cs
- src/System.Runtime.Analyzers/UnitTests/UseOrdinalStringComparisonTests.cs
Overview of issues in unittest code fragments:
* Copy/paste errors
* Private classes cannot exist in namespace scope
* Missing members that are referenced in tests
* Incorrectly escaped string values
* Struct parameterless constructor not allowed
* Unescaped indentifier names that are keywords (VB)
* Assignment of return value from void method to a local
* `_arglist` must be: `__arglist`
* Unassigned locals
* Missing type suffix in constant declaration of `float`/`Single` fields
> Fixed compiler errors in System.Runtime.Analyzers.UnitTests

- src/Microsoft.ApiDesignGuidelines.Analyzers/UnitTests/ImplementIDisposableCorrectlyTests.cs
As mentioned in #1011 input for tests related to CA1063 is not correct C# code because of missing return type.
> Adds missing 'void' return type in tests of CA1063: ImplementDisposableCorrectly

- BuildAndTest.proj
- src/ApiReview.Analyzers/UnitTests/ApiReview.Analyzers.UnitTests.csproj
- src/Desktop.Analyzers/UnitTests/Desktop.Analyzers.UnitTests.csproj
- src/MetaCompilation/MetaCompilation/MetaCompilation.Test/MetaCompilation.Test.csproj
- src/Microsoft.ApiDesignGuidelines.Analyzers/UnitTests/Microsoft.ApiDesignGuidelines.Analyzers.UnitTests.csproj
- src/Microsoft.CodeAnalysis.Analyzers/Test/CodeAnalysisDiagnosticAnalyzersTest.csproj
- src/Microsoft.Composition.Analyzers/UnitTests/Microsoft.Composition.Analyzers.UnitTests.csproj
- src/Microsoft.Maintainability.Analyzers/UnitTests/Microsoft.Maintainability.Analyzers.UnitTests.csproj
- src/Microsoft.QualityGuidelines.Analyzers/UnitTests/Microsoft.QualityGuidelines.Analyzers.UnitTests.csproj
- src/Roslyn.Diagnostics.Analyzers/UnitTests/Roslyn.Diagnostics.Analyzers.UnitTests.csproj
- src/System.Collections.Immutable.Analyzers/UnitTests/System.Collections.Immutable.Analyzers.UnitTests.csproj
- src/System.Resources.Analyzers/UnitTests/System.Resources.Analyzers.UnitTests.csproj
- src/System.Runtime.Analyzers/UnitTests/System.Runtime.Analyzers.UnitTests.csproj
- src/System.Runtime.InteropServices.Analyzers/UnitTests/System.Runtime.InteropServices.Analyzers.UnitTests.csproj
- src/System.Security.Cryptography.Hashing.Algorithms.Analyzers/UnitTests/System.Security.Cryptography.Hashing.Algorithms.Analyzers.UnitTests.csproj
- src/System.Threading.Tasks.Analyzers/UnitTests/System.Threading.Tasks.Analyzers.UnitTests.csproj
- src/Text.Analyzers/UnitTests/Text.Analyzers.UnitTests.csproj
- src/Tools/AnalyzerCodeGenerator/template/BuildAndTest.proj
- src/Tools/AnalyzerCodeGenerator/template/src/REPLACE.ME/UnitTests/REPLACE.ME.Analyzers.UnitTests.csproj
- src/Tools/AnalyzerCodeGenerator/template/src/Test/Utilities/DiagnosticsTestUtilities.csproj
- src/Unfactored/AsyncPackage/AsyncPackage.Test/AsyncPackage.Test.csproj
- src/Unfactored/Roslyn/Test/RoslynDiagnosticAnalyzersTest.csproj
- src/XmlDocumentationComments.Analyzers/UnitTests/XmlDocumentationComments.Analyzers.UnitTests.csproj
After clean repro, F5 on unittest projects fails again. This is caused by package upgrade from xunit 2.0.0. to 2.1.0. After running cibuild, the 2.0.0 package is also installed and F5 works.
This PR updates all remaining references from 2.0.0 to 2.1.0, including unittests and cibuild.
> Fixed broken references after package update

- src/Analyzer.Utilities/Extensions/INamedTypeSymbolExtensions.cs
- src/Analyzer.Utilities/SyntaxGeneratorExtensions.cs
- src/Microsoft.ApiDesignGuidelines.Analyzers/Core/MicrosoftApiDesignGuidelinesAnalyzersResources.Designer.cs
- src/Microsoft.ApiDesignGuidelines.Analyzers/Core/MicrosoftApiDesignGuidelinesAnalyzersResources.resx
- src/Microsoft.ApiDesignGuidelines.Analyzers/Core/OperatorOverloadsHaveNamedAlternates.Fixer.cs
- src/Microsoft.ApiDesignGuidelines.Analyzers/Core/OverloadOperatorEqualsOnOverridingValueTypeEquals.Fixer.cs
- src/Microsoft.ApiDesignGuidelines.Analyzers/Core/OverrideEqualsAndOperatorEqualsOnValueTypes.Fixer.cs
- src/Microsoft.ApiDesignGuidelines.Analyzers/Core/OverrideEqualsOnOverloadingOperatorEquals.Fixer.cs
- src/Microsoft.ApiDesignGuidelines.Analyzers/Core/OverrideGetHashCodeOnOverridingEquals.Fixer.cs
- src/Microsoft.ApiDesignGuidelines.Analyzers/Core/OverrideMethodsOnComparableTypes.Fixer.cs
- src/Microsoft.ApiDesignGuidelines.Analyzers/Core/OverrideMethodsOnComparableTypes.cs
- src/Microsoft.ApiDesignGuidelines.Analyzers/UnitTests/OperatorOverloadsHaveNamedAlternatesTests.Fixer.cs
- src/Microsoft.ApiDesignGuidelines.Analyzers/UnitTests/OverloadOperatorEqualsOnOverridingValueTypeEqualsTests.Fixer.cs
- src/Microsoft.ApiDesignGuidelines.Analyzers/UnitTests/OverrideEqualsAndOperatorEqualsOnValueTypesTests.Fixer.cs
- src/Microsoft.ApiDesignGuidelines.Analyzers/UnitTests/OverrideEqualsOnOverloadingOperatorEqualsTests.Fixer.cs
- src/Microsoft.ApiDesignGuidelines.Analyzers/UnitTests/OverrideMethodsOnComparableTypesTests.Fixer.cs
- src/Microsoft.ApiDesignGuidelines.Analyzers/UnitTests/OverrideMethodsOnComparableTypesTests.cs
This fixes most of #791.
Because a fixer for EquatableAnalyzer (CA1066/CA1067) does not yet exist, generating method bodies for ``System.IEquatable`1`` members is not in this PR.
> Makes fixers add null checks in method bodies for Equals, CompareTo and comparison operators

- src/Analyzer.Utilities/SyntaxGeneratorExtensions.cs
- src/Microsoft.ApiDesignGuidelines.Analyzers/UnitTests/OverrideMethodsOnComparableTypesTests.Fixer.cs
Passing `null` for both arguments returns `false`, which should be: `true`.
> Fixes incorrect operator==

- src/System.Runtime.Analyzers/Core/SpecifyIFormatProvider.cs
- src/System.Runtime.Analyzers/UnitTests/SpecifyIFormatProviderTests.cs
A typo in the source code causes `CA1305` to crash. The code used a binary AND (`&`) to check if a local was null, before incorrectly assuming it would shortcircuit a later access. The code now correctly uses a logical AND (`&&`).
> Fix System.NullReferenceException in CA1305

- src/Analyzer.Utilities/Extensions/IEnumerableOfIMethodSymbolExtensions.cs
- src/Analyzer.Utilities/WellKnownTypes.cs
- src/System.Runtime.Analyzers/Core/SpecifyCultureInfo.cs
- src/System.Runtime.Analyzers/Core/SpecifyIFormatProvider.cs
- src/System.Runtime.Analyzers/UnitTests/SpecifyCultureInfoTests.cs
- src/System.Runtime.Analyzers/UnitTests/SpecifyIFormatProviderTests.cs
CA1304 recommends overloads that take CultureInfo arguments; similarly CA1305 recommends overloads that take IFormatProvider arguments. This change prevents the rules from recommending overloads that are marked with [System.ObsoleteAttribute]. Otherwise, the developer will find themselves in a loop where there cannot satisfy this rule without breaking CA1041 that prevents usage of obsolete members. CA1041 supercedes CA1304/CA1305 since the rules should never recommend obsolete functionality.
> Fix to CA1304/CA1305 to not recommend obsolete overloads

- src/Microsoft.ApiDesignGuidelines.Analyzers/Core/ParameterNamesShouldMatchBaseDeclaration.cs
- src/Microsoft.ApiDesignGuidelines.Analyzers/UnitTests/ParameterNamesShouldMatchBaseDeclarationTests.cs
Two issues are fixed with this change:
1) `System.IndexOutOfRangeException` if the base type has method overloads with varying number of parameters.
```C#
public interface ITest
{
void TestMethod(string arg1);
void TestMethod(string arg1, string arg2);
}
public class TestClass : ITest
{
public void TestMethod(string arg1) { }
public void TestMethod(string arg1, string arg2) { }
}
```
2) `System.InvalidCastException` if the type implements a property with the same name as a method being checked.
```C#
public interface ITest1
{
void TestMethod(string arg1, string arg2);
}
public interface ITest2
{
int TestMethod { get; set; }
}
public class TestClass : ITest1, ITest2
{
public void TestMethod(string arg1, string arg2) { }
int ITest2.TestMethod { get; set; }
}
```
Without the fix, the tests …
> Fix crashes in CA1725

- src/Microsoft.ApiDesignGuidelines.Analyzers/Core/DoNotDecreaseInheritedMemberVisibility.cs
- src/Microsoft.ApiDesignGuidelines.Analyzers/UnitTests/DoNotDecreaseInheritedMemberVisibilityTests.cs
CA2222 shouldn't apply to constructors because "when you use a
constructor, you know you are dealing with a subtype." Having different
constructors (or none at all) does not violate the Liskov substitution
principle, as elaborated on here:
http://stackoverflow.com/questions/5490824/should-constructors-comply-with-the-liskov-substitution-principle
Thus, CA2222 has been changed to ignore all methods that are constructors,
and tests for each language have been added.
> Fix #1085 CA2222 reports less visible constructors

- src/Microsoft.Maintainability.Analyzers/UnitTests/AvoidUnusedPrivateFieldsTests.cs
CA1823 does not correctly see usages of private fields in attributes. If those are the only usages, it incorrectly marks them as unused. The new test case documents this behavior.
> Add test case to document issue #933 with CA1823

- build/Rulesets/Analyzers.ruleset
- src/Analyzer.Utilities/Extensions/ISymbolExtensions.cs
- src/Microsoft.ApiDesignGuidelines.Analyzers/Core/DoNotRaiseExceptionsInUnexpectedLocations.cs
- src/Microsoft.ApiDesignGuidelines.Analyzers/Core/ImplementIDisposableCorrectly.cs
- src/Microsoft.ApiDesignGuidelines.Analyzers/Core/OperatorOverloadsHaveNamedAlternates.cs
- src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/RegisterActionAnalyzer.cs
- src/Roslyn.Diagnostics.Analyzers/Core/DeclarePublicAPIAnalyzer.Impl.cs
- src/Roslyn.Diagnostics.Analyzers/Core/SpecializedEnumerableCreationAnalyzer.cs
- src/System.Runtime.Analyzers/Core/TestForNaNCorrectly.Fixer.cs
CA1801 is causing false positives, and ~the code fix renders~ the light bulb is unusable when this occurs. This pull request disables the analyzer until the known problems can be corrected.
Edit: I'm not certain the code fix is the cause of the light bulb usability problem, but its implementation is suspect.
> Disable problematic analyzer CA1801

- cibuild.cmd
"VS2017 does not add VS150COMNTOOLS as a system environment variable." [1] Therefore, cibuild.cmd only currently works from a VS 2017 developer prompt. This is unideal, as cibuild.cmd should load the appropriate environment, as it did in VS 2015. "This makes it easier for people to simply clone this repo and build." [2]
This is a port of Microsoft/visualfsharp@bf52776167fe6a9f2354ea96094a025191dbd3e7 [2].
[1] https://github.com/Microsoft/visualfsharp/issues/1761
[2] https://github.com/Microsoft/visualfsharp/pull/2690
> Fix cibuild.cmd: assuming VS150COMNTOOLS exists

- src/Roslyn.Diagnostics.Analyzers/Core/DeclarePublicAPIAnalyzer.Impl.cs
- src/Roslyn.Diagnostics.Analyzers/Core/DeclarePublicAPIAnalyzer.cs
- src/Roslyn.Diagnostics.Analyzers/UnitTests/DeclarePublicAPIAnalyzerTests.cs
If our assembly forwards types and the forwarded types are also public, then they are effectively a public API of our assembly.
*Review:* @dotnet/roslyn-analysis, @dotnet/roslyn-compiler
> Support type forwarding in PublicAPI checker

- src/Microsoft.NetCore.Analyzers/Core/System.Runtime.Analyzers/NormalizeStringsToUppercase.cs
- src/Microsoft.NetCore.Analyzers/UnitTests/System.Runtime.Analyzers/NormalizeStringsToUppercaseTests.cs
When ToLower() is passed its culture as a local variable, the invocation's first argument is of type BoundLocal, which derives from ILocalReferenceExpression. ILocalReferenceExpression does not derive from IMemberReferenceExpression, so the cast throws an exception. Thus, the code has been updated to gracefully handle any failing cast.
> Fix CA1308 throwing InvalidCastException

- .coby.yml
- BuildAndTest.proj
- README.md
- src/.nuget/NuGetRestore.ps1
- Now that msbuild support restore we don't need separate restore script 
- No need of Coby.yml file 
- Updated readme to reflect the same.
@mavasani  for review
> Miscellaneous  Clean up 

- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/ImplementIDisposableCorrectly.cs
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/MicrosoftApiDesignGuidelinesAnalyzersResources.Designer.cs
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/MicrosoftApiDesignGuidelinesAnalyzersResources.resx
- src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/ImplementIDisposableCorrectlyTests.cs
- Changed the two diagnostics that direct a user to remove a finalizer or a Dispose override in favor of overriding Dispose(bool) so they are only emitted if there is an overridable Dispose(bool) definition in an ancestor class.
- Changed the "IDisposable reimplemented" rule's message and updated emission logic accordingly. Previously the message included "...override the base class Dispose implementation instead." This only makes sense if both the derived class and the base/ancestor class have Dispose implementations, in which case the derived class is either (1) already overriding properly, or (2) already getting a more general error about a method hiding the implementation from a base class.
The new message simply warns to remove a redundant "IDisposable" declaration when it is already …
> Fix for CA1063: Implement IDisposable correctly

- BuildAndTest.proj
- build/Targets/Analyzers.Imports.targets
- build/Targets/References.Targets
- cibuild.cmd
- src/Microsoft.CodeAnalysis.Analyzers/Setup/Microsoft.CodeAnalysis.Analyzers.Setup.csproj
- src/Microsoft.CodeQuality.Analyzers/Setup/Microsoft.CodeQuality.Analyzers.Setup.csproj
- src/Microsoft.NetCore.Analyzers/Setup/Microsoft.NetCore.Analyzers.Setup.csproj
- src/Roslyn.Diagnostics.Analyzers/Setup/Roslyn.Diagnostics.Analyzers.Setup.csproj
- src/Text.Analyzers/Setup/Text.Analyzers.Setup.csproj
1. Always build and deploy VSIXes with cibuild.cmd
2. Always generate TestResults.xml after running unit tests with BuildAndTest.proj
3. Use Microsoft.VSSDK.BuildTools NuGet package instead of relying on the VSSDK installation on the box.
4. Bump the package and assembly version for analyzer packages to 2.0.0 and beta1.
5. Fix BuildNumber/Version computation and add switch to cibuild to trigger official builds.
> Some infrastructure fixes for the repo

- src/Microsoft.CodeQuality.Analyzers/CSharp/ApiDesignGuidelines/CSharpDoNotHideBaseClassMethods.Fixer.cs
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/DoNotHideBaseClassMethods.Fixer.cs
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/DoNotHideBaseClassMethods.cs
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/MicrosoftApiDesignGuidelinesAnalyzersResources.Designer.cs
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/MicrosoftApiDesignGuidelinesAnalyzersResources.resx
- src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/DoNotHideBaseClassMethodsTests.Fixer.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/DoNotHideBaseClassMethodsTests.cs
- src/Microsoft.CodeQuality.Analyzers/VisualBasic/ApiDesignGuidelines/BasicDoNotHideBaseClassMethods.Fixer.vb
This code should duplicate the FxCop rule CA1061 exactly except when the
base type method is private. In this circumstance, my implementation does
not report a diagnostic while FxCop does.
The fixer is only boilerplate at this time.
> Add CA1061: Do not hide base class methods

- src/Analyzer.Utilities/Extensions/INamedTypeSymbolExtensions.cs
- src/Analyzer.Utilities/Extensions/ISymbolExtensions.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/StaticHolderTypeTests.Fixer.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/StaticHolderTypeTests.cs
Static methods that are not externally accessible should not be considered when determining if a method is a static holder type. We also now consider explicit conversion operators to be disqualifying from marking a class as a static holder type, much like user-defined operators also disqualify a class from being a static holder type.
Tagging @dotnet/analyzer-ioperation @sharwell for review. Fixes https://github.com/dotnet/roslyn-analyzers/issues/1162.
> Added a few exceptions to the definition of Static Holder types

- BuildAndTest.proj
- build/Config/SignToolData.json
- build/Targets/References.Targets
Eventually we want to move away from the hard coded list of binaries to sign and our custom signtool, but this should unblock the signing for now.
> Add SignTool functionality to sign our analyzer assemblies and VSIXes.

- src/Analyzer.Utilities/AbstractVersionCheckAnalyzer.cs
- src/Analyzer.Utilities/AnalyzerUtilitiesResources.Designer.cs
- src/Analyzer.Utilities/AnalyzerUtilitiesResources.resx
- src/Analyzer.Utilities/Extensions/AnalysisContextExtensions.cs
- src/Microsoft.CodeQuality.Analyzers/Core/VersionCheckAnalyzer.cs
- src/Microsoft.NetCore.Analyzers/Core/VersionCheckAnalyzer.cs
- src/Microsoft.NetFramework.Analyzers/Core/VersionCheckAnalyzer.cs
- src/Roslyn.Diagnostics.Analyzers/Core/VersionCheckAnalyzer.cs
We now do couple of things:
1. All the RegisterOperationXXXAction invocations in our analyzer packages verify that the loaded version of Microsoft.CodeAnalysis is in the range against which the analyzer package was built. If not, then they silently bail out, preventing crashes downstream.
2. Each of the analyzer packages get a new VersionCheckAnalyzer that detects this version mismatch and reports a version mismatch warning between analyzer package and Microsoft.CodeAnalysis package.
> Verify IOperation API version in analyzer packages

- src/Analyzer.Utilities/Extensions/INamedTypeSymbolExtensions.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/StaticHolderTypeTests.cs
Updates CA1052 to ignore classes that have any inherited interface. Fixes #1163. Tagging @sharwell @dotnet/roslyn-analysis for review.
> Don't warn on marker interfaces

- src/Analyzer.Utilities/WellKnownTypes.cs
- src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/DoNotIgnoreMethodResults.cs
- src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/MicrosoftMaintainabilityAnalyzersResources.Designer.cs
- src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/MicrosoftMaintainabilityAnalyzersResources.resx
- src/Microsoft.CodeQuality.Analyzers/UnitTests/Maintainability/DoNotIgnoreMethodResultsTests.cs
Functions that are marked `Pure` have no side effects, and should be considered when we check to see if function results are discarded without use. Fixes #1164. Tagging @dotnet/analyzer-ioperation @sharwell for review.
> Consider pure functions as part of CA1806.

- src/FxCopAnalyzersSetup/FxCopAnalyzersSetup/FxCopAnalyzersPackage.cs
- src/FxCopAnalyzersSetup/FxCopAnalyzersSetup/FxCopAnalyzersSetup.csproj
This allows us to detect the VSIX installation in VS by asking the shell if this package is installed. Tagging @mavasani @jinujoseph for review.
> Added dummy package for detection in VS

- src/AggregateNugetPackages/Microsoft.Net.RoslynDiagnostics/NuGet/Microsoft.Net.RoslynDiagnostics.nuspec
This metapackage is used the roslyn repos and they explicit import the build\Microsoft.Net.RoslynDiagnostics.props file in the package and don't import the package through regular nuget mechanisms. However, because this props file follows nuget convetions, if it is imported as a PackageReference, then all analyzers get imported twice. I want to pull this package in the project system repo as a PackageReference. Ideally we would just delete the props file entirely but that would break roslyn. So making a smaller breaking change here by just changing the folder that the props gets laid out in to something custom so that nuget is not aware of this props when included as a PackageReference. When roslyn updates to a newer version, they need to adjust the path to the props.
@mavasani …
> Make the Microsoft.Net.RoslyDiagnostics metapackage work as a PackageReference

- src/Analyzer.Utilities/WellKnownTypes.cs
- src/Microsoft.NetCore.Analyzers/Core/Composition/DoNotMixAttributesFromDifferentVersionsOfMEF.cs
- src/Microsoft.NetCore.Analyzers/UnitTests/Composition/DoNotMixAttributesFromDifferentVersionsOfMEFTests.cs
Handle metadata attributes such as CPS AppliesToAttribute, which has MetadataAttribute from more than one MEF namespace. We now report RS0006 (DoNotMixAttributesFromDifferentVersionsOfMEFAnalyzer) only if applied attribute has no metadata attribute from a good namespace (namespace from which ExportAttribute was applied).
Verified that the new test fails prior to the fix, and passes fine now.
Fixes #955
> Fix a false positive with RS0006 (DoNotMixAttributesFromDifferentVersionsOfMEFAnalyzer) analyzer

- src/Analyzer.Utilities/Extensions/IMethodSymbolExtensions.cs
- src/Analyzer.Utilities/Extensions/ISymbolExtensions.cs
- src/Microsoft.CodeQuality.Analyzers/CSharp/QualityGuidelines/CSharpRemoveEmptyFinalizersAnalyzer.cs
- src/Microsoft.CodeQuality.Analyzers/Core/QualityGuidelines/AbstractRemoveEmptyFinalizers.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/QualityGuidelines/RemoveEmptyFinalizersTests.Fixer.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/QualityGuidelines/RemoveEmptyFinalizersTests.cs
- src/Microsoft.CodeQuality.Analyzers/VisualBasic/QualityGuidelines/BasicRemoveEmptyFinalizersAnalyzer.vb
Because of the Higher vs Lower issue in IOperation right now, and since we want to ship this analyzer as part of our default set, we need to move RemoveEmptyFinalizersAnalyzer back to Symbol+Syntax for now. Tagging @dotnet/roslyn-analysis @mavasani for review.
> Move RemoveEmptyFinalizersAnalyzer to syntax analyzer

- src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/ReviewUnusedParameters.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/Maintainability/ReviewUnusedParametersTests.cs
Makes CA1801 aware of methods that are used as delegates, and does not warn on unused variables for them. It also makes it aware of methods annotated with the `Obsolete` attribute.
VB delegate warning is currently blocked on https://github.com/dotnet/roslyn/issues/19917.
Tagging @mavasani @dotnet/roslyn-analysis for review.
> Ca1801 false positives

- src/Analyzer.Utilities/AbstractVersionCheckAnalyzer.cs
- src/FxCopAnalyzersSetup/FxCopAnalyzersSetup/source.extension.vsixmanifest
We changed the minimum required VS version for FxCop analyzers VSIX from 15.0 to 15.3. However, the version of vsixinstaller.exe in Dev15.3 preview is still 15.0, and hence this blocks the VSIX installation. So, we are reverting this change.
Additionally, I also enabled our version check analyzer to be turned on by default for both VSIX and NuGet (currently it was on only for NuGet packages).
> Fix the VSIX break introduced from prior manifest change

- src/Analyzer.Utilities/Extensions/IOperationExtensions.cs
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/PassSystemUriObjectsInsteadOfStrings.cs
- src/Microsoft.NetCore.Analyzers/Core/ImmutableCollections/DoNotCallToImmutableArrayOnAnImmutableArrayValue.cs
- src/Microsoft.NetCore.Analyzers/Core/Runtime/NormalizeStringsToUppercase.cs
- src/Microsoft.NetCore.Analyzers/Core/Tasks/DoNotCreateTasksWithoutPassingATaskScheduler.cs
we are trying to remove IOperation.IsInvalid from IOperation interface. made roslyn analyzers not to rely on the obsolete API.
> made roslyn analyzers not to use IsInvalid which will be removed soon.

- build/build.ps1
- src/Analyzer.Utilities/Extensions/IEnumerableExtensions.cs
- src/Analyzers.ruleset
- src/Microsoft.CodeAnalysis.FxCopAnalyzers/Setup/FxCopAnalyzersPackage.cs
- src/Microsoft.NetFramework.Analyzers/VisualBasic/Helpers/SyntaxNodeHelper.vb
- src/Roslyn.Diagnostics.Analyzers/VisualBasic/BasicInvokeTheCorrectPropertyToEnsureCorrectUseSiteDiagnostics.vb
The underlying IOp issues have been fixed. Fixes #1103, #933, and #935. Tagging @dotnet/roslyn-analysis for review.
> Disabled suppressions of 1801, 1804, and 1823

- src/Directory.Build.props
Previous RepoToolset change broke test runs in microbuild. Avoid using ```<XUnitConfigurationFile>``` for now.
> Copy test runner configuration json

- src/Analyzer.Utilities/Extensions/IOperationExtensions.cs
Computing semantic diagnostics is causing a large perf regression. Until we can figure out a performant implementation, we will just use syntax errors to determine if the operation is invalid.
> Change IsInvalid to use only syntax diagnostics

- src/Microsoft.NetCore.Analyzers/UnitTests/InteropServices/PInvokeDiagnosticAnalyzerTests.cs
- src/Microsoft.NetFramework.Analyzers/UnitTests/MarkAllNonSerializableFieldsTests.Fixer.cs
- src/Microsoft.NetFramework.Analyzers/UnitTests/MarkAllNonSerializableFieldsTests.cs
- src/Test/Utilities/CodeFixTestBase.cs
- src/Test/Utilities/DiagnosticAnalyzerTests.Extensions.cs
Skip tests for analyzers returning no supported diagnostics and also for couple of analyzers that have rules enabled only for NuGet build. This is basically a falloff from https://github.com/dotnet/roslyn-analyzers/pull/1276.
> Skip tests for disabled analyzers

- src/Microsoft.NetCore.Analyzers/Core/Runtime/TestForNaNCorrectly.cs
Fixing and re-enabling tracked by https://github.com/dotnet/roslyn/issues/21448
> Disable CA2242 until it can be switched to the new IOperation API

- build/Targets/Analyzers.Imports.targets
- build/Targets/Versions.props
My previous change broke the build by updating the consumed analyzer package version instead of the generated package version.
> Correctly fix the generated package version to 2.3.0-beta2

- build/Versions.props
- src/MetaCompilation.Analyzers/UnitTests/UnitTests.cs
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/DoNotDirectlyAwaitATask.cs
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/DoNotRaiseExceptionsInUnexpectedLocations.cs
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/ImplementIDisposableCorrectly.cs
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/InterfaceMethodsShouldBeCallableByChildTypes.cs
- src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/ReviewUnusedParameters.cs
- src/Microsoft.CodeQuality.Analyzers/Core/QualityGuidelines/DoNotRaiseExceptionsInExceptionClauses.cs
- src/Microsoft.CodeQuality.Analyzers/Core/QualityGuidelines/UseLiteralsWhereAppropriate.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/DoNotDirectlyAwaitATaskTests.Fixer.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/DoNotDirectlyAwaitATaskTests.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/DoNotRaiseExceptionsInUnexpectedLocationsTests.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/QualityGuidelines/DoNotRaiseExceptionsInExceptionClausesTests.cs
- src/Microsoft.NetCore.Analyzers/Core/Runtime/AvoidZeroLengthArrayAllocations.cs
- src/Microsoft.NetCore.Analyzers/Core/Runtime/CallGCSuppressFinalizeCorrectly.cs
- src/Microsoft.NetCore.Analyzers/Core/Runtime/DisposableTypesShouldDeclareFinalizer.cs
- src/Microsoft.NetCore.Analyzers/Core/Runtime/DoNotLockOnObjectsWithWeakIdentity.cs
- src/Microsoft.NetCore.Analyzers/Core/Runtime/SpecifyIFormatProvider.cs
- src/Microsoft.NetCore.Analyzers/Core/Runtime/TestForEmptyStringsUsingStringLength.cs
- src/Microsoft.NetCore.Analyzers/Core/Runtime/TestForNaNCorrectly.cs
- src/Microsoft.NetCore.Analyzers/Core/Runtime/UseOrdinalStringComparison.cs
- src/Microsoft.NetFramework.Analyzers/Core/DoNotCatchCorruptedStateExceptions.cs
- src/Microsoft.NetFramework.Analyzers/Core/DoNotUseInsecureDtdProcessing.cs
- src/Microsoft.NetFramework.Analyzers/UnitTests/DoNotCatchCorruptedStateExceptionsTests.cs
Disabled following analyzers and their unit tests, with a tracking issue:
1. DoNotDirectlyAwaitATaskAnalyzer CA2007: https://github.com/dotnet/roslyn-analyzers/issues/1303 tracking revert of https://github.com/mavasani/roslyn-analyzers/commit/6d86ee10cf873c9fc478bce0741d87c084345a08 and https://github.com/mavasani/roslyn-analyzers/commit/7444a7d6d4ac76cb4cc215ee7efea41ff4617f6e
2. DoNotCatchCorruptedStateExceptionsAnalyzer CA2153: https://github.com/dotnet/roslyn-analyzers/issues/1304 tracking revert of https://github.com/mavasani/roslyn-analyzers/commit/1ac4bae56bc41c93a514bd9a82cdfaa7a50f50b5
3. DoNotRaiseExceptionsInExceptionClausesAnalyzer CA2219: https://github.com/dotnet/roslyn-analyzers/issues/1305 tracking revert of https://github.com/mavasani/roslyn-analyzers/commit/086f5dfc6b0d1a …
> Move repo to latest 2.6 Microsoft.CodeAnalysis package and fix analyzers from new API changes

- build/Versions.props
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/DoNotDirectlyAwaitATask.cs
- src/Microsoft.CodeQuality.Analyzers/Core/QualityGuidelines/DoNotRaiseExceptionsInExceptionClauses.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/DoNotDirectlyAwaitATaskTests.Fixer.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/DoNotDirectlyAwaitATaskTests.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/QualityGuidelines/DoNotRaiseExceptionsInExceptionClausesTests.cs
- src/Microsoft.NetCore.Analyzers/Core/Runtime/AvoidZeroLengthArrayAllocations.cs
- src/Microsoft.NetFramework.Analyzers/Core/DoNotCatchCorruptedStateExceptions.cs
- src/Microsoft.NetFramework.Analyzers/Core/DoNotUseInsecureDtdProcessing.cs
- src/Microsoft.NetFramework.Analyzers/UnitTests/DoNotCatchCorruptedStateExceptionsTests.cs
This change moves the analyzers to the latest IOperation APIs. Additionally, it reverts a bunch of commits from https://github.com/dotnet/roslyn-analyzers/pull/1308/ when we moved to the prior IOperation APIs with many of them internalized.
Fixes #1303
Fixes #1304 
Fixes #1305
Once this change is merged, we should be good to kick off a signed build for the analyzers.
>  Move to the latest IOperation APIs

- src/Analyzer.Utilities/Extensions/INamedTypeSymbolExtensions.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/StaticHolderTypeTests.Fixer.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/StaticHolderTypeTests.cs
Fixes https://github.com/dotnet/roslyn-analyzers/issues/1320
Fixes https://github.com/dotnet/roslyn-analyzers/issues/1292
This PR is adjusting the implementation to match FxCop behavior.
> CA1052 should ignore sealed types.

- src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/ReviewUnusedParameters.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/Maintainability/ReviewUnusedParametersTests.cs
Fixes https://github.com/dotnet/roslyn-analyzers/issues/1220
Fixes #1357
This updates CA1801 to be aware of method bodies that are only `throw NotImplementedException()`, and makes sure that diagnostics aren't registered for them.
> Make ca1801 aware of methods that just throw NotImplementedException

- src/Microsoft.CodeAnalysis.Analyzers/Core/FixAnalyzers/FixerWithFixAllAnalyzer.cs
- src/Microsoft.CodeAnalysis.Analyzers/UnitTests/FixAnalyzers/FixerWithFixAllAnalyzerTests.cs
This bug is causing quite a few code fixers to be skipped during analysis.
Fixes #1413
> Do not skip FixAllProvider analysis for abstract types

- src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/UseNameofInPlaceOfString.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/Maintainability/UseNameOfInPlaceOfStringTests.cs
Added additional check for  `argument.ArgumentKind != ArgumentKind.Explicit` and a unit test.
> Fix Nameof in response to issue #1426

- src/Microsoft.NetCore.Analyzers/Core/Runtime/AvoidZeroLengthArrayAllocations.Fixer.cs
- src/Microsoft.NetCore.Analyzers/Core/Runtime/AvoidZeroLengthArrayAllocations.cs
- src/Microsoft.NetCore.Analyzers/UnitTests/Runtime/AvoidZeroLengthArrayAllocationsTests.cs
Fixes #1298 
The original case was failing because it assumed the type of the declaration would match up with the type of the expression. e.g. for `object[] a = new string[0]`, the codefix would be `Array.Empty<object>()`. This PR changes that approach so it doesn't look at the declaration, and determines the element type solely from the expression using IOperation APIs.
/cc @333fred
> Fix NRE in CA1825: AvoidZeroLengthArrayAllocations

- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/CollectionPropertiesShouldBeReadOnly.cs
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/NonConstantFieldsShouldNotBeVisible.cs
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/OperatorOverloadsHaveNamedAlternates.cs
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/OperatorsShouldHaveSymmetricalOverloads.cs
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/OverloadOperatorEqualsOnOverridingValueTypeEquals.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/CollectionPropertiesShouldBeReadOnlyTests.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/NonConstantFieldsShouldNotBeVisibleTests.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/OperatorOverloadsHaveNamedAlternatesTests.Fixer.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/OperatorOverloadsHaveNamedAlternatesTests.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/OperatorsShouldHaveSymmetricalOverloadsTests.Fixer.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/OperatorsShouldHaveSymmetricalOverloadsTests.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/OverloadOperatorEqualsOnOverridingValueTypeEqualsTests.cs
- src/Microsoft.NetCore.Analyzers/Core/Runtime/InstantiateArgumentExceptionsCorrectly.cs
Addresses https://github.com/dotnet/roslyn-analyzers/issues/1432#issuecomment-349475438
> Fix ported FxCop analyzers for Usage rules to analyze only externally visible symbols

- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/EnumsShouldHavePluralNames.cs
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/IdentifiersShouldHaveCorrectPrefix.cs
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/IdentifiersShouldNotContainTypeNames.cs
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/IdentifiersShouldNotContainUnderscores.cs
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/ParameterNamesShouldMatchBaseDeclaration.cs
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/PropertyNamesShouldNotMatchGetMethods.cs
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/TypeNamesShouldNotMatchNamespaces.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/EnumsShouldHavePluralNamesTests.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/IdentifiersShouldHaveCorrectPrefixTests.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/IdentifiersShouldNotContainTypeNamesTests.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/IdentifiersShouldNotContainUnderscoresTests.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/ParameterNamesShouldMatchBaseDeclarationTests.Fixer.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/ParameterNamesShouldMatchBaseDeclarationTests.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/PropertyNamesShouldNotMatchGetMethodsTests.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/TypeNamesShouldNotMatchNamespacesTests.cs
Addresses https://github.com/dotnet/roslyn-analyzers/issues/1432#issuecomment-349579767
> Ensure that ported analyzers for FxCop Naming rules analyze only externally visible symbols

- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/DoNotDeclareStaticMembersOnGenericTypes.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/DoNotDeclareStaticMembersOnGenericTypesTests.cs
Fixes https://github.com/dotnet/roslyn-analyzers/issues/1287
> CA1000 should not fire for conversion operators on static classes

- build/Versions.props
Infrastructure only: Fixes paths to toolset build tasks.
> Update to RepoToolset 1.0.0-beta-62412-04

- src/Directory.Build.props
- src/Microsoft.CodeQuality.Analyzers/CSharp/Maintainability/CSharpRemoveUnusedLocals.Fixer.cs
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/CancellationTokenParametersMustComeLast.cs
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/DoNotHideBaseClassMethods.cs
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/ImplementIDisposableCorrectly.cs
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/NestedTypesShouldNotBeVisible.cs
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/OverloadOperatorEqualsOnOverridingValueTypeEquals.cs
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/PropertiesShouldNotReturnArrays.cs
- src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/UseNameofInPlaceOfString.cs
- src/Microsoft.CodeQuality.Analyzers/Core/QualityGuidelines/DoNotRaiseExceptionsInExceptionClauses.cs
- src/Microsoft.CodeQuality.Analyzers/Core/QualityGuidelines/MarkMembersAsStatic.cs
- src/Microsoft.CodeQuality.Analyzers/Core/QualityGuidelines/UseLiteralsWhereAppropriate.cs
- src/Microsoft.CodeQuality.Analyzers/VisualBasic/Maintainability/BasicRemoveUnusedLocals.Fixer.vb
- src/Microsoft.NetCore.Analyzers/Core/Runtime/AvoidZeroLengthArrayAllocations.cs
- src/Microsoft.NetCore.Analyzers/Core/Runtime/InitializeStaticFieldsInline.cs
- src/Microsoft.NetCore.Analyzers/Core/Runtime/TestForEmptyStringsUsingStringLength.cs
- src/Utilities/DiagnosticHelpers.cs
Enable more rules by default in Microsoft CodeAnalysis VSIX. This change is built on top of https://github.com/dotnet/roslyn-analyzers/pull/1462 and needs that PR to be merged first.
> Enable more vsix rules

- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/CancellationTokenParametersMustComeLast.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/CancellationTokenParametersMustComeLastTests.cs
Fixes #1491
/cc @333fred, @mavasani
> Do not fire CA1608 if the CancellationToken is the first parameter of an extension method

- src/Microsoft.NetFramework.Analyzers/Core/SerializationRulesDiagnosticAnalyzer.cs
- src/Microsoft.NetFramework.Analyzers/UnitTests/MarkAllNonSerializableFieldsTests.cs
https://github.com/dotnet/roslyn/issues/3898 prevents the existing attribute based detection code to work for large number of cases. This PR adds a workaround to use reflection to read this property. Once the Roslyn issue is fixed, this code must be removed.
Fixes #1510
> Correctly detect serializable types from metadata using reflection

- src/Microsoft.CodeQuality.Analyzers/CSharp/Maintainability/CSharpReviewUnusedParameters.Fixer.cs
- src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/MicrosoftMaintainabilityAnalyzersResources.resx
- src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/ReviewUnusedParameters.Fixer.cs
- src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/ReviewUnusedParameters.cs
- src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/xlf/MicrosoftMaintainabilityAnalyzersResources.cs.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/xlf/MicrosoftMaintainabilityAnalyzersResources.de.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/xlf/MicrosoftMaintainabilityAnalyzersResources.es.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/xlf/MicrosoftMaintainabilityAnalyzersResources.fr.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/xlf/MicrosoftMaintainabilityAnalyzersResources.it.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/xlf/MicrosoftMaintainabilityAnalyzersResources.ja.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/xlf/MicrosoftMaintainabilityAnalyzersResources.ko.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/xlf/MicrosoftMaintainabilityAnalyzersResources.pl.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/xlf/MicrosoftMaintainabilityAnalyzersResources.pt-BR.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/xlf/MicrosoftMaintainabilityAnalyzersResources.ru.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/xlf/MicrosoftMaintainabilityAnalyzersResources.tr.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/xlf/MicrosoftMaintainabilityAnalyzersResources.zh-Hans.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/xlf/MicrosoftMaintainabilityAnalyzersResources.zh-Hant.xlf
- src/Microsoft.CodeQuality.Analyzers/UnitTests/Maintainability/ReviewUnusedParametersTests.Fixer.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/Maintainability/ReviewUnusedParametersTests.cs
- src/Microsoft.CodeQuality.Analyzers/VisualBasic/Maintainability/BasicReviewUnusedParameters.Fixer.vb
Fixes #459
The current version performs all the fixes: safe and unsafe.
```
void M1(int x) { }
int M2(int x) => x;
void Caller1()
{
M1(M2(0));
}
```
would be fixed.
> Fixer for rule CA1801: ReviewUnusedParameters

- src/Microsoft.CodeQuality.Analyzers/CSharp/Maintainability/CSharpUseNameofInPlaceOfString.Fixer.cs
- src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/UseNameofInPlaceOfString.Fixer.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/Maintainability/UseNameOfInPlaceOfStringTests.Fixer.cs
- src/Microsoft.CodeQuality.Analyzers/VisualBasic/Maintainability/BasicUseNameofInPlaceOfString.Fixer.vb
This PR adds a workaround for https://github.com/dotnet/roslyn/issues/24212
Once the above Roslyn bug is fixed, we should revert the product changes made in this PR.
Fixes #1364
> Workaround for Roslyn bug in SyntaxGenerator.NameOfExpression in nameof fixer

- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/MicrosoftApiDesignGuidelinesAnalyzersResources.resx
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.cs.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.de.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.es.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.fr.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.it.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.ja.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.ko.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.pl.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.pt-BR.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.ru.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.tr.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.zh-Hans.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.zh-Hant.xlf
Fixes https://github.com/dotnet/roslyn-analyzers/issues/1397. We were already passing the correct symbols to the message, but the message didn't do anything with them. https://github.com/dotnet/roslyn-analyzers/blob/master/src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/InterfaceMethodsShouldBeCallableByChildTypes.cs#L139
> Update CA1033 message to be more explanatory.

- src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Analysis/NullAnalysis/NullAnalysis.NullAbstractValueDomain.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Analysis/NullAnalysis/NullAnalysis.NullDataFlowOperationVisitor.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Analysis/NullAnalysis/NullAnalysis.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAnalysis.PointsToAbstractValueDomain.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAnalysis.PointsToDataFlowOperationVisitor.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAnalysis.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Analysis/StringContentAnalysis/StringContentAnalysis.StringContentAbstractDomain.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Analysis/StringContentAnalysis/StringContentAnalysis.StringContentDataFlowOperationVisitor.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Analysis/StringContentAnalysis/StringContentAnalysis.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Framework/DataFlow/AbstractValueDomain.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Framework/DataFlow/AnalysisEntity.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Framework/DataFlow/AnalysisEntityFactory.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Framework/DataFlow/AnalysisEntityMapAbstractDomain.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Framework/DataFlow/MapAbstractDomain.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/UnitTests/Maintainability/ReviewSQLQueriesForSecurityVulnerabilitiesTests_FlowAnalysis.cs
Addresses #1567
Add temporary code to DataFlowOperationVisitor to handle flow analysis for loops and if-else statements. This code will be removed once we move to compiler's CFG, which would have lowered all IOperations for these constructs. #1567 will be kept active to track this code removal.
Enabling skipped tests for if-else statement identified a bug in the merge algorithm for merging analysis data in presence of points to analysis, which has now been fixed.
> Handle loops and if-else statements and fix a bug in merge algorithm

- src/Microsoft.CodeQuality.Analyzers.Exp/Core/DisposeAnalysisHelper.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Analysis/DisposeAnalysis/DisposeAbstractValue.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Analysis/DisposeAnalysis/DisposeAnalysis.DisposeAbstractValueDomain.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Analysis/DisposeAnalysis/DisposeAnalysis.DisposeDataFlowOperationVisitor.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Analysis/DisposeAnalysis/DisposeAnalysis.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Framework/DataFlow/AbstractLocationDataFlowOperationVisitor.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Framework/DataFlow/AnalysisEntityDataFlowOperationVisitor.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/Reliability/DisposeObjectsBeforeLosingScope.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/Usage/DisposableFieldsShouldBeDisposed.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/Usage/MicrosoftUsageAnalyzersResources.resx
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/Usage/xlf/MicrosoftUsageAnalyzersResources.cs.xlf
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/Usage/xlf/MicrosoftUsageAnalyzersResources.de.xlf
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/Usage/xlf/MicrosoftUsageAnalyzersResources.es.xlf
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/Usage/xlf/MicrosoftUsageAnalyzersResources.fr.xlf
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/Usage/xlf/MicrosoftUsageAnalyzersResources.it.xlf
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/Usage/xlf/MicrosoftUsageAnalyzersResources.ja.xlf
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/Usage/xlf/MicrosoftUsageAnalyzersResources.ko.xlf
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/Usage/xlf/MicrosoftUsageAnalyzersResources.pl.xlf
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/Usage/xlf/MicrosoftUsageAnalyzersResources.pt-BR.xlf
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/Usage/xlf/MicrosoftUsageAnalyzersResources.ru.xlf
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/Usage/xlf/MicrosoftUsageAnalyzersResources.tr.xlf
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/Usage/xlf/MicrosoftUsageAnalyzersResources.zh-Hans.xlf
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/Usage/xlf/MicrosoftUsageAnalyzersResources.zh-Hant.xlf
- src/Microsoft.CodeQuality.Analyzers.Exp/UnitTests/Usage/DisposableFieldsShouldBeDisposedTests.cs
- src/Utilities/Extensions/IMethodSymbolExtensions.cs
- src/Utilities/Extensions/ITypeSymbolExtensions.cs
See https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2213-disposable-fields-should-be-disposed for the rule description.
FxCop implementation for this rule reported CA2213 only for those fields which were assigned a locally created disposable object within the containing type methods/initializers. This reduced noise for cases where the type did not own the dispose responsibility for certain disposable fields. We are matching this implementation and will need to get the docs updated accordingly (#1593)
TODO: #1594 (Improve CA2213 (DisposableFieldsShouldBeDisposed) to handle cases where fields are disposed by helper methods invoked by Dispose)
Fixes #695
> Implement CA2213 (DisposableFieldsShouldBeDisposed)

- src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Analysis/NullAnalysis/NullAnalysis.NullDataFlowOperationVisitor.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/UnitTests/Reliability/DisposeObjectsBeforeLosingScopeTests.cs
Don't assume that target of an assigment operation always has non-null type. Verified the NRE repros for the added test before the fix.
Fixes #1597
> Fix NRE for invalid code in NullDataFlowOperationVisitor

- src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Analysis/DisposeAnalysis/DisposeAnalysis.DisposeDataFlowOperationVisitor.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Analysis/NullAnalysis/NullAnalysis.NullDataFlowOperationVisitor.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAbstractValue.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAnalysis.PointsToAbstractValueDomain.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAnalysis.PointsToDataFlowOperationVisitor.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Framework/DataFlow/AnalysisEntityDataFlowOperationVisitor.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Framework/DataFlow/AnalysisEntityMapAbstractDomain.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Framework/DataFlow/DataFlowAnalysis.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/UnitTests/Reliability/DisposeObjectsBeforeLosingScopeTests.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/UnitTests/Usage/DisposableFieldsShouldBeDisposedTests.cs
1. Due to lack of a *real* CFG (#1567), we did not correctly merge analysis states from all return statements at CFG exit block. This change adds a temporary workaround to correctly track analysis state for methods with intermediate return statements.
2. Due to pending dataflow support for tuple operations (#1571), we need to pessimistically reset the analysis values for all tuple elements to ensure we do not report incorrect violations for dispose rules.
> Couple more fixes to flow analysis for false positives on Roslyn.sln

- src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Analysis/PointsToAnalysis/DefaultPointsToValueGenerator.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAbstractValue.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAnalysis.PointsToAbstractValueDomain.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAnalysis.PointsToDataFlowOperationVisitor.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAnalysis.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAnalysisDomain.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Analysis/PointsToAnalysis/PointsToBlockAnalysisResult.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Framework/DataFlow/AbstractLocation.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Framework/DataFlow/AnalysisEntityMapAbstractDomain.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Framework/DataFlow/SetAbstractDomain.cs
Commit https://github.com/dotnet/roslyn-analyzers/pull/1620/commits/8bc1cdfccbd29640edfd6d37b1c1645f5be534f2 improved preciseness of PointsTo analysis by tracking known location subset even for entities with PointsToAbstractValueKind.Unknown. This led to a considerable performance regression in building Roslyn.sln. This change fixes that regression by optimizing PointsToAnalysis to not create unnecessary key-value pairs for non-symbol entities and unrelated symbol based entities. With this change, the performance for building Roslyn.sln with or without dispose rules is almost identical.
> Fix performance regression for points to analysis from recent commit

- Directory.Build.props
- README.md
- build/Codecov.proj
- build/GenerateAnalyzerNuspec.targets
- build/NuGet.props
- build/Toolset.proj
- build/Versions.props
- build/build.ps1
- codecov.yml
- nuget/Directory.Build.props
- nuget/Directory.Build.targets
- src/Directory.Build.props
- src/Directory.Build.targets
- src/MetaCompilation.Analyzers/Directory.Build.props
- src/Test.Utilities/Directory.Build.props
- src/Test.Utilities/Directory.Build.targets
- tools/AnalyzerCodeGenerator/template/build/Targets/Analyzers.Imports.targets
- tools/AnalyzerCodeGenerator/template/build/Targets/Analyzers.NuGet.Imports.targets
- tools/AnalyzerCodeGenerator/template/build/Targets/Analyzers.NuGet.Settings.targets
- tools/AnalyzerCodeGenerator/template/build/Targets/Analyzers.Settings.targets
- tools/AnalyzerCodeGenerator/template/build/Targets/Analyzers.Versions.targets
- tools/AnalyzerCodeGenerator/template/build/Targets/GenerateAssemblyInfo.targets
- tools/AnalyzerCodeGenerator/template/build/Targets/GenerateInternalsVisibleTo.targets
This pull request demonstrates the work required to complete #1614. It needs to get cleaned up, and the core functionality needs to be incorporated into RepoToolset.
This pull request builds on #1608.
> Integrate OpenCover and codecov.io for code coverage

- src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Analysis/CopyAnalysis/CopyAbstractValue.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Analysis/DisposeAnalysis/DisposeAbstractValue.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAbstractValue.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAnalysis.PointsToDataFlowOperationVisitor.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Analysis/StringContentAnalysis/StringContentAbstractValue.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Framework/DataFlow/AbstractEquatable.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Framework/DataFlow/AbstractIndex.ConstantValueIndex.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Framework/DataFlow/AbstractIndex.OperationBasedIndex.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Framework/DataFlow/AbstractIndex.SymbolBasedIndex.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Framework/DataFlow/AbstractIndex.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Framework/DataFlow/AbstractLocation.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Framework/DataFlow/AnalysisEntity.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Framework/DataFlow/AnalysisEntityDataFlowOperationVisitor.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Framework/DataFlow/AnalysisEntityFactory.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Framework/DataFlow/AnalysisEntityMapAbstractDomain.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs
- src/Utilities/Extensions/IOperationExtensions.cs
1. Cache the hash code of analysis values. GetHashCode shows up quite a bit on analysis perf traces.
2. Reduce merge invocations for binary operations.
3. Avoid walking the IOperation parent chain when attempting to compute the instance corresponding to an IInstanceOperation. For majority of cases we are not within an object initializer and don't need the associated perf hit.
4. Some other small misc improvements from perf traces.
> Performance improvements for DFA

- build/Versions.props
Changes included in the toolset:
https://github.com/dotnet/roslyn-tools/commits/pre-SDK/sdks/RepoToolset
Previous update was dotnet/roslyn-tools@1bc665575121187618aabc26cdc35afde255d1f5 ([diff](https://github.com/dotnet/roslyn-tools/compare/1bc665575121187618aabc26cdc35afde255d1f5...e6c328b0dcbdc304182f168c64e55e5c8959a65f))
> Update RepoToolset to 1.0.0-beta-62705-01

- src/Roslyn.Diagnostics.Analyzers/Core/DeclarePublicAPIAnalyzer.Impl.cs
- src/Roslyn.Diagnostics.Analyzers/UnitTests/DeclarePublicAPIAnalyzerTests.cs
During normal operation, properties are not added to the public API surface area because the analyzer does not register a symbol
action for `SymbolKind.Property`. This works fine, there is an action registered for `SymbolKind.Method`, which ensures that getters
and setters are added as expected. Things are a bit different for forwarded types.
In the case of a forwarded type, the public API surface area is discovered by recursively searching members and nested types. However,
this code adds both properties *and* accessors, resulting in the PublicAPI.Shipped.txt file needs to include an entry for the property
and the accessors, like so:
```
Microsoft.CodeAnalysis.FileTextLoader.Path.get -> string (forwarded, contained in Microsoft.CodeAnalysis.Workspaces) …
```
> Only add getters and setters for type-forwarded properties to public API

- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/IdentifiersShouldNotHaveIncorrectSuffix.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/IdentifiersShouldNotHaveIncorrectSuffixTests.cs
Currently, a type ending with "Dictionary" that inherits from System.Collections.Generic.IDictionary<TKey,TValue> will be reported. This change prevents that from happening and tests it.
> Fix issue #1656: CA1711 incorrectly reports "Dictionary" types

- src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Analysis/CopyAnalysis/CopyAnalysis.CopyDataFlowOperationVisitor.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Analysis/NullAnalysis/NullAnalysis.NullDataFlowOperationVisitor.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Analysis/StringContentAnalysis/StringContentAnalysis.StringContentDataFlowOperationVisitor.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Framework/DataFlow/AbstractLocationDataFlowOperationVisitor.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Framework/DataFlow/AnalysisEntity.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Framework/DataFlow/AnalysisEntityDataFlowOperationVisitor.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Framework/DataFlow/DataFlowAnalysisResult.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Framework/DataFlow/WellKnownTypeProvider.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/Maintainability/AvoidDeadConditionalCode.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/UnitTests/Design/ValidateArgumentsOfPublicMethodsTests.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/UnitTests/Maintainability/AvoidDeadConditionalCode_NullAnalysis.cs
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/DoNotRaiseExceptionsInUnexpectedLocations.cs
- src/Utilities/Extensions/IMethodSymbolExtensions.cs
- src/Utilities/Extensions/INamedTypeSymbolExtensions.cs
1. Improve the precision of predicate analysis by infering various Equals and ReferenceEquals methods for equality checks.
2. Be more conservative in presence of lock statements.
3. Fix false positives in presence of break and continue statements for loops and switch statement.
> Fix some false positives for new DFA rules

- nuget/Microsoft.CodeQuality.Analyzers.Exp/Microsoft.CodeQuality.Analyzers.Exp.props
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/Usage/DisposeMethodsShouldCallBaseClassDispose.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/Usage/MicrosoftUsageAnalyzersResources.resx
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/Usage/xlf/MicrosoftUsageAnalyzersResources.cs.xlf
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/Usage/xlf/MicrosoftUsageAnalyzersResources.de.xlf
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/Usage/xlf/MicrosoftUsageAnalyzersResources.es.xlf
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/Usage/xlf/MicrosoftUsageAnalyzersResources.fr.xlf
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/Usage/xlf/MicrosoftUsageAnalyzersResources.it.xlf
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/Usage/xlf/MicrosoftUsageAnalyzersResources.ja.xlf
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/Usage/xlf/MicrosoftUsageAnalyzersResources.ko.xlf
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/Usage/xlf/MicrosoftUsageAnalyzersResources.pl.xlf
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/Usage/xlf/MicrosoftUsageAnalyzersResources.pt-BR.xlf
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/Usage/xlf/MicrosoftUsageAnalyzersResources.ru.xlf
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/Usage/xlf/MicrosoftUsageAnalyzersResources.tr.xlf
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/Usage/xlf/MicrosoftUsageAnalyzersResources.zh-Hans.xlf
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/Usage/xlf/MicrosoftUsageAnalyzersResources.zh-Hant.xlf
- src/Microsoft.CodeQuality.Analyzers.Exp/Microsoft.CodeQuality.Analyzers.Exp.md
- src/Microsoft.CodeQuality.Analyzers.Exp/UnitTests/Usage/DisposeMethodsShouldCallBaseClassDisposeTests.cs
- src/Utilities/Analyzer.Utilities.projitems
- src/Utilities/Extensions/IOperationExtensions.cs
- src/Utilities/InstanceReferenceKind.cs
_A type that implements System.IDisposable inherits from a type that also implements IDisposable. The Dispose method of the inheriting type does not call the Dispose method of the parent type._
**Rule Description:** https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2215-dispose-methods-should-call-base-class-dispose
Fixes #535
TODO: #1654 tracks improving the rule precision with dataflow analysis.
> Implement CA2215 (DisposeMethodsShouldCallBaseClassDispose)

- src/Roslyn.Diagnostics.Analyzers/Core/DeclarePublicAPIFix.cs
- src/Roslyn.Diagnostics.Analyzers/UnitTests/DeclarePublicAPIAnalyzerTests.cs
Sorted unshipped files are nice for reviewing the entire file (infrequent), but they often make incremental reviews harder whenever the order was messed up by a merge.
This PR relaxes the sorting logic. When new entries are added, we scan from the top and find the first suitable place, with the rest of the file in its original order.
Relates to https://github.com/dotnet/roslyn/issues/26285
> DeclarePublicAPI: Relax sorting logic

- Build.cmd
- Restore.cmd
- Test.cmd
- src/Microsoft.CodeAnalysis.Analyzers/CSharp/CSharpUpgradeMSBuildWorkspaceAnalyzer.cs
- src/Microsoft.CodeAnalysis.Analyzers/CSharp/Microsoft.CodeAnalysis.CSharp.Analyzers.csproj
- src/Microsoft.CodeAnalysis.Analyzers/Core/CodeAnalysisDiagnosticsResources.resx
- src/Microsoft.CodeAnalysis.Analyzers/Core/DiagnosticIds.cs
- src/Microsoft.CodeAnalysis.Analyzers/Core/UpgradeMSBuildWorkspaceAnalyzer.cs
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.cs.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.de.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.es.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.fr.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.it.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.ja.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.ko.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.pl.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.pt-BR.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.ru.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.tr.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.zh-Hans.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.zh-Hant.xlf
- src/Microsoft.CodeAnalysis.Analyzers/UnitTests/UpgradeMSBuildWorkspaceAnalyzerTests.cs
- src/Microsoft.CodeAnalysis.Analyzers/VisualBasic/Microsoft.CodeAnalysis.VisualBasic.Analyzers.vbproj
- src/Microsoft.CodeAnalysis.Analyzers/VisualBasic/VisualBasicUpgradeMSBuildWorkspaceAnalyzer.vb
This analyzer will report a diagnostic under the following conditions:
1. The current compilation references `Microsoft.CodeAnalysis.Workspaces.Desktop`.
2. The current compilation does not reference `Microsoft.CodeAnalysis.Workspaces.MSBuild`.
3. The current compilation does not contain the type `Microsoft.CodeAnalysis.Workspaces.MSBuildWorkspace`.
4. An unbound identifier is encountered with the name `MSBuildWorkspace`.
Ultimately, the diagnostic will simply point to guidance that helps customers use `MSBuildWorkspace` properly.
There is a still a bit of work yet before this can be merged:
Finally, note that the unit tests do not verify the first two checks above. This is actually very hard to do with the current test infrastructure.
> Add an analyzer that reports a diagnostic when MSBuildWorkspace likely needs upgrading

- src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/ReviewUnusedParameters.cs
- src/Microsoft.CodeQuality.Analyzers/Core/QualityGuidelines/MarkMembersAsStatic.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/QualityGuidelines/MarkMembersAsStaticTests.cs
- src/Utilities/Analyzer.Utilities.projitems
- src/Utilities/Extensions/OperationBlockAnalysisContextExtension.cs
Fixes #1544
This updates CA1822 to be aware of method bodies that are only throw NotImplementedException() and makes sure that diagnostics aren't registered for them.
> Fix: CA1822 Mark Members As Static should not trigger for methods containing only NotImplementedException #1544

- src/Microsoft.NetCore.Analyzers/UnitTests/Runtime/SpecifyCultureInfoTests.cs
- src/Microsoft.NetCore.Analyzers/UnitTests/Runtime/SpecifyIFormatProviderTests.cs
- src/Microsoft.NetCore.Analyzers/UnitTests/Runtime/SpecifyStringComparisonTests.cs
- src/Utilities/Extensions/IEnumerableOfIMethodSymbolExtensions.cs
Affected rules: CA1304, CA1305 and CA1307
Fixes #1734
> Account for parameter RefKind while identifying alternate overloads.

- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/TypeNamesShouldNotMatchNamespaces.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/TypeNamesShouldNotMatchNamespacesTests.cs
The implementation becomes more stricter then legacy implementation, which considers all namespaces at least one type, externally or non-externally visible. However, given the intent of the rule to help design a consumable public library, the stricter implementation seems less noisy as the library clients would only care about externally visible types.
Fixes #1673
> Only consider namespaces with externally visible types for CA1724

- src/Microsoft.CodeQuality.Analyzers/CSharp/QualityGuidelines/CSharpUseLiteralsWhereAppropriate.Fixer.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/DoNotDirectlyAwaitATaskTests.Fixer.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/EnumsShouldHaveZeroValueTests.Fixer.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/Microsoft.CodeQuality.Analyzers.UnitTests.csproj
- src/Microsoft.CodeQuality.Analyzers/UnitTests/QualityGuidelines/UseLiteralsWhereAppropriateTests.Fixer.cs
- src/Test.Utilities/CodeFixRunner.cs
- src/Test.Utilities/CodeFixTestBase.cs
All the VerifyXXXFix test helpers now take an optional FixAllScope, which defaults to document/project based on whether the test verifies a single document or multiple documents. After validating the individual diagnostic code fix, the test framework also invokes the FixAll and verifies the result is identical.
For unit tests which have multiple fixable diagnostics in the original source code, they should explicitly disable FixAll testing in the VerifyXXXFix call by passing a null FixAllScope and have a separate FixAll test with appropriate baseline.
For code fixers which have no FixAll support, they can override the `TestFixAllByDefault` property to turn off FixAll testing for all it's unit tests.
Fixes #1420
> Enable FixAll testing by default for all code fix tests

- src/Directory.Build.props
- src/Utilities/CodeMetrics/CodeAnalysisMetricData.NamedTypeMetricData.cs
- src/Utilities/CodeMetrics/CodeAnalysisMetricData.cs
- src/Utilities/CodeMetrics/ComputationalComplexityMetrics.cs
- src/Utilities/CodeMetrics/MetricsHelper.cs
- src/Utilities/Extensions/IOperationExtensions.cs
Define a new preprocessor directive to generate code metrics based on legacy mode heuristics (FxCop based MSIL analysis). This is done as part of customer requests for compat. Note that majority of these heursitics are very specific to IL analysis and hence are not included in the default code metrics mode.
Fixes #1840
@jgold6 Once this PR is merged in, customers can get code metrics data using legacy/compat mode by compiling the Metrics.csproj with following command: 
`msbuild /m /v:m /t:rebuild /p:LEGACY_CODE_METRICS_MODE=true Metrics.csproj`
I have attached the new code metrics reported generated by Metrics.exe for MobileApp/XamarinCRM in the new legacy mode. The numbers match a lot more with the legacy code metrics generation in VS. Please verify: …
> Enable generating code metrics in legacy mode

- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/ImplementIDisposableCorrectly.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/ImplementIDisposableCorrectlyTests.cs
Fixes #1795
"Implement IDisposable Correctly" was still fired, when type was internal and not inherited from base type.
> ImplementIDisposableCorrectly should only analyze externally visible type

- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/StaticHolderTypes.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/StaticHolderTypeTests.cs
Fixes issue #1820 Base class is should not be detected as a static holder type
> Don't trigger ca1052 for abstract classes

- src/Microsoft.CodeQuality.Analyzers/UnitTests/QualityGuidelines/ValidateArgumentsOfPublicMethodsTests.cs
- src/Utilities/FlowAnalysis/Framework/DataFlow/AnalysisEntity.cs
- src/Utilities/FlowAnalysis/Framework/DataFlow/AnalysisEntityDataFlowOperationVisitor.cs
This fixes the assert in CopyAnalysis identified by @dotpaul in https://github.com/dotnet/roslyn-analyzers/issues/1870#issuecomment-435544389
> Fix GetChildAnalysisEntities to not return the original given entity

- src/Microsoft.CodeQuality.Analyzers/UnitTests/QualityGuidelines/ValidateArgumentsOfPublicMethodsTests.cs
- src/Utilities/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAnalysis.PointsToDataFlowOperationVisitor.cs
There are bunch of cases where we don't add abstract value to the CurrentAnalysisData map if the default value is the same, primarily for performance reasons.
> Remove an invalid assert

- src/Microsoft.CodeQuality.Analyzers/UnitTests/QualityGuidelines/ValidateArgumentsOfPublicMethodsTests.cs
- src/Utilities/FlowAnalysis/Analysis/CopyAnalysis/CopyAbstractValue.cs
- src/Utilities/FlowAnalysis/Analysis/CopyAnalysis/CopyAnalysisContext.cs
- src/Utilities/FlowAnalysis/Analysis/DisposeAnalysis/DisposeAbstractValue.cs
- src/Utilities/FlowAnalysis/Analysis/DisposeAnalysis/DisposeAnalysis.DisposeDataFlowOperationVisitor.cs
- src/Utilities/FlowAnalysis/Analysis/DisposeAnalysis/DisposeAnalysisContext.cs
- src/Utilities/FlowAnalysis/Analysis/ParameterValidationAnalysis/ParameterValidationAnalysis.ParameterValidationDataFlowOperationVisitor.cs
- src/Utilities/FlowAnalysis/Analysis/ParameterValidationAnalysis/ParameterValidationAnalysisContext.cs
- src/Utilities/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAbstractValue.cs
- src/Utilities/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAnalysisContext.cs
- src/Utilities/FlowAnalysis/Analysis/PropertySetAnalysis/PropertySetAnalysisContext.cs
- src/Utilities/FlowAnalysis/Analysis/TaintedDataAnalysis/SymbolAccess.cs
- src/Utilities/FlowAnalysis/Analysis/TaintedDataAnalysis/TaintedDataAbstractValue.cs
- src/Utilities/FlowAnalysis/Analysis/TaintedDataAnalysis/TaintedDataAnalysisContext.cs
- src/Utilities/FlowAnalysis/Analysis/ValueContentAnalysis/ValueContentAbstractValue.cs
- src/Utilities/FlowAnalysis/Analysis/ValueContentAnalysis/ValueContentAnalysisContext.cs
- src/Utilities/FlowAnalysis/Framework/DataFlow/AbstractDataFlowAnalysisContext.cs
- src/Utilities/FlowAnalysis/Framework/DataFlow/AbstractIndex.ConstantValueIndex.cs
- src/Utilities/FlowAnalysis/Framework/DataFlow/AbstractIndex.OperationBasedIndex.cs
- src/Utilities/FlowAnalysis/Framework/DataFlow/AbstractIndex.SymbolBasedIndex.cs
- src/Utilities/FlowAnalysis/Framework/DataFlow/AbstractLocation.cs
- src/Utilities/FlowAnalysis/Framework/DataFlow/AnalysisEntity.cs
- src/Utilities/FlowAnalysis/Framework/DataFlow/AnalysisEntityMapAbstractDomain.cs
- src/Utilities/FlowAnalysis/Framework/DataFlow/ArgumentInfo.cs
- src/Utilities/FlowAnalysis/Framework/DataFlow/CacheBasedEquatable.cs
- src/Utilities/FlowAnalysis/Framework/DataFlow/InterproceduralAnalysisData.cs
- src/Utilities/HashUtilities.cs
We now do a quick pass that compares reference equality and hash codes, which if required is followed by a slow pass that compares individual part hash codes. If this still turns out to cause hash code clashes, we will implement the true equality checks on an even slower equality compare path.
> Fix CacheBasedEquatable to handle hash code clashes

- src/Microsoft.CodeQuality.Analyzers/UnitTests/QualityGuidelines/ValidateArgumentsOfPublicMethodsTests.cs
- src/Utilities/Extensions/BasicBlockExtensions.cs
- src/Utilities/FlowAnalysis/Analysis/CopyAnalysis/CopyAnalysis.CopyDataFlowOperationVisitor.cs
- src/Utilities/FlowAnalysis/Analysis/CopyAnalysis/CopyAnalysisData.cs
- src/Utilities/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAbstractValue.cs
- src/Utilities/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAnalysis.CorePointsToAnalysisDataDomain.cs
- src/Utilities/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAnalysis.PointsToAbstractValueDomain.cs
- src/Utilities/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAnalysis.PointsToDataFlowOperationVisitor.cs
- src/Utilities/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAnalysisData.cs
- src/Utilities/FlowAnalysis/Analysis/TaintedDataAnalysis/TaintedDataAnalysisData.cs
- src/Utilities/FlowAnalysis/Analysis/ValueContentAnalysis/ValueContentAnalysisData.cs
- src/Utilities/FlowAnalysis/Framework/DataFlow/AbstractLocation.cs
- src/Utilities/FlowAnalysis/Framework/DataFlow/AnalysisEntity.cs
- src/Utilities/FlowAnalysis/Framework/DataFlow/AnalysisEntityBasedPredicateAnalysisData.cs
- src/Utilities/FlowAnalysis/Framework/DataFlow/DataFlowAnalysis.cs
- src/Utilities/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs
Fix some more asserts from dogfooding interprocedural rule. https://github.com/dotnet/roslyn-analyzers/commit/6c1df8331f3b36126a3530414b653d19c1401606 is the primary bulky commit that changes PointsToAbstractValue merging logic.
> Asserts continued - interprocedural analysis

- src/Microsoft.CodeQuality.Analyzers/UnitTests/QualityGuidelines/ValidateArgumentsOfPublicMethodsTests.cs
- src/Utilities/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAbstractValue.cs
- src/Utilities/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAbstractValueKind.cs
- src/Utilities/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAnalysis.CorePointsToAnalysisDataDomain.cs
- src/Utilities/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAnalysis.PointsToAbstractValueDomain.cs
- src/Utilities/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAnalysis.PointsToDataFlowOperationVisitor.cs
- src/Utilities/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAnalysisData.cs
- src/Utilities/FlowAnalysis/Framework/DataFlow/AnalysisEntity.cs
- src/Utilities/FlowAnalysis/Framework/DataFlow/AnalysisEntityFactory.cs
- src/Utilities/FlowAnalysis/Framework/DataFlow/DataFlowAnalysis.cs
- src/Utilities/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs
- src/Utilities/FlowAnalysis/Framework/DataFlow/InterproceduralCaptureId.cs
1. https://github.com/dotnet/roslyn-analyzers/commit/b519d7e7d4bc914c4361e8842e700de3bd845816: Fix implementation of `IsLValueFlowCapture(AnalysisEntity)` computation for Interprocedural capture ID across method calls.
2. https://github.com/dotnet/roslyn-analyzers/commit/a3de3e54b9c33d597f347f3620a0120b2c2de43b: Fix merging of PointsToAbstractValue by inserting new `PointsToAbstractValueKind.UnknownNull` and `PointsToAbstractValueKind.UnknownNotNull` to track values with unknown locations but known null state from predicate analysis. For example, points to value of a `field` in if statment below:
```
class C
{
private object field;
void M()
{
if (field != null)
{
// 'field' has unknown, but non-null PointsTo value here
}
}
}
```
> Fix couple more asserts in PointsToAbstractValue merge

- src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/AvoidDeadConditionalCode.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/Maintainability/AvoidDeadConditionalCode_NullAnalysis.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/Maintainability/AvoidDeadConditionalCode_ValueContentAnalysis.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/QualityGuidelines/ValidateArgumentsOfPublicMethodsTests.cs
- src/Utilities/Extensions/IOperationExtensions.cs
- src/Utilities/FlowAnalysis/Analysis/CopyAnalysis/CopyAnalysis.CopyDataFlowOperationVisitor.cs
- src/Utilities/FlowAnalysis/Analysis/CopyAnalysis/CopyAnalysisData.cs
- src/Utilities/FlowAnalysis/Analysis/ParameterValidationAnalysis/ParameterValidationAnalysis.ParameterValidationDataFlowOperationVisitor.cs
- src/Utilities/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAbstractValueKind.cs
- src/Utilities/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAnalysis.CorePointsToAnalysisDataDomain.cs
- src/Utilities/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAnalysis.PointsToAbstractValueDomain.cs
- src/Utilities/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAnalysis.PointsToDataFlowOperationVisitor.cs
- src/Utilities/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAnalysisData.cs
- src/Utilities/FlowAnalysis/Analysis/PropertySetAnalysis/PropertySetAnalysis.PropertySetDataFlowOperationVisitor.cs
- src/Utilities/FlowAnalysis/Analysis/TaintedDataAnalysis/TaintedDataAnalysis.CoreTaintedDataAnalysisDataDomain.cs
- src/Utilities/FlowAnalysis/Analysis/ValueContentAnalysis/ValueContentAnalysis.CoreAnalysisDataDomain.cs
- src/Utilities/FlowAnalysis/Framework/DataFlow/AbstractDataFlowAnalysisContext.cs
- src/Utilities/FlowAnalysis/Framework/DataFlow/AddressSharedEntitiesProvider.cs
- src/Utilities/FlowAnalysis/Framework/DataFlow/AnalysisEntityFactory.cs
- src/Utilities/FlowAnalysis/Framework/DataFlow/AnalysisEntityMapAbstractDomain.cs
- src/Utilities/FlowAnalysis/Framework/DataFlow/CacheBasedEquatable.cs
- src/Utilities/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs
- src/Utilities/FlowAnalysis/Framework/DataFlow/IDataFlowAnalysisContext.cs
- src/Utilities/FlowAnalysis/Framework/DataFlow/InterproceduralAnalysisData.cs
Each commit has a description of the fix, but high level changes:
1. Fixes related to address shared entities (i.e. ref/out parameter) to ensure the analysis values are tracked properly across inter-procedural calls, especially copy analysis values.
2. Fixes related to recursive and chained invocations of lambda/local functions
3. Support for handling flow analysis values for pattern operations (see #1571).
4. Fixes related to accessing flow captures and flow capture references across inter-procedural calls
5. General improvements to CopyAnalysis with lot more stronger asserts to help catch non-monotonic updates upfront.
> Fix some more asserts and also implement support for IsPatternOperation

- src/Utilities/FlowAnalysis/Analysis/TaintedDataAnalysis/TaintedDataAnalysis.CoreTaintedDataAnalysisDataDomain.cs
TaintedDataAnalysis still tracks sanitized entities, so it seems possible that for mappings to contain NotTainted abstract values.
But I still need to look into the root cause of the assert I saw.
Just removing the assert for now.
> Removing TaintedDataAnalysis assert

- src/Microsoft.CodeQuality.Analyzers/UnitTests/QualityGuidelines/ValidateArgumentsOfPublicMethodsTests.cs
- src/Utilities/Extensions/PooledHashSetExtensions.cs
- src/Utilities/FlowAnalysis/Analysis/CopyAnalysis/CopyAbstractValue.cs
- src/Utilities/FlowAnalysis/Analysis/CopyAnalysis/CopyAnalysis.CopyDataFlowOperationVisitor.cs
- src/Utilities/FlowAnalysis/Analysis/CopyAnalysis/CopyAnalysisData.cs
- src/Utilities/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAnalysis.PointsToDataFlowOperationVisitor.cs
- src/Utilities/FlowAnalysis/Analysis/TaintedDataAnalysis/TaintedDataAnalysis.TaintedDataOperationVisitor.cs
- src/Utilities/FlowAnalysis/Analysis/ValueContentAnalysis/ValueContentAnalysis.ValueContentDataFlowOperationVisitor.cs
- src/Utilities/FlowAnalysis/Framework/DataFlow/AnalysisEntity.cs
- src/Utilities/FlowAnalysis/Framework/DataFlow/AnalysisEntityDataFlowOperationVisitor.cs
- src/Utilities/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs
- src/Utilities/FlowAnalysis/Framework/DataFlow/InterproceduralAnalysisData.cs
Fixes https://github.com/dotnet/roslyn-analyzers/issues/1811
1. Filter the key-value pairs passed to interprocedural analysis to improve its performance:
https://github.com/dotnet/roslyn-analyzers/commit/bfe11f22610ef3ad82a003cff0446f0cba384f71 is the core commit, and significantly improves the performance for interprocedural analysis
2. https://github.com/dotnet/roslyn-analyzers/commit/aad10b5eececd6d28d8d4d83b5e248c2e4925fcb also does some more minor perf optimizations found from traces
> Performance improvements for context-sensitive interprocedural analysis

- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/EquatableAnalyzer.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/EquatableAnalyzerTests.cs
Account for interfaces implemented by the base types.
Fixes #1914
> Fix CA1066 (Implement IEquatable<T> when overriding Object.Equals)

- src/Microsoft.CodeQuality.Analyzers/Core/QualityGuidelines/MarkMembersAsStatic.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/QualityGuidelines/MarkMembersAsStaticTests.cs
- src/Utilities/Extensions/ISymbolExtensions.cs
Don't fire CA1822 on property/event symbols unless all its accessors are candidates for being marked static.
Fixes #1933
> Fix CA1822 (MarkMembersAsStatic) for property/event symbols

- src/Microsoft.NetFramework.Analyzers/Core/SerializationRulesDiagnosticAnalyzer.cs
- src/Microsoft.NetFramework.Analyzers/UnitTests/MarkAllNonSerializableFieldsTests.cs
Diagnostic is only intended for instance fields.
Fixes #1883
> Do not report CA2235 for static and const fields

- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/ImplementIDisposableCorrectly.cs
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/MicrosoftApiDesignGuidelinesAnalyzersResources.resx
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.cs.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.de.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.es.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.fr.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.it.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.ja.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.ko.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.pl.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.pt-BR.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.ru.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.tr.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.zh-Hans.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.zh-Hant.xlf
- src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/ImplementIDisposableCorrectlyTests.cs
Relax the implementation of this rule to allow for derived types to implement the destructor/finalizer, but still check that the finalizer implementation invokes Dispose(false) and returns if any of its base type has a Dispose(bool) implementation.
Fixes #1950
> Fix CA1063 when implementing the dispose pattern for a derived class

- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/CollectionPropertiesShouldBeReadOnly.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/CollectionPropertiesShouldBeReadOnlyTests.cs
- src/Utilities/Extensions/ITypeSymbolExtensions.cs
- src/Utilities/WellKnownTypes.cs
1. Ensure that we fire for types implementing `ICollection<T>`. Currently implementation only checked for the non-generic `ICollection`.
2. Ensure that we don't fire for immutable collection types - the rule is only intended for properties of non-immutable types.
Fixes #1900
> Fixes for CA2227: Collection properties should be read only

- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/IdentifiersShouldHaveCorrectSuffix.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/IdentifiersShouldHaveCorrectSuffixTests.cs
- src/Utilities/Extensions/IMethodSymbolExtensions.cs
- src/Utilities/Extensions/ISymbolExtensions.cs
Fire CA1710 (Event type name should end with "EventHandler") only if event type matches event handler signature
Fixes #1822
> Fix CA1710 (IdentifiersShouldHaveCorrectSuffix) for event symbol type

- src/Microsoft.NetCore.Analyzers/Core/Security/MicrosoftNetCoreSecurityResources.resx
- src/Microsoft.NetCore.Analyzers/Core/Security/ReviewCodeForRegexInjectionVulnerabilities.cs
- src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.cs.xlf
- src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.de.xlf
- src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.es.xlf
- src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.fr.xlf
- src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.it.xlf
- src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.ja.xlf
- src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.ko.xlf
- src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.pl.xlf
- src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.pt-BR.xlf
- src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.ru.xlf
- src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.tr.xlf
- src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.zh-Hans.xlf
- src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.zh-Hant.xlf
- src/Microsoft.NetCore.Analyzers/UnitTests/Security/ReviewCodeForRegexInjectionVulnerabilitiesTests.cs
- src/Utilities/Analyzer.Utilities.projitems
- src/Utilities/FlowAnalysis/Analysis/TaintedDataAnalysis/RegexSinks.cs
- src/Utilities/FlowAnalysis/Analysis/TaintedDataAnalysis/SinkKind.cs
- src/Utilities/FlowAnalysis/Analysis/TaintedDataAnalysis/TaintedDataAnalysis.TaintedDataOperationVisitor.cs
- src/Utilities/FlowAnalysis/Analysis/TaintedDataAnalysis/TaintedDataConfig.cs
- src/Utilities/WellKnownTypes.cs
- Sinks hardcoded from FxCop.
- Fixed a bug with passing all the arguments as taintedArguments, instead of just the tainted ones.
> Regex injection tainted data DFA

- src/Utilities/Options/CategorizedAnalyzerConfigOptions.cs
Use the rule ID + option name as the key, otherwise option value computed for first rule will be used for all rules. For example:
```
dotnet_code_quality.CA1707.api_surface = all
dotnet_code_quality.CA1720.api_surface = public
```
We will apply only one of the above settings for all rules based on which rule queries the option first.
> Fix a race condition in getting editor config option value

- .editorconfig
- Directory.Build.props
- eng/Versions.props
- src/GenerateAnalyzerRulesets/Program.cs
- src/MetaCompilation.Analyzers/Core/CodeFixProvider.cs
- src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/RegisterActionAnalyzer.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Framework/DataFlow/DataFlowAnalysis.cs
- src/Microsoft.CodeQuality.Analyzers.Exp/Core/FlowAnalysis/Framework/DataFlow/DataFlowAnalysisResult.cs
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/CollectionsShouldImplementGenericInterface.cs
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/ImplementIDisposableCorrectly.cs
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/PassSystemUriObjectsInsteadOfStrings.cs
- src/Microsoft.NetCore.Analyzers/Core/Runtime/AttributeStringLiteralsShouldParseCorrectly.cs
- src/Microsoft.NetCore.Analyzers/Core/Security/ApprovedCipherModeAnalyzer.cs
- src/Microsoft.NetCore.Analyzers/Core/Security/DoNotUseInsecureCryptographicAlgorithms.cs
- src/Microsoft.NetFramework.Analyzers/Core/DoNotUseInsecureDtdProcessing.cs
- src/Microsoft.NetFramework.Analyzers/Core/DoNotUseInsecureXSLTScriptExecution.cs
- src/Microsoft.NetFramework.Analyzers/VisualBasic/Helpers/SyntaxNodeHelper.vb
- src/Roslyn.Diagnostics.Analyzers/Core/DeclarePublicAPIAnalyzer.Impl.cs
- src/Test.Utilities/DiffUtil.cs
- src/Utilities/AbstractVersionCheckAnalyzer.cs
- src/Utilities/WordParser.cs
Primarily increases the analyzed API surface for CA rules to include all APIs (public + non-public APIs), and corresponding fixes/suppressions.
**TODO:** Update Versions.props to use latest 2.6.4-beta1 myget drop once #2018 is merged and corresponding signed build is published
> Dogfood .editorconfig based configuration for FxCop analyzers

- RoslynAnalyzers.sln
- assets/install.ps1
- assets/uninstall.ps1
- eng/GenerateAnalyzerNuspec.csx
- eng/GenerateAnalyzerNuspec.targets
- nuget/Microsoft.CodeMetrics/Microsoft.CodeMetrics.Package.csproj
- nuget/Microsoft.CodeMetrics/Microsoft.CodeMetrics.targets
- src/Tools/Metrics.Legacy.csproj
Fixes #1756
See https://docs.microsoft.com/en-us/visualstudio/code-quality/how-to-generate-code-metrics-data?view=vs-2017#command-line-code-metrics for background
1. Users can now execute Metrics.exe by installing the `Microsoft.CodeMetrics` NuGet package and then executing `msbuild /t:Metrics` on their project file.
2. Metrics can be executed in legacy mode by specifying `/p:LEGACY_CODE_METRICS_MODE=true` on the MSBuild command line.
3. Additionally, users can override the output file by specifying `/p:MetricsOutputFile=<filename>` on the MSBuild command line.
Verified that the locally generated Microsoft.CodeMetrics NuGet package can be installed on a managed project and above functionality works.
------
**Example 1:**
```
C:\Users\mavasani\source\repos\ClassLibrary3\ClassLibrary3>msbuil …
```
> Add a NuGet package for command line Code Metrics

- src/Microsoft.NetCore.Analyzers/Core/Security/DoNotUseInsecureDeserializerMethodsBase.cs
- src/Microsoft.NetCore.Analyzers/Core/Security/DoNotUseInsecureDeserializerNetDataContractSerializerMethods.cs
- src/Microsoft.NetCore.Analyzers/Core/Security/DoNotUseInsecureDeserializerNetDataContractSerializerWithoutBinder.cs
- src/Microsoft.NetCore.Analyzers/Core/Security/DoNotUseInsecureDeserializerWithoutBinderBase.cs
- src/Microsoft.NetCore.Analyzers/Core/Security/Helpers/SecurityHelpers.cs
- src/Microsoft.NetCore.Analyzers/Core/Security/MicrosoftNetCoreSecurityResources.resx
- src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.cs.xlf
- src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.de.xlf
- src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.es.xlf
- src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.fr.xlf
- src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.it.xlf
- src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.ja.xlf
- src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.ko.xlf
- src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.pl.xlf
- src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.pt-BR.xlf
- src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.ru.xlf
- src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.tr.xlf
- src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.zh-Hans.xlf
- src/Microsoft.NetCore.Analyzers/Core/Security/xlf/MicrosoftNetCoreSecurityResources.zh-Hant.xlf
- src/Microsoft.NetCore.Analyzers/UnitTests/Security/DoNotUseInsecureDeserializationLosFormatterTests.cs
- src/Microsoft.NetCore.Analyzers/UnitTests/Security/DoNotUseInsecureDeserializerBinaryFormatterMethodsTests.cs
- src/Microsoft.NetCore.Analyzers/UnitTests/Security/DoNotUseInsecureDeserializerNetDataContractSerializerMethodsTests.cs
- src/Microsoft.NetCore.Analyzers/UnitTests/Security/DoNotUseInsecureDeserializerNetDataContractSerializerWithoutBinderTests.cs
- src/Test.Utilities/DiagnosticAnalyzerTestBase.cs
- src/Utilities/WellKnownTypes.cs
- More deserialization rules.
- Checking types by looking at the instance of invoked / referenced methods, rather than the target method itself, since NetDataContractSerializer derives from XmlObjectSerializer.
> NetDataContractSerializer insecure deserializer rules

- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/DoNotPrefixEnumValuesWithTypeName.cs
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/MicrosoftApiDesignGuidelinesAnalyzersResources.resx
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.cs.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.de.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.es.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.fr.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.it.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.ja.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.ko.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.pl.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.pt-BR.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.ru.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.tr.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.zh-Hans.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.zh-Hant.xlf
- src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/DoNotPrefixEnumValuesWithTypeNameTests.cs
Fixes #448 
Reporting a single diagnostic on the enum type if any field member's name starts with the enum type's name (case-insensitive comparison).
> Implement CA1712: Do not prefix enum values with type name

- src/Microsoft.CodeQuality.Analyzers/UnitTests/Maintainability/AvoidDeadConditionalCode_ValueContentAnalysis.cs
- src/Utilities/BranchWithInfo.cs
- src/Utilities/FlowAnalysis/Analysis/ValueContentAnalysis/ValueContentAbstractValue.cs
- src/Utilities/FlowAnalysis/Framework/DataFlow/AnalysisEntityDataFlowOperationVisitor.cs
- src/Utilities/FlowAnalysis/Framework/DataFlow/DataFlowAnalysis.cs
- src/Utilities/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs
- src/Utilities/FlowAnalysis/Framework/DataFlow/MapAbstractDomain.cs
Avoid merging analysis data if the input data is coming from a unique predecessor branch, instead just overwrite the new input data.
Also added a threshold on number of tracked literal values for value content analysis - otherwise, we can run into infinite analysis iterations for loops that modify constant value stores for each iteration.
> Some more flow analysis performance improvements

- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/DoNotCatchGeneralExceptionTypes.cs
- src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/AvoidDeadConditionalCode.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/Maintainability/AvoidDeadConditionalCode_NullAnalysis.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/Maintainability/AvoidDeadConditionalCode_ValueContentAnalysis.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/QualityGuidelines/ValidateArgumentsOfPublicMethodsTests.cs
- src/Utilities/Analyzer.Utilities.projitems
- src/Utilities/BranchWithInfo.cs
- src/Utilities/Extensions/IMethodSymbolExtensions.cs
- src/Utilities/Extensions/IOperationExtensions.cs
- src/Utilities/Extensions/ISymbolExtensions.cs
- src/Utilities/Extensions/ITypeSymbolExtensions.cs
- src/Utilities/FlowAnalysis/Analysis/CopyAnalysis/CopyAbstractValue.cs
- src/Utilities/FlowAnalysis/Analysis/CopyAnalysis/CopyAbstractValueKind.cs
- src/Utilities/FlowAnalysis/Analysis/CopyAnalysis/CopyAnalysis.CopyAbstractValueDomain.cs
- src/Utilities/FlowAnalysis/Analysis/CopyAnalysis/CopyAnalysis.CopyDataFlowOperationVisitor.cs
- src/Utilities/FlowAnalysis/Analysis/CopyAnalysis/CopyAnalysisData.cs
- src/Utilities/FlowAnalysis/Analysis/CopyAnalysis/SetCopyAbstractValuePredicateKind.cs
- src/Utilities/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAnalysis.PointsToDataFlowOperationVisitor.cs
- src/Utilities/FlowAnalysis/Analysis/ValueContentAnalysis/ValueContentAnalysis.ValueContentDataFlowOperationVisitor.cs
- src/Utilities/FlowAnalysis/Framework/DataFlow/AddressSharedEntitiesProvider.cs
- src/Utilities/FlowAnalysis/Framework/DataFlow/AnalysisEntityDataFlowOperationVisitor.cs
- src/Utilities/FlowAnalysis/Framework/DataFlow/AnalysisEntityFactory.cs
- src/Utilities/FlowAnalysis/Framework/DataFlow/ConversionInference.cs
- src/Utilities/FlowAnalysis/Framework/DataFlow/DataFlowAnalysis.cs
- src/Utilities/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs
- src/Utilities/FlowAnalysis/Framework/DataFlow/InterproceduralAnalysisConfigurationParameters.cs
- src/Utilities/FlowAnalysis/Framework/DataFlow/InterproceduralAnalysisData.cs
- src/Utilities/FlowAnalysis/Framework/DataFlow/PredicatedAnalysisData.cs
- src/Utilities/HashUtilities.cs
Also handle the boxing/unboxing conversions and copy values properly, which required support to handle reference copies in CopyAnalysis.
I have few more asserts while building Roslyn C# compilers, which I plan to address in subsequent commits/PR.
~~TODO: File an issue for one assert I disabled in this PR as this needs a bigger refactoring/feature level work.~~ Filed https://github.com/dotnet/roslyn-analyzers/issues/2106
> Fix a bunch of asserts in flow analysis

- eng/GenerateAnalyzerNuspec.targets
Fixes a mistake introduced in #2081 related to the path to csi.exe. This tool remains in the 15.0\Bin\Roslyn folder in Visual Studio 2019, but the script was attempting to call it in Current\Bin\Roslyn.
> Fix incorrect location of csi.exe in VS 2019

- src/Utilities/FlowAnalysis/FlowAnalysis.Utilities.projitems
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PropertySetAnalysis/PropertySetAbstractValue.ValuePool.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PropertySetAnalysis/PropertySetAbstractValue.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PropertySetAnalysis/PropertySetAnalysis.PropertySetDataFlowOperationVisitor.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PropertySetAnalysis/PropertySetAnalysis.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PropertySetAnalysis/PropertySetAnalysisContext.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PropertySetAnalysis/PropertySetBlockAnalysisResult.cs
- I only have scenarios involving two properties so far, so just pooling PropertySetAbstractValues for up to two PropertySetAbstractValueKinds.
> Minimizing PropertySetAbstractValue allocations and minor cleanup

- src/Microsoft.CodeAnalysis.FlowAnalysis.Utilities/PublicAPI.Unshipped.txt
- src/Microsoft.NetCore.Analyzers/Core/Runtime/DisposableFieldsShouldBeDisposed.cs
- src/Microsoft.NetCore.Analyzers/Core/Runtime/DisposeObjectsBeforeLosingScope.cs
- src/Microsoft.NetCore.Analyzers/Core/Runtime/SystemRuntimeAnalyzersResources.resx
- src/Microsoft.NetCore.Analyzers/Core/Runtime/xlf/SystemRuntimeAnalyzersResources.cs.xlf
- src/Microsoft.NetCore.Analyzers/Core/Runtime/xlf/SystemRuntimeAnalyzersResources.de.xlf
- src/Microsoft.NetCore.Analyzers/Core/Runtime/xlf/SystemRuntimeAnalyzersResources.es.xlf
- src/Microsoft.NetCore.Analyzers/Core/Runtime/xlf/SystemRuntimeAnalyzersResources.fr.xlf
- src/Microsoft.NetCore.Analyzers/Core/Runtime/xlf/SystemRuntimeAnalyzersResources.it.xlf
- src/Microsoft.NetCore.Analyzers/Core/Runtime/xlf/SystemRuntimeAnalyzersResources.ja.xlf
- src/Microsoft.NetCore.Analyzers/Core/Runtime/xlf/SystemRuntimeAnalyzersResources.ko.xlf
- src/Microsoft.NetCore.Analyzers/Core/Runtime/xlf/SystemRuntimeAnalyzersResources.pl.xlf
- src/Microsoft.NetCore.Analyzers/Core/Runtime/xlf/SystemRuntimeAnalyzersResources.pt-BR.xlf
- src/Microsoft.NetCore.Analyzers/Core/Runtime/xlf/SystemRuntimeAnalyzersResources.ru.xlf
- src/Microsoft.NetCore.Analyzers/Core/Runtime/xlf/SystemRuntimeAnalyzersResources.tr.xlf
- src/Microsoft.NetCore.Analyzers/Core/Runtime/xlf/SystemRuntimeAnalyzersResources.zh-Hans.xlf
- src/Microsoft.NetCore.Analyzers/Core/Runtime/xlf/SystemRuntimeAnalyzersResources.zh-Hant.xlf
- src/Microsoft.NetCore.Analyzers/UnitTests/Runtime/DisposeObjectsBeforeLosingScopeTests.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/DisposeAnalysis/DisposeAbstractValue.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/DisposeAnalysis/DisposeAbstractValueKind.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/DisposeAnalysis/DisposeAnalysis.DisposeAbstractValueDomain.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/DisposeAnalysis/DisposeAnalysis.DisposeDataFlowOperationVisitor.cs
Current implementation of CA2000 dispose analysis only flags disposable creations for which we are certain that _no Dispose invocations_ are made on **all control flow paths**.
New implementation makes the analysis more aggressive by also flagging the cases where disposable creations **may not be disposed on some program paths**. For such cases, we recommend usage of standard dispose patterns such as using statement, using declaration or a try-finally with a dedicated local variable to hold the disposable creation and a dispose invocation in finally. The diagnostic message for the may be disposed violations is weaker in the sense that it does not state that a dispose leak will certainly happen on some program path, as claiming that requires complete path sensitive analysis, which is …
> Make DisposeAnalysis and CA2000 (DisposeObjectsBeforeLosingScope) more aggressive

- src/Microsoft.NetFramework.Analyzers/Core/DoNotUseInsecureDtdProcessing.cs
- src/Microsoft.NetFramework.Analyzers/UnitTests/DoNotUseInsecureDtdProcessingCreateUsingInsecureInputXmlReaderSettingsTests.cs
- src/Microsoft.NetFramework.Analyzers/UnitTests/DoNotUseInsecureDtdProcessingXmlReaderCreateUsingInsecureConstructedXmlReaderSettingsTests.cs
Fixes #2105.  With the analyzer only looking at one code block at a time, XmlReaderSetting instances from member fields and input parameters are in an unknown state.  Instead of assuming insecure, we should not generate diagnostics on unknowns.
> CA3075 don't pessimistically assume insecure XmlReaderSettings if unknown

- src/Microsoft.NetCore.Analyzers/CSharp/Runtime/CSharpTestForEmptyStringsUsingStringLength.Fixer.cs
- src/Microsoft.NetCore.Analyzers/Core/Runtime/TestForEmptyStringsUsingStringLength.Fixer.cs
- src/Microsoft.NetCore.Analyzers/UnitTests/Runtime/TestForEmptyStringsUsingStringLengthTests.Fixer.cs
- src/Microsoft.NetCore.Analyzers/VisualBasic/Runtime/BasicTestForEmptyStringsUsingStringLength.Fixer.vb
much of the implementation and test cases mirrored what was done for the TestForNanCorrectly rule, which is very similar to testing for the empty string. The major difference we have is that the rule suggests two fixes: either use string.IsNullOrEmpty or test that string.Length == 0.
Fixes #2165
> implementing fixer for CA1820

- README.md
1. More emphasis on Microsoft.CodeAnalysis.FxCopAnalyzers package as the primary analyzer package of the repo
2. Add pointers to docs.microsoft.com documentation for migration from legacy FxCop to FxCop analyzers.
First step towards addressing #2025.
> Improve the Readme for the repo

- eng/Versions.props
- src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/AvoidDeadConditionalCode.cs
- src/Microsoft.CodeQuality.Analyzers/Core/QualityGuidelines/ValidateArgumentsOfPublicMethods.cs
- src/Microsoft.NetCore.Analyzers/Core/Data/ReviewSqlQueriesForSecurityVulnerabilities.cs
- src/Microsoft.NetCore.Analyzers/Core/Runtime/DisposableFieldsShouldBeDisposed.cs
- src/Microsoft.NetCore.Analyzers/Core/Runtime/DisposeObjectsBeforeLosingScope.cs
- src/Microsoft.NetCore.Analyzers/Core/Runtime/DoNotPassLiteralsAsLocalizedParameters.cs
Address follow up items from https://github.com/dotnet/roslyn-analyzers/pull/2190
Verified:
1. No AD0001 on consuming the locally generated 2.9.0-ci package
2. Explicitly enabling any flow-analysis rule in ruleset generates AD0001 as expected in VS2017. AD0001 is not generated on VS2019, unless the project references a 2.x.x or earlier version of Microsoft.Net.Compilers.
3. Adding the flow-analysis feature flag causes flow analysis rules to work as expected on VS2017
https://github.com/dotnet/roslyn-analyzers/issues/2191 tracks reverting https://github.com/dotnet/roslyn-analyzers/commit/22b4d0db2a65cd9abbafb29bbe92a1e4209c621f
> Address follow up items from features/dataflow RI

- src/Utilities/FlowAnalysis/Extensions/BasicBlockExtensions.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/DisposeAnalysis/DisposeAnalysis.DisposeDataFlowOperationVisitor.cs
https://github.com/dotnet/roslyn-analyzers/issues/2152#issuecomment-473393239 tracks reverting this workaround once the IOperation/CFG support has been added for using declarations.
> Add a workaround to ensure we do not flag using declarations in Dispose rules

- src/Microsoft.NetCore.Analyzers/Core/Security/DoNotAddSchemaByURL.cs
- src/Microsoft.NetCore.Analyzers/Core/Security/DoNotDisableHttpHeaderChecking.cs
- src/Microsoft.NetCore.Analyzers/Core/Security/SetViewStateUserKey.cs
- src/Microsoft.NetCore.Analyzers/UnitTests/Security/SetViewStateUserKeyTests.cs
- Temporarily disabling new rules.
- One NullReferenceException fix for SetViewStateUserKey (CA5368).
> NullRef fix for CA5368

- src/Microsoft.CodeQuality.Analyzers/UnitTests/QualityGuidelines/MarkMembersAsStaticTests.Fixer.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/QualityGuidelines/MarkMembersAsStaticTests.cs
These tests are providing problematic in the 3.0.0 upgrade (#2255), and this change improves the clarity of error messages in those failures.
> Use testing library for MarkMembersAsStaticAnalyzer

- Directory.Build.props
- src/MetaCompilation.Analyzers/UnitTests/Helpers/DiagnosticVerifier.Helper.cs
- src/Microsoft.CodeAnalysis.Analyzers/Core/FixAnalyzers/FixerWithFixAllAnalyzer.cs
- src/Microsoft.CodeAnalysis.FlowAnalysis.Utilities/Microsoft.CodeAnalysis.FlowAnalysis.Utilities.csproj
- src/Microsoft.NetCore.Analyzers/Core/Security/DoNotCallDangerousMethodsInDeserialization.cs
- src/Microsoft.NetCore.Analyzers/Core/Security/DoNotDisableCertificateValidation.cs
- src/Microsoft.NetCore.Analyzers/Core/Security/DoNotReferSelfInSerializableClass.cs
- src/Microsoft.NetCore.Analyzers/Core/Security/DoNotSerializeTypeWithPointerFields.cs
- src/Microsoft.NetCore.Analyzers/Core/Security/DoNotUseInsecureDeserializerBinaryFormatterMethods.cs
- src/Microsoft.NetCore.Analyzers/Core/Security/DoNotUseInsecureDeserializerBinaryFormatterWithoutBinder.cs
- src/Microsoft.NetCore.Analyzers/Core/Security/DoNotUseInsecureDeserializerNetDataContractSerializerMethods.cs
- src/Microsoft.NetCore.Analyzers/Core/Security/DoNotUseInsecureDeserializerNetDataContractSerializerWithoutBinder.cs
- src/Microsoft.NetCore.Analyzers/Core/Security/DoNotUseInsecureDeserializerWithoutBinderBase.cs
- src/Microsoft.NetCore.Analyzers/Core/Security/Helpers/SecurityHelpers.cs
- src/Utilities.UnitTests/FlowAnalysis/Analysis/PropertySetAnalysis/PropertySetAnalysisTests.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PropertySetAnalysis/ConstructorMapper.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PropertySetAnalysis/HazardousUsageEvaluator.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PropertySetAnalysis/PropertyMapper.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/TaintedDataAnalysis/TaintedDataAnalysis.TaintedDataOperationVisitor.cs
Prior to this change, this repository was treating `///` comments as `//` comments, resulting in many errors related to their usage and placement. This change updates the project config to treat `///` comments as documentation comments.
> Analyze documentation comments

- src/Microsoft.NetCore.Analyzers/Core/ImmutableCollections/DoNotCallToImmutableCollectionOnAnImmutableCollectionValue.Fixer.cs
- src/Microsoft.NetCore.Analyzers/Core/ImmutableCollections/DoNotCallToImmutableCollectionOnAnImmutableCollectionValue.cs
- src/Microsoft.NetCore.Analyzers/UnitTests/ImmutableCollections/DoNotCallToImmutableCollectionOnAnImmutableCollectionValueTests.Fixer.cs
- src/Microsoft.NetCore.Analyzers/UnitTests/ImmutableCollections/DoNotCallToImmutableCollectionOnAnImmutableCollectionValueTests.cs
- src/Utilities/Compiler/Extensions/IOperationExtensions.cs
Addresses the issue - https://github.com/dotnet/roslyn-analyzers/issues/2283
> CA2009 VB analyzer false negative case fix

- src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/AvoidUnusedPrivateFields.cs
This was previously a compilation end analyzer.
~~This change also fixes a race condition which could lead to the incorrect reporting of CA1823 on a field which is used.~~ This change moved to #2342.
> Report CA1823 (AvoidUnusedPrivateFields) at symbol end

- src/Microsoft.NetCore.Analyzers/Core/Runtime/DisposableFieldsShouldBeDisposed.cs
- src/Microsoft.NetCore.Analyzers/UnitTests/Runtime/DisposableFieldsShouldBeDisposedTests.cs
- src/Microsoft.NetCore.Analyzers/UnitTests/Runtime/DisposeObjectsBeforeLosingScopeTests.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/DisposeAnalysis/DisposeAnalysis.DisposeDataFlowOperationVisitor.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAnalysis.PointsToDataFlowOperationVisitor.cs
Fixes #2306: CA2213 (DisposableFieldsShouldBeDisposed)
1. https://github.com/dotnet/roslyn-analyzers/commit/ba955a4f1204771477e64be8c4ff68b554e7151c: Ensure that analysis is executed on generated code to account for Dispose implementation in generated code files.
Fixes #2245 (2 scenarios): CA2000 (DisposeObjectsBeforeLosingScope)
1. https://github.com/dotnet/roslyn-analyzers/commit/74dd361b5ee472f4aafd7eb91dc31755819c5056: Handle escaping of disposable creations through ref/out field arguments.
2. https://github.com/dotnet/roslyn-analyzers/commit/5f3209af3fe77d83a5f2df9b20ac8892bbf7cf91: Prevent false positives for disposable `out` arguments of invocations within conditional expression. We assume that an `out` argument of an invocation returning false within a conditional branch is …
> Fix false positives for Dispose rules

- src/Microsoft.NetCore.Analyzers/Core/Security/DoNotUseXslTransform.cs
- src/Microsoft.NetCore.Analyzers/Core/Security/SystemSecurityCryptographyResources.resx
- src/Microsoft.NetCore.Analyzers/Core/Security/xlf/SystemSecurityCryptographyResources.cs.xlf
- src/Microsoft.NetCore.Analyzers/Core/Security/xlf/SystemSecurityCryptographyResources.de.xlf
- src/Microsoft.NetCore.Analyzers/Core/Security/xlf/SystemSecurityCryptographyResources.es.xlf
- src/Microsoft.NetCore.Analyzers/Core/Security/xlf/SystemSecurityCryptographyResources.fr.xlf
- src/Microsoft.NetCore.Analyzers/Core/Security/xlf/SystemSecurityCryptographyResources.it.xlf
- src/Microsoft.NetCore.Analyzers/Core/Security/xlf/SystemSecurityCryptographyResources.ja.xlf
- src/Microsoft.NetCore.Analyzers/Core/Security/xlf/SystemSecurityCryptographyResources.ko.xlf
- src/Microsoft.NetCore.Analyzers/Core/Security/xlf/SystemSecurityCryptographyResources.pl.xlf
- src/Microsoft.NetCore.Analyzers/Core/Security/xlf/SystemSecurityCryptographyResources.pt-BR.xlf
- src/Microsoft.NetCore.Analyzers/Core/Security/xlf/SystemSecurityCryptographyResources.ru.xlf
- src/Microsoft.NetCore.Analyzers/Core/Security/xlf/SystemSecurityCryptographyResources.tr.xlf
- src/Microsoft.NetCore.Analyzers/Core/Security/xlf/SystemSecurityCryptographyResources.zh-Hans.xlf
- src/Microsoft.NetCore.Analyzers/Core/Security/xlf/SystemSecurityCryptographyResources.zh-Hant.xlf
- src/Microsoft.NetCore.Analyzers/UnitTests/Security/DoNotUseXslTransformTests.cs
- src/Utilities/Compiler/WellKnownTypeNames.cs
This rule checks using constructor of XslTransform to create object. I don't check it's derived classes cause XslTransform is a sealed class.
> Do not use XslTransform

- src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/DoNotCatchGeneralExceptionTypesTests.cs
- src/Microsoft.NetFramework.Analyzers/UnitTests/DoNotCatchCorruptedStateExceptionsTests.cs
- src/Utilities/Compiler/DoNotCatchGeneralUnlessRethrown.cs
Fixes #2278
This changes the behavior to be more lenient, avoiding a diagnostic if the catch block contains any throw statement. Previously, we required a rethrow.
> CA1031 should not report diagnostic if catch block throws

- src/Microsoft.CodeAnalysis.BannedApiAnalyzers/Setup/source.extension.vsixmanifest
- src/PublicApiAnalyzers/Setup/source.extension.vsixmanifest
Three extensions were using the same ID. I changed the ID for the two most recently added extensions.
> Fix GUID conflict between extensions

- src/Utilities/Compiler/Extensions/IEnumerableExtensions.cs
If DataFlowAnalysis.Run()'s try block throws an exception, and the finally block eventually calls IEnumerableExtensions.Dispose(), which may throw an null reference exception due to incomplete analysis, hiding the original exception.
> Just checking for null before calling Dispose()

- src/Microsoft.CodeQuality.Analyzers/Core/QualityGuidelines/ValidateArgumentsOfPublicMethods.cs
- src/Microsoft.NetCore.Analyzers/Core/Data/ReviewSqlQueriesForSecurityVulnerabilities.cs
- src/Microsoft.NetCore.Analyzers/Core/Runtime/DisposableFieldsShouldBeDisposed.cs
- src/Microsoft.NetCore.Analyzers/Core/Runtime/DisposeObjectsBeforeLosingScope.cs
- src/Microsoft.NetCore.Analyzers/Core/Runtime/DoNotPassLiteralsAsLocalizedParameters.cs
This reverts commit 22b4d0db2a65cd9abbafb29bbe92a1e4209c621f.
Fixes #2191 
We have already added the flow-analysis feature flag to the packages, so we do not need to disable these DFA rules by default.
> Revert "Turn off dataflow analysis based rules by default"

- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/DoNotDirectlyAwaitATask.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/DoNotDirectlyAwaitATaskTests.cs
We may miss out analyzing async lambdas/local functions defined in non-async methods.
Fixes #2393
> Do not bail out upfront for non-async methods

- src/Microsoft.NetCore.Analyzers/Core/Runtime/DisposableFieldsShouldBeDisposed.cs
- src/Microsoft.NetCore.Analyzers/Core/Runtime/DoNotPassLiteralsAsLocalizedParameters.cs
- src/Utilities/FlowAnalysis/Extensions/OperationBlocksExtensions.cs
- src/Utilities/FlowAnalysis/FlowAnalysis.Utilities.projitems
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/DisposeAnalysis/DisposeAnalysisHelper.cs
Make sure we only analyze types that implement IDisposable and at least have one disposable field. Additionally, run DFA lazily only if required.
Fixes #2319
> Perf optimization for CA2213 analyzer (DisposableFieldsShouldBeDisposed)

- src/Microsoft.NetCore.Analyzers/Core/Security/DoNotDisableRequestValidation.cs
- src/Microsoft.NetCore.Analyzers/Core/Security/SystemSecurityCryptographyResources.resx
- src/Microsoft.NetCore.Analyzers/Core/Security/xlf/SystemSecurityCryptographyResources.cs.xlf
- src/Microsoft.NetCore.Analyzers/Core/Security/xlf/SystemSecurityCryptographyResources.de.xlf
- src/Microsoft.NetCore.Analyzers/Core/Security/xlf/SystemSecurityCryptographyResources.es.xlf
- src/Microsoft.NetCore.Analyzers/Core/Security/xlf/SystemSecurityCryptographyResources.fr.xlf
- src/Microsoft.NetCore.Analyzers/Core/Security/xlf/SystemSecurityCryptographyResources.it.xlf
- src/Microsoft.NetCore.Analyzers/Core/Security/xlf/SystemSecurityCryptographyResources.ja.xlf
- src/Microsoft.NetCore.Analyzers/Core/Security/xlf/SystemSecurityCryptographyResources.ko.xlf
- src/Microsoft.NetCore.Analyzers/Core/Security/xlf/SystemSecurityCryptographyResources.pl.xlf
- src/Microsoft.NetCore.Analyzers/Core/Security/xlf/SystemSecurityCryptographyResources.pt-BR.xlf
- src/Microsoft.NetCore.Analyzers/Core/Security/xlf/SystemSecurityCryptographyResources.ru.xlf
- src/Microsoft.NetCore.Analyzers/Core/Security/xlf/SystemSecurityCryptographyResources.tr.xlf
- src/Microsoft.NetCore.Analyzers/Core/Security/xlf/SystemSecurityCryptographyResources.zh-Hans.xlf
- src/Microsoft.NetCore.Analyzers/Core/Security/xlf/SystemSecurityCryptographyResources.zh-Hant.xlf
- src/Microsoft.NetCore.Analyzers/UnitTests/Security/DoNotDisableRequestValidationTests.cs
1. The old message is "The method {1} has request validation disabled". However, it could be a class.
2. Add support for scenario like setting up the ValidateInput attribute for both method and its type.
> Fix do not disable request validation

- Directory.Build.props
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/xlf/MicrosoftApiDesignGuidelinesAnalyzersResources.cs.xlf
- src/Microsoft.NetCore.Analyzers/Core/Runtime/xlf/SystemRuntimeAnalyzersResources.cs.xlf
- src/Microsoft.NetCore.Analyzers/Core/Runtime/xlf/SystemRuntimeAnalyzersResources.de.xlf
- src/Microsoft.NetCore.Analyzers/Core/Runtime/xlf/SystemRuntimeAnalyzersResources.es.xlf
- src/Microsoft.NetCore.Analyzers/Core/Runtime/xlf/SystemRuntimeAnalyzersResources.fr.xlf
- src/Microsoft.NetCore.Analyzers/Core/Runtime/xlf/SystemRuntimeAnalyzersResources.it.xlf
- src/Microsoft.NetCore.Analyzers/Core/Runtime/xlf/SystemRuntimeAnalyzersResources.ja.xlf
- src/Microsoft.NetCore.Analyzers/Core/Runtime/xlf/SystemRuntimeAnalyzersResources.ko.xlf
- src/Microsoft.NetCore.Analyzers/Core/Runtime/xlf/SystemRuntimeAnalyzersResources.pl.xlf
- src/Microsoft.NetCore.Analyzers/Core/Runtime/xlf/SystemRuntimeAnalyzersResources.pt-BR.xlf
- src/Microsoft.NetCore.Analyzers/Core/Runtime/xlf/SystemRuntimeAnalyzersResources.ru.xlf
- src/Microsoft.NetCore.Analyzers/Core/Runtime/xlf/SystemRuntimeAnalyzersResources.tr.xlf
- src/Microsoft.NetCore.Analyzers/Core/Runtime/xlf/SystemRuntimeAnalyzersResources.zh-Hans.xlf
- src/Microsoft.NetCore.Analyzers/Core/Runtime/xlf/SystemRuntimeAnalyzersResources.zh-Hant.xlf
Update the version of XliffTasks used by dotnet/roslyn-analyzers. The version we're getting from the dotnet/arcade toolset is fairly old and is missing bug fixes and improved error reporting that can make it easier to track down XLF failures during a build.
A number of .xlf files have been updated by a newer features that detects when the `source` and `target` texts have different numbers of placeholders and resets the `target` text completely; this avoids string formatting exceptions at runtime.
> Update XliffTasks version

- src/Microsoft.NetCore.Analyzers/Core/Security/DoNotUseDeprecatedSecurityProtocols.cs
- src/Microsoft.NetCore.Analyzers/UnitTests/Security/DoNotUseDeprecatedSecurityProtocolsTests.cs
My last change produces duplicate diagnostics, since both examining the field reference and examining the constant values report.  Now when looking at the assignment value, also make sure there isn't a FieldReference that would've reported.
> Fixing duplicate diagnostics in CA5364

- src/Roslyn.Diagnostics.Analyzers/Core/ExportedPartsShouldHaveImportingConstructor.cs
- src/Roslyn.Diagnostics.Analyzers/Core/ImportingConstructorShouldBeObsolete.cs
- src/Roslyn.Diagnostics.Analyzers/Core/PartsExportedWithMEFv2MustBeMarkedAsShared.cs
- src/Roslyn.Diagnostics.Analyzers/Core/SpecializedEnumerableCreationAnalyzer.cs
- src/Roslyn.Diagnostics.Analyzers/Core/TestExportsShouldNotBeDiscoverable.cs
- src/Roslyn.Diagnostics.Analyzers/UnitTests/ExportedPartsShouldHaveImportingConstructorTests.cs
- src/Utilities/Compiler/Extensions/ITypeSymbolExtensions.cs
- src/Utilities/Compiler/WellKnownTypeNames.cs
- src/Utilities/Compiler/WellKnownTypes.cs
`ExportAttribute` is not treated as inherited unless the attribute type inherits `InheritedExportAttribute`.
>  Use MEF rules for export attribute inheritance

- src/Microsoft.CodeAnalysis.BannedApiAnalyzers/CSharp/CSharpRestrictedInternalsVisibleToAnalyzer.cs
- src/Microsoft.CodeAnalysis.BannedApiAnalyzers/Core/BannedApiAnalyzerResources.resx
- src/Microsoft.CodeAnalysis.BannedApiAnalyzers/Core/RestrictedInternalsVisibleToAnalyzer.cs
- src/Microsoft.CodeAnalysis.BannedApiAnalyzers/Core/xlf/BannedApiAnalyzerResources.cs.xlf
- src/Microsoft.CodeAnalysis.BannedApiAnalyzers/Core/xlf/BannedApiAnalyzerResources.de.xlf
- src/Microsoft.CodeAnalysis.BannedApiAnalyzers/Core/xlf/BannedApiAnalyzerResources.es.xlf
- src/Microsoft.CodeAnalysis.BannedApiAnalyzers/Core/xlf/BannedApiAnalyzerResources.fr.xlf
- src/Microsoft.CodeAnalysis.BannedApiAnalyzers/Core/xlf/BannedApiAnalyzerResources.it.xlf
- src/Microsoft.CodeAnalysis.BannedApiAnalyzers/Core/xlf/BannedApiAnalyzerResources.ja.xlf
- src/Microsoft.CodeAnalysis.BannedApiAnalyzers/Core/xlf/BannedApiAnalyzerResources.ko.xlf
- src/Microsoft.CodeAnalysis.BannedApiAnalyzers/Core/xlf/BannedApiAnalyzerResources.pl.xlf
- src/Microsoft.CodeAnalysis.BannedApiAnalyzers/Core/xlf/BannedApiAnalyzerResources.pt-BR.xlf
- src/Microsoft.CodeAnalysis.BannedApiAnalyzers/Core/xlf/BannedApiAnalyzerResources.ru.xlf
- src/Microsoft.CodeAnalysis.BannedApiAnalyzers/Core/xlf/BannedApiAnalyzerResources.tr.xlf
- src/Microsoft.CodeAnalysis.BannedApiAnalyzers/Core/xlf/BannedApiAnalyzerResources.zh-Hans.xlf
- src/Microsoft.CodeAnalysis.BannedApiAnalyzers/Core/xlf/BannedApiAnalyzerResources.zh-Hant.xlf
- src/Microsoft.CodeAnalysis.BannedApiAnalyzers/UnitTests/RestrictedInternalsVisibleToAnalyzerTests.cs
- src/Microsoft.CodeAnalysis.BannedApiAnalyzers/VisualBasic/BasicRestrictedInternalsVisibleToAnalyzer.vb
- src/Roslyn.Diagnostics.Analyzers/Core/RoslynDiagnosticIds.cs
- src/Test.Utilities/DiagnosticAnalyzerTestBase.cs
- src/Utilities/Compiler/SymbolDisplayFormats.cs
Allow assemblies to supply a _restricted_ version of InternalsVisibleTo assembly level attribute which restricts the allowed namespaces from which internal APIs can be accessed, instead of allowing access to all internal types from the assembly.
The analyzer expects that the API producer assembly's compilation (i.e. the referenced assembly's compilation) contains the attribute definition for the new `RestrictedInternalsVisibleToAttribute` with the following namespace and ctor signature:
```csharp
namespace System.Runtime.CompilerServices
{
[System.AttributeUsage(System.AttributeTargets.Assembly, AllowMultiple = true)]
internal class RestrictedInternalsVisibleToAttribute : System.Attribute
{
// Restrict 'assemblyName' to only access internal types from 'restrictedNamespaces'
public …
```
> Add RestrictedInternalsVisibleToAnalyzer

- src/Microsoft.CodeAnalysis.FlowAnalysis.Utilities/PublicAPI.Unshipped.txt
- src/Microsoft.NetCore.Analyzers/Core/Security/DoNotSetSwitch.cs
- src/Microsoft.NetCore.Analyzers/UnitTests/Security/DoNotDisableSchUseStrongCryptoTests.cs
- src/Microsoft.NetCore.Analyzers/UnitTests/Security/DoNotDisableUsingServicePointManagerSecurityProtocolsTests.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/ValueContentAnalysis/ValueContentAbstractValue.cs
Someone wrote an example using a variable rather than a constant for the switch name, so just enabling those test cases and handling them with ValueContentAnalysis.
> A pinch of ValueContentAnalysis for DoNotSetSwitch

- nuget/Microsoft.CodeAnalysis.Metrics/Microsoft.CodeAnalysis.Metrics.targets
Microsoft.CodeAnalysis.Metrics.targets fails if the MetricsExeFolder has folder with a space.
This Pull Request fixes this issue.
> Fixes Metrics.targets missing quotes on filepath

- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/DoNotCatchGeneralExceptionTypes.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/DoNotCatchGeneralExceptionTypesTests.cs
- src/Microsoft.NetFramework.Analyzers/Core/DoNotCatchCorruptedStateExceptions.cs
- src/Utilities/Compiler/DoNotCatchGeneralUnlessRethrown.cs
Fixes #2518
Also changed the diagnostic span to be just the catch keyword instead of the entire catch block.
> Handle catch clauses without exception variable in CA1031

- src/Microsoft.NetCore.Analyzers/Core/Runtime/DoNotPassLiteralsAsLocalizedParameters.cs
- src/Microsoft.NetCore.Analyzers/UnitTests/Runtime/DoNotPassLiteralsAsLocalizedParametersTests.cs
Fix for issue #2574 where string literals that contain new line characters cause the project to not build with a CSC.exe code 1 error.
The fix replaces and newlines in the literals with a space
> Sanitized multiple-line string-literals by replacing with a space for CA1303

- src/Microsoft.CodeQuality.Analyzers/UnitTests/QualityGuidelines/ValidateArgumentsOfPublicMethodsTests.cs
- src/Utilities.UnitTests/FlowAnalysis/Analysis/PropertySetAnalysis/PropertySetAnalysisTests.cs
- src/Utilities/Compiler/Extensions/IMethodSymbolExtensions.cs
- src/Utilities/Compiler/Extensions/ISymbolExtensions.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/ParameterValidationAnalysis/ParameterValidationAnalysis.ParameterValidationDataFlowOperationVisitor.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAnalysis.PointsToDataFlowOperationVisitor.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAnalysis.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs
I recommend reviewing commit by commit - each commit has very minor product fixes
1. https://github.com/dotnet/roslyn-analyzers/commit/38dc20a0a5570e19c37dd5d81647feeab1bdabfd: Handle argument null check methods in the PredicateAnalysis done with in core dataflow operation visitor. Fixes #2369
2. https://github.com/dotnet/roslyn-analyzers/commit/1ebfb476a05e4912c86f55c1daac026987b1b649: Special case few more field/property/methods that return non-null instances. Fixes #2582
1. static readonly members named "Empty"
2. static factory methods whose name starts with "Create"
3. https://github.com/dotnet/roslyn-analyzers/commit/c5dd3e42f2ede6888f15b88c310b091a57cd35b6: Ensure param arrays are always assumed to be non-null. Fixes #2528
4. …
> Fix bunch of CA1062 (ValidateArgmentsOfPublicMethods) false positives

- docs/Analyzer Configuration.md
- src/Microsoft.CodeQuality.Analyzers/Core/QualityGuidelines/ValidateArgumentsOfPublicMethods.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/QualityGuidelines/ValidateArgumentsOfPublicMethodsTests.cs
- src/Utilities/Compiler/Extensions/ISymbolExtensions.cs
- src/Utilities/Compiler/Options/AnalyzerOptionsExtensions.cs
- src/Utilities/Compiler/Options/EditorConfigOptionNames.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/ParameterValidationAnalysis/ParameterValidationAnalysis.ParameterValidationDataFlowOperationVisitor.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/ParameterValidationAnalysis/ParameterValidationAnalysis.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/ParameterValidationAnalysis/ParameterValidationAnalysisContext.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/AbstractLocation.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/AnalysisEntityFactory.cs
1. https://github.com/dotnet/roslyn-analyzers/commit/757591f8b5dbcea7365750ce66ff4c0367dfbf28: Do not flag CA1062 for protected members of sealed classes if the entire overridden method chain is defined in the same assembly. Fixes #2269
2. https://github.com/dotnet/roslyn-analyzers/commit/6539472700e2b31a1eefb9cf08f41da0d98e589b: Add editorconfig option to allow specifying method names or signatures for null check validation methods. Fixes #2578
**Option Name:** `null_check_validation_methods`
**Option Values:** Names of null check validation methods (separated by '~') that validate arguments passed to the method are non-null for [CA1062](https://docs.microsoft.com/visualstudio/code-quality/ca1062-validate-arguments-of-public-methods).
Allowed method name formats:
1. Method name only …
> Fix couple more issues for CA1062 (ValidateAgumentsOfPublicMethods)

- src/Microsoft.CodeAnalysis.FlowAnalysis.Utilities/PublicAPI.Unshipped.txt
- src/Microsoft.NetCore.Analyzers/Core/Security/DoNotSetSwitch.cs
- src/Microsoft.NetCore.Analyzers/UnitTests/Security/DoNotDisableSchUseStrongCryptoTests.cs
- src/Microsoft.NetCore.Analyzers/UnitTests/Security/DoNotDisableUsingServicePointManagerSecurityProtocolsTests.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/ValueContentAnalysis/ValueContentAbstractValue.cs
Someone wrote an example using a variable rather than a constant for the switch name, so just enabling those test cases and handling them with ValueContentAnalysis.
This can wait until after 2.9.3.
> Redoing a pinch of ValueContentAnalysis to DoNotSetSwitch

- src/Utilities/Compiler/Extensions/ISymbolExtensions.cs
I haven't been able to create a repro for #2502, so just adding a defensive check based on the callstack in the bug
Fixes #2502
> Defensive check for NRE in #2502

- eng/GenerateAnalyzerNuspec.csx
Fixes #2577
Verified the packages generated in CIBuild now contain resource assemblies.
> Embed satellite resource assemblies in analyzer packages

- src/Microsoft.NetCore.Analyzers/Core/Runtime/DisposableFieldsShouldBeDisposed.cs
- src/Microsoft.NetCore.Analyzers/UnitTests/Runtime/DisposableFieldsShouldBeDisposedTests.cs
Flag non-disposed fields only if the containing type has a Dispose method implementation. Found this issue while dogfooding.
> Fix a false positive in CA2213 (DisposableFieldsShouldBeDisposed)

- src/Microsoft.CodeQuality.Analyzers/Core/QualityGuidelines/AvoidPropertySelfAssignment.cs
- src/Microsoft.CodeQuality.Analyzers/Core/QualityGuidelines/MicrosoftQualityGuidelinesAnalyzersResources.resx
- src/Microsoft.CodeQuality.Analyzers/Core/QualityGuidelines/xlf/MicrosoftQualityGuidelinesAnalyzersResources.cs.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/QualityGuidelines/xlf/MicrosoftQualityGuidelinesAnalyzersResources.de.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/QualityGuidelines/xlf/MicrosoftQualityGuidelinesAnalyzersResources.es.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/QualityGuidelines/xlf/MicrosoftQualityGuidelinesAnalyzersResources.fr.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/QualityGuidelines/xlf/MicrosoftQualityGuidelinesAnalyzersResources.it.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/QualityGuidelines/xlf/MicrosoftQualityGuidelinesAnalyzersResources.ja.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/QualityGuidelines/xlf/MicrosoftQualityGuidelinesAnalyzersResources.ko.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/QualityGuidelines/xlf/MicrosoftQualityGuidelinesAnalyzersResources.pl.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/QualityGuidelines/xlf/MicrosoftQualityGuidelinesAnalyzersResources.pt-BR.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/QualityGuidelines/xlf/MicrosoftQualityGuidelinesAnalyzersResources.ru.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/QualityGuidelines/xlf/MicrosoftQualityGuidelinesAnalyzersResources.tr.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/QualityGuidelines/xlf/MicrosoftQualityGuidelinesAnalyzersResources.zh-Hans.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/QualityGuidelines/xlf/MicrosoftQualityGuidelinesAnalyzersResources.zh-Hant.xlf
- src/Microsoft.CodeQuality.Analyzers/UnitTests/QualityGuidelines/AvoidPropertySelfAssignmentTests.cs
This is related to issue #2496 
I've implemented a *rough draft* that I'll clean up before merging, and would like feedback on the following:
- Overall design, especially with checking context types.
- Opinions on diagnostic category. I chose ```DiagnosticCategory.Design```, but I'm open to other options
- Should this be enabled by default?
- How does this get a rule ID assigned?
- What do I need to do to write help information for the help URL field in ```DiagnosticDescriptor```? It looks like all of them reference the .NET website. 
Thanks for the help!
> #2496 Property self assignment protection

- src/Microsoft.NetCore.Analyzers/UnitTests/Security/DoNotAddArchiveItemPathToTheTargetFileSystemPathTests.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/TaintedDataAnalysis/PooledHashSetExtensions.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/TaintedDataAnalysis/SanitizerInfo.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/TaintedDataAnalysis/TaintedDataAnalysis.TaintedDataOperationVisitor.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/TaintedDataAnalysis/ZipSlipSanitizers.cs
static ZipSlipSanitizers()
{
var builder = PooledHashSet<SanitizerInfo>.GetInstance();
builder.AddSanitizerInfo(
WellKnownTypeNames.SystemString,
isInterface: false,
isConstructorSanitizing: false,
sanitizingMethods: new[] {
"Substring",
},
sanitizingParameterMethods: new[] {
"StartsWith",
});
SanitizerInfos = builder.ToImmutableAndFree();
}
In this example above, If a stringA is tainted, it will be not tainted after calling stringA.StartsWith("start").
> Extend tainted data analysis

- eng/GenerateAnalyzerNuspec.targets
- src/GenerateAnalyzerRulesets/Program.cs
- src/MetaCompilation.Analyzers/MetaCompilation.Analyzers.sarif
- src/Microsoft.CodeAnalysis.Analyzers/Microsoft.CodeAnalysis.Analyzers.sarif
- src/Microsoft.CodeAnalysis.BannedApiAnalyzers/Microsoft.CodeAnalysis.BannedApiAnalyzers.sarif
- src/Microsoft.CodeAnalysis.FxCopAnalyzers/Microsoft.CodeAnalysis.FxCopAnalyzers.sarif
- src/Microsoft.CodeAnalysis.VersionCheckAnalyzer/Microsoft.CodeAnalysis.VersionCheckAnalyzer.sarif
- src/Microsoft.CodeQuality.Analyzers/Microsoft.CodeQuality.Analyzers.sarif
- src/Microsoft.NetCore.Analyzers/Microsoft.NetCore.Analyzers.sarif
- src/Microsoft.NetFramework.Analyzers/Microsoft.NetFramework.Analyzers.sarif
- src/PerformanceSensitiveAnalyzers/Microsoft.CodeAnalysis.PerformanceSensitiveAnalyzers.sarif
- src/PublicApiAnalyzers/Microsoft.CodeAnalysis.PublicApiAnalyzers.sarif
- src/Roslyn.Diagnostics.Analyzers/Roslyn.Diagnostics.Analyzers.sarif
This PR adds the languages supported by the rule (**C#** and/or **Visual Basic**) and the name of the type implementing the rules.
It also splits the output in one run per assembly.
> Add type name and languages to SARIF output.

- src/Microsoft.CodeQuality.Analyzers/Core/QualityGuidelines/AvoidPropertySelfAssignment.cs
@mavasani realized I missed updating the comment when I changed the rule. This should correct that.
> Fix incorrect rule number in comment

- src/Microsoft.NetCore.Analyzers/UnitTests/Runtime/DisposeObjectsBeforeLosingScopeTests.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/DisposeAnalysis/DisposeAbstractValue.cs
Ensure that an escaping operation, such as a return statement, changes the dispose kind to escaped even for allocations which are currently maybe disposed state
Fixes #2637
> Fix another CA2000 false positive

- src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/MicrosoftMaintainabilityAnalyzersResources.resx
- src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/ReviewUnusedParameters.cs
- src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/xlf/MicrosoftMaintainabilityAnalyzersResources.cs.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/xlf/MicrosoftMaintainabilityAnalyzersResources.de.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/xlf/MicrosoftMaintainabilityAnalyzersResources.es.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/xlf/MicrosoftMaintainabilityAnalyzersResources.fr.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/xlf/MicrosoftMaintainabilityAnalyzersResources.it.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/xlf/MicrosoftMaintainabilityAnalyzersResources.ja.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/xlf/MicrosoftMaintainabilityAnalyzersResources.ko.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/xlf/MicrosoftMaintainabilityAnalyzersResources.pl.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/xlf/MicrosoftMaintainabilityAnalyzersResources.pt-BR.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/xlf/MicrosoftMaintainabilityAnalyzersResources.ru.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/xlf/MicrosoftMaintainabilityAnalyzersResources.tr.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/xlf/MicrosoftMaintainabilityAnalyzersResources.zh-Hans.xlf
- src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/xlf/MicrosoftMaintainabilityAnalyzersResources.zh-Hant.xlf
- src/Microsoft.CodeQuality.Analyzers/UnitTests/Maintainability/ReviewUnusedParametersTests.cs
- src/Test.Utilities/WorkItemAttribute.cs
- src/Utilities/Compiler/Extensions/ISymbolExtensions.cs
1. https://github.com/dotnet/roslyn-analyzers/commit/97d6b44dc23aad5413e99181294e2fcb8ef1b416: Bail out on discard symbol names.
Fixes #2589
Fixes #2593
Fixes #2465
Fixes #1359
2. https://github.com/dotnet/roslyn-analyzers/commit/9255c80106d85526c03dc7aad524fd6c7d3a6215: Analyze local function parameters.
Fixes #2466
> Fixes for CA1801 (ReviewUnusedParameters)

- src/ReleaseNotesUtil/AnalyzerAssemblyLoader.cs
- src/ReleaseNotesUtil/CategoryThenIdComparer.cs
- src/ReleaseNotesUtil/DiagnosticIdComparer.cs
- src/ReleaseNotesUtil/FixerExtensions.cs
- src/ReleaseNotesUtil/GenDiffNotes.cmd
- src/ReleaseNotesUtil/Program.cs
- src/ReleaseNotesUtil/ReleaseNotesUtil.csproj
- src/ReleaseNotesUtil/RuleFileContent.cs
- src/ReleaseNotesUtil/RuleInfo.cs
Generates a list of added/removed rules from analyzer binaries for release notes.
Fixes #2601 
If the format looks fine, I'll edit the previous 2.9.x releases.
> Release notes util

- docs/Analyzer Configuration.md
- src/Microsoft.NetCore.Analyzers/UnitTests/Runtime/DoNotPassLiteralsAsLocalizedParametersTests.cs
- src/Utilities/Compiler/Extensions/ISymbolExtensions.cs
- src/Utilities/Compiler/Options/AnalyzerOptionsExtensions.cs
- src/Utilities/Compiler/Options/EditorConfigOptionNames.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/ParameterValidationAnalysis/ParameterValidationAnalysis.cs
Follow up to #2640, which enabled excluding specific symbols only. The new option being added here enables excluding specific types and its derived types.
> Add editorconfig option to exclude type names and its derived types

- src/Microsoft.CodeAnalysis.BannedApiAnalyzers/Core/SymbolIsBannedAnalyzer.cs
- src/Microsoft.CodeAnalysis.BannedApiAnalyzers/UnitTests/SymbolIsBannedAnalyzerTests.cs
Issue Details:
`BannedApiAnalyzer` currently only looks for direct invocations of member methods, but it does not recognize member invocations using conversion or operator syntax.
Fix Details:
Register actions for usage of conversion, unary operators, binary operators and increment/decrement operators which will verify the method being invoked (if present).
> BannedApiAnalyzer should recognize invocations of user-defined conversion and operators.

- src/Microsoft.CodeAnalysis.BannedApiAnalyzers/Core/RestrictedInternalsVisibleToAnalyzer.cs
- src/Microsoft.CodeAnalysis.BannedApiAnalyzers/UnitTests/RestrictedInternalsVisibleToAnalyzerTests.cs
1. https://github.com/dotnet/roslyn-analyzers/commit/be936b6eacfb8cd8dbcb41d97aaced02b0a4172d: Guard against NRE in RestrictedIVT analyzer for symbol without a ContainingAssembly: I was unable to get a repro, but likely occurred for erroneous code. Fixes #2651
2. https://github.com/dotnet/roslyn-analyzers/commit/a471727ad856cfdaf6dd240a1e2689ffe8d98550: Handle few more OperationKinds in Restricted IVT analyzer. Fixes #2655
> Couple of fixes to Restricted IVT analyzer

- src/Microsoft.NetCore.Analyzers/Core/Runtime/DisposeObjectsBeforeLosingScope.cs
Workaround for missing IOperation/CFG support for using declarations: https://github.com/dotnet/roslyn/issues/32100
Fixes #2703
> Add a workaround to CA2000 for using declarations

- src/Microsoft.NetCore.Analyzers/Core/Security/SourceTriggeredTaintedDataAnalyzerBase.cs
- src/Microsoft.NetCore.Analyzers/UnitTests/Security/DoNotHardCodeEncryptionKeyTests.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/TaintedDataAnalysis/TaintedDataAnalysis.TaintedDataOperationVisitor.cs
> Hopefully fixed the bug.

- src/Microsoft.NetCore.Analyzers/Core/Data/ReviewSqlQueriesForSecurityVulnerabilities.cs
- src/Microsoft.NetCore.Analyzers/Core/Security/DoNotSetSwitch.cs
- src/Microsoft.NetCore.Analyzers/Core/Security/SourceTriggeredTaintedDataAnalyzerBase.cs
- src/Microsoft.NetCore.Analyzers/Core/Security/UseContainerLevelAccessPolicy.cs
- src/Microsoft.NetCore.Analyzers/Core/Security/UseSharedAccessProtocolHttpsOnly.cs
- src/Microsoft.NetCore.Analyzers/UnitTests/Security/DoNotHardCodeEncryptionKeyTests.cs
- src/Utilities.UnitTests/FlowAnalysis/Analysis/PropertySetAnalysis/PropertySetAnalysisTests.cs
- src/Utilities/Compiler/Extensions/IOperationExtensions.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/CopyAnalysis/CopyAnalysis.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/DisposeAnalysis/DisposeAnalysis.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAnalysis.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PropertySetAnalysis/PropertySetAnalysis.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/TaintedDataAnalysis/TaintedDataAnalysis.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/ValueContentAnalysis/ValueContentAnalysis.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowAnalysis.cs
[ControlFlowGraph.Create](http://source.roslyn.io/#q=ControlFlowGraph.Create) API has overloads for all operation block roots, except for attribute code blocks, which have OperationKind.None as the root operation. Compiler does not support CFG creation for attribute blocks, but it is likely that some of our current/future DFA analyzers may not have an explicit check and bail out for attribute blocks. So, we are now much more defensive in handling CFG/DFA requests for such attribute blocks and bail out gracefully instead of throwing not supported/NRE exception.
Fixes #2723
> Handle unsupported CFG/DFA requests for attribute code blocks gracefully

- src/Microsoft.NetFramework.Analyzers/Core/MarkVerbHandlersWithValidateAntiforgeryTokenAnalyzer.cs
- src/Microsoft.NetFramework.Analyzers/UnitTests/Security/MarkVerbHandlersWithValidateAntiforgeryTokenTests.cs
> CA3147 handle non-async Task<ActionResult-derived> ASP.NET MVC controller action methods

- docs/Analyzer Configuration.md
Several of the markdown tables in the edited file include code examples with pipe characters ('|') that are not escaped. This change escapes those characters so that they are not considered as column separators in the tables.
> Escape pipe characters in table content

- src/Microsoft.NetCore.Analyzers/UnitTests/Runtime/DisposeObjectsBeforeLosingScopeTests.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAnalysis.PointsToDataFlowOperationVisitor.cs
Escaping logic in PointsToAnalysis was not using unique escaping key for each array element initializer.
Fixes https://github.com/dotnet/roslyn/issues/37528
> Fix CA2000 false positive for array initializers with multiple elements

- src/Microsoft.NetCore.Analyzers/Core/MicrosoftNetCoreAnalyzersResources.resx
- src/Microsoft.NetCore.Analyzers/Core/Security/SetHttpOnlyForHttpCookie.cs
- src/Microsoft.NetCore.Analyzers/Core/xlf/MicrosoftNetCoreAnalyzersResources.cs.xlf
- src/Microsoft.NetCore.Analyzers/Core/xlf/MicrosoftNetCoreAnalyzersResources.de.xlf
- src/Microsoft.NetCore.Analyzers/Core/xlf/MicrosoftNetCoreAnalyzersResources.es.xlf
- src/Microsoft.NetCore.Analyzers/Core/xlf/MicrosoftNetCoreAnalyzersResources.fr.xlf
- src/Microsoft.NetCore.Analyzers/Core/xlf/MicrosoftNetCoreAnalyzersResources.it.xlf
- src/Microsoft.NetCore.Analyzers/Core/xlf/MicrosoftNetCoreAnalyzersResources.ja.xlf
- src/Microsoft.NetCore.Analyzers/Core/xlf/MicrosoftNetCoreAnalyzersResources.ko.xlf
- src/Microsoft.NetCore.Analyzers/Core/xlf/MicrosoftNetCoreAnalyzersResources.pl.xlf
- src/Microsoft.NetCore.Analyzers/Core/xlf/MicrosoftNetCoreAnalyzersResources.pt-BR.xlf
- src/Microsoft.NetCore.Analyzers/Core/xlf/MicrosoftNetCoreAnalyzersResources.ru.xlf
- src/Microsoft.NetCore.Analyzers/Core/xlf/MicrosoftNetCoreAnalyzersResources.tr.xlf
- src/Microsoft.NetCore.Analyzers/Core/xlf/MicrosoftNetCoreAnalyzersResources.zh-Hans.xlf
- src/Microsoft.NetCore.Analyzers/Core/xlf/MicrosoftNetCoreAnalyzersResources.zh-Hant.xlf
- src/Microsoft.NetCore.Analyzers/UnitTests/Security/SetHttpOnlyForHttpCookieTests.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PropertySetAnalysis/HazardousUsageEvaluator.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PropertySetAnalysis/HazardousUsageEvaluatorCollection.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PropertySetAnalysis/HazardousUsageEvaluatorKind.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PropertySetAnalysis/PropertySetAnalysis.PropertySetDataFlowOperationVisitor.cs
Those scenarios are flagged with diagnostics:
1. HttpCookie.HttpOnly is set to false explicitly.
2. Return a httpCookie whose HttpOnly property is not set. The default value of HttpOnly is false.
3. Create a HttpCookie whose name is x-ms-cpim-trans and value is Invalid_Base64_String.
> Implement semmle rule "HttpOnlyCookie.ql" into Roslyn

- src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowAnalysis.cs
Given our interprocedural analysis is context sensitive, it is highly unlikely that we will re-use the result after computing.
This brings down our flow analysis memory usage for some of the high memory usage repros to 15-20% of the original (down from 12-13 GB to close to 2 GB)
> Do not cache interprocedural dataflow analysis results

- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/DoNotRaiseExceptionsInUnexpectedLocations.cs
- src/Utilities/Compiler/Extensions/IOperationExtensions.cs
- src/Utilities/Compiler/Extensions/OperationBlockAnalysisContextExtension.cs
- src/Utilities/FlowAnalysis/Extensions/IOperationExtensions_FlowAnalysis.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs
Fixes #2761
IOperation tree for IThrowOperation now has an implicit IConversionOperation wrapping the underlying thrown object. Details at https://github.com/dotnet/roslyn/blame/a5418f7398495db4ea858f0c9efd9b13541ff478/src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs#L395
> Handle IOperation tree shape change for IThrowOperation

- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/EquatableAnalyzer.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/EquatableAnalyzerTests.cs
Analyzer flags types that are equatable and implements exactly one of IEquatable.Equals and object.Equals. Current implementation generates false positives for cases where IEquatable.Equals is implemented by some base type, which we avoid now.
Fixes #2027
> Add bail out cases for CA1067 (EquatableAnalyzer)

- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/PropertyNamesShouldNotMatchGetMethods.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/PropertyNamesShouldNotMatchGetMethodsTests.cs
Do not flag property/method pairs whose `IsStatic` value differs. There are few real world code bases (including Roslyn) where such an API pair is completely reasonable.
Fixes #2085
> Fix a false positive from CA1721 (PropertyNamesShouldNotMatchGetMethods)

- eng/GenerateAnalyzerNuspec.csx
- eng/GenerateAnalyzerNuspec.targets
- global.json
- nuget/Microsoft.CodeAnalysis.Analyzers/Microsoft.CodeAnalysis.Analyzers.Package.csproj
- nuget/Microsoft.CodeAnalysis.FxCopAnalyzers/Microsoft.CodeAnalysis.FxCopAnalyzers.Package.csproj
- nuget/Microsoft.CodeQuality.Analyzers/Microsoft.CodeQuality.Analyzers.Package.csproj
- nuget/Microsoft.NetCore.Analyzers/Microsoft.NetCore.Analyzers.Package.csproj
- nuget/Microsoft.NetFramework.Analyzers/Microsoft.NetFramework.Analyzers.Package.csproj
- nuget/Roslyn.Diagnostics.Analyzers/Roslyn.Diagnostics.Analyzers.Package.csproj
Fixes #2220
Also update the Description field for our important analyzer NuGet packages to be more informative.
Fixes #2024
> Fix the license tag generation in our NuGet packages.

- src/Microsoft.NetCore.Analyzers/UnitTests/Security/DoNotHardCodeEncryptionKeyTests.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/AbstractDataFlowAnalysisContext.cs
AbstractDataFlowAnalysisContext hash code computation did not account for the whole CFG, just the original operation of the CFG. This bug was masked by our prior CWT based caching/leak that ensured that the static cache on IOperationExtensions from IOperation to CFG always returned the same CFG. With the new BoundedCache approach, it is more likely for the cache entries to get evicted under high memory pressure and multiple simultaneous compilations, which makes this failure lot more prominent, even though non-deterministic.
Unit test `Test_PassTaintedSourceInfoAsParameter_SinkProperties_Interprocedual_Diagnostic` fails intermittently prior to this fix. I updated the test to execute multiple instances in parallel and it fails consistently prior to the fix. It passed consistently multiple …
> Fix an indeterministic test failure

- PostReleaseActivities.md
- eng/Versions.props
- nuget/Microsoft.CodeAnalysis.FlowAnalysis.Utilities/Microsoft.CodeAnalysis.FlowAnalysis.Utilities.Package.csproj
We just released https://www.nuget.org/packages/Microsoft.CodeAnalysis.FlowAnalysis.Utilities/2.9.5 for consumption in Roslyn, so bump up the package version.
> Bump up the FlowAnalysis utilities package version

- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/EnumsShouldHavePluralNames.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/EnumsShouldHavePluralNamesTests.cs
As commented by @hubuk in https://github.com/dotnet/roslyn-analyzers/issues/2229 having a rule that only applies on some regions causes a false impression that code is OK when it isn't and it is really hard to diagnose, apart that there is no documentation about it.
When having a distributed development team between different regions in the world there is no any reason to have different compiling rules. The same behavior should exist in every PC compiling the code.
> Remove rule condition based on user region

- src/Microsoft.CodeAnalysis.FlowAnalysis.Utilities/PublicAPI.Unshipped.txt
- src/Microsoft.CodeQuality.Analyzers/UnitTests/Maintainability/AvoidDeadConditionalCode_ValueContentAnalysis.cs
- src/Microsoft.NetCore.Analyzers/UnitTests/Runtime/DisposeObjectsBeforeLosingScopeTests.cs
- src/Utilities/Compiler/Extensions/IMethodSymbolExtensions.cs
- src/Utilities/Compiler/WellKnownTypeNames.cs
- src/Utilities/Compiler/WellKnownTypeProvider.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/DisposeAnalysis/DisposeAnalysis.DisposeDataFlowOperationVisitor.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAnalysis.PointsToDataFlowOperationVisitor.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs
1. https://github.com/dotnet/roslyn-analyzers/commit/a36d5ac16ff4e9a0ae295e1767a864378fea79cd: Fix CA2000 false positive from assigning to a field via an out argument. Fixes #2746
2. https://github.com/dotnet/roslyn-analyzers/commit/40e5146ec45013c2dc169730392edf0d9532c332: Handle Interlocked.Exchange and Interlocked.CompareExchange operations. Fixes #2681
> Fix couple of CA2000 false positives

- eng/GenerateAnalyzerNuspec.csx
- eng/GenerateAnalyzerNuspec.targets
Given the number of new configuration options being requested and added, this would help easy mapping of configuration options available in each package.
I will file a follow-up docs bug to update https://docs.microsoft.com/en-us/visualstudio/code-quality/fxcop-analyzer-options?view=vs-2019 to mention this.
> Embed analyzer configuration file in the analyzer NuGet packages

- src/Microsoft.NetCore.Analyzers/UnitTests/Security/DoNotUseInsecureSettingsForJsonNetTests.cs
- src/Test.Utilities/DiagnosticExtensions.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs
error AD0001: Analyzer 'Microsoft.NetCore.Analyzers.Security.DoNotUseInsecureSettingsForJsonNet' threw an exception of type 'System.InvalidCastException' with message 'Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberFieldSymbolFromDeclarator' to type 'Microsoft.CodeAnalysis.IMethodSymbol'.'.
> Fixing an InvalidCastException

- src/Microsoft.NetCore.Analyzers/Core/Security/SourceTriggeredTaintedDataAnalyzerBase.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/TaintedDataAnalysis/PooledHashSetExtensions.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/TaintedDataAnalysis/SourceInfo.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/TaintedDataAnalysis/TaintedDataSymbolMapExtensions.cs
Avoiding using PointsToAnalysis and ValueContentAnalysis unnecessarily when evaluating whether to do TaintedDataAnalysis.
> Fixing tainted data analyzers performance regression

- src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/AbstractDataFlowAnalysisContext.cs
The parameter 'valueDomain' is optional in the constructor of `AbstractDataFlowAnalysisContext` and must not be null in `ComputeHashCodeParts` which looks like a NR exception waiting to happen.
> Add assert for required parameter 'valueDomain'

- src/ReleaseNotesUtil/FixerExtensions.cs
- src/ReleaseNotesUtil/Program.cs
In another PR, we can consolidate FixerExtensions.cs implementations, and make sure GenerateAnalyzerRulesets works (I seem to be getting different results between ReleaseNotesUtil and GenerateAnalyzerRulesets even before this change).
> ReleaseNoteUtil: Ignore CodeFixProviders with no-op RegisterCodeFixesAsync() methods

- eng/Versions.props
Just published https://www.nuget.org/packages/Microsoft.CodeAnalysis.FlowAnalysis.Utilities/2.9.6 (still indexing), so bump up the flow analysis utilities version.
> Bump up the version of Microsoft.CodeAnalysis.FlowAnalysis.Utilities

- src/Microsoft.CodeQuality.Analyzers/CSharp/QualityGuidelines/CSharpRethrowToPreserveStackDetails.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/QualityGuidelines/RethrowToPreserveStackDetailsTests.cs
- src/Microsoft.CodeQuality.Analyzers/VisualBasic/QualityGuidelines/BasicRethrowToPreserveStackDetails.vb
If the caught exception is reassigned (new or set to another reference), it's then not actually "rethrowing the caught exception" such that it should not be reported as a diagnostic.
For example, this should be allowed:
```
try
{
//.....
}
catch(Exception ex)
{
//.....
ex = new SomeCustomException("some msg");
throw ex;
}
```
> Improve CA2200 Rethrow analyzer to allow reassigned exception

- src/Microsoft.CodeAnalysis.VersionCheckAnalyzer/Microsoft.CodeAnalysis.VersionCheckAnalyzer.csproj
- src/Microsoft.CodeAnalysis.VersionCheckAnalyzer/VersionCheckAnalyzer.cs
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/IdentifiersShouldDifferByMoreThanCase.cs
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/MarkAssembliesWithAttributesDiagnosticAnalyzer.cs
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/MarkAssembliesWithComVisible.cs
- src/Microsoft.NetCore.Analyzers/Core/Resources/MarkAssembliesWithNeutralResourcesLanguage.cs
- src/Utilities/Compiler/Analyzer.Utilities.projitems
- src/Utilities/Compiler/Extensions/DiagnosticExtensions.cs
- src/Utilities/Compiler/Extensions/ReportDiagnosticExtensions.cs
First item listed in https://github.com/dotnet/roslyn/issues/38042: `Diagnostics with Location.None cannot be configured with .editorconfig` leads to the Location.None diagnostics being non-configurable in editorconfig. This is also currently blocking https://github.com/dotnet/roslyn/pull/37795, as FxCop analyzers is the primary analyzer package with Location.None diagnostics.
This change should be able to unblock https://github.com/dotnet/roslyn/pull/37795.
> Add workaround for no location diagnostics

- src/Microsoft.CodeQuality.Analyzers/Core/QualityGuidelines/AssigningSymbolAndItsMemberInSameStatement.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/QualityGuidelines/AssigningSymbolAndItsMemberInSameStatementTests.cs
> Fix NRE in AssigningSymbolAndItsMemberInSameStatement analyzer

- src/Microsoft.NetCore.Analyzers/Core/Runtime/DoNotLockOnObjectsWithWeakIdentity.cs
- src/Microsoft.NetCore.Analyzers/UnitTests/Runtime/DoNotLockOnObjectsWithWeakIdentityTests.cs
I have updated the `DoNotLockOnObjectsWithWeakIdentity` to also report when locking on `this` or `Me`.
Fix #294
> Update CA2002 to detect usage of lock (this) and SyncLock Me

- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/PropertyNamesShouldNotMatchGetMethods.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/PropertyNamesShouldNotMatchGetMethodsTests.cs
When a base class with virtual members is not complying with the rule (i.e. has a property and a get method with the same name) and your derived class override one or two of the member you will get the issue raised upon your override. Sadly there is nothing much you can do if you don't own the base class so the analyzer should not raise an issue here.
I have tried to add test for C# and VB.NET for all the cases I could think of.
Fix #2914
> Fix CA1721 - Do not report on overriden members

- src/Microsoft.NetCore.Analyzers/Core/Security/SourceTriggeredTaintedDataAnalyzerBase.cs
Partially fixes #2900 
From my observations with slow analysis with DoNotHardCodeEncryptionKey, the root cause is a combination of ValueContent analysis can be slow and ValueContentAnalysisResult cache misses, due to the limited DFA result cache. That causes ValueContent analysis to be invoked multiple times.
This somewhat mitigates the problem, by caching analysis on a per-analyzer-operationblock basis, in TaintedData analyzers that use ValueContentAnalysis.
Longer term we should see if we can come up with a way of caching DFA results on a per compilation basis without memory leaks, and see what we can do to optimize ValueContent analysis.
> Somewhat cache DFA results

- src/Microsoft.NetCore.Analyzers/Core/Runtime/SpecifyIFormatProvider.cs
- src/Microsoft.NetCore.Analyzers/UnitTests/Runtime/SpecifyIFormatProviderTests.cs
Add `bool` and `char` to the exclusion list as the `IFormatProvider` parameter is ignored.
Fix #2394
> CA1305: Do not raise for bool.ToString() and char.ToString()

- src/Microsoft.CodeQuality.Analyzers/CSharp/ApiDesignGuidelines/CSharpTypesThatOwnDisposableFieldsShouldBeDisposable.cs
- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/TypesThatOwnDisposableFieldsShouldBeDisposable.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/TypesThatOwnDisposableFieldsShouldBeDisposableTests.cs
- src/Microsoft.CodeQuality.Analyzers/VisualBasic/ApiDesignGuidelines/BasicTypesThatOwnDisposableFieldsShouldBeDisposable.vb
- src/Utilities/Compiler/WellKnownTypeNames.cs
Fix #2325 
Note that the documentation will need to be updated.
I will need some help with the unit test, I don't know how to prevent the error about the unknown type `IAsyncDisposable`. Note that I have tried to use parse options with C#8 and Preview but both are failing.
> Update CA1001 to stop reporting on types implementing IAsyncDisposable

- src/Microsoft.CodeQuality.Analyzers/Core/QualityGuidelines/MarkMembersAsStatic.Fixer.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/QualityGuidelines/MarkMembersAsStaticTests.Fixer.cs
This PR was made to fix issue #2888, `async` modifier is lost during refactoring, but turned out as a more global problem where previous modifiers are always lost.
Fix #2888
> Update CA1822 code fix to preserve modifiers

- eng/Versions.props
- src/BannedSymbols.txt
- src/Directory.Build.targets
- src/MetaCompilation.Analyzers/Core/CodeFixProvider.cs
- src/MetaCompilation.Analyzers/Core/DiagnosticAnalyzer.cs
- src/MetaCompilation.Analyzers/Core/MetaCompilation.Analyzers.csproj
- src/Microsoft.CodeAnalysis.BannedApiAnalyzers/Core/RestrictedInternalsVisibleToAnalyzer.cs
- src/PerformanceSensitiveAnalyzers/Core/AbstractAllocationAnalyzer.cs
- src/PerformanceSensitiveAnalyzers/Core/AbstractAllocationAnalyzer`1.cs
- src/PublicApiAnalyzers/Core/Analyzers/DeclarePublicApiAnalyzer.Impl.cs
- src/Utilities/Compiler/WellKnownTypeProvider.cs
Fixes #2953
This is using the analyzer via NuGet.
> Ban Compilation.GetTypeByMetadataName

- src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/AvoidUninstantiatedInternalClasses.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/Maintainability/AvoidUninstantiatedInternalClassesTests.cs
- src/Utilities/Compiler/WellKnownTypeNames.cs
Update CA1812 to not report on internal types referenced by `CoClassAttribute`.
FYI I made an unrelated change to avoid getting an instance of the `WellKnownTypeProvider` multiple times. The changes are in a separate commit so that I can remove it or move it to a separate PR if needed.
Fix #2751
> Update CA1812: Do not report on internal types referenced by CoClassAttribute

- src/Microsoft.NetCore.Analyzers/Core/Performance/UsePropertyInsteadOfCountMethodWhenAvailable.cs
- src/Microsoft.NetCore.Analyzers/UnitTests/Performance/UsePropertyInsteadOfCountMethodWhenAvailableTests.cs
- src/Utilities/Compiler/Extensions/ITypeSymbolExtensions.cs
Extend the rule to cover the `IReadOnlyCollection.Count` property. 
Extract an helper to find whether the type has any collection `Count` property so that we can reuse it in #2968 
Fix #2974
> CA1829: Extend the rule to cover IReadOnlyCollection<T>.Count

- src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/UsePropertiesWhereAppropriate.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/UsePropertiesWhereAppropriateTests.cs
- Add a test to show that no issue is reported on explicit interface.
- Update the rule (and add a test) to stop reporting on implicit interface implementation.
- Do nothing regarding `override` as it is already handled.
Fix #1551
> CA1024: Do not report on implicit interface implementation

- src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/CollectionPropertiesShouldBeReadOnlyTests.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/CollectionsShouldImplementGenericInterfaceTests.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/EnumWithFlagsAttributeTests.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/IdentifiersShouldNotContainTypeNamesTests.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/ImplementStandardExceptionConstructorsTests.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/MarkAssembliesWithComVisibleTests.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/MarkAttributesWithAttributeUsageTests.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/MovePInvokesToNativeMethodsClassTests.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/NonConstantFieldsShouldNotBeVisibleTests.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/OperatorOverloadsHaveNamedAlternatesTests.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/StaticHolderTypeTests.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/TypesThatOwnDisposableFieldsShouldBeDisposableTests.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/UsePropertiesWhereAppropriateTests.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/Maintainability/AvoidUnusedPrivateFieldsTests.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/Maintainability/DoNotIgnoreMethodResultsTests.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/Maintainability/ReviewUnusedParametersTests.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/Maintainability/UseNameOfInPlaceOfStringTests.cs
- src/Microsoft.NetCore.Analyzers/UnitTests/Runtime/NormalizeStringsToUppercaseTests.cs
- Simplify cases where `MessageFormat.ToString` was used
- Simplify cases where `.WithMessage(string.Format` was used
- Add missing await for a couple of tests
Relates to #2988
> Couple of small changes post migration to new test framework

- src/Microsoft.CodeQuality.Analyzers/UnitTests/QualityGuidelines/MarkMembersAsStaticTests.cs
Cannot reproduce the issue described in #2785 neither with a unit test (included in this PR) nor with some console application using MSTest v2 and FxCop 2.9.4 (version declared in the issue) or 2.9.6.
@mavasani Could you confirm you are also experiencing the issue on your side?
> CA1822: Add unit test for custom TestMethodAttribute

- src/PublicApiAnalyzers/PublicApiAnalyzers.Help.md
Explain how to use multiple pairs of `PublicAPI.*.txt` files to differentiate API surface areas across properties such as target framework.
Fixes #2621.
> Document use of multiple public API files

- src/Tools/Metrics/MetricsOutputWriter.cs
The class doesn't have any test so there is no test to update.
Fix #2804
> Use fully qualified name for types in generated xml metrics

- src/Microsoft.CodeAnalysis.Analyzers/Core/CodeAnalysisDiagnosticsResources.resx
- src/Microsoft.CodeAnalysis.Analyzers/Core/DiagnosticIds.cs
- src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/ClassIsNotDiagnosticAnalyzer.cs
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.cs.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.de.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.es.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.fr.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.it.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.ja.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.ko.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.pl.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.pt-BR.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.ru.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.tr.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.zh-Hans.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.zh-Hant.xlf
- src/Microsoft.CodeAnalysis.Analyzers/UnitTests/MetaAnalyzers/ClassIsNotDiagnosticAnalyzerTests.cs
I did the implementation as a new rule but if you prefer me to update the behavior of `RS0001` instead I could do so.
Fix #1690
> New analyzer for classes that are not DiagnosticAnalyzer

- eng/Versions.props
- src/Microsoft.NetCore.Analyzers/Core/Runtime/SerializationRulesDiagnosticAnalyzer.cs
- src/Microsoft.NetCore.Analyzers/UnitTests/Performance/UsePropertyInsteadOfCountMethodWhenAvailableTests.cs
- src/Test.Utilities/AdditionalMetadataReferences.cs
- src/Test.Utilities/CSharpCodeFixVerifier`2+Test.cs
- src/Test.Utilities/DiagnosticAnalyzerTestBase.cs
- src/Test.Utilities/VisualBasicCodeFixVerifier`2+Test.cs
This is a backport of #3011 and #3020 to the 2.9.x branch.
> Update testing library for 2.9.x branch

- src/Microsoft.NetCore.Analyzers/Core/Security/DoNotDisableHttpClientCRLCheck.cs
- src/Microsoft.NetCore.Analyzers/Core/Security/DoNotInstallRootCert.cs
- src/Microsoft.NetCore.Analyzers/Core/Security/DoNotSerializeTypeWithPointerFields.cs
- src/Microsoft.NetCore.Analyzers/Core/Security/DoNotUseCreateEncryptorWithNonDefaultIV.cs
- src/Microsoft.NetCore.Analyzers/Core/Security/DoNotUseInsecureCryptographicAlgorithms.cs
- src/Microsoft.NetCore.Analyzers/Core/Security/DoNotUseInsecureDeserializerJavascriptSerializerWithSimpleTypeResolver.cs
- src/Microsoft.NetCore.Analyzers/Core/Security/DoNotUseInsecureDeserializerJsonNetWithoutBinder.cs
- src/Microsoft.NetCore.Analyzers/Core/Security/DoNotUseInsecureDeserializerWithoutBinderBase.cs
- src/Microsoft.NetCore.Analyzers/Core/Security/DoNotUseInsecureSettingsForJsonNet.cs
- src/Microsoft.NetCore.Analyzers/Core/Security/DoNotUseWeakKDFInsufficientIterationCount.cs
- src/Microsoft.NetCore.Analyzers/Core/Security/SetHttpOnlyForHttpCookie.cs
- src/Microsoft.NetCore.Analyzers/Core/Security/SourceTriggeredTaintedDataAnalyzerBase.cs
- src/Microsoft.NetCore.Analyzers/Core/Security/UseSecureCookiesASPNetCore.cs
- src/Microsoft.NetFramework.Analyzers/Core/DoNotUseInsecureDtdProcessing.cs
- src/Microsoft.NetFramework.Analyzers/Core/DoNotUseInsecureDtdProcessingInApiDesign.cs
- src/Microsoft.NetFramework.Analyzers/Core/DoNotUseInsecureXSLTScriptExecution.cs
- src/Microsoft.NetFramework.Analyzers/Core/Helpers/SecurityDiagnosticHelpers.cs
- src/TestReferenceAssembly/OtherDllClass.cs
- src/TestReferenceAssembly/OtherDllStaticMethods.cs
- src/Tools/ReleaseNotesUtil/Program.cs
- src/Tools/ReleaseNotesUtil/RuleFileContent.cs
- src/Tools/ReleaseNotesUtil/RuleInfo.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PropertySetAnalysis/ConstructorMapper.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PropertySetAnalysis/HazardousUsageEvaluator.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PropertySetAnalysis/HazardousUsageEvaluatorCollection.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PropertySetAnalysis/PropertyMapper.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PropertySetAnalysis/PropertyMapperCollection.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PropertySetAnalysis/PropertySetAnalysis.PropertySetDataFlowOperationVisitor.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PropertySetAnalysis/PropertySetAnalysis.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PropertySetAnalysis/PropertySetAnalysisResult.cs
Fixes #3069 - XML rules, which I will reimplement with DFA one year.
> Use nullable references in security rules

- src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/DoNotCatchGeneralExceptionTypesTests.cs
* Convert DoNotCatchGeneralExceptionTypesTests to Microsoft.CodeAnalysis.Testing
* Convert tests in DoNotCatchGeneralExceptionTypesTests to markup syntax
Markup syntax does a better job of revealing https://github.com/dotnet/roslyn-analyzers/issues/2518#issuecomment-499105568.
> Convert DoNotCatchGeneralExceptionTypesTests to Microsoft.CodeAnalysis.Testing

- src/Microsoft.CodeQuality.Analyzers/Core/QualityGuidelines/MarkMembersAsStatic.cs
- src/Microsoft.CodeQuality.Analyzers/UnitTests/QualityGuidelines/MarkMembersAsStaticTests.cs
- src/Test.Utilities/AdditionalMetadataReferences.cs
- src/Utilities/Compiler/WellKnownTypeNames.cs
Fix #3123 and also handles `Application_Start` and `Application_End` special methods.
> Update CA1822: Do not report for web specific methods

- docs/Analyzer Configuration.md
Fix typos: The option prefix in the example should be `T:` not `M:` for type name specification.
> Fix typos in AnalyzerConfiguration.md

- eng/Versions.props
- src/PublicApiAnalyzers/Core/Analyzers/DeclarePublicApiAnalyzer.Impl.cs
- src/PublicApiAnalyzers/Core/Analyzers/DeclarePublicApiAnalyzer.cs
- src/PublicApiAnalyzers/Core/Analyzers/PublicApiAnalyzerResources.resx
- src/PublicApiAnalyzers/Core/Analyzers/xlf/PublicApiAnalyzerResources.cs.xlf
- src/PublicApiAnalyzers/Core/Analyzers/xlf/PublicApiAnalyzerResources.de.xlf
- src/PublicApiAnalyzers/Core/Analyzers/xlf/PublicApiAnalyzerResources.es.xlf
- src/PublicApiAnalyzers/Core/Analyzers/xlf/PublicApiAnalyzerResources.fr.xlf
- src/PublicApiAnalyzers/Core/Analyzers/xlf/PublicApiAnalyzerResources.it.xlf
- src/PublicApiAnalyzers/Core/Analyzers/xlf/PublicApiAnalyzerResources.ja.xlf
- src/PublicApiAnalyzers/Core/Analyzers/xlf/PublicApiAnalyzerResources.ko.xlf
- src/PublicApiAnalyzers/Core/Analyzers/xlf/PublicApiAnalyzerResources.pl.xlf
- src/PublicApiAnalyzers/Core/Analyzers/xlf/PublicApiAnalyzerResources.pt-BR.xlf
- src/PublicApiAnalyzers/Core/Analyzers/xlf/PublicApiAnalyzerResources.ru.xlf
- src/PublicApiAnalyzers/Core/Analyzers/xlf/PublicApiAnalyzerResources.tr.xlf
- src/PublicApiAnalyzers/Core/Analyzers/xlf/PublicApiAnalyzerResources.zh-Hans.xlf
- src/PublicApiAnalyzers/Core/Analyzers/xlf/PublicApiAnalyzerResources.zh-Hant.xlf
- src/PublicApiAnalyzers/Core/CodeFixes/AnnotatePublicApiFix.cs
- src/PublicApiAnalyzers/Core/CodeFixes/DeclarePublicApiFix.cs
- src/PublicApiAnalyzers/Core/CodeFixes/NullableEnablePublicApiFix.cs
- src/PublicApiAnalyzers/UnitTests/AnnotatePublicApiAnalyzerTests.cs
- src/PublicApiAnalyzers/UnitTests/DeclarePublicApiAnalyzerTests.cs
- src/PublicApiAnalyzers/UnitTests/Microsoft.CodeAnalysis.PublicApiAnalyzers.UnitTests.csproj
- src/PublicApiAnalyzers/UnitTests/NullableEnablePublicApiAnalyzerTests.cs
- src/Roslyn.Diagnostics.Analyzers/Core/RoslynDiagnosticIds.cs
This PR adds `?` annotations to public APIs.
Before we can add `!` annotations, we need the compiler to expose an internal flag. I'll get that going.
I didn't manage to update the reference to `CodeAnalysis.Common`, so couldn't use `SymbolDisplayMiscellaneousOptions)IncludeNullableReferenceTypeModifier` enum value.
Relates to https://github.com/dotnet/roslyn/issues/40502 (Shipped APIs files should include nullable annotations)
> Add nullability to shipped API files

- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStatic.cs
- src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStaticTests.cs
Fix #3019 
With this change the analyzer will look for invocations located in _ALL_ methods but will keep raising issues only on correct ones. Thanks to this change we shall be able to report a lot more cases where the method could be made `static`.
> CA1822: Update rule to flag more cases

- docs/Analyzer Configuration.md
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/IdentifiersShouldHaveCorrectSuffix.cs
- src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/IdentifiersShouldHaveCorrectSuffixTests.cs
Contributes to #1818 
⚠️ Breaking change!
> Update CA1710: Exclude indirect base-types by default

- src/PublicApiAnalyzers/Core/Analyzers/DeclarePublicApiAnalyzer.Impl.cs
- src/PublicApiAnalyzers/UnitTests/DeclarePublicApiAnalyzerTests.cs
The test added in this PR was running into an issue with the test framework iterating on fixes. That's because the fixer was incorrectly removing APIs already marked with nullability information.
This PR adjusts the logic for recognizing APIs (to decide whether they were removed or not) to account for nullability format.
> PublicAPI: Keep found APIs regardless of nullability

- src/PerformanceSensitiveAnalyzers/CSharp/TypeConversionAllocationAnalyzer.cs
ReadonlyMethodGroupAllocationRule is using a name in the DiagnosticDescriptor id field, this corrects it to use an actual id.
This is ported from https://github.com/microsoft/RoslynClrHeapAllocationAnalyzer/pull/76. Originally commited by @nnpcYvIVl 
FYI @mjsabby
> Port "DiagnosticDescriptor id fix"

- src/PerformanceSensitiveAnalyzers/CSharp/AnalyzersResources.resx
- src/PerformanceSensitiveAnalyzers/CSharp/CallSiteImplicitAllocationAnalyzer.cs
- src/PerformanceSensitiveAnalyzers/CSharp/xlf/AnalyzersResources.cs.xlf
- src/PerformanceSensitiveAnalyzers/CSharp/xlf/AnalyzersResources.de.xlf
- src/PerformanceSensitiveAnalyzers/CSharp/xlf/AnalyzersResources.es.xlf
- src/PerformanceSensitiveAnalyzers/CSharp/xlf/AnalyzersResources.fr.xlf
- src/PerformanceSensitiveAnalyzers/CSharp/xlf/AnalyzersResources.it.xlf
- src/PerformanceSensitiveAnalyzers/CSharp/xlf/AnalyzersResources.ja.xlf
- src/PerformanceSensitiveAnalyzers/CSharp/xlf/AnalyzersResources.ko.xlf
- src/PerformanceSensitiveAnalyzers/CSharp/xlf/AnalyzersResources.pl.xlf
- src/PerformanceSensitiveAnalyzers/CSharp/xlf/AnalyzersResources.pt-BR.xlf
- src/PerformanceSensitiveAnalyzers/CSharp/xlf/AnalyzersResources.ru.xlf
- src/PerformanceSensitiveAnalyzers/CSharp/xlf/AnalyzersResources.tr.xlf
- src/PerformanceSensitiveAnalyzers/CSharp/xlf/AnalyzersResources.zh-Hans.xlf
- src/PerformanceSensitiveAnalyzers/CSharp/xlf/AnalyzersResources.zh-Hant.xlf
- src/PerformanceSensitiveAnalyzers/UnitTests/CallSiteImplicitAllocationAnalyzerTests.cs
HAA0101 was incorrectly implemented because the statement This results in an array allocation even if no parameter is passed in for the params parameter is not always true. If no parameter is passed then the compiler will insert Array.Empty<T>() in the method invocation. This PR fixes this issue.
Ported from https://github.com/microsoft/RoslynClrHeapAllocationAnalyzer/pull/78
This is originally committed by @cezarypiatek
FYI @mjsabby
> Port "Prevent reporting HAA0101 when no value for params is provided"

- src/PerformanceSensitiveAnalyzers/CSharp/TypeConversionAllocationAnalyzer.cs
- src/PerformanceSensitiveAnalyzers/UnitTests/TypeConversionAllocationAnalyzerTests.cs
Ported from https://github.com/microsoft/RoslynClrHeapAllocationAnalyzer/pull/79. 
Originally implemented by @cezarypiatek
FYI @mjsabby
> Port "Verify symbol type when reporting HAA0602"

- src/Microsoft.CodeAnalysis.BannedApiAnalyzers/BannedApiAnalyzers.Help.md
Add additional examples of usage, and fixed the generic method usage which looked incorrect in markdown.
> Add additional examples of usage

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/DisposeObjectsBeforeLosingScope.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/DisposeObjectsBeforeLosingScopeTests.cs
fixes #3297
Basically any scope that contains a `nameof` operator will be ignored by the CA2000:DisposeObjectsBeforeLosingScope rule. And, in my opinion, `nameof` is used quite often (parameter checks, exception messages, logging, etc.), so it's quite a serious bug.
This bug was introduced by #2704 (workaround for issue #2703), see also: https://github.com/dotnet/roslyn/issues/32100. The contents of the `nameof` expression are an `OperationKind.None`, which is why the hack breaks it. I added additional check for `INameOfOperation` specifically.
> Fix for CA2000 not detected if nameof() is in the scope

- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/DisposeObjectsBeforeLosingScopeTests.cs
- src/Utilities/Compiler/Analyzer.Utilities.projitems
- src/Utilities/Compiler/Extensions/IMethodSymbolExtensions.cs
- src/Utilities/Compiler/Extensions/ITypeSymbolExtensions.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/DisposeAnalysis/DisposeAnalysis.DisposeDataFlowOperationVisitor.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAnalysis.cs
fixes https://github.com/dotnet/roslyn-analyzers/issues/3305
In this fix:
- three new tests: `LocalWithRefStructDisposableAssignment_NotDisposed_Diagnostic`, `LocalWithRefStructDisposableAssignment_Internal_NotDisposed_Diagnostic` and `LocalWithRefStructDisposableAssignment_Disposed_NoDiagnostic` (C# only, `protected` is not covered as structs can not declare new `protected` methods)
- `GetDisposeMethodKind` returns `DisposeMethodKind.Dispose` for parameterless `Dispose` instance method on ref-only structs
- `IsDisposable` returns `true` for ref-only structs with non-private parameterless `Dispose` instance method
- `PointsToAnalysis` and `DisposeDataFlowOperationVisitor` track ref-only value types in addition to reference types
> CA2000 for ref structs, that are not disposed properly

- src/PublicApiAnalyzers/Core/Analyzers/DeclarePublicApiAnalyzer.Impl.cs
- src/PublicApiAnalyzers/UnitTests/DeclarePublicApiAnalyzerTests.cs
Workaround for https://github.com/dotnet/wpf/issues/2690
> Ignore XamlGeneratedNamespace.GeneratedInternalTypeHelper

- src/Roslyn.Diagnostics.Analyzers/CSharp/PreferNullLiteral.cs
- src/Roslyn.Diagnostics.Analyzers/CSharp/PreferNullLiteralCodeFixProvider.cs
- src/Roslyn.Diagnostics.Analyzers/Core/RoslynDiagnosticIds.cs
- src/Roslyn.Diagnostics.Analyzers/Core/RoslynDiagnosticsAnalyzersResources.resx
- src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.cs.xlf
- src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.de.xlf
- src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.es.xlf
- src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.fr.xlf
- src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.it.xlf
- src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.ja.xlf
- src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.ko.xlf
- src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.pl.xlf
- src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.pt-BR.xlf
- src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.ru.xlf
- src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.tr.xlf
- src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.zh-Hans.xlf
- src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.zh-Hant.xlf
- src/Roslyn.Diagnostics.Analyzers/UnitTests/PreferNullLiteralTests.cs
Prefer `null` to `default(T)` (or `default`) when `T` is a reference type.
Additional cases that need to be accounted for:
> Implement RS0038 (Prefer null literal)

- src/Roslyn.Diagnostics.Analyzers/CSharp/PreferNullLiteral.cs
- src/Roslyn.Diagnostics.Analyzers/CSharp/PreferNullLiteralCodeFixProvider.cs
- src/Roslyn.Diagnostics.Analyzers/UnitTests/PreferNullLiteralTests.cs
* A diagnostic was incorrectly reported when a default value was passed for a nullable value type argument
* The code fix failed to indent parameters replaced with `null`
* The code fix failed to preserve trivia
> Fix default→null bugs

- .editorconfig
- src/Roslyn.Diagnostics.Analyzers/Core/Roslyn.Diagnostics.Analyzers.csproj
RS1024 (Compare symbols correctly) has been disabled to avoid a highly-disruptive bug in the code fix. See dotnet/roslyn-analyzers#3389.
> Update Roslyn.Roslyn.Diagnostics.Analyzers to Microsoft.CodeAnalysis 3.3.1

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Tasks/UseValueTasksCorrectly.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Tasks/UseValueTaskCorrectlyTests.cs
Just treat it the same as a ternary and walk up to the parent.
Also some minor refactoring just to simplify/clarify things.
And explicitly added in handling of discards.
Fixes https://github.com/dotnet/roslyn-analyzers/issues/3384
cc: @sharwell
> Fix UseValueTasksCorrectly handling of null conditionals

- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/IdentifiersShouldHaveCorrectSuffix.cs
- src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/IdentifiersShouldHaveCorrectSuffixTests.cs
> Handle null base type in CA1710

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Tasks/UseValueTasksCorrectly.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Tasks/UseValueTaskCorrectlyTests.cs
Fixes https://github.com/dotnet/roslyn-analyzers/issues/3433
cc: @mavasani, @Tan90909090
> Fix null ref in UseValueTasksCorrectly for parentless operation

- src/Microsoft.CodeAnalysis.Analyzers/Core/CodeAnalysisDiagnosticsResources.resx
- src/Microsoft.CodeAnalysis.Analyzers/Core/DiagnosticIds.cs
- src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/DiagnosticDescriptorCreationAnalyzer.cs
- src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/DiagnosticDescriptorCreationAnalyzer_IdRangeAndCategoryValidation.cs
- src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/DiagnosticDescriptorCreationAnalyzer_ReleaseTracking.cs
- src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/Fixers/AnalyzerReleaseTrackingFix.FixAllProvider.cs
- src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/Fixers/AnalyzerReleaseTrackingFix.cs
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.cs.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.de.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.es.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.fr.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.it.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.ja.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.ko.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.pl.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.pt-BR.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.ru.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.tr.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.zh-Hans.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.zh-Hant.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Directory.Build.props
- src/Microsoft.CodeAnalysis.Analyzers/ReleaseTrackingAnalyzers.Help.md
- src/Microsoft.CodeAnalysis.Analyzers/UnitTests/MetaAnalyzers/ReleaseTrackingAnalyzerTests.cs
- src/Utilities/Compiler/DiagnosticCategory.cs
- src/Utilities/Compiler/DiagnosticCategoryAndIdRanges.txt
- src/Utilities/Compiler/Extensions/DiagnosticExtensions.cs
- src/Utilities/Compiler/RuleLevel.cs
Release tracking analyzer enables third party analyzer packages to define analyzer releases with associated versions. Each release can track the following changes:
1. Additions: Set of new analyzer rules that shipped for the first time in this release.
2. Removals: Set of old analyzer rules that shipped in an earlier release, but are removed starting this release.
3. Changes: Set of existing analyzer rules that shipped in an earlier release, but one of the following attributes of the diagnostic changed in this release:
1. Category of the diagnostic.
2. Default severity of the diagnostic
3. Enabled by default status.
This analyzer expects that the third party analyzer project has two additional files, namely `AnalyzerReleases.Unshipped.md` and `AnalyzerReleases.Shipped.md`, to track this …
> Add "Release tracking" analyzer to track 'analyzer releases' <-> 'shipped rules'

- src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/DiagnosticDescriptorCreationAnalyzer.cs
- src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/DiagnosticDescriptorCreationAnalyzer_ReleaseTracking.cs
- src/Microsoft.CodeAnalysis.Analyzers/ReleaseTrackingAnalyzers.Help.md
- src/Microsoft.CodeAnalysis.Analyzers/UnitTests/MetaAnalyzers/ReleaseTrackingAnalyzerTests.cs
1. Use quoted `<Undetected>` instead of unquoted <Undetected> for undetected fields in AnalyzerReleases file - this renders properly in md file viewers.
2. Rename the optional "HelpLink" column to "Notes" column in AnalyzerReleases file and also include the analyzer name in the Notes generated by the code fix.
> Couple of bug fixes to ReleaseTrackingAnalyzer

- src/PublicApiAnalyzers/Core/Analyzers/DeclarePublicApiAnalyzer.Impl.cs
- src/PublicApiAnalyzers/Core/CodeFixes/AnnotatePublicApiFix.cs
- src/PublicApiAnalyzers/UnitTests/AnnotatePublicApiAnalyzerTests.cs
- src/PublicApiAnalyzers/UnitTests/DeclarePublicApiAnalyzerTests.cs
Follows up on https://github.com/dotnet/roslyn-analyzers/pull/3386 (tracking oblivious APIs)
In trying the analyzer on roslyn, I found two bugs:
- we would produce a spurious warning on nested enums in `#nullable enable` context because of incorrect detection of oblivious types (more details below)
- in the upgrade of oblivious APIs previously marked with `~`, we would not recognize the existing API line as corresponding to a newly annotated member (the `~` needed to be trimmed)
Sorry I missed those scenarios in my previous PR :-(
Detection of oblivious types:
In `class C { enum E { None } }`, we would look at the field `C.E.None` which returns a `C.E` and see an oblivious on the containing type. That is not a place where an annotation `?` could go, therefore that is not a place where …
> PublicAPI: Fix spurious oblivious warning on nested enum

- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/DoNotUseReferenceEqualsWithValueTypesTests.cs
- src/Test.Utilities/CSharpCodeFixVerifier`2.cs
- src/Test.Utilities/VisualBasicCodeFixVerifier`2.cs
Inline a `VerifyAnalyzerAsync` helper method to avoid bloating the shared analyzer entry points.
> Inline test helper

- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/AvoidExcessiveParametersOnGenericTypes.cs
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/DoNotNameEnumValuesReserved.cs
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/DoNotPassTypesByReference.cs
I have disabled in fxcop all newly added fxcop analyzers (in the unshipped file) for which the state is disabled.
Tagging @mavasani
> Disable analyzer by default in fxcop

- eng/GenerateAnalyzerNuspec.csx
- src/Tools/GenerateGlobalAnalyzerConfigs/Program.cs
1. Do not generate different global analyzer config files for build and live analysis. https://github.com/dotnet/roslyn/pull/43546 will ensure that we do not need special logic in each analyzer package to disable hidden/suggestion analyzers in build - this will be baked into the compiler.
2. Update the contents of generated targets and editorconfig file as per the new design for global analyzer config: Everything for global analyzer config files will match regular analyzer config files (file name should be .editorconfig, existing MSBuild property "EditorConfigFiles" will be used, etc.), except for a special entry "is_global = true" to indicate global analyzer config.
I verified that a locally built analyzer NuGet package has the desired global editor config and it also gets passed to the …
> Update global analyzer config generation in the repo

- src/NetAnalyzers/CSharp/Microsoft.NetCore.Analyzers/Runtime/PreferStreamAsyncMemoryOverloads.Fixer.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/MicrosoftNetCoreAnalyzersResources.resx
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/PreferStreamAsyncMemoryOverloads.Fixer.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/PreferStreamAsyncMemoryOverloads.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.cs.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.de.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.es.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.fr.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.it.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ja.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ko.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.pl.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.pt-BR.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ru.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.tr.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.zh-Hans.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.zh-Hant.xlf
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/PreferStreamAsyncMemoryOverloadsTestBase.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/PreferStreamReadAsyncMemoryOverloadsTests.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/PreferStreamWriteAsyncMemoryOverloadsTests.cs
- src/NetAnalyzers/VisualBasic/Microsoft.NetCore.Analyzers/Runtime/PreferStreamAsyncMemoryOverloads.Fixer.vb
Fixes dotnet/runtime#33790
If the user invokes any of these methods from an object that is or inherits from Stream:
```cs
ReadAsync(byte[] buffer, int offset, int count)
ReadAsync(byte[] buffer, int offset, int count, CancellationToken cancellationToken)
WriteAsync(byte[] buffer, int offset, int count)
WriteAsync(byte[] buffer, int offset, int count, CancellationToken cancellationToken)
```
We should suggest to instead use:
```cs
ReadAsync(Memory<byte> buffer, CancellationToken cancellationToken)
WriteAsync(ReadOnlyMemory<byte> buffer, CancellationToken cancellationToken)
```
Works for both C# and VB.
All unit tests are passing locally.
> Fixer: Prefer Memory overloads for Stream async Read/Write methods

- azure-pipelines-microbuild.yml
- eng/Version.Details.xml
- global.json
This is the first part of a set of changes that will allot the roslyn-analyzers repo to be consumed from the .NET Core SDK
> publish our nuget package to the azure blob feed so the .NET Core SDK can consume them

- docs/NetCore_GettingStarted.md
Specify `AutoGenerateAssemblyVersion=false` for building to test against `dotnet/runtime`
> Update build command in test instructions for runtime repo

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Tasks/UseValueTasksCorrectly.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Tasks/UseValueTaskCorrectlyTests.cs
I didn't realize Destination could be null: IntelliSense lied to me again ;-) ("'Destination' is not null here.)
Fixes https://github.com/dotnet/roslyn-analyzers/issues/3642
> Fix handling of successor.Destination in UseValueTasksCorrectly

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/MicrosoftNetCoreAnalyzersResources.resx
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/PreferStringContainsOverIndexOf.Fixer.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.cs.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.de.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.es.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.fr.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.it.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ja.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ko.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.pl.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.pt-BR.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ru.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.tr.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.zh-Hans.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.zh-Hant.xlf
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/PreferStringContainsOverIndexOfTests.cs
Offers a code-fix for the following cases when they appear inside a binary expression such as `if (string.IndexOf() == -1)`:
``` csharp
String.IndexOf(char) -> string.Contains(char)
String.IndexOf(string) -> string.Contains(string, StringComparison.CurrentCulture)
String.IndexOf(string/char, StringComparison.Ordinal) -> string.Contains(string/char)
String.IndexOf(string/char, NON StringComparison.Ordinal) -> string.Contains(string/char, NON StringComparison.Ordinal)
```
The analyzer also tags the following case, but @mavasani recommended against offering a code-fix here(since it involves more data flow analysis than roslyn provides currently). Note: The analyzer will still fire:
``` csharp
int index = str.IndexOf("AString");
if (index == -1)
```
> Fixer for https://github.com/dotnet/runtime/issues/33785

- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/UseIntegralOrStringArgumentForIndexers.cs
- src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/UseIntegralOrStringArgumentForIndexersTests.cs
- src/Utilities/Compiler/WellKnownTypeNames.cs
Fix #3638 for the original 2 points but there are still some open questions (they might deserve a separate thread).
The first commit of the PR is the actual fix, the second is a code refactoring to reduce nesting, improve performance by checking the `api_surface` later in the code and also by using `ImmutableHashSet` instead of `array` for the contains check. Please feel free to push a revert for the second commit if you prefer not to have it.
> CA1043: Allow System.Index and System.Range for indexers

- docs/Analyzer Configuration.md
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/ProvideCorrectArgumentsToFormattingMethods.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/ProvideCorrectArgumentsToFormattingMethodsTests.cs
- src/Utilities/Compiler/Options/EditorConfigOptionNames.cs
In the end this was very simple as the method to detect a Format method already existed.
We could completely delete the existing configuration and simply check if the called method has a format parameter followed by a params parameter. This can not be much more expensive than checking the configuration.
> CA2241: AutoDetectStringFormattingMethods

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/InstantiateArgumentExceptionsCorrectly.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/InstantiateArgumentExceptionsCorrectlyTests.cs
Fixes last comment for  https://github.com/dotnet/runtime/issues/33763
Related to PR comment `apply the rule to the all ArgumentException-derived types (including itself) that have a constructor accepting a paramName parameter, including user-defined types.`  https://github.com/dotnet/runtime/pull/35717#discussion_r424655024
> Check for constructor with parameterName parameter

- src/NetAnalyzers/CSharp/Microsoft.NetCore.Analyzers/Runtime/CSharpPreferStreamAsyncMemoryOverloads.Fixer.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/PreferStreamAsyncMemoryOverloadsTestBase.cs
- src/NetAnalyzers/VisualBasic/Microsoft.NetCore.Analyzers/Runtime/BasicPreferStreamAsyncMemoryOverloads.Fixer.vb
Small fix. I realized I didn't name the classes and files properly.
> Rename CA1835 C#/VB specific classes

- docs/NetCore_GettingStarted.md
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/MicrosoftNetCoreAnalyzersResources.resx
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Performance/UseAsSpanInsteadOfRangeIndexer.Fixer.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.cs.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.de.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.es.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.fr.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.it.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ja.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ko.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.pl.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.pt-BR.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ru.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.tr.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.zh-Hans.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.zh-Hant.xlf
1. Updated getting started: "Definition of done" to test roslyn-analyzers repo same as runtime
2. As per VS doc [PR feedback](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/6679#discussion_r437781158) updated UseAsSpanInsteadOfRangeIndexer Fixer title
> Update fixer title, update getting started doc

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Tasks/DoNotCreateTaskCompletionSourceWithWrongArguments.Fixer.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Tasks/DoNotCreateTaskCompletionSourceWithWrongArguments.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Tasks/DoNotCreateTaskCompletionSourceWithWrongArgumentsTests.cs
- src/Utilities/Compiler/WellKnownTypeNames.cs
A non-generic TaskCompletionSource was added in .NET 5.  Add checking for it in addition to the generic in CA2247.
> Add non-generic TCS support to CA2247

- eng/Versions.props
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/EnumsShouldHavePluralNames.cs
- src/Test.Utilities/CSharpCodeFixVerifier`2+Test.cs
- src/Test.Utilities/VisualBasicCodeFixVerifier`2+Test.cs
- src/Tools/GenerateGlobalAnalyzerConfigs/GenerateGlobalAnalyzerConfigs.csproj
- src/Tools/GenerateGlobalAnalyzerConfigs/Program.cs
- src/Utilities/Compiler/Analyzer.Utilities.projitems
- src/Utilities/Compiler/Options/AbstractCategorizedAnalyzerConfigOptions.cs
- src/Utilities/Compiler/Options/AggregateCategorizedAnalyzerConfigOptions.cs
- src/Utilities/Compiler/Options/AnalyzerOptionsExtensions.cs
- src/Utilities/Compiler/Options/CompilationCategorizedAnalyzerConfigOptions.cs
- src/Utilities/Compiler/Options/ICategorizedAnalyzerConfigOptions.cs
- src/Utilities/Compiler/Options/MSBuildPropertyOptionNames.cs
- src/Utilities/Compiler/Options/OptionKind.cs
Using the new global analyzerconfig feature added by the compiler team, analyzers and end users can now thread in any required MSBuild property values as analyzer options. This change adds the following support:
1. Define a new type `MSBuildPropertyOptionNames` with the names of properties that required to be threaded to analyzers
2. Update the targets file dropped in with our analyzer packages to have the properties defined in the above type to be threaded to the analyzers
3. Add extension method `GetMSBuildPropertyValue` to `AnalyzerOptions` fetch option value inside our analyzers:
```csharp
var optionValue = context.Options.GetMSBuildPropertyValue(MSBuildPropertyOptionNames.TargetFramework, ...);
```
> Add support to read in MSBuild property values required by analyzers

- src/Utilities/Compiler/Options/AbstractCategorizedAnalyzerConfigOptions.cs
- src/Utilities/Compiler/Options/AggregateCategorizedAnalyzerConfigOptions.cs
- src/Utilities/Compiler/Options/AnalyzerOptionsExtensions.cs
- src/Utilities/Compiler/Options/ICategorizedAnalyzerConfigOptions.cs
:memo: Instances of `[MaybeNull] T` that can be converted to `T??` later have been indicated with `/*??*/`.
> Fix nullability attributes

- src/Utilities/Compiler/Options/MSBuildPropertyOptionNames.cs
This change codifies our pattern of property names in code matching property names in the project file.
> Use nameof where appropriate

- src/Microsoft.CodeAnalysis.Analyzers/Core/FixAnalyzers/FixerWithFixAllAnalyzer.Fixer.cs
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/ImplementStandardExceptionConstructors.Fixer.cs
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/TypesThatOwnDisposableFieldsShouldBeDisposable.Fixer.cs
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/UriParametersShouldNotBeStrings.Fixer.cs
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/Maintainability/ReviewUnusedParameters.Fixer.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Resources/MarkAssembliesWithNeutralResourcesLanguage.cs
This PR applies Roslyn analyzer CA2016: It identified methods that had a CancellationToken parameter, and then looked inside its method body for any method invocations that could accept a token as an argument, but weren't taking it yet.
The Roslyn analyzer/fixer is up for review here: dotnet/roslyn-analyzers#3641
Original issue here: #33774
@mavasani the rule behaved strange in all the `model.GetDeclaredSymbol(classDecl)` invocations - The method overload that takes a `CancellationToken` is located in an extension class, which I wasn't expecting to diagnose, but it was diagnosed and an incorrect fix was offered, because the object was being substituted by the class name.
> Apply CA2016 - Forward CancellationToken to methods that can take it

- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/DoNotInitializeUnnecessarily.cs
- src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/DoNotInitializeUnnecessarilyTests.cs
Or, rather, punt.  If fields are annotated with nullable attributes, it's possible you end up in a situation like:
```C#
[AllowNull] private T _value = default;
```
where for whatever reason (https://github.com/dotnet/roslyn/issues/37138), the compiler won't warn on the above, but will warn on:
```C#
[AllowNull] private T _value;
```
> Fix CA1805 handling of nullable attributes

- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/DoNotInitializeUnnecessarily.cs
- src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/DoNotInitializeUnnecessarilyTests.cs
Found this case when analyzing dotnet/runtime
> Don't warn CA1805 for default struct ctors with initializers

- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/DoNotInitializeUnnecessarily.cs
- src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/DoNotInitializeUnnecessarilyTests.cs
The rule is currently warning on fields like:
```C#
private static readonly object s_boxedDefaultInt = default(int);
```
but that's not actually setting the field to its default value.
> Fix CA1805 for boxed value types

- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/DoNotInitializeUnnecessarily.cs
- src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/DoNotInitializeUnnecessarilyTests.cs
One more case found from dotnet/runtime.  Code like:
```C#
private int? _value = 0;
```
shouldn't warn, but it currently does.
This is the last issue discovered in running the rule over dotnet/runtime:
https://github.com/dotnet/runtime/pull/38410
> Fix CA1805 assignment of default to nullable

- src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/ValidateArgumentsOfPublicMethodsTests.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/ParameterValidationAnalysis/ParameterValidationAnalysis.cs
Fixes #2919
Switch parameter validation analysis from pessimistic to optimistic - if we encounter a call that cannot be analyzed interprocedurally, we don't reset analysis data, which would nullify all the prior validations in the method.
> Fix CA1062 for untracked interprocedural calls

- azure-pipelines.yml
Tests are completing at 28-29 mins, and occasionally timing out at 30 mins.
> Increase test timeout

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Tasks/DoNotCreateTaskCompletionSourceWithWrongArguments.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Tasks/DoNotCreateTaskCompletionSourceWithWrongArgumentsTests.cs
IConversionOperation.Operand.Type can return null.
Fixes https://github.com/dotnet/roslyn-analyzers/issues/3811
cc: @jonasric, @madenwala, @mavasani
> Fix null reference exception in DoNotCreateTaskCompletionSourceWithWrongArguments

- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/MicrosoftCodeQualityAnalyzersResources.resx
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.cs.xlf
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.de.xlf
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.es.xlf
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.fr.xlf
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.it.xlf
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.ja.xlf
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.ko.xlf
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.pl.xlf
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.pt-BR.xlf
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.ru.xlf
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.tr.xlf
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.zh-Hans.xlf
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.zh-Hant.xlf
Refactor title and message to add a mention to public constructors to avoid confusion for end-users.
Fix #3632 
@mavasani I haven't renamed the class, is it mandatory to allow renaming the documentation header?
> Update CA1012: Reword title and message

- src/Utilities/Compiler/WellKnownTypeProvider.cs
Attempt to address #3870 without making things worse.
Idea was to avoid (number of tainted data source types + maybe sink / sanitizer types) * (number of referenced assemblies) = (number of calls to `IAssemblySymbol.GetTypeByMetadataName()`), by checking `IAssemblySymbol.TypeNames` first. But realizing `TypeNames` seemed to allocate more than unnecessary `IAssemblySymbol.GetTypeByMetadataName()` calls. So I'm settling on checking `NamespaceNames` instead.
What do you think of avoiding the `Compilation.GetTypeByMetadataName()` call entirely? That seemed to account for a bunch of allocations.
```
Callees of the TaintedDataSymbolMap constructor from the reported trace:
Name | Inc % | Inc
-- | -- | --
Microsoft.NetCore.Analyzers!Analyzer.Utilities.FlowAnalysis.Analysis.TaintedDataAnalysis.Tain …
```
> WellKnownTypeProvider optimizations attempt #A

- src/Microsoft.CodeAnalysis.Analyzers/Core/AnalyzerReleases.Unshipped.md
- src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/DiagnosticDescriptorCreationAnalyzer.cs
- src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/DiagnosticDescriptorCreationAnalyzer_ResourceStringsFormat.cs
- src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/Fixers/DefineDiagnosticDescriptorArgumentsCorrectlyFix.CustomFixAllProvider.cs
- src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/Fixers/DefineDiagnosticDescriptorArgumentsCorrectlyFix.cs
- src/Microsoft.CodeAnalysis.Analyzers/UnitTests/MetaAnalyzers/DiagnosticDescriptorCreationAnalyzerTests.cs
- src/Utilities/Compiler/Extensions/DiagnosticExtensions.cs
- src/Utilities/Compiler/Extensions/IOperationExtensions.cs
- src/Utilities/Compiler/WellKnownTypeNames.cs
Closes #3525
Adds a code fix for RS1031, RS1032 and RS1033
Additionally, if the resx file with analyzer resource strings is provided as an additional file to the analyzer, also validates the strings in the resx file.
> Add resource string analyzer/code fix for DiagnosticDescriptor arguments

- eng/Versions.props
- src/Microsoft.CodeAnalysis.Analyzers/Core/UpgradeMSBuildWorkspaceAnalyzer.cs
- src/Microsoft.CodeAnalysis.Analyzers/UnitTests/MetaAnalyzers/DiagnosticDescriptorCreationAnalyzerTests.cs
- src/Microsoft.CodeAnalysis.Analyzers/UnitTests/MetaAnalyzers/ReleaseTrackingAnalyzerTests.cs
- src/Microsoft.CodeAnalysis.Analyzers/UnitTests/MetaAnalyzers/StartActionWithNoRegisteredActionsRuleTests.cs
- src/Microsoft.CodeAnalysis.Analyzers/UnitTests/UpgradeMSBuildWorkspaceAnalyzerTests.cs
- src/Microsoft.CodeAnalysis.BannedApiAnalyzers/UnitTests/RestrictedInternalsVisibleToAnalyzerTests.cs
- src/Microsoft.CodeAnalysis.BannedApiAnalyzers/UnitTests/SymbolIsBannedAnalyzerTests.cs
- src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/DoNotDirectlyAwaitATaskTests.Fixer.cs
- src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/Maintainability/ReviewUnusedParametersTests.Fixer.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/DoNotPassLiteralsAsLocalizedParametersTests.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/SpecifyStringComparisonTests.cs
- src/PerformanceSensitiveAnalyzers/UnitTests/CSharpPerformanceCodeFixVerifier`2.cs
- src/PerformanceSensitiveAnalyzers/UnitTests/CallSiteImplicitAllocationAnalyzerTests.cs
- src/PerformanceSensitiveAnalyzers/UnitTests/VisualBasicPerformanceCodeFixVerifier`2.cs
- src/PublicApiAnalyzers/UnitTests/AnnotatePublicApiAnalyzerTests.cs
- src/PublicApiAnalyzers/UnitTests/DeclarePublicApiAnalyzerTests.cs
- src/PublicApiAnalyzers/UnitTests/NullableEnablePublicApiAnalyzerTests.cs
- src/Test.Utilities/CSharpSecurityCodeFixVerifier`2+Test.cs
- src/Test.Utilities/VisualBasicSecurityCodeFixVerifier`2+Test.cs
* Infer Fix All in Document iteration counts
* Infer generated code analysis configuration
* Use markup keys for locations in additional files when the same test uses markup keys for locations in source
> Update to Microsoft.CodeAnalysis.Testing 1.0.1-beta1.20374.2

- src/NetAnalyzers/Core/AnalyzerReleases.Unshipped.md
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Tasks/UseValueTasksCorrectly.cs
As requested by @stephentoub, this rule was initially merged with severity Hidden and we want it to be Info instead.
> CA2012 change severity from Hidden to Info

- src/Tools/GenerateGlobalAnalyzerConfigs/GenerateGlobalAnalyzerConfigs.csproj
- src/Tools/GenerateGlobalAnalyzerConfigs/Program.cs
- src/Utilities/Compiler/Analyzer.Utilities.projitems
- src/Utilities/Compiler/Options/AnalyzerOptionsExtensions.cs
- src/Utilities/Compiler/Options/MSBuildItemOptionNames.cs
- src/Utilities/Compiler/Options/MSBuildPropertyOptionNames.cs
Addresses analyzer part of https://github.com/dotnet/sdk/issues/12706
Adds support for platform compat check analyzer to be able to read `SupportedPlatform` items.
Analyzers should invoke `context.Options.GetMSBuildItemMetadataValues` extension method to query this option.
> Add support for threading MSBuild item metadata to analyzer options

- src/PublicApiAnalyzers/Core/Analyzers/DeclarePublicApiAnalyzer.cs
- src/PublicApiAnalyzers/PublicApiAnalyzers.Help.md
- src/PublicApiAnalyzers/UnitTests/DeclarePublicApiAnalyzerTests.cs
https://github.com/dotnet/roslyn-analyzers/pull/3916 added support to public API analyzer to treat missing API files as empty files and report diagnostics. This can be a breaking change for consumers where they relied on old semantics and installed this package or dependent package `Roslyn.Diagnostics.Analyzers` for the whole repo. This change adds an option to fall back the analyzer to old semantics.
> Add option for public API analyzer to bail out on missing API files

- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/UsePropertiesWhereAppropriate.cs
- src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/UsePropertiesWhereAppropriateTests.cs
> CA1024: Do not report on tasks return types

- src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/Fixers/CompareSymbolsCorrectlyFix.cs
- src/Microsoft.CodeAnalysis.Analyzers/UnitTests/MetaAnalyzers/CompareSymbolsCorrectlyTests.cs
Change so we always replace with `SymbolEqualityComparer.Equals` but include the instance variable if it was used 
for the initial equals call. 
Fixes #3975
> Make sure to add as arguments to equal call on comparer

- src/Tools/GenerateGlobalAnalyzerConfigs/Program.cs
Relates to https://github.com/dotnet/sdk/pull/12898. This allows us to avoid dealing with special values for AnalysisLevel such as 'none', 'preview', 'latest', etc.
Verified that we now correctly handle values such as `5`, `5.0`, `5.0.0.0` and so on to map to `AnalysisLevel_5.editorconfig` for warning wave.
> Use EffectiveAnalysisLevel instead of AnalysisLevel for warning wave mapping

- src/NetAnalyzers/CSharp/Microsoft.NetCore.Analyzers/Runtime/CSharpPreferStreamAsyncMemoryOverloads.Fixer.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/PreferStreamAsyncMemoryOverloads.Fixer.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/PreferStreamReadAsyncMemoryOverloadsTests.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/PreferStreamWriteAsyncMemoryOverloadsTests.cs
- src/NetAnalyzers/VisualBasic/Microsoft.NetCore.Analyzers/Runtime/BasicPreferStreamAsyncMemoryOverloads.Fixer.vb
- src/Utilities/Workspaces/SyntaxNodeExtensions.cs
Fixes https://github.com/dotnet/roslyn-analyzers/issues/3827
If rule CA1835 finds a diagnostic and applies a fix, but the `System` namespace has not yet been added (which contains the `AsMemory()` method for byte arrays), then the compilation can fail.
With this change, the `System` namespace should be added if the user has not added it yet.
> CA1835 fix - Automatically add using/imports System if not yet included

- src/NetAnalyzers/CSharp/Microsoft.NetCore.Analyzers/Runtime/CSharpPreferStreamAsyncMemoryOverloads.Fixer.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/PreferStreamAsyncMemoryOverloads.Fixer.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/PreferStreamReadAsyncMemoryOverloadsTests.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/PreferStreamWriteAsyncMemoryOverloadsTests.cs
- src/NetAnalyzers/VisualBasic/Microsoft.NetCore.Analyzers/Runtime/BasicPreferStreamAsyncMemoryOverloads.Fixer.vb
- src/Utilities/Workspaces/SyntaxNodeExtensions.cs
This is a backport of https://github.com/dotnet/roslyn-analyzers/pull/3931
If rule CA1835 finds a diagnostic and applies a fix, but the System namespace has not yet been added (which contains the `AsMemory()` method for byte arrays), then the compilation can fail.
With this change, the `System` namespace should be automatically added when the user applies the fix, if the namespace has not been added it yet.
> [RC1] CA1835 fix - Automatically add using/imports System if not yet included

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/SpecifyStringComparison.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/SpecifyStringComparisonTests.cs
Fixes #2581
When we know that a comparison is between a string type receiver and a non-string type parameter OR that the method is not a string comparison method, do not report CA1307.
> Do not report CA1307 for known non-string comparisons

- src/NetAnalyzers/Core/AnalyzerReleases.Shipped.md
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/MicrosoftNetCoreAnalyzersResources.resx
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/SpecifyStringComparison.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.cs.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.de.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.es.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.fr.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.it.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ja.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ko.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.pl.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.pt-BR.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ru.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.tr.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.zh-Hans.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.zh-Hant.xlf
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/SpecifyStringComparisonTests.cs
- src/Utilities/Compiler/DiagnosticCategoryAndIdRanges.txt
Fixes #2581, again!
1. `CA1310`: Correctness rule that only flags string compare methods that are known to use culture specific string comparison by default
2. `CA1307`: Maintainability/Readability rule that flags the remainder methods that have an overload with an additional StringComparison parameter at the end. This rule does not care about the default string comparison used by the API.
> Separate out CA1307 into two rules

- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/Maintainability/AvoidUninstantiatedInternalClasses.cs
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/Maintainability/ReviewUnusedParameters.cs
- src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/IdentifiersShouldNotContainTypeNamesTests.cs
- src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/Maintainability/AvoidUninstantiatedInternalClassesTests.cs
- src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/Maintainability/ReviewUnusedParametersTests.cs
- src/Utilities/Compiler/Extensions/IMethodSymbolExtensions.cs
- src/Utilities/Compiler/Extensions/INamedTypeSymbolExtensions.cs
- src/Utilities/Compiler/Options/AnalyzerOptionsExtensions.cs
Fixes #4052
Fixes #4068
C# 9 language feature: https://devblogs.microsoft.com/dotnet/welcome-to-c-9-0/#top-level-programs
This change fixes an AD0001 and couple of false positives from CA analyzers for top level programs
> Few analyzer bug fixes in presence of top level programs

- .github/ISSUE_TEMPLATE/bug-report.md
Also moved the `Analyzer` section near the top
> Update bug-report.md to mention .NET5 SDK as the primary source for analyzers

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/DoNotUseStackallocInLoops.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/DoNotUseStackallocInLoopsTests.cs
> CA2014: Don't warn if a local function containing stackalloc is inside a loop

- docs/Analyzer Configuration.md
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzer.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzerTests.GuardedCallsTests.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzerTests.cs
- src/Utilities/Compiler/Options/EditorConfigOptionNames.cs
Fixes https://github.com/dotnet/roslyn-analyzers/issues/4091
> By default platform compat analyzer should be disabled for TFM < 5.0

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Security/UseContainerLevelAccessPolicy.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Security/UseContainerLevelAccessPolicyTests.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Security/UseSharedAccessProtocolHttpsOnlyTests.cs
As per https://github.com/dotnet/roslyn-analyzers/pull/4109#discussion_r481397796
> CA5377 shouldn't warn when unable to get control flow graph

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzer.OperationVisitor.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzerTests.GuardedCallsTests.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/GlobalFlowStateAnalysis/GlobalFlowStateAnalysis.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/GlobalFlowStateAnalysis/GlobalFlowStateDataFlowOperationVisitor.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowAnalysisResult.cs
Fixes #4182
Verified that the added unit test causes an infinite loop in flow analysis prior to this fix.
Analyzers executing global flow analysis need the global flow state values at each operation in the flow graph. Currently, we store these global values into the operation state map while performing analysis, but this seems to lead to incorrect analysis results. As these global analysis values per operation are not required by the flow analysis itself, we now store these values in separate global value map during analysis. These values will be stored onto the final result after analysis, so the analyzers will see only global flow state values in the result.
> Store the global flow values per operation as a post-step

- docs/Analyzer Configuration.md
Fix #3242
The following documentation web pages need to be updated accordingly
> Update documentation to mention use of the wildcard symbol

- .editorconfig
- eng/Versions.props
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/TypesThatOwnDisposableFieldsShouldBeDisposable.cs
- src/NetAnalyzers/VisualBasic/Microsoft.NetCore.Analyzers/Performance/BasicDoNotUseCountWhenAnyCanBeUsedFixer.vb
- src/NetAnalyzers/VisualBasic/Microsoft.NetCore.Analyzers/Performance/BasicUsePropertyInsteadOfCountMethodWhenAvailable.Fixer.vb
- src/NetAnalyzers/VisualBasic/Microsoft.NetCore.Analyzers/Performance/BasicUsePropertyInsteadOfCountMethodWhenAvailable.vb
- src/Utilities/Compiler/Extensions/ReportDiagnosticExtensions.cs
- src/Utilities/Compiler/WordParser.cs
NOTE: Developers will require to be on VS2019 16.8 Preview3 or later after this change
> [2.9.x] Move to latest CodeStyle package and fix violations

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzer.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzerTests.GuardedCallsTests.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzerTests.cs
Fixes https://github.com/dotnet/roslyn-analyzers/issues/4168
Besides fixing the inconsistency issue this PR is updating out attributes handling logic:
**Before**: We were collecting all attributes for the invoked member and its containing types, after that were determining attributes inconsistency along with suppression from call site attributes when incosistency occurs bailout to avoid false positives. Also in case lowest version of supported and unsupported attributes are equal that counted as Deny list
**Now**: We are checking attributes consistency for each level, starting from the Parent, for merging each child member's attributes follow the rule suggested by @terrajobst: `child annotations can narrow support, but they cannot widen it`, attributes not respecting the rule are ignored. …
> Fix inconsistency bug, child cannot widen as support, can narrow

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzer.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzerTests.GuardedCallsTests.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/GlobalFlowStateAnalysis/GlobalFlowStateAnalysis.cs
Fixes #4209
Our flow analyses take a boolean parameter `pessimisticAnalysis` that determines the state change to be done when we encounter invocation to an unknown lambda target. Currently, the analysis was pessimistically reseting the state to unknown, but now we optimistically assume such a call does not change current flow analysis state.
> Switch platform compat analyzer to do an optimistic flow analysis

- NuGet.config
These were the only occurances of 'myget' in this repo.
> Remove MyGet feeds now that dependencies are published to AzDO

- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/CancellationTokenParametersMustComeLast.cs
- src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/CancellationTokenParametersMustComeLastTests.cs
- src/Utilities/Compiler/WellKnownTypeNames.cs
> CA1068: Allow caller attributes to come after cancellation token

- src/Utilities/Compiler/Extensions/IMethodSymbolExtensions.cs
Related to #4253 (keeping the issue open to track using the compiler API)
> Fix unspeakable main name

- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzerTests.GuardedCallsTests.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzerTests.cs
For fixing test failures for localization PR https://github.com/dotnet/roslyn-analyzers/pull/4262#issuecomment-702287401
> Use WithArguments instead of WithMessage in unit test

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Tasks/UseValueTasksCorrectly.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Tasks/UseValueTaskCorrectlyTests.cs
Fixes https://github.com/dotnet/roslyn-analyzers/issues/4271
cc: @NickCraver
> Ignore identity conversions in UseValueTasksCorrectly

- src/NetAnalyzers/CSharp/Microsoft.NetCore.Analyzers/Runtime/CSharpPreferStreamAsyncMemoryOverloads.Fixer.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/PreferStreamAsyncMemoryOverloads.Fixer.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/PreferStreamAsyncMemoryOverloadsTestBase.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/PreferStreamReadAsyncMemoryOverloadsTests.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/PreferStreamWriteAsyncMemoryOverloadsTests.cs
- src/NetAnalyzers/VisualBasic/Microsoft.NetCore.Analyzers/Runtime/BasicPreferStreamAsyncMemoryOverloads.Fixer.vb
Fixes https://github.com/dotnet/roslyn-analyzers/issues/4235
For invocations of ReadAsync/WriteAsync that consider the full buffer (from `0` to `buffer.Length`):
```cs
await stream.ReadAsync(buffer, 0, buffer.Length);
```
Instead of suggesting this:
```cs
await stream.ReadAsync(buffer.AsMemory(0, buffer.Length));
```
We now want to suggest this:
```cs
await stream.ReadAsync(buffer);
```
> Fix to improve code fixer heuristic employed by CA1835

- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/RethrowToPreserveStackDetails.cs
- src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/RethrowToPreserveStackDetailsTests.cs
> Fix bug when exception declared in filter is thrown

- src/PublicApiAnalyzers/Core/Analyzers/DeclarePublicApiAnalyzer.Impl.cs
- src/PublicApiAnalyzers/UnitTests/AnnotatePublicApiAnalyzerTests.cs
- src/PublicApiAnalyzers/UnitTests/DeclarePublicApiAnalyzerTests.cs
Fixes https://github.com/dotnet/roslyn-analyzers/issues/4040
> Fix oblivious analysis of type parameters

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzer.OperationVisitor.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzer.Value.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzer.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzerTests.GuardedCallsTests.cs
As part of https://github.com/dotnet/runtime/issues/42335 we need to ensure that each of runtime projects can produce warnings/errors from the platform compat analyzer during a normal build. There are several projects not having access to the System.Runtime.InteropServices.RuntimeInformation, System.Runtime.InteropServices.OSPlatofrm which are used as one of the guard methods for the analzyer. Normally we bail out when any of the types used for the analysis is not loaded/found, but the types mentioned are not essential for the analysis we want to continue the analysis in that case and get warnings if there is any.
> Continue analysis even RuntimeInformation, OSPlatofrm types not loaded

- src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/StaticHolderTypeTests.cs
The behavior is currently correct as records can't be marked static. This is just to prevent any later refactoring from introducing a bug.
> Add test for records in static holder analyzer

- src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/DiagnosticDescriptorCreationAnalyzer_ReleaseTracking.cs
Follow up to #4291
Contributes to #4317
The issue #4317 will be fully fixed after:
1. This fix is released.
2. The new version is used in the repository.
3. Confirm that release tracking analyzer produce a warning for outdated documentation link.
> Update docs link in release tracking analyzer

- eng/GenerateAnalyzerNuspec.targets
The code wasn't previously working as expected. `GenerateAnalyzerRulesMissingDocumentationFile` was already true in CI builds. Now with the CI validation introduced recently, we even don't need it to be false for CI at all.
> Update comment for clarity

- eng/Versions.props
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzerTests.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Performance/UseAsSpanInsteadOfRangeIndexerTests.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/DoNotUseReferenceEqualsWithValueTypesTests.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/ForwardCancellationTokenToInvocationsTests.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/PreferStreamAsyncMemoryOverloadsTestBase.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/PreferStringContainsOverIndexOfTests.cs
- src/Roslyn.Diagnostics.Analyzers/CSharp/PreferNullLiteral.cs
- src/Roslyn.Diagnostics.Analyzers/UnitTests/CreateTestAccessorTests.cs
* Microsoft.CodeAnalysis.Testing was updated since https://github.com/dotnet/roslyn-sdk/pull/644 is now required
* Added tests for records in CreateTestAccessor (currently skipped since dotnet/roslyn#48096 is not available in 16.8)
> Update to Roslyn 3.8.0-4.final for testing

- src/Microsoft.CodeAnalysis.FxCopAnalyzers/Microsoft.CodeAnalysis.FxCopAnalyzers.sarif
- src/Microsoft.CodeQuality.Analyzers/Microsoft.CodeQuality.Analyzers.sarif
- src/Microsoft.NetCore.Analyzers/Microsoft.NetCore.Analyzers.sarif
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/Maintainability/AvoidUnusedPrivateFields.cs
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/Maintainability/ReviewUnusedParameters.cs
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStatic.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/DisposableFieldsShouldBeDisposed.cs
- src/NetAnalyzers/Microsoft.CodeAnalysis.NetAnalyzers.sarif
> Remove 'isReportedAtCompilationEnd: true' for compilation end analyzers ported to symbol start/end analyzers

- src/Directory.Build.targets
Same change that occurred in https://github.com/dotnet/roslyn/pull/46306/files
> Fix _RunOnCore property when running on .NET 5.0

- src/Roslyn.Diagnostics.Analyzers/Core/DoNotCopyValue.cs
- src/Roslyn.Diagnostics.Analyzers/UnitTests/DoNotCopyValueTests.cs
Addresses issues found in the implementation of https://github.com/dotnet/roslyn/pull/48896.
> Initial support for IForEachLoopOperation in DoNotCopyValue

- src/Roslyn.Diagnostics.Analyzers/CSharp/CSharpDoNotCopyValue.cs
- src/Roslyn.Diagnostics.Analyzers/Core/AbstractDoNotCopyValue.cs
- src/Roslyn.Diagnostics.Analyzers/Core/DoNotCopyValue.cs
- src/Roslyn.Diagnostics.Analyzers/Roslyn.Diagnostics.Analyzers.sarif
- src/Roslyn.Diagnostics.Analyzers/UnitTests/DoNotCopyValueTests.cs
- src/Roslyn.Diagnostics.Analyzers/VisualBasic/VisualBasicDoNotCopyValue.vb
> Support foreach over parameters in DoNotCopyValue

- src/Microsoft.CodeAnalysis.BannedApiAnalyzers/Core/RestrictedInternalsVisibleToAnalyzer.cs
Updating Microsoft.CodeAnalysis to 3.7.0 (which has more nullable annotations) revealed a potential problem, which is now fixed with a null check.
Fixes #4366
> Add null check for AttributeConstructor

- src/PerformanceSensitiveAnalyzers/CSharp/Analyzers/CallSiteImplicitAllocationAnalyzer.cs
- src/PerformanceSensitiveAnalyzers/UnitTests/CallSiteImplicitAllocationAnalyzerTests.cs
The bug stated in https://github.com/microsoft/RoslynClrHeapAllocationAnalyzer/issues/84 existed in the copy of the analyzer in this repository too.
I couldn't fix it without refactoring. Relying on syntax here is very error-prone. So I switched to getting `IOperation`s. However, the analyzer is still a syntax one its base class is so.
> Fix bugs in CallSiteImplicitAllocationAnalyzer

- README.md
- VERSIONING.md
Release: [5.0.0](https://github.com/dotnet/roslyn-analyzers/releases/tag/5.0.0)
> Update repo docs for released Microsoft.CodeAnalysis.NetAnalyzers 5.0.0 NuGet package

- eng/GenerateAnalyzerNuspec.targets
- nuget/Microsoft.CodeQuality.Analyzers/Microsoft.CodeQuality.Analyzers.Package.csproj
- src/Tools/GenerateAnalyzerNuspec/GenerateAnalyzerNuspec.csproj
- src/Tools/GenerateAnalyzerNuspec/Program.cs
There's no csi.exe in the .NET 5 (or .NET Core) SDK.  So move away from a csx script to a full-blown tool written in C#.
For ease of review, I have kept the original tool code unmodified (not even indentation has been fixed). To work around build warnings/errors, disable the warnings.
Also fix the case of path to the dll in the local nuget cache. It doesn't matter on Windows, but most file systems on Linux are case-sensitive.
This is a followup to https://github.com/dotnet/roslyn-analyzers/pull/4419
> Fix ./build.sh --pack to work on Linux

- eng/Analyzers_NonShippingRules.ruleset
- src/Utilities.UnitTests/Options/SymbolNamesWithValueOptionTests.cs
- src/Utilities/Compiler/Options/SymbolNamesWithValueOption.cs
For default **.editorconfig** scenarios, `SymbolNamesWithValueOption<TValue>.Empty` is used. This has an empty set of wildcard match names, but still caches symbols. Since the `Empty` value is static, this means the process keeps a cached copy of _all_ symbols for which `Contains` is called until the process runs out of memory.
This issue is also the reason why other `ConditionalWeakTable<TKey, TValue>` instances were never releasing values, since the `Compilation` keys were retaining strong roots through this path.
Fixes [AB#1242125](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1242125)
> Fix fast-path cache

- eng/GenerateAnalyzerNuspec.targets
PR #4442 has reports where the build fails because the project is being rebuilt multiple time with highly parallel builds and that causes file conflicts.
I am not sure why that's happening, to be honest. Or at least why it's only happening for GenerateAnalyzerNuspec. That project uses the `MSBuild` + `Exec` pattern:
https://github.com/dotnet/roslyn-analyzers/blob/37eba3a5aa2d706745f37692ad7ba7cb0a66a115/eng/GenerateAnalyzerNuspec.targets#L140-L144
That's the same pattern used elsewhere in the same file:
https://github.com/dotnet/roslyn-analyzers/blob/37eba3a5aa2d706745f37692ad7ba7cb0a66a115/eng/GenerateAnalyzerNuspec.targets#L105-L109
Still, this PR tries to reduce how many times that project is rebuilt, which should (hopefully) reduce the frequency of the error, if not eliminate it.
Any …
> Reduce rebuilding GenerateAnalyzerNuspec.csproj

- src/Tools/GenerateAnalyzerNuspec/GenerateAnalyzerNuspec.csproj
- src/Tools/GenerateDocumentationAndConfigFiles/GenerateDocumentationAndConfigFiles.csproj
- src/Tools/GenerateGlobalAnalyzerConfigs/GenerateGlobalAnalyzerConfigs.csproj
The tool projects are building the apphost, but we always invoke the tool through `dotnet tool.dll` instead of the apphost (`tool`). Removing the apphost should have no effects.
Keeping the AppHosts introduces additional prebuilts for source build and it would be nice to not have to maintain this patch in source-build. See https://github.com/dotnet/source-build/issues/1905 for more details.
> Remove AppHosts from tools

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzer.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/MicrosoftNetCoreAnalyzersResources.resx
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.cs.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.de.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.es.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.fr.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.it.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ja.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ko.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.pl.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.pt-BR.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ru.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.tr.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.zh-Hans.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.zh-Hant.xlf
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzerTests.GuardedCallsTests.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzerTests.cs
Fixes https://github.com/dotnet/roslyn-analyzers/issues/4021
This PR only has messaging updates, no any functional change or bugfix
The messages update into the following structure:
List | Messaging structure
-- | -- 
Allow list | '{0}' is only supported on: {1}. This call site is reachable on all platforms. 
Allow list | '{0}' is only supported on: {1}. This call site is unreachable on: {2}.
Allow list | '{0}' is only supported on: {1}. This call site is reachable on: {2}. 
Deny list | '{0}' is unsupported on: {1}, This call site is reachable on all platforms.
Deny list | '{0}' is unsupported on: {1}, This call site is reachable on: {2}.
Deny list | '{0}' is supported on: {1}, This call site is reachable on all platforms.
Deny list | '{0}' is supported on: {1}, This call site is …
> Improve messaging for Platform Compat Analyzer

- eng/Versions.props
This way, when we upload this package to nuget folks will be able to reference it explicitly
> bumping the version number to match 5.0.2 release

- src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/CompareSymbolsCorrectlyAnalyzer.cs
- src/Microsoft.CodeAnalysis.Analyzers/UnitTests/MetaAnalyzers/CompareSymbolsCorrectlyTests.cs
> Fix RS1024: Do not report when SymbolEqualityComparer.Default is passed

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzer.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzerTests.GuardedCallsTests.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzerTests.cs
Fixes https://github.com/dotnet/roslyn-analyzers/issues/4061
Remove Mock class, attributes used for testing Platform Compatibility Analyzer
> Remove mock APIs used for PC analyzer as now we can use new APIs in 5.0

- eng/Versions.props
- src/NetAnalyzers/Microsoft.CodeAnalysis.NetAnalyzers.sarif
This PR enables seamless migration from `3.x` FxCop analyzers packages published out of master to a stable NetAnalyzers package by following steps at https://docs.microsoft.com/visualstudio/code-quality/migrate-from-fxcop-analyzers-to-net-analyzers
Will revert this PR as soon as we get a signed build candidate for publishing 5.0.1 package for latest bug fixes. We need to finalize our long term story on which branch do we target bug fixes to existing analyzers versus add new .NET vNext analyzers.
> Update Versions.props to enable releasing NetAnalyzers 5.0.1 package

- src/Tools/GenerateGlobalAnalyzerConfigs/Program.cs
This prevents clashes between property values when executed in context of different analyzer packages. Found this issue while dogfooding the NetAnalyzers package, when also referencing another analyzer package produced from this repo.
> Use package name suffix for property names used inside `AddGlobalAnalyzerConfigForPackage` target

- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/MicrosoftCodeQualityAnalyzersResources.resx
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.cs.xlf
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.de.xlf
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.es.xlf
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.fr.xlf
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.it.xlf
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.ja.xlf
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.ko.xlf
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.pl.xlf
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.pt-BR.xlf
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.ru.xlf
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.tr.xlf
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.zh-Hans.xlf
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.zh-Hant.xlf
- An article is needed since the word 'method' is there
- Flows better and matches other messages when it's just a name and not quoted as code
I used VS Code's replace-in-all-files across the repo.
> Fix wording of one of the CA2231 messages

- eng/Versions.props
- src/Microsoft.CodeAnalysis.FxCopAnalyzers/Microsoft.CodeAnalysis.FxCopAnalyzers.sarif
- src/Microsoft.CodeQuality.Analyzers/Microsoft.CodeQuality.Analyzers.sarif
- src/NetAnalyzers/CSharp/Microsoft.CodeQuality.Analyzers/Maintainability/CSharpReviewUnusedParametersAnalyzer.cs
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/Maintainability/ReviewUnusedParameters.cs
- src/NetAnalyzers/Microsoft.CodeAnalysis.NetAnalyzers.sarif
- src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/Maintainability/ReviewUnusedParametersTests.Fixer.cs
- src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/Maintainability/ReviewUnusedParametersTests.cs
- src/NetAnalyzers/VisualBasic/Microsoft.CodeQuality.Analyzers/Maintainability/BasicReviewUnusedParametersAnalyzer.vb
Replace #4476 and fix #4462 and fix #4397
> Fix CA1801 false positive with positional records primary ctor

- docs/Analyzer Configuration.md
Update analyzer configuration doc to make it explicit that all rules implementing the `excluded_symbol_names` option automatically implements the `excluded_type_names_with_derived_types`.
> Update configuration to reflect actual behavior

- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Security/ReviewCodeForSqlInjectionVulnerabilitiesTests.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/TaintedDataAnalysis/TaintedDataAnalysis.TaintedDataOperationVisitor.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/TaintedDataAnalysis/WebInputSources.cs
> Find tainted data parameter SyntaxNodes more robustly, and don't treat ASP.NET MVC Controller property setter parameters as tainted

- .github/PULL_REQUEST_TEMPLATE.md
> Update PR template to reflect the deletion of FxCopAnalyzers.sln

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/MicrosoftNetCoreAnalyzersResources.resx
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.cs.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.de.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.es.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.fr.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.it.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ja.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ko.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.pl.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.pt-BR.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ru.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.tr.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.zh-Hans.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.zh-Hant.xlf
Improving the message of PreferIsEmptyOverCountMessage (CA1836):
old  : Prefer 'IsEmpty' over 'Count' to determine whether the object contains or not any items
new: Prefer 'IsEmpty' over 'Count' to determine whether the object is empty
Also slightly improved the german & french translations.
> Fixing grammer of & improving CA1836 messages.

- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/IdentifiersShouldHaveCorrectSuffix.cs
- src/Utilities.UnitTests/Options/SymbolNamesWithValueOptionTests.cs
- src/Utilities/Compiler/Analyzer.Utilities.projitems
- src/Utilities/Compiler/Extensions/KeyValuePairExtensions.cs
- src/Utilities/Compiler/Options/AbstractCategorizedAnalyzerConfigOptions.cs
- src/Utilities/Compiler/Options/AggregateCategorizedAnalyzerConfigOptions.cs
- src/Utilities/Compiler/Options/AnalyzerOptionsExtensions.cs
- src/Utilities/Compiler/Options/ICategorizedAnalyzerConfigOptions.cs
- src/Utilities/Compiler/Options/SymbolNamesWithValueOption.cs
* Support global options in Roslyn 3.7+
* Fix nullability for `SymbolNamesWithValueOption`
Fixes #4350
> Fix nullability for SymbolNamesWithValueOption

- src/Tools/GenerateDocumentationAndConfigFiles/Program.cs
Implements category specific AnalysisLevel properties as per https://github.com/dotnet/roslyn/issues/49250#issuecomment-742901055.
Users would now be able to specify the core AnalysisLevel and override category specific AnalysisLevel for each category.
```xml
<AnalysisLevel>5-minimum</AnalysisLevel>
<AnalysisLevelSecurity>latest-all</AnalysisLevelSecurity>
<AnalysisLevelPerformance>preview-recommended</AnalysisLevelPerformance>
<AnalysisLevelGlobalization>5-none</AnalysisLevelGlobalization>
```
1. The post-build tool now generates category-specific global configs for each supported analysis mode
2. The tool also generates category-specific `AddGlobalAnalyzerConfigForPackage` targets so that if user overrides a category-specific AnalysisLevel property, we pass in both the configs
3. …
> Add support for category-specific AnalysisLevel properties

- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/SealMethodsThatSatisfyPrivateInterfaces.cs
- src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/SealMethodsThatSatisfyPrivateInterfacesTests.cs
Fix #4566
Feel free to drop 1st commit if you don't want it to be included in this fix.
> Fix CA2119 to report only on correct interface members

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzer.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzerTests.GuardedCallsTests.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzerTests.cs
- src/Utilities/Compiler/Extensions/OperationBlockAnalysisContextExtension.cs
- src/Utilities/Compiler/WellKnownTypeNames.cs
Fixes https://github.com/dotnet/roslyn-analyzers/issues/4545. Related to https://github.com/dotnet/roslyn-analyzers/pull/4576 raising PR for 5.0.2
@jmarolf this PR is not introducing any new warning, instead reduces false positives, so we decided to merge it to 5.0.2 
CC @jeffhandley @mavasani 
We should ignore diagnostics in throw statements as they are not platform specific operation and causing false positives, i made sure it ignores exception messages for a block not only just throwing, but having some other statements too, i think this will be more useful for conditional throwing like:
```csharp
[SupportedOSPlatform("browser")]
public static class SR
{
public static string Message {get; set;}
public static void M1() { }
}
public class Test
{
void …
```
> CA1416 Do not warn for OS dependent messages for creating NotSupportedExceptions

- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzerTests.GuardedCallsTests.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzerTests.cs
Use localization strings for diagnostic arguments instead of hard coded English
> Fix localization failure

- azure-pipelines.yml
- eng/GenerateAnalyzerNuspec.targets
- restore.sh
- src/Microsoft.CodeAnalysis.Analyzers/UnitTests/MetaAnalyzers/DiagnosticDescriptorCreationAnalyzerTests.cs
- src/Microsoft.CodeAnalysis.Analyzers/UnitTests/MetaAnalyzers/ReleaseTrackingAnalyzerTests.cs
- src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/AvoidEmptyInterfacesTests.cs
- src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/IdentifiersShouldNotMatchKeywordsTypeRuleTests.cs
- src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/Maintainability/ReviewUnusedParametersTests.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/DoNotPassLiteralsAsLocalizedParametersTests.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Security/UseDefaultDllImportSearchPathsAttributeTests.cs
- src/PublicApiAnalyzers/UnitTests/DeclarePublicApiAnalyzerTests.cs
- src/Roslyn.Diagnostics.Analyzers/UnitTests/ImportingConstructorShouldBeObsoleteTests.cs
- src/Test.Utilities/CSharpCodeFixVerifier`2+Test.cs
- src/Test.Utilities/StringExtensions.cs
- src/Test.Utilities/VisualBasicCodeFixVerifier`2+Test.cs
- src/Test.Utilities/WindowsOnlyFactAttribute.cs
- src/Test.Utilities/WindowsOnlyTheoryAttribute.cs
- test.sh
> add linux CI

- src/Microsoft.CodeAnalysis.Analyzers/UnitTests/MetaAnalyzers/DiagnosticDescriptorCreationAnalyzerTests.cs
These tests are failing intermittently on newly added Unix queues.
#4586 tracks fixing and enabling these tests on these queues.
> Add WindowsOnlyFact to RS1031, RS1032 and RS1033 tests

- eng/Versions.props
- src/NetAnalyzers/Microsoft.CodeAnalysis.NetAnalyzers.sarif
Bump NetAnalyzers version to 5.0.3 as the version released with 5.0.2 .NET SDK is shipping from release/5.0.2xxx branch which has older analyzers as compared to master branch
> Bump NetAnalyzers version to 5.0.3

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/SpecifyStringComparison.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/TestForEmptyStringsUsingStringLength.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/TestForEmptyStringsUsingStringLengthTests.cs
- src/Utilities/Compiler/Extensions/IOperationExtensions.cs
> Update CA1820 to not report on expression trees

- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/UsePropertiesWhereAppropriate.cs
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStatic.cs
- src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/UsePropertiesWhereAppropriateTests.cs
- src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStaticTests.cs
- src/Utilities/Compiler/Extensions/IMethodSymbolExtensions.cs
- src/Utilities/Compiler/Extensions/IPropertySymbolExtensions.cs
- src/Utilities/Compiler/WellKnownTypeNames.cs
Fix #4623
There is a first commit meant to ensure all code related to skipping the analysis is contained in the `ShouldAnalyze` method instead of being in multiple place. I suggest to review it first.
> Do not report on awaitable-awaiter patterns

- azure-pipelines.yml
Replaces #4666
I'm not sure why the fix in #4666 didn't work. But that's another way that seems to work.
> Workaround warning in Markdownlint job

- src/PublicApiAnalyzers/UnitTests/DeclarePublicApiAnalyzerTests.cs
Adding a couple of tests to illustrate a compiler issue that's affecting the publicAPI analyzer (complaining about oblivious in code that is seemingly fully nullable-enabled).
Taggging @mavasani for review.
> Illustrate unexpected oblivious on implicit containing type in public API

- src/NetAnalyzers/CSharp/Microsoft.NetCore.Analyzers/Runtime/CSharpTestForEmptyStringsUsingStringLength.Fixer.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/TestForEmptyStringsUsingStringLength.Fixer.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/TestForEmptyStringsUsingStringLengthTests.Fixer.cs
- src/NetAnalyzers/VisualBasic/Microsoft.NetCore.Analyzers/Runtime/BasicTestForEmptyStringsUsingStringLength.Fixer.vb
Fixes #4537
Added new code path to emit a code fix for CA 1820 when then code is in the following form in addition to a binary expression:
```
String s = "Hello";
if (s.Equals(string.Empty))
{
// do something
}
```
> Adding code fix for CA1820 when it is a member invocation

- src/NetAnalyzers/CSharp/Microsoft.NetCore.Analyzers/Runtime/CSharpPreferStreamAsyncMemoryOverloads.Fixer.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/PreferStreamAsyncMemoryOverloads.Fixer.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/PreferStreamAsyncMemoryOverloadsTestBase.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/PreferStreamReadAsyncMemoryOverloadsTests.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/PreferStreamWriteAsyncMemoryOverloadsTests.cs
- src/NetAnalyzers/VisualBasic/Microsoft.NetCore.Analyzers/Runtime/BasicPreferStreamAsyncMemoryOverloads.Fixer.vb
Fixes https://github.com/dotnet/roslyn-analyzers/issues/3826
> Ensure CA1835 preserves nullability

- src/Tools/GenerateDocumentationAndConfigFiles/Program.cs
Fixes #4715
@mavasani I'm not sure if changes are needed for other `RulesetKind`s. For example, `CategoryEnabled`, should it enable all the category as warnings? or enable the category with the default severity?
> Make all rules warning for RulesetKind.AllEnabled

- src/NetAnalyzers/CSharp/Microsoft.CodeQuality.Analyzers/Documentation/CSharpAvoidUsingCrefTagsWithAPrefix.Fixer.cs
- src/NetAnalyzers/CSharp/Microsoft.CodeQuality.Analyzers/Documentation/CSharpAvoidUsingCrefTagsWithAPrefix.cs
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/Documentation/AvoidUsingCrefTagsWithAPrefix.Fixer.cs
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/Documentation/AvoidUsingCrefTagsWithAPrefix.cs
- src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/Documentation/AvoidUsingCrefTagsWithAPrefixTests.cs
- src/NetAnalyzers/VisualBasic/Microsoft.CodeQuality.Analyzers/Documentation/BasicAvoidUsingCrefTagsWithAPrefix.Fixer.vb
- src/NetAnalyzers/VisualBasic/Microsoft.CodeQuality.Analyzers/Documentation/BasicAvoidUsingCrefTagsWithAPrefix.vb
https://github.com/dotnet/roslyn-analyzers/blob/4bbb229fda9e3e2bdf9389350ade042237075cec/src/Roslyn.Diagnostics.Analyzers/Core/RoslynDiagnosticIds.cs#L16
Not of much value, but did it anyway as a small cleanup.
> Fix outdated rule id in comments

- src/Test.Utilities/CSharpCodeFixVerifier`2+Test.cs
> Remove workaround for fixed issue

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzer.Data.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzer.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzerTests.cs
- src/Utilities/Compiler/SmallDictionary.cs
Related to https://github.com/dotnet/runtime/issues/44231
[By design](https://github.com/dotnet/designs/blob/main/accepted/2020/platform-checks/platform-checks.md#platform-context), SDK adds SuuportedOSPlatform attribute with the targeted OS platform from TFMs, which works well for normal condition but for multitargeted env like `runtime` repo it is causing warnings mentioned in  https://github.com/dotnet/runtime/issues/44231 and requiring clear separation of platform-specific APIs which forcing developers to duplicate their code to conform to the strict supported-platform name rules. After evaluating of possible solution and several discussions we have decided to resolve it at the analyzer level. The TFM target attributes are causing inconsistent scenarios in the call site and the real …
> CA1416 handle call-site empty sets causing warnings when TFM attributes applied

- azure-pipelines.yml
Noticed this error while looking for platform-specific tests in Azure:
> Fix 'testRunTitle' and 'Artifact Name' for Ubuntu jobs

- src/PublicApiAnalyzers/Core/Analyzers/DeclarePublicApiAnalyzer.Impl.cs
- src/PublicApiAnalyzers/UnitTests/DeclarePublicApiAnalyzerTests.cs
Fixes https://github.com/dotnet/roslyn-analyzers/issues/4766.
~~I currently excluded obsolete overloads from RS0027 analysis only. Let me know if the same should be done for RS0026.~~ (Done.)
> Don't report RS0027 if overload is obsolete

- docs/NetCore_GettingStarted.md
Per [this discussion](https://github.com/dotnet/runtime/pull/47868#issuecomment-773635368), it could be helpful to call out that we don't expect all info-level messages be resolved as part of the Definition of Done for libraries analyzers.
> Indicate that info-level messages can remain

- src/Roslyn.Diagnostics.Analyzers/CSharp/CSharpDoNotCopyValue.cs
- src/Roslyn.Diagnostics.Analyzers/Core/AbstractDoNotCopyValue.cs
- src/Roslyn.Diagnostics.Analyzers/Core/RoslynDiagnosticsAnalyzersResources.resx
- src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.cs.xlf
- src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.de.xlf
- src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.es.xlf
- src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.fr.xlf
- src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.it.xlf
- src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.ja.xlf
- src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.ko.xlf
- src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.pl.xlf
- src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.pt-BR.xlf
- src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.ru.xlf
- src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.tr.xlf
- src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.zh-Hans.xlf
- src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.zh-Hant.xlf
- src/Roslyn.Diagnostics.Analyzers/Roslyn.Diagnostics.Analyzers.md
- src/Roslyn.Diagnostics.Analyzers/Roslyn.Diagnostics.Analyzers.sarif
- src/Roslyn.Diagnostics.Analyzers/UnitTests/DoNotCopyValueTests.cs
- src/Roslyn.Diagnostics.Analyzers/VisualBasic/VisualBasicDoNotCopyValue.vb
* Do not allow a non-copyable field to be defined in a copyable type
* Do not allow a non-copyable auto-property to be defined (the getter in this case always copies the backing field value)
> Non-copyable analysis for fields and auto-properties

- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzerTests.GuardedCallsTests.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzerTests.cs
Cherry-picked commit merged into master for fixing localization errors in master https://github.com/dotnet/roslyn-analyzers/commit/46c1e522b981b5c1f46334e116e31477949ea173 CC @Youssef1313
To fix test failures in https://github.com/dotnet/roslyn-analyzers/pull/4805
Original PR https://github.com/dotnet/roslyn-analyzers/pull/4583
> Fix localization failure (#4583)

- src/Roslyn.Diagnostics.Analyzers/Core/RoslynDiagnosticIds.cs
Related to dotnet/roslyn#50358
I made this change to avoid accidental removal/re-use of these IDs.
> Comment out rule ids that're ported to roslyn

- src/Microsoft.CodeAnalysis.Analyzers/UnitTests/MetaAnalyzers/ReleaseTrackingAnalyzerTests.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/DoNotPassLiteralsAsLocalizedParameters.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/DoNotPassLiteralsAsLocalizedParametersTests.cs
Fixing part of https://github.com/dotnet/roslyn-analyzers/issues/4586.
> Fix Windows-only tests

- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/DisposeMethodsShouldCallBaseClassDisposeTests.cs
> Delete test which is unrelated to the analyzer of interest

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzer.cs
As discussed with @terrajobst and @jeffhandley disabling it in 5.0. We will make it configurable by the user within 6.0 when `AnalysisContext.AnalyzerOptions.AnalyzerConfigOptionsProvider.GlobalOptions` became available in the repo
> Disable generated code analysis for CA-1416 

- .github/PULL_REQUEST_TEMPLATE.md
> Small rewording on the PR issue template

- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/TaintedDataAnalysis/SourceInfo.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/TaintedDataAnalysis/TaintedDataConfig.cs
Saves over 100GB allocations when analyzing dotnet/roslyn-analyzers.
> Cache hash sets for TaintedDataConfig

- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Security/ReviewCodeForSqlInjectionVulnerabilitiesTests.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/TaintedDataAnalysis/TaintedDataAnalysis.TaintedDataOperationVisitor.cs
This PR adds support for taint analysis in lambda expressions as described in #4823.
The implementation is quite simple and follows the suggestion made by @dotpaul in the issue discussion to implement `VisitInvocation_Lambda` in `TaintedDataOperationVisitor`. Because they are quite similar, I just adapted this and the corresponding test case from `VisitInvocation_LocalFunction`. 
I can't really answer the question, whether it was intentional to leave out `VisitInvocation_Lambda` when implementing `TaintedDataOperationVisitor`, as I don't really know the code base. Likewise, I can not judge whether this breaks something, but at least it doesn't break the unit tests 😄 
Closes #4823
> Add support for lambdas in taint analysis

- azure-pipelines-microbuild.yml
- azure-pipelines.yml
Adds main to yml trigger list while we switch from master -> main. Hopefully keeping master in the trigger list for now avoids the build breakage seen yesterday in the roslyn repo. Once the transition is complete, master will be removed from the list and I will fix up the rest of the references in the repo.
> Add main to yml trigger list

- src/Microsoft.CodeAnalysis.Analyzers/CSharp/MetaAnalyzers/Fixers/CSharpPreferIsKindFix.cs
- src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/Fixers/PreferIsKindFix.cs
- src/Microsoft.CodeAnalysis.Analyzers/VisualBasic/MetaAnalyzers/Fixers/BasicPreferIsKindFix.vb
This change allows PreferIsKindFix to complete without crashing in projects with thousands of violations.
> Rewrite PreferIsKindFix using DocumentBasedFixAllProvider

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/InteropServices/UseValidPlatformString.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/InteropServices/UseValidPlatformStringTest.cs
Related to https://github.com/dotnet/runtime/issues/49323
While testing the Known Platform names analyzer in runtime repo we discovered that runtime repo is using OSX in TFM which is  alias (old name) of MacOS. As OSX can be used instead if MacOS we should add it as known platform in case MacOS exist in the known platforms list
> OSX is alias for MacOS

- src/Utilities/Compiler/Analyzer.Utilities.projitems
- src/Utilities/Compiler/HashUtilities.cs
- src/Utilities/Compiler/Options/AbstractCategorizedAnalyzerConfigOptions.cs
- src/Utilities/Compiler/Options/OptionKey.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PropertySetAnalysis/HazardousUsageEvaluator.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/TaintedDataAnalysis/TaintedDataConfig.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/AnalysisEntity.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/ArgumentInfo.cs
These changes have less impact from the previous round, but address some low-hanging fruit.
Fixes #4905
> Additional performance work from compilation traces collected for dotnet/roslyn-analyzers

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzer.OperationVisitor.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzerTests.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/GlobalFlowStateAnalysis/GlobalFlowStateAnalysis.GlobalFlowStateAnalysisValueSetDomain.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/GlobalFlowStateAnalysis/GlobalFlowStateAnalysisValueSet.cs
[dotnet build doesn't terminate in 5.0.200](https://github.com/dotnet/roslyn-analyzers/issues/4920)
[C# compiler freezes in certain platform analysis scenarios](https://github.com/dotnet/roslyn/issues/51652)
In .NET 5.0.202 (for some corner cases) the build does not terminate , resulting in VS freeze.
The DFA for Platform Compatibility Analyzer enters an infinite loop in certain edge case code patterns, where platform checks are performed inside/outside a loop and there is a try/catch within the loop.  This untested edge case scenario was hidden under [another bug](https://github.com/dotnet/roslyn-analyzers/issues/4372) that when [fixed in 5.0.2](https://github.com/dotnet/roslyn-analyzers/pull/4393) revealed this issue.
Customers reported this bug.
All .NET 5.0 SDK (v5.0.200) and above …
> Port #4928 to release/5.0.2xx branch

- Directory.Build.props
- azure-pipelines.yml
- eng/SourceBuild.props
- eng/SourceBuildPrebuiltBaseline.xml
- eng/Version.Details.xml
- eng/source-build-patches/0001-WIP-for-source-build.patch
- eng/source-build-patches/0004-Update-to-netstandard2.0.patch
- eng/source-build-patches/0005-Update-Microsoft.CodeAnalysis-packages.patch
- eng/source-build-patches/0008-Fix-version-for-Microsoft.CodeAnalysis.CSharp.CodeSt.patch
- eng/source-build-patches/0009-Disable-code-analyzers-when-building-from-source.patch
- eng/source-build-patches/0010-Build-roslyn-analyzer-tools-with-net5.0-TFM.patch
- eng/source-build-patches/0011-Reference-latest-when-running-in-build.patch
- eng/source-build-patches/0012-Fix-version-for-MCVC.patch
- eng/source-build-patches/0013-package-versions.patch
- eng/source-build-patches/0014-comment-performancesensitive.patch
This enables 'source-build', which makes it easier to build the entire shipping .NET SDK from source.
This is the first and second step of arcade-powered-source-build: https://github.com/dotnet/source-build/blob/master/Documentation/planning/arcade-powered-source-build/README.md
See dotnet/sourcelink#692 for a similar PR, that this is based on.
> Add arcade-powered-source-build local and ci builds

- src/Directory.Build.props
This is the final cleanup expected before merging features/source-build back to main.
> Remove customized NoWarn property from source build

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/ForwardCancellationTokenToInvocations.Analyzer.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/ForwardCancellationTokenToInvocationsTests.cs
Fixes https://github.com/dotnet/roslyn-analyzers/issues/4985
> Do Not consider overloads with different return types for CA2016

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzer.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzerTests.cs
By the design, attributes applied to a member should be Allow list (supported attributes version is lowes) or Deny list (unsupported attributes version is lowest), but not both. If both applied it causes inconsistency and could lead the analyzer to malfunction., depending on which attributes first added to the collection. For example, if Supported attributes (Allow list) added to the tree first there will be no issue, but if Unsupported attributes added to the tree first it is causing an issue.  There is no better way to solve this other than removing the unneeded Unsupported attribute.
Example:      
```cs
[UnsupportedOSPlatform(""browser"")]
[SupportedOSPlatform(""windows"")]
[SupportedOSPlatform(""Linux"")]
public static void UnsupportedBrowserSupportedOnWindowsLinux() { }
```
This is …
> CA1416 Remove unsupported attribute when allow deny list mixed

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzer.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzerTests.GuardedCallsTests.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzerTests.cs
OSX needs to treated  as the same platform as MacOS, everywhere
Somehow the code handling this logic lost 🙅 (i remember had it handled in my first version, I guess it is lost in the design change refactoring result).
The brute force way for treating `OSX` as `MacOS` would add additional check for each OS platform check and platform lookup, which don't like to do. So instead:
- Whenever an OSPlatform attribute with OSX found for an API adding it as `MacOs` in the internal cache, so no need to add `OSX` specific special handling anymore
- The only issue with this solution can be seen in reporting the incompatible APIs, i.e. when there is `OSX` specific API used from an incompatible call site then developers would get a warning that the API is supported on `MacOS` instead of `OSX`. Handling …
> OSX needs to treated  as the same platform as MacOS, everywhere

- src/NetAnalyzers/Core/AbstractGlobalizationDiagnosticAnalyzer.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/InteropServices/PInvokeDiagnosticAnalyzer.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/DoNotPassLiteralsAsLocalizedParameters.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/NormalizeStringsToUppercase.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/SpecifyCultureInfo.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/SpecifyIFormatProvider.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/SpecifyStringComparison.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/UseOrdinalStringComparison.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/SpecifyCultureInfoTests.cs
- src/NetAnalyzers/UnitTests/MiscellaneousAnalyzerTests.cs
- src/Tools/GenerateDocumentationAndConfigFiles/Program.cs
- src/Utilities/Compiler/Options/MSBuildPropertyOptionNames.cs
Fixes #4629
Tagging @tarekgh for confirmation that [Globalization](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/globalization-warnings) rules shouldn't be produced if the option is set to true.
Hide whitespace changes when viewing diff will ease reviewing.
> Introduce a base class for globalization analyzers

- src/Utilities.UnitTests/AdditionalFileProviderTests.cs
One of these tests failed in Test Explorer without this change. Not sure why, but this fixes it.
> Update DesiredFileMissing_GetFile_ReturnsNull to work with Test Explorer

- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStatic.cs
- src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStaticTests.cs
This false positive was caught in dotnet/roslyn.
> Add test: InstanceMemberUsedInXml_NoDiagnostic

- README.md
There is a lot of information in the README today, and it's hard to skim read. This table provides high level status of each package, and links to the more detailed sections beneath.
> Add a table of packages to the README file

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzer.Value.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzer.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzerTests.GuardedCallsTests.cs
- src/Utilities/Compiler/Analyzer.Utilities.projitems
- src/Utilities/Compiler/Extensions/VersionExtensions.cs
Fixes https://github.com/dotnet/roslyn-analyzers/issues/4932
The comparison operations of the Version type is a bit strange:
```
Console.WriteLine(Version.Parse("10.0.17763.0") < Version.Parse("10.0.17763")); // False
Console.WriteLine(Version.Parse("10.0.17763.0") > Version.Parse("10.0.17763")); // True
Console.WriteLine(Version.Parse("10.0.17763.0") == Version.Parse("10.0.17763")); // False
```
Because of that now `[SupportedOSPlatform("windows10.0.17763.0")]` is not equal to `[SupportedOSPlatform("windows10.0.17763")]`  because `Version.Revision` will be defaulted to `-1`.
Accordingly API with `[SupportedOSPlatform("windows10.0.17763.0")]` attribute  cannot be guarded with `OperatingSystem.IsWindowsVersionAtLeast(10, 0, 17763)`
Added extension method for version comparison
> CA1416 Fix Version comparison ambiguity

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Security/Helpers/InsecureDeserializationTypeDecider.cs
- src/Utilities/Compiler/PooledObjects/PooledSortedSet.cs
Fixes #5059.
From what I can tell, there's a memory leak with using PooledSortedSet&lt;T&gt; with different instances of SymbolByDisplayStringComparer, since SymbolByDisplayStringComparer has a different instance of SymbolDisplayStringCache for each compilation. So just using SortedSets&lt;T&gt; instead.
> Don't use PooledSortedSet that differ by compilations

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzer.OperationVisitor.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzer.Value.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzer.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzerTests.GuardedCallsTests.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzerTests.cs
Fixes https://github.com/dotnet/roslyn-analyzers/issues/4428 Related to https://github.com/dotnet/runtime/issues/51541 and https://github.com/dotnet/runtime/issues/44922#issuecomment-789212369
The CA1416 Platform Compatibility analyzer already recognizes platform guards using the methods on OperatingSystem/RuntimeInformation, such as OperatingSystem.IsWindows and OperatingSystem.IsWindowsVersionAtLeast. However, the analyzer does not recognize other guard options like when a field, property, or helper methods cached the platform check result and used as platform guards. 
Expanding this support involved adding new attributes `SupportedOSPlatformGuard` and `UnsupportedOSPlatformGuard` and annotated the custom guards with those attributes with the corresponding platform and/or version. Now …
> CA1416 Support custom guard members annotated with guard attributes

- src/PublicApiAnalyzers/Core/Analyzers/DeclarePublicApiAnalyzer.Impl.cs
- src/PublicApiAnalyzers/UnitTests/DeclarePublicApiAnalyzerTests.cs
Fixes https://github.com/dotnet/roslyn-analyzers/issues/4133
I'm not sure what is the best way to test `record` but I targeted `ReferenceAssemblies.Net.Net50`
> Fix incorrect removal of implicit property from PublicApi

- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Security/ReviewCodeForCommandExecutionVulnerabilitiesTests.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Security/ReviewCodeForDllInjectionVulnerabilitiesTests.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Security/ReviewCodeForFileCanonicalizationVulnerabilitiesTests.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Security/ReviewCodeForLdapInjectionVulnerabilitiesTests.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Security/ReviewCodeForRegexInjectionVulnerabilitiesTests.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Security/ReviewCodeForSqlInjectionVulnerabilitiesTests.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Security/ReviewCodeForXmlInjectionVulnerabilitiesTests.cs
- src/Utilities/Compiler/WellKnownTypeNames.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/TaintedDataAnalysis/WebInputSources.cs
Fixes #5095
Adds unit tests for CA3001, CA3003, CA3005, CA3006, CA3009, CA3011 and CA3012 security rules.
> Add .NET Core taint tracking

- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/InteropServices/SpecifyMarshalingForPInvokeStringArgumentsTests.Fixer.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/PreferStreamAsyncMemoryOverloadsTestBase.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/PreferStreamReadAsyncMemoryOverloadsTests.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/PreferStreamWriteAsyncMemoryOverloadsTests.cs
- src/NetAnalyzers/VisualBasic/Microsoft.NetCore.Analyzers/InteropServices/BasicSpecifyMarshalingForPInvokeStringArguments.Fixer.vb
- src/NetAnalyzers/VisualBasic/Microsoft.NetCore.Analyzers/Runtime/BasicPreferStreamAsyncMemoryOverloads.Fixer.vb
> #4775 Use case-insensitive identifier comparisons in VB

- src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/Maintainability/ReviewUnusedParametersTests.cs
- src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStaticTests.cs
- src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/ValidateArgumentsOfPublicMethodsTests.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Publish/AvoidAssemblyLocationInSingleFileTests.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/DisposableFieldsShouldBeDisposedTests.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/DisposeObjectsBeforeLosingScopeTests.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/DoNotPassLiteralsAsLocalizedParametersTests.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/SpecifyCultureInfoTests.cs
- src/PublicApiAnalyzers/UnitTests/DeclarePublicApiAnalyzerTests.cs
- src/Test.Utilities/CSharpCodeFixVerifier`2+Test.cs
- src/Test.Utilities/VisualBasicCodeFixVerifier`2+Test.cs
This was recently added in the testing library in https://github.com/dotnet/roslyn-sdk/pull/734.
~~The main goal of this is to (later) remove the logic of parsing editorconfig files and leave that up to the compiler (https://github.com/dotnet/roslyn-sdk/pull/734#discussion_r581165302)~~ This comment is about `AdditionalFiles`, not `AnalyzerConfigDocument`.
> Use AnalyzerConfigFiles instead of AnalyzerConfigDocument

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzer.Data.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzer.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzerTests.GuardedCallsTests.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzerTests.cs
- src/Utilities/Compiler/Options/MSBuildPropertyOptionNames.cs
Fixes #5023
By the design, child APIs should not extend parent support. `SupportedOSPlatform` attributes illustrate that the API/assembly is only reachable for that platform and it should not have any API supported on other platforms inside it. We have planned to warn if it happens by dotnet/runtime#43971, but this scenario is happening in runtime for targeted cross-platform builds. Ideally, all platform-specific implementation should be separated from cross-platform src. Though that causing code duplication at some level, so most developers would not like to apply strict separation of code.
Even though it is an expected scenario by design it is unfortunate to not get any warning about this inconsistency or possible reference of incompatible APIs within the same assembly
Initially, we …
> [CA1416] Targeted build attributes can be overriden in cross platform assemblies

- src/NetAnalyzers/CSharp/Microsoft.NetCore.Analyzers/Resources/CSharpMarkAssembliesWithNeutralResourcesLanguage.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Resources/MarkAssembliesWithNeutralResourcesLanguage.cs
- src/NetAnalyzers/VisualBasic/Microsoft.NetCore.Analyzers/Resources/BasicMarkAssembliesWithNeutralResourcesLanguage.vb
Closes #5123
**First commit**:
Main idea is to move the line:
```csharp
INamedTypeSymbol? generatedCode = model.Compilation.GetOrCreateTypeByMetadataName(WellKnownTypeNames.SystemCodeDomCompilerGeneratedCodeAttribute);
```
from `CheckResxGeneratedFile` to `RegisterCompilationStartAction` and bail-out early if needed.
Extra cleanups:
- Avoid unneeded type checking and cast the node directly to AttributeSyntax. The cast can't fail because the registered node action is for `SyntaxKind.Attribute`.
- Rename `nc` to `context`
---
**Second commit**:
Move `TryCheckNeutralResourcesLanguageAttribute` to compilation start to avoid unnecessary callbacks when we're sure there is no diagnostics to be produced.
> Tiny Refactoring CA1824

- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStatic.cs
- src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStaticTests.cs
- src/Utilities/Compiler/WellKnownTypeNames.cs
Fixes #4995 
Fixes #5110
A method that has an attribute implementing `NUnit.Framework.Interfaces.ITestBuilder` will not receive a CA1822 diagnostic (mark method as static).
Some of those attributes are:
- `NUnit.Framework.TestCaseAttribute`
- `NUnit.Framework.TestCaseSourceAttribute`
- `NUnit.Framework.TheoryAttribute`
> No CA1822 diagnostic if attribute implements NUnit's ITestBuilder

- src/PublicApiAnalyzers/Core/Analyzers/DeclarePublicApiAnalyzer.Impl.cs
- src/PublicApiAnalyzers/Core/Analyzers/DeclarePublicApiAnalyzer.cs
- src/PublicApiAnalyzers/UnitTests/DeclarePublicApiAnalyzerTests.cs
Previously, api file validation would only check for exact matches of symbols.
The addition of the oblivious marker for nullable and non-nullable annotations broke the duplication validation.
The change is to ignore the oblivious marker on duplicate comparison to prevent duplicates going unnoticed when adding the nullable reference type support.
Fixes: #4584
> Fix detection of duplicate symbols with oblivious markers

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/ForwardCancellationTokenToInvocations.Fixer.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/ForwardCancellationTokenToInvocationsTests.cs
Fixes https://github.com/dotnet/roslyn-analyzers/issues/4870
* Adds a failing test case for the problem matching the description of https://github.com/dotnet/roslyn-analyzers/issues/4870
* Adds a test case for a static generic method, which was green before applying the fix, to guard against regressions in that behavior
> Fix CA2016 when used on instance method with generic types

- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/EnumShouldNotHaveDuplicatedValues.cs
- src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/EnumShouldNotHaveDuplicatedValuesTests.cs
Fixes #3871
I ended up revising the way this works pretty heavily.
Initially I tried to fix this by gathering up all the initializer operations into a `ConcurrentDictionary<IFieldSymbol, IFieldInitializerOperation>`, then enumerating the enum members at the end and looking up the initializers.
It occurred to me that most enum values are probably *not* duplicates, though, and it would probably take less memory and fewer modifications on concurrent collections by instead using:
1. a `membersByValue` dictionary which is populated single-threaded and read concurrently
2. a `duplicates` set which is read and written concurrently
@jmarolf @sharwell
> Fix concurrency issue in CA1069 analyzer

- .editorconfig
The IDE dispose analyzer rules have been deleted from Roslyn:
https://github.com/dotnet/roslyn/commit/eeba499ecf839ec35bca25062d69d2fc5c4885b9
> Delete IDE dispose analyzer rules from .editorconfig

- eng/Versions.props
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Performance/UseAsSpanInsteadOfRangeIndexerTests.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/DetectPreviewFeatureUnitTests.cs
- src/Test.Utilities/AdditionalMetadataReferences.cs
* Update MicrosoftCodeAnalysisVersionForTests to 4.0.0-2.final
* Add Net60 reference assemblies
* Use Net60 reference assemblies in `DetectPreviewFeatureUnitTests`
> Update test dependency

- NuGet.config
- azure-pipelines-richnav.yml
- azure-pipelines.yml
This PR adds a new build pipeline yml which runs RichNav indexing. A new pipeline from this yml will need to be created manually on Azure DevOps.
This was validated by copying the step to the PR build yml and having it run there:
[RichNav run in PR build pipeline](https://dev.azure.com/dnceng/public/_build/results?buildId=1253791&view=logs&j=fc533387-d81d-5071-290a-b060f31dec76&t=1b420e69-e7e9-5794-165e-c8f61678a3fb)
> Adding RichNav indexing

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzer.OperationVisitor.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzer.Value.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzer.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzerTests.GuardedCallsTests.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzerTests.cs
Related to https://github.com/dotnet/runtime/issues/53084
To consider the proposal of using `SupportedOSPlatformGuard` attributes on the `OperatingSystem` methods to achieve a relationship of MacCatalyst as a superset of IOS, we will utilize the following acceptance criteria.
1. APIs annotated as supported on IOS are available on MacCatalyst without warning
* This allows existing APIs annotated as supported on IOS to be automatically supported on MacCatalyst
2. Guarding those calls only requires checking a single platform
* `OperatingSystem.IsIOS()` matches both IOS and MacCatalyst
3. APIs can still be annotated as being supported on one but not both IOS and MacCatalyst
* `OperatingSystem.IsIOS() && !OperatingSystem.IsMacCatalyst()` matches only IOS but not MacCatalyst
* …
> CA1416 MacCatalyst is a superset of iOS

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/BufferBlockCopyLengthAnalyzer.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/BufferBlockCopyLengthTests.cs
Fixes #5353 
CA2018 currently only checks for `Byte` and `SByte` array types. `Boolean` should also be included, since it has a size of 1 byte.
This PR adds support for `bool[]` arrays to prevent a false positive.
cc @pgovind @Youssef1313
> CA2018: Do not throw a diagnostic for Boolean arrays

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/LoggerMessageDefineAnalyzer.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/LoggerMessageDefineTests.cs
Fixes exception on LoggerMessageAnalyzer for missing named placeholder.
Fixes https://github.com/dotnet/roslyn-analyzers/issues/5362
> Fixes exception on LoggerMessageAnalyzer for missing named placeholder

- azure-pipelines-richnav.yml
The richnav build pipeline yml had some incorrect indentation, making AzDo unable to parse it. 
This PR fixes the indentation, you can see it now running successfully [here](https://dev.azure.com/dnceng/public/_build/results?buildId=1299775&view=results).
> Fix RichNav yaml formatting

- src/NetAnalyzers/CSharp/Microsoft.NetCore.Analyzers/Performance/CSharpUseStringContainsCharOverloadWithSingleCharactersFixer.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Performance/UseStringContainsCharOverloadWithSingleCharacters.Fixer.cs
- src/NetAnalyzers/VisualBasic/Microsoft.NetCore.Analyzers/Performance/BasicUseStringContainsCharOverloadWithSingleCharactersFixer.vb
Doesn't make sense to propagate an abstract type for registration as a code fix provider
Resolves #5335
> Move ExportCodeFixProvider attribute onto the concrete type

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/DetectPreviewFeatureAnalyzer.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/DetectPreviewFeatureTests.Dependencies.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/DetectPreviewFeatureUnitTests.Misc.cs
The containing symbol information for dependencies didn't work the way I expected. If a symbol is not contained within a type, `symbol.ContainingSymbol` returns null. However the `symbol.ContainingAssembly` and `symbol.ContainingModule` are populated correctly, so we can use those instead.
Contributes to https://github.com/dotnet/designs/blob/main/accepted/2021/preview-features/preview-features.md
> Support for detecting preview-ness in dependencies

- src/NetAnalyzers/CSharp/Microsoft.NetCore.Analyzers/Runtime/CSharpDetectPreviewFeatureAnalyzer.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/DetectPreviewFeatureAnalyzer.cs
- src/NetAnalyzers/Microsoft.CodeAnalysis.NetAnalyzers.sarif
- src/NetAnalyzers/RulesMissingDocumentation.md
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/DetectPreviewFeatureTests.Classes.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/DetectPreviewFeatureTests.Dependencies.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/DetectPreviewFeatureTests.Enums.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/DetectPreviewFeatureTests.Events.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/DetectPreviewFeatureTests.Fields.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/DetectPreviewFeatureTests.Generics.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/DetectPreviewFeatureTests.Interfaces.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/DetectPreviewFeatureTests.Methods.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/DetectPreviewFeatureTests.Operators.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/DetectPreviewFeatureTests.Properties.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/DetectPreviewFeatureUnitTests.Misc.cs
- src/NetAnalyzers/VisualBasic/Microsoft.NetCore.Analyzers/Runtime/BasicDetectPreviewFeatureAnalyzer.vb
I've implemented better diagnostic locations for types implementing preview interfaces. Instead of the diagnostic appearing on the type itself, it now appears on the interface in the interface list. I think this is a good starting point to get feedback first, and if I get sign off here, I can merge this PR and work on improving the diagnostic location for methods and other types with the same approach.
> Better diagnostic location for types

- .github/PULL_REQUEST_TEMPLATE.md
It wasn't clear how to run this command or that `dotnet msbuild /t:Pack /v:m` could be used as an alternative command.
> Clarify instructions for running msbuild /t:Pack

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/SpecifyIFormatProvider.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/SpecifyIFormatProviderTests.cs
> Add support for CA1305 suppression.

- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/MarkAssembliesWithComVisible.cs
With the bitwise operator, it's possible to get `NullReferenceException`, because the right-hand operand will execute.
With the boolean operator if the `attributeInstance.ConstructorArguments[0].Value != null` will false the next operand will  not run.
> Replace bitwise operator to boolean

- .markdownlint.json
- README.md
This is just a small update to the readme. If you wrap badges in `<sub>`_badge_`</sub>` it _nearly_ vertically centers them as opposed to them to being offset above the text line.
Before:
After:
I just wanted to make the suggestion as I think it looks nicer, but feel free to disregard this PR if not desired.
> readme: nearly vertically center badges with `<sub>`

- src/NetAnalyzers/CSharp/Microsoft.NetCore.Analyzers/Runtime/CSharpDetectPreviewFeatureAnalyzer.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/DetectPreviewFeatureAnalyzer.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/DetectPreviewFeatureTests.Classes.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/DetectPreviewFeatureTests.Events.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/DetectPreviewFeatureTests.Fields.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/DetectPreviewFeatureTests.Generics.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/DetectPreviewFeatureTests.Methods.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/DetectPreviewFeatureTests.Properties.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/DetectPreviewFeatureUnitTests.Misc.cs
- src/NetAnalyzers/VisualBasic/Microsoft.NetCore.Analyzers/Runtime/BasicDetectPreviewFeatureAnalyzer.vb
Follow up to https://github.com/dotnet/roslyn-analyzers/pull/5402. This improves the diagnostic location for:
1. Type constrained by preview types
2. Method or Properties returning a preview type
3. Methods taking in a preview parameter
4. Fields or Events with a preview type. Also fixes #5428
> Follow up diagnostic location for types/methods/properties

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/DetectPreviewFeatureAnalyzer.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/DetectPreviewFeatureTests.Properties.cs
Fixes https://github.com/dotnet/roslyn-analyzers/issues/5450
Currently, the analyzer assumes that a property.UsageInfo == Write implies that a `Set` method exists. This leads to a crash when dealing with auto properties where they are not backed by explicit fields. This PR fixes that.
> Fix crash when querying auto properties

- src/Microsoft.CodeAnalysis.BannedApiAnalyzers/Core/SymbolIsBannedAnalyzer.cs
- src/Microsoft.CodeAnalysis.BannedApiAnalyzers/UnitTests/SymbolIsBannedAnalyzerTests.cs
I added a feature to warn Analyzer when a BannedText's target is specified in the argument of typeof().
```cs
class Banned {  }
class C
{
void M()
{
var type = typeof(Banned);
}
}
```
It does not give any warning at all.
I think the BannedApiAnalyzer should create a Diagnostic for this case.
If a BannedText target is specified in the argument of typeof(), the BannedApiAnalyzer will create and report a Diagnostic.
> [BannedApiAnalyzers] Add typeof() argument's analyzer

- src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/Maintainability/CodeMetricsComputationTests.cs
- src/Utilities/Compiler/CodeMetrics/CodeAnalysisMetricData.NamedTypeMetricData.cs
- src/Utilities/Compiler/CodeMetrics/MetricsHelper.cs
Just noticed a couple of places where we are doing divisions of 2 `int` members.
> Ensure double cast in int-int division

- src/Utilities/Compiler/PooledObjects/ArrayBuilder.cs
`IReadonlyCollection` is inherited by `IReadonlyLsit` so there is no need for the extra declaration.
> Remove un-needed interface declaration

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzer.Value.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzerTests.GuardedCallsTests.cs
Fixes https://github.com/dotnet/roslyn-analyzers/issues/5205
Because `OSX` is the alias of `MacOS` we are replacing the `OSX` with `MacOS` while parsing the OS platform attributes
https://github.com/dotnet/roslyn-analyzers/blob/c5c6a7df6452524557baaa28c47da1d4828c1687/src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzer.cs#L1815-L1816
There is no guard for OSX in `OperatingSystem` type and the guard `OperatingSystem.IsMacOS()` is working just fine with the above change, though we forgot about `RuntimeInformaiton.IsOSPlatform(OSPlatform.OSX)` can be used as a guard for `macOS/OSX`. This PR is fixing that gap.
Not sure if 6.0 is already closed, but it is good to have in 6.0 if possible @jmarolf @jeffhandley
> Fix RuntimeInformaiton.IsOSPlatform(OSPlatform.OSX) guard

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/LoggerMessageDefineAnalyzer.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/LoggerMessageDefineTests.cs
Skipping CA2254 diagnostic when message template references constant values
Fixes https://github.com/dotnet/roslyn-analyzers/issues/5415
/cc: @sharwell @jmarolf @333fred
TODO:
> Skipping CA2254 diagnostic when message template references constant values

- .gitignore
- src/Microsoft.CodeAnalysis.BannedApiAnalyzers/BannedApiAnalyzers.Help.md
- src/Microsoft.CodeAnalysis.BannedApiAnalyzers/Core/SymbolIsBannedAnalyzer.cs
- src/Microsoft.CodeAnalysis.BannedApiAnalyzers/UnitTests/SymbolIsBannedAnalyzerTests.cs
Fixes #5143.
`SymbolIsBannedAnalyzer` will now accept the following file patterns: `BannedSymbols.txt` and `BannedSymbols.*.txt`.
Note that a duplicate pattern in different files will still generate RS0031. I'm not sure if we should allow that or not, but that can go into a separate issue.
> Allow multiple input files for SymbolIsBannedAnalyzer

- src/Microsoft.CodeAnalysis.Analyzers/Core/CodeAnalysisDiagnosticsResources.resx
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.cs.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.de.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.es.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.fr.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.it.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.ja.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.ko.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.pl.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.pt-BR.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.ru.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.tr.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.zh-Hans.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.zh-Hant.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Microsoft.CodeAnalysis.Analyzers.md
- src/Microsoft.CodeAnalysis.Analyzers/Microsoft.CodeAnalysis.Analyzers.sarif
- src/Microsoft.CodeAnalysis.Analyzers/RulesMissingDocumentation.md
- src/NetAnalyzers/RulesMissingDocumentation.md
Fixes #3427
New messages: 
Title: `Symbols should be compared for equality`
Message: `Use 'SymbolEqualityComparer' when comparing symbols` 
Description: `Symbols should be compared for equality, not identity. Use an overload accepting an 'IEqualityComparer' and pass 'SymbolEqualityComparer'.`
> Update messages for symbol comparison diagnostic and codefix

- .github/workflows/enable-auto-merge.yml
Implements the following rule using GitHub Actions automation:
> Enable auto-merge for OneLoc pull requests

- .github/workflows/community-pr.yml
Avoids a discrepancy where the V3 API returns the association `CONTRIBUTOR` for @dotnet-bot where the V4 API returns `MEMBER`.
See #5567 for a more complete explanation
> Filter to author association using GraphQL

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzer.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzerTests.GuardedCallsTests.cs
This fixes a customer-reported issue related to a combination of `SupportedOSPlatform` attributes along with flow analysis handling of `OperatingSystem` guard methods. With this edge case bug, we report a false-positive diagnostic on a call site, indicating that the call site is reachable on a version of the platform that differs from what is actually reachable.
Here is the specific scenario that was reported:
```cs
using System.Runtime.Versioning;
[SupportedOSPlatform("android23.0")]
[SupportedOSPlatform("ios13.0")]
[SupportedOSPlatform("windows8.1")]
[UnsupportedOSPlatform("MacCatalyst")]
class MyUsage
{
public void M()
{
if (!OperatingSystem.IsWindows() || OperatingSystem.IsWindowsVersionAtLeast(10, 0, 10240))
{
// FALSE POSITIVE DIAGNOSTIC REPORTED
// CA1416: This call site is …
```
> Update the flow analysis result evaluation to account the call site reachability

- .github/workflows/community-pr.yml
The API appears to occasionally return the wrong authorAssociation for pull requests submitted by these users. Excluding them by name is the easiest way to avoid applying the Community label to these pull requests.
Part of #5565
> Avoid applying Community PR label to dotnet-bot and dotnet-maestro

- .github/workflows/review-sdk.yml
> Review automatic pull requests

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/DetectPreviewFeatureAnalyzer.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/DetectPreviewFeatureTests.Properties.cs
The Requires Preview Features Analyzer (CA2252) encounters an unhandled exception in some scenarios when `null` symbols are evaluated. This was discovered while @tannergooding was consuming preview features in the [TerraFX](https://github.com/terrafx/terrafx) project and an indexer property was evaluated.
```
Severity Code Description Project File Line Suppression State Detail Description
Error AD0001 Analyzer 'Microsoft.NetCore.Analyzers.Runtime.DetectPreviewFeatureAnalyzer' threw an exception of type 'System.ArgumentNullException' with message 'Value cannot be null.
Parameter name: key'.
Exception occurred with following context:
Compilation: TerraFX.Samples.DirectX
IOperation: PropertyReference
SyntaxTree: C:\Users\tagoo\Source\repos\terrafx.interop.windows\samples\DirectX\D3D12\HelloTr …
```
> PreviewFeatures - Handle an error case where GetOverriddenMembers() returns null for an indexer

- docs/NetCore_GettingStarted.md
The `release/7.0.1xx` branch was removed in favor of using the main branch for .NET 7.x releases. If appears that docs for the main branch were updated, but that docs for the .NET 7 release branch were not.
> Update Getting Started page's branch list

- eng/Versions.props
Metrics.exe no longer seems to work with the older version of MSBuild locator.
> [Code Metrics] Upgrade MSBuild locator version

- README.md
move the CI nuget packages links to point to .NET 7
> Update CI build links

- src/NetAnalyzers/CSharp/Microsoft.NetCore.Analyzers/Runtime/CSharpDoNotUseStackallocInLoops.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/DoNotUseStackallocInLoopsTests.cs
Fixes https://github.com/dotnet/roslyn-analyzers/issues/5693
> Fix CS2014 handling of stackalloc in a foreach expression

- src/Microsoft.CodeAnalysis.AnalyzerUtilities/PublicAPI.Unshipped.txt
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/DisposeObjectsBeforeLosingScopeTests.cs
- src/Utilities/Compiler/WellKnownTypeNames.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/DisposeAnalysis/DisposeAnalysis.DisposeDataFlowOperationVisitor.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs
Fixes #4147.
We all never want to see this code again right!:
```
#pragma warning disable CA2000 // Dispose objects before losing scope
var stream = new MemoryStream();
#pragma warning restore CA2000 // Dispose objects before losing scope
```
> No more noisy pragmas needed for 'new System.IO.MemoryStream'

- src/NetAnalyzers/CSharp/Microsoft.NetCore.Analyzers/Performance/CSharpPreferHashDataOverComputeHash.Fixer.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Performance/PreferHashDataOverComputeHash.Fixer.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Performance/PreferHashDataOverComputeHashTests.cs
- src/NetAnalyzers/VisualBasic/Microsoft.NetCore.Analyzers/Performance/BasicPreferHashDataOverComputeHash.Fixer.vb
Fixes https://github.com/dotnet/roslyn-analyzers/issues/5682
> Fix CA1850 codefix not taking the original fully-qualified name into account

- src/NetAnalyzers/CSharp/Microsoft.NetCore.Analyzers/Performance/CSharpPreferHashDataOverComputeHash.Fixer.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Performance/PreferHashDataOverComputeHash.Fixer.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Performance/PreferHashDataOverComputeHashTests.cs
- src/NetAnalyzers/VisualBasic/Microsoft.NetCore.Analyzers/Performance/BasicPreferHashDataOverComputeHash.Fixer.vb
Fixes https://github.com/dotnet/roslyn-analyzers/issues/5683
> Fix CA1850 codefix to keep trivia if it's interesting

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/ImmutableCollections/DoNotCallToImmutableCollectionOnAnImmutableCollectionValue.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/InteropServices/DynamicInterfaceCastableImplementation.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/InteropServices/ProvidePublicParameterlessSafeHandleConstructor.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/InteropServices/UseValidPlatformString.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Performance/UseStringContainsCharOverloadWithSingleCharactersAnalyzer.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/BufferBlockCopyLengthAnalyzer.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/DetectPreviewFeatureAnalyzer.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/LoggerMessageDefineAnalyzer.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/ModuleInitializerAttributeShouldNotBeUsedInLibraries.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/PreferAsSpanOverSubstring.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/PreferDictionaryContainsMethods.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/ProvideStreamMemoryBasedAsyncOverrides.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/UseAsyncMethodInAsyncContext.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/UseCancellationTokenThrowIfCancellationRequested.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/UseEnvironmentMembers.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/UseSpanBasedStringConcat.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/UseStringEqualsOverStringCompare.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Security/DoNotAlwaysSkipTokenValidationInDelegates.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Security/DoNotDisableTokenValidationChecks.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Tasks/DoNotUseWhenAllOrWaitAllWithSingleArgument.cs
- src/PerformanceSensitiveAnalyzers/CSharp/Analyzers/CallSiteImplicitAllocationAnalyzer.cs
- src/PerformanceSensitiveAnalyzers/CSharp/Analyzers/ConcatenationAllocationAnalyzer.cs
- src/PerformanceSensitiveAnalyzers/CSharp/Analyzers/DisplayClassAllocationAnalyzer.cs
- src/PerformanceSensitiveAnalyzers/CSharp/Analyzers/EnumeratorAllocationAnalyzer.cs
- src/PerformanceSensitiveAnalyzers/CSharp/Analyzers/TypeConversionAllocationAnalyzer.cs
- src/PerformanceSensitiveAnalyzers/Core/ExplicitAllocationAnalyzer.cs
- src/PerformanceTests/Utilities/Common/EmptyAnalyzer.cs
- src/Utilities/Compiler/Extensions/ISymbolExtensions.cs
`ImmutableArray.Create` calls does an array allocation:
https://github.com/dotnet/runtime/blob/d9afc1ecd6f22d836e1d7665847917aa09f580e9/src/libraries/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableArray.cs#L30-L53
With the previous code, `ImmutableArray.Create` will be called EVERY time `SupportedDiagnostics` is accessed. With an initializer, the call to `ImmutableArray.Create` will only be done once. See [SharpLab](https://sharplab.io/#v2:EYLgtghglgdgNAExAagD4AEDMACdAmbAYQFgAoAbzO2tx3QEYAGAbQF1sBle7AXgD5sMAKYB3XE2YBWVgG4qNLOJbsOBctgDmQgC4zsAX16DRSqbLL6gA===).
> Use a property initializer to guarantee one-time array allocation

- src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/PreferIsKindAnalyzer.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/InteropServices/ProvidePublicParameterlessSafeHandleConstructor.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/InteropServices/UseValidPlatformString.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/BufferBlockCopyLengthAnalyzer.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/DetectPreviewFeatureAnalyzer.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/LoggerMessageDefineAnalyzer.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/ModuleInitializerAttributeShouldNotBeUsedInLibraries.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/UseAsyncMethodInAsyncContext.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Security/DoNotAlwaysSkipTokenValidationInDelegates.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Security/DoNotDisableTokenValidationChecks.cs
- src/PerformanceSensitiveAnalyzers/CSharp/Analyzers/CallSiteImplicitAllocationAnalyzer.cs
- src/PerformanceSensitiveAnalyzers/CSharp/Analyzers/ConcatenationAllocationAnalyzer.cs
- src/PerformanceSensitiveAnalyzers/CSharp/Analyzers/DisplayClassAllocationAnalyzer.cs
- src/PerformanceSensitiveAnalyzers/CSharp/Analyzers/EnumeratorAllocationAnalyzer.cs
- src/PerformanceSensitiveAnalyzers/CSharp/Analyzers/TypeConversionAllocationAnalyzer.cs
- src/PerformanceSensitiveAnalyzers/Core/ExplicitAllocationAnalyzer.cs
- src/Roslyn.Diagnostics.Analyzers/CSharp/CSharpAvoidOptSuffixForNullableEnableCode.cs
- src/Roslyn.Diagnostics.Analyzers/CSharp/PreferNullLiteral.cs
- src/Roslyn.Diagnostics.Analyzers/Core/AbstractDoNotCopyValue.cs
- src/Roslyn.Diagnostics.Analyzers/Core/DefaultableTypeShouldHaveDefaultableFieldsAnalyzer.cs
- src/Roslyn.Diagnostics.Analyzers/Core/DoNotMixAttributesFromDifferentVersionsOfMEF.cs
- src/Roslyn.Diagnostics.Analyzers/Core/ExportedPartsShouldHaveImportingConstructor.cs
- src/Roslyn.Diagnostics.Analyzers/Core/ImportingConstructorShouldBeObsolete.cs
- src/Roslyn.Diagnostics.Analyzers/Core/PartsExportedWithMEFv2MustBeMarkedAsShared.cs
- src/Roslyn.Diagnostics.Analyzers/Core/TemporaryArrayAsRefAnalyzer.cs
- src/Roslyn.Diagnostics.Analyzers/Core/TestExportsShouldNotBeDiscoverable.cs
- src/Text.Analyzers/Core/EnumsShouldHavePluralNames.cs
- src/Text.Analyzers/Core/IdentifiersShouldBeSpelledCorrectly.cs
Fixes https://github.com/dotnet/roslyn-analyzers/issues/5169
> Make DiagnosticDescriptors readonly

- src/Microsoft.CodeAnalysis.Analyzers/CSharp/MetaAnalyzers/CSharpRegisterActionAnalyzer.cs
- src/Microsoft.CodeAnalysis.Analyzers/Core/FixAnalyzers/FixerWithFixAllAnalyzer.cs
- src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/CompareSymbolsCorrectlyAnalyzer.cs
- src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/ConfigureGeneratedCodeAnalysisAnalyzer.cs
- src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/DiagnosticAnalyzerAPIUsageAnalyzer.cs
- src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/DiagnosticAnalyzerCorrectnessAnalyzer.DiagnosticAnalyzerSymbolAnalyzer.cs
- src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/DiagnosticAnalyzerFieldsAnalyzer.cs
- src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/DiagnosticDescriptorCreationAnalyzer.cs
- src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/DoNotUseCompilationGetSemanticModelAnalyzer.cs
- src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/EnableConcurrentExecutionAnalyzer.cs
- src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/RegisterActionAnalyzer.cs
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/CancellationTokenParametersMustComeLast.cs
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/CollectionPropertiesShouldBeReadOnly.cs
- src/Utilities/Compiler/Analyzer.Utilities.projitems
- src/Utilities/Compiler/Extensions/IMethodSymbolExtensions.cs
- src/Utilities/Compiler/Extensions/ISymbolExtensions.cs
- src/Utilities/Compiler/Extensions/ITypeSymbolExtensions.cs
- src/Utilities/Compiler/Extensions/OperationBlockAnalysisContextExtension.cs
- src/Utilities/Compiler/SymbolEqualityComparer.cs
- src/Utilities/Compiler/WellKnownTypeProvider.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/CopyAnalysis/CopyAnalysis.CopyDataFlowOperationVisitor.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/AbstractLocationDataFlowOperationVisitor.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/AnalysisEntityDataFlowOperationVisitor.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/AnalysisEntityMapAbstractDomain.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/ThrownExceptionInfo.cs
Not sure why but I have started to get hundreds of warning related to `RS1024` in the codebase so I decided to start tackling them.
In this PR, I am focusing on the `Equals` because for some reason most of the complains on collections don't get fixed after applying the comparer.
> Fix a bunch of RS1024 on Equals

- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzerTests.GuardedCallsTests.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs
Fixes https://github.com/dotnet/roslyn-analyzers/issues/5403
Flow analysis doesn't support `Debug.Assert(bool, string? message)` or any other overload except `Debug.Assert(bool)`:
```cs
void M1()
{
Debug.Assert(OperatingSystem.IsWindows(), "Only supported on windows");
WindowsOnly(); // warns even not supposed to
Debug.Assert(OperatingSystem.IsWindows());
WindowsOnly(); // not warn
}
[SupportedOSPlatform("windows")]
void WindwosOnly () { }
```
I believe all overloads of Debug.Assert(...) should be supported cc @mavasani
> Support all Debug.Assert(...) overloads in flow analysis

- eng/Versions.props
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/DeclareTypesInNamespaces.cs
- src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/DeclareTypesInNamespacesTests.cs
> Fix CA1050 (declare types in namespaces) false positive with top-level statements

- src/Utilities/Compiler/Options/AnalyzerOptionsExtensions.cs
Closes #5725
Closes #5748
@sharwell @mavasani Do you think this is a good fix?
> Don't throw exception: "Passing '.editorconfig' files as additional files is no longer needed."

- src/NetAnalyzers/CSharp/Microsoft.NetCore.Analyzers/Runtime/CSharpDetectPreviewFeatureAnalyzer.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/DetectPreviewFeatureAnalyzer.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/DetectPreviewFeatureTests.Classes.cs
- src/NetAnalyzers/VisualBasic/Microsoft.NetCore.Analyzers/Runtime/BasicDetectPreviewFeatureAnalyzer.vb
@jeffhandley Can you take a look?
Fixes #5802
> Fix crash and record diagnostic location in preview feature analyzer

- src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/CompareSymbolsCorrectlyAnalyzer.cs
- src/Microsoft.CodeAnalysis.Analyzers/UnitTests/MetaAnalyzers/CompareSymbolsCorrectlyTests.cs
> Fix 'Compare symbols correctly' false positive with custom comparers

- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/Maintainability/UseNameofInPlaceOfString.cs
This avoid enumerating every parameter and property in scope.
I haven't measured performance/allocations to see if this makes any noticeable improvement, but thought it's good anyway.
> Refactor UseNameofInPlaceOfString

- README.md
Observed those sudden failures in https://dev.azure.com/dnceng/public/_build/results?buildId=1595722&view=logs&jobId=636081a6-586b-5581-8301-2023f5546d3b&j=636081a6-586b-5581-8301-2023f5546d3b&t=c568974c-96f7-57d5-725b-96c1e4bcdfed
@DavidAnson Is this a known recent change to markdownlint?
> Fix markdownlint violations

- src/NetAnalyzers/CSharp/Microsoft.NetCore.Analyzers/Runtime/CSharpForwardCancellationTokenToInvocations.Fixer.cs
SyntaxGenerator does nothing with this annotation. In Roslyn, it's only used for metadata-as-source
> Remove invalid use of `NullableSyntaxAnnotation`

- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/AvoidMultipleEnumerations/AvoidMultipleEnumerations.cs
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/AvoidMultipleEnumerations/AvoidMultipleEnumerationsHelpers.cs
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/AvoidMultipleEnumerations/WellKnownSymbolsInfo.cs
- src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/AvoidMultipleEnumerationsTests.cs
- src/Utilities/Compiler/Options/AnalyzerOptionsExtensions.cs
- src/Utilities/Compiler/Options/EditorConfigOptionNames.cs
A small PR addresses this comment
https://github.com/dotnet/roslyn-analyzers/pull/5882#discussion_r817505300
> Add an option to control the default behavior of IEnumerable Analyzer

- src/Roslyn.Diagnostics.Analyzers/Core/AbstractRunIterations`1.cs
- src/Roslyn.Diagnostics.Analyzers/UnitTests/RunIterationsTests.cs
`SyntaxGenerator.WithName` converts `Fact` to `[Theory]` (wrapping `AttributeSyntax` in an `AttributeListSyntax`), which makes it incompatible for direct replacement. This change unwraps the `AttributeSyntax` before replacing the original node in the tree.
> Update Run Iterations refactoring to work with attribute lists

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/InteropServices/DisableRuntimeMarshalling.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/InteropServices/DisableRuntimeMarshallingTests.cs
This fixes a bug in the DisableRuntimeMarshallingAnalyzer that causes it to stack-overflow on recursive types. Generally these types are invalid in C#, but some special cases (the definitions of primitive types) exist. This bug is blocking dotnet/runtime from intaking new copies of dotnet/roslyn-analyzers
cc: @dotnet/roslyn-analysis @dotnet/runtime-infrastructure
> Fix handling of recursive types in DisableRuntimeMarshalling analyzer

- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzerTests.cs
- src/Utilities/Compiler/SmallDictionary.cs
Fixes https://github.com/dotnet/roslyn-analyzers/issues/5936
Platform compatibility analyzer crushes for some platform attributes combinations while removing Unsupported  platforms from Supported platforms list
> Fix CA1416 failure with NullReferenceExcpetion

- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/MicrosoftCodeQualityAnalyzersResources.resx
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.cs.xlf
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.de.xlf
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.es.xlf
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.fr.xlf
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.it.xlf
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.ja.xlf
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.ko.xlf
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.pl.xlf
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.pt-BR.xlf
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.ru.xlf
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.tr.xlf
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.zh-Hans.xlf
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.zh-Hant.xlf
- src/NetAnalyzers/Microsoft.CodeAnalysis.NetAnalyzers.md
- src/NetAnalyzers/Microsoft.CodeAnalysis.NetAnalyzers.sarif
In this comment https://github.com/dotnet/docs/pull/28732#discussion_r831458450
@gewarren mentioned it should be 'avoids' instead of 'avoid'
Bring this change to the analyzer resources
> Fix a typo in IEnumerable Analyzer

- README.md
Old links used to work. But for some reason they don't work now.
I couldn't find a link that doesn't have a version hardcoded in it, so these links were best I could find.
Let me know if there are better links.
> Update prerelease links

- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/AvoidMultipleEnumerations/AvoidMultipleEnumerations.DataFlowOperationVisitor.cs
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/AvoidMultipleEnumerations/FlowAnalysis/GlobalFlowStateDictionaryAnalysisValue.cs
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/AvoidMultipleEnumerations/FlowAnalysis/GlobalFlowStateDictionaryFlowOperationVisitor.cs
- src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/AvoidMultipleEnumerationsTests.cs
Found this problem during my daily use of the analyzer.
Currently, there is a false positive this sample
```
foreach (var l in collection)
{
var x = Create();
var d = [|x|].ElementAt(100);
}
```
It is because the analyzer is tracking a dictionary like
'Create()' operation -> 'x.ElementAt(10)' in the after the first iteration of the loop.
Then in the second iteration,
'Create()' operation is visited again, but since it is the same creation operation, it is consider 'x.ElementAt()' enumerate 'Create()' operation twice.
This PR adds a reset logic in the OperationVisitor, when an assignment operation is visited, and the assigned operation has been tracked, reset it. So the example above would become:
After the first iteration, the tracked entity is like:
'Create()' operation -> …
> Reset the value when CreationOperation is visited again for IEnumerable

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/SealInternalTypes.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/SealInternalTypesTests.cs
Without this there are too many false positives in libraries that use InternalsVisibleTo, in particular to tests.
cc: @GrabYourPitchforks, @mavasani
> Make CA1852 aware of InternalsVisibleTo

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/MicrosoftNetCoreAnalyzersResources.resx
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.cs.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.de.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.es.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.fr.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.it.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ja.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ko.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.pl.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.pt-BR.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ru.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.tr.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.zh-Hans.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.zh-Hant.xlf
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/SpecifyCultureForToLowerAndToUpperTests.Fixer.cs
- src/NetAnalyzers/VisualBasic/Microsoft.NetCore.Analyzers/Runtime/BasicSpecifyCultureForToLowerAndToUpper.Fixer.vb
- src/NetAnalyzers/VisualBasic/Microsoft.NetCore.Analyzers/Runtime/BasicSpecifyCultureForToLowerAndToUpper.vb
This PR is a follow-up of these two - https://github.com/dotnet/roslyn-analyzers/pull/5970/ https://github.com/dotnet/roslyn-analyzers/pull/2186
@buyaa-n @Youssef1313 Here's the new PR addressing the issues left over from the previous ones.
I've updated the fixer to address the VB edge case and I've also fixed the typo in the resource files.
I haven't however moved unit tests into a single file. Is that a must? I see that many analyzers/fixers in the codebase have separate files for unit tests.
> CA1311 various fixes

- src/NetAnalyzers/VisualBasic/Microsoft.NetCore.Analyzers/Runtime/BasicSpecifyCultureForToLowerAndToUpper.Fixer.vb
Even though the `IsKind` extension method is implemented in a null-tolerant way, it is still better to not check the right hand side of the or expression when it's not necessary, hence this PR.
@buyaa-n this is a follow-up of this - https://github.com/dotnet/roslyn-analyzers/pull/6010
> CA1311 VB - short-circuiting or

- src/NetAnalyzers/CSharp/Microsoft.NetCore.Analyzers/Runtime/CSharpPreferDictionaryTryGetValueFixer.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/PreferDictionaryTryGetValueFixer.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/PreferDictionaryTryGetValueMethodsTests.cs
> Respect editorconfig var preference in CA1854

- PostReleaseActivities.md
- src/Microsoft.CodeAnalysis.ResxSourceGenerator/Microsoft.CodeAnalysis.ResxSourceGenerator/Microsoft.CodeAnalysis.ResxSourceGenerator.csproj
- src/Tools/ReleaseNotesUtil/Program.cs
- src/Tools/ReleaseNotesUtil/ReleaseNotesUtil.csproj
The other reference comes from
https://github.com/dotnet/roslyn-analyzers/blob/0e7f40d1709f0d7ffd316d89e452151a7365354b/src/Utilities/Compiler/Analyzer.Utilities.projitems#L145-L147
> Remove duplicate `PackageReference`

- src/NetAnalyzers/RulesMissingDocumentation.md
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzerTests.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/GlobalFlowStateAnalysis/GlobalFlowStateAnalysis.GlobalFlowStateAnalysisValueSetDomain.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/GlobalFlowStateAnalysis/GlobalFlowStateValueSetFlowOperationVisitor.cs
Fixes #6015
`GlobalFlowStateAnalysisValueSet.Unset` is used to represent unanalyzed flow state, `GlobalFlowStateAnalysisValueSet.Empty` is used to represent analyzed flow state with no analysis values. We initialize the flow states for the entry basic block of the CFG with `Unset` value, but never replace the `Unset` with `Empty` for subsequent passes. This in turn leads to incorrect merge when a `Known` value flows from the back edge to the loop start and ends up overriding the `Unset` value instead of being overridden by the `Empty` value. Now we correctly perform this merge logic.
I verified that prior to this fix, the added unit test hang due to this issue. I also verified that building the github repo cited in the feedback ticket with platform compat analyzer also leads to a hang …
> Fix the incorrect merge logic for back edges for GlobalFlowStateAnalysis

- PostReleaseActivities.md
- global.json
- src/Microsoft.CodeAnalysis.ResxSourceGenerator/Microsoft.CodeAnalysis.ResxSourceGenerator/Microsoft.CodeAnalysis.ResxSourceGenerator.csproj
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzerTests.cs
- src/Tools/ReleaseNotesUtil/Program.cs
- src/Tools/ReleaseNotesUtil/ReleaseNotesUtil.csproj
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/GlobalFlowStateAnalysis/GlobalFlowStateAnalysis.GlobalFlowStateAnalysisValueSetDomain.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/GlobalFlowStateAnalysis/GlobalFlowStateDataFlowOperationVisitor.cs
Ports https://github.com/dotnet/roslyn-analyzers/pull/6029 to .NET6 release branch.
A customer reported the issue in VS feedbacks which transferred to github: https://github.com/dotnet/roslyn-analyzers/issues/6015 and it is reproduceable with the [linked project](https://github.com/Slazanger/SMT/tree/dotnet6_upgrade). 
When builds the project with CA1416 Platform Compatibility Analyzer enabled then the build never ends and memory grows continually, even stopping the build and closed the VS the `VBCSCompiler` process stays alive and memory keep growing, only option is kill the process
CA1416 is included in SDK and enabled by default, therefore it could happen for any customer's project that happens to have a code section that reproes the issue.
- **Unit tested** verified that prior to this …
> [Port] Fix the incorrect merge logic for back edges for GlobalFlowStateAnalysis

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/SpecifyIFormatProvider.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/SpecifyIFormatProviderTests.cs
Fixes #5999.
Provides an extensible method to add other types later if some of the other new `Parse` methods in .NET 7 also end up triggering this warning. For now, it seems that since `char` etc. implement `IParseable<T>.Parse(string, IFormatProvider)` explicitly, a call to `char.Parse(string)` doesn't trigger CA1305 (which is good), so this PR only implements an opt-out for `Guid`.
> Suppress CA1305 for `Guid.Parse`

- azure-pipelines.yml
@mavasani This prevents breaking changes in markdownlint-cli to break CI suddenly.
> Pin markdownlint version

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzer.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzerTests.GuardedCallsTests.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzerTests.cs
The `MockOperatingSystem` type was used for testing the iOS is MacCatalyst scenario before the updates of real `OperatingSystem` type updates became available in the repo.
It was mockink the `OperatingSystem.IsIOS()`, `OperatingSystem.IsIOSVersionAtLeast(...)` APIs  as applied the `[SupportedOSPlatformGuard(""maccatalyst"")]` attribute and also newly added APIs like `OperatingSystem.IsMacCatalyst()`, `OperatingSystem.IsMacCatalystVersionAtLeast(...)` 
```cs
public class MockOperatingSystem
{
[SupportedOSPlatformGuard("maccatalyst")]
public static bool IsIOS() => true;
[SupportedOSPlatformGuard("maccatalyst")]
public static bool IsIOSVersionAtLeast(int major, int minor = 0, int build = 0) => false;
public static bool IsMacCatalyst() => false;
public static bool …
```
> Clean up mock API that not needed anymore

- src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/DiagnosticDescriptorCreationAnalyzer.cs
- src/Microsoft.CodeAnalysis.Analyzers/UnitTests/MetaAnalyzers/ReleaseTrackingAnalyzerTests.cs
Fixes https://github.com/dotnet/roslyn-analyzers/issues/5828
@mavasani @sharwell for a small PR review.
See https://github.com/dotnet/roslyn/issues/59171 for details.
> Fix target-typed new false positive

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/ProvideStreamMemoryBasedAsyncOverrides.cs
I don't think `[Shared]` will do anything for analyzers.
> Remove `[Shared]` from an analyzer

- eng/Versions.props
Resolves https://github.com/dotnet/roslyn-sdk/issues/1006
> Update M.CA.Testing to 1.1.2-beta1.22419.1

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/InteropServices/DisableRuntimeMarshalling.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/InteropServices/DisableRuntimeMarshallingAnalyzer.DelegateInteropUsageAnalyzer.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/InteropServices/DisableRuntimeMarshallingTests.cs
> Fix detection of DisableRuntimeMarshalling delegate interop to only warn when the delegate type is in an assembly with DisableRuntimeMarshalling

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzer.Data.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzer.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzer.ObsoletedOSPlatformTests.cs
The `ObsoletedInOSPlatformAttribute` is renamed to `ObsoletedOSPlatformAttribute` with https://github.com/dotnet/runtime/issues/72970, updating the Platform Compat Analyzer accordingly
> React to Obsoleted attribute renaming

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Usage/ImplementGenericMathInterfacesCorrectly.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Usage/ImplementGenericMathInterfacesCorrectlyTests.cs
Fix bug found in https://github.com/dotnet/runtime/pull/75675
> GM interfaces implementations can be self constrained

- azure-pipelines-microbuild.yml
- azure-pipelines-richnav.yml
- azure-pipelines.yml
> Run CI using the new VM images

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/InteropServices/PInvokeDiagnosticAnalyzer.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/InteropServices/PInvokeDiagnosticAnalyzerTests.cs
The documentation for CA2101 clearly indicates that the problem is not the use of single-byte character marshalling itself, but that when doing so .NET will by default try and substitute characters that cannot be directly marshalled, which could cause globalization or even security problems in the code being analyzed.
Unfortunately, when a developer actually tries to use BestFitMapping=false, such as when using ANSI-only APIs (which are particularly common on non-Windows operating systems), CA2101 triggers anyway and the developer has no choice but to suppress the Diagnostic or disable the rule, adding noise to their code and reducing trust in the analyzer.
CA2101 appears to work correctly in Microsoft.CodeAnalysis.FxCopAnalyzers and in Microsoft.CodeAnalysis.NetAnalyzers through version …
> Fix CA2101 triggering when BestFitMapping=false

- azure-pipelines.yml
Ubuntu 18.04 is obsolete and needs to be updated to either 20.04 or 22.04.
> Update markdown-lint CI to ubuntu 22.04

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzer.OperationVisitor.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzer.Value.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzerTests.GuardedCallsTests.cs
CA1416 by default recognizes platform version check APIs provided by .Net libraries, in addition to that a user API can be annotated with SupportedOSPlatformGuard/UnsupportedOSPlatformGuard attribute in order to recognized by the analyzer during platform/version check. 
The platform name and version must be passed with the attribute constructor argument. As mentioned in https://github.com/dotnet/roslyn-analyzers/issues/6204 we need to update that logic to support dynamic versions that provided by the called API, example:
```cs
public class UIDevice
{
[SupportedOSPlatformGuard("ios")]
public bool CheckSystemVersion(int major, int minor);
}
public class Test
{
[SupportedOSPlatform("ios13.0")]
void SupportedOnIos13() { }
void M1()
{
[|SupportedOnIos13()|];  // warns
if …
```
> Update SupportedOSPlatformGuard/UnsupportedOSPlatformGuard logic to support dynamic versions

- src/Roslyn.Diagnostics.Analyzers/CSharp/NumberCommentsRefactoring.cs
- src/Roslyn.Diagnostics.Analyzers/UnitTests/NumberCommentsRefactoringTests.cs
For context, this refactoring helps fix number comments in roslyn tests. See a pictured example below.
The problem is that it didn't work with the newly added raw strings literals. This PR fixes that.
> Update `NumberCommentsRefactoring` to support raw string literals

- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/DisposableFieldsShouldBeDisposedTests.cs
- src/Utilities/Compiler/Extensions/IMethodSymbolExtensions.cs
Fixes https://github.com/dotnet/roslyn-analyzers/issues/6075
> Tracks disposed objects through implicit interface implementations

- src/Directory.Build.targets
- src/Tools/GenerateDocumentationAndConfigFiles/Program.cs
Fixes #6247
Our generated globalconfig files that we ship in the analyzer NuGet packages and .NET SDK should likely include a vNext set of globalconfig files so that when the analysis level is set to latest or explicitly to vNext for upcoming .NET Release, we still find a proper mapped globalconfig file. This will avoid regressions such as #6245 in future.
Verified that locally built Microsoft.CodeAnalysis.NetAnalyzers package with this change includes globalconfig files specific to 8.0 release version.
> Enhance GenerateDocumentationAndConfigFiles tool to generate vNext globalconfig files

- src/NetAnalyzers/CSharp/Microsoft.NetCore.Analyzers/Runtime/CSharpDoNotUseStackallocInLoops.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/DoNotUseStackallocInLoopsTests.cs
> Support ForEachVariableStatement in stackalloc analyzer

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/SealInternalTypes.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/SealInternalTypesTests.cs
> SealInternalTypes (CA1852): Don't warn for top-level type

- src/PublicApiAnalyzers/Core/Analyzers/DeclarePublicApiAnalyzer.cs
- src/PublicApiAnalyzers/UnitTests/DeclarePublicAPIAnalyzerTestsBase.cs
The current logic was broken for projects that only have public or only have internal APIs. I refactored the registration logic to run completely separately for both public and internal to fix this.
> Fix PublicAPI enablement checks

- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/RethrowToPreserveStackDetails.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/UseCancellationTokenThrowIfCancellationRequested.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/UseExceptionThrowHelpers.cs
- src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/RethrowToPreserveStackDetailsTests.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/UseCancellationTokenThrowIfCancellationRequestedTests.cs
- src/Utilities/Compiler/Extensions/IOperationExtensions.cs
Fixes #6284
Starting C# 8.0, C# compiler wraps the thrown operation within an implicit conversion to `System.Exception` type.
> Handle conversion operation as operands of IThrowOperation

- NuGet.config
- src/NetAnalyzers/UnitTests/Microsoft.CodeAnalysis.NetAnalyzers.UnitTests.csproj
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/InteropServices/DisableRuntimeMarshallingTests.cs
Reverts small part of https://github.com/dotnet/roslyn-analyzers/commit/ac9e29440ed5484fe65668e22737ab6c82dd0f60 and use `ReferenceAssemblies.Net.Net70`
> Use ReferenceAssemblies.Net.Net70

- azure-pipelines-perf.yml
- azure-pipelines.yml
This is a change similar to https://github.com/dotnet/roslyn/pull/58723 to avoid running PR unnecessarily when modifying specific files.
> Don't run CI for doc changes

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/UseExceptionThrowHelpers.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/UseExceptionThrowHelpersTests.cs
I went back and forth on this initially, but decided it makes more sense to be conservative here and only recommend using ArgumentNullException.ThrowIfNull if the type of the parameter is known to be a class.  While it could be used for nullable value types or unconstrained generics, both result in boxing that we then rely on the JIT to eliminate.
> Update UseExceptionThrowHelpers to only recommend ANE for classes

- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/ValidateArgumentsOfPublicMethods.cs
> Remove comment about param-null checking feature that was dropped

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/rule-improvement.md
- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- docs/Analyzer Configuration.md
- docs/NetCore_GettingStarted.md
- eng/common/templates/job/job.yml
- eng/common/templates/job/onelocbuild.yml
- eng/common/templates/job/publish-build-assets.yml
- eng/common/templates/jobs/codeql-build.yml
- eng/common/templates/jobs/jobs.yml
- eng/common/tools.ps1
- src/Microsoft.CodeAnalysis.BannedApiAnalyzers/UnitTests/SymbolIsBannedAnalyzerTests.cs
- src/NetAnalyzers/Core/AnalyzerReleases.Unshipped.md
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/EnumShouldNotHaveDuplicatedValues.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Security/Helpers/XmlSerializationAttributeTypes.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/DisposeObjectsBeforeLosingScopeTests.cs
- src/NetAnalyzers/readme.md
- src/PublicApiAnalyzers/PublicApiAnalyzers.Help.md
- src/Utilities/Compiler/Options/EditorConfigOptionNames.cs
> Replace docs.microsoft.com with learn.microsoft.com

- src/NetAnalyzers/Core/Microsoft.CodeAnalysis.NetAnalyzers.csproj
> Cleanup `Microsoft.CodeAnalysis.NetAnalyzers.csproj`

- src/NetAnalyzers/RulesMissingDocumentation.md
- src/PublicApiAnalyzers/Core/Analyzers/DeclarePublicApiAnalyzer_Diagnostics.cs
- src/PublicApiAnalyzers/Microsoft.CodeAnalysis.PublicApiAnalyzers.md
- src/PublicApiAnalyzers/Microsoft.CodeAnalysis.PublicApiAnalyzers.sarif
I assume this is the intended description.
> Fix analyzer description

- src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/Maintainability/AvoidUninstantiatedInternalClassesTests.cs
> Add file-local class test for CA1812

- docs/NetCore_GettingStarted.md
> Update "Branch Definitions" documentation

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzer.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzer.ObsoletedOSPlatformTests.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzerTests.GuardedCallsTests.cs
Two bugs found while investigating #6158 that fixed with this PR
1. When a child API narrows down parent support version the guarding version was compared with parent version only when it should be compared with child version
```cs
[SupportedOSPlatform("ios")]
[SupportedOSPlatform("tvos")]
[SupportedOSPlatform("maccatalyst")]
class Program
{
[SupportedOSPlatform("tvos10.2")]
[SupportedOSPlatform("ios10.3")]
[SupportedOSPlatform("maccatalyst10.3")]
public static int P1 => 1;
}
class Test
{
[SupportedOSPlatform("ios10.0")]
public void M1()
{
var rate = (OperatingSystem.IsIOSVersionAtLeast(10, 3) || OperatingSystem.IsMacCatalystVersionAtLeast(10, 3) || OperatingSystem.IsTvOSVersionAtLeast(10, 3))
? Program.P1 // was warning here even if it was guarded
: 0; 
}
}
```
2. When a called API has …
> Fix bugs found in MAUI repo

- src/NetAnalyzers/CSharp/Microsoft.NetCore.Analyzers/Runtime/CSharpPreferStreamAsyncMemoryOverloads.Fixer.cs
- src/NetAnalyzers/CSharp/Microsoft.NetCore.Analyzers/Runtime/CSharpUseSpanBasedStringConcat.Fixer.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/PreferStreamAsyncMemoryOverloads.Fixer.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/UseSpanBasedStringConcat.Fixer.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/PreferStreamReadAsyncMemoryOverloadsTests.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/PreferStreamWriteAsyncMemoryOverloadsTests.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/UseSpanBasedStringConcatTests.cs
- src/NetAnalyzers/VisualBasic/Microsoft.NetCore.Analyzers/Runtime/BasicPreferStreamAsyncMemoryOverloads.Fixer.vb
- src/NetAnalyzers/VisualBasic/Microsoft.NetCore.Analyzers/Runtime/BasicUseSpanBasedStringConcat.Fixer.vb
> Don't import System when it's already imported by global using

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/SpecifyIFormatProvider.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/SpecifyIFormatProviderTests.cs
> Refactor CA1305 to compare symbols

- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/Maintainability/AvoidUninstantiatedInternalClasses.cs
- src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/Maintainability/AvoidUninstantiatedInternalClassesTests.cs
> Simplify AvoidUninstantiatedInternalClasses

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/UseExceptionThrowHelpers.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/UseExceptionThrowHelpersTests.cs
Based on additional false positives discovered while enabling the rules in dotnet/runtime:
- We don't want to warn to use ObjectDisposedException.ThrowIf when inside of a struct, as doing so is likely to lead to additional costs (e.g. boxing).
- We don't want to warn to use ArgumentXxException.ThrowIfXx when the code to compute the argument name is more complicated than just a literal / nameof, e.g. a method call that determines what parameter name should be employed.
> Fix a couple of issues in UseExceptionThrowHelpers

- src/Microsoft.CodeAnalysis.Analyzers/Core/AnalyzerReleases.Unshipped.md
- src/Microsoft.CodeAnalysis.Analyzers/Core/CodeAnalysisDiagnosticsResources.resx
- src/Microsoft.CodeAnalysis.Analyzers/Core/DiagnosticIds.cs
- src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/DiagnosticDescriptorCreationAnalyzer.cs
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.cs.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.de.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.es.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.fr.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.it.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.ja.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.ko.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.pl.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.pt-BR.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.ru.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.tr.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.zh-Hans.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.zh-Hant.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Microsoft.CodeAnalysis.Analyzers.md
- src/Microsoft.CodeAnalysis.Analyzers/Microsoft.CodeAnalysis.Analyzers.sarif
- src/Microsoft.CodeAnalysis.Analyzers/RulesMissingDocumentation.md
- src/Microsoft.CodeAnalysis.Analyzers/UnitTests/MetaAnalyzers/DiagnosticDescriptorCreationAnalyzerTests.cs
> Add RSxxxx diagnostic for compilation end diagnostic descriptors without CompilationEnd custom tag

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Performance/UseConcreteTypeAnalyzer.Collector.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Performance/UseConcreteTypeAnalyzer.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Performance/UseConcreteTypeTests.cs
* When using the ?? operator, the nullable annotation for the left-hand operand is now erased. This prevents the analyzer suggesting to use a replacement nullable type rather than its non-nullable variation. #6413 
* We no longer suggest to upgrade the type of a local/field/parameter if the symbol is being used to invoke a method that is an explicit implementation of an interface method. If the user would upgrade the type, the call to that method would no longer work. #6416 
* Ensure that we never recommend upgrading the signature of a method that implements an interface method.
* Don't recommend a method to be upgraded if the method is an implementation of a partial method definition. This is because there might be different implementations of the method with conflicting behavior. Note …
> Bunch of fixes for CA1859

- src/Tools/GenerateAnalyzerNuspec/Program.cs
Closes https://github.com/dotnet/roslyn-analyzers/issues/6229
@jmarolf Can you please take a look?
> Generate packages props and targets in `buildTransitive` directory

- src/Microsoft.CodeAnalysis.Analyzers/UnitTests/Microsoft.CodeAnalysis.Analyzers.UnitTests.csproj
- src/Microsoft.CodeAnalysis.BannedApiAnalyzers/UnitTests/Microsoft.CodeAnalysis.BannedApiAnalyzers.UnitTests.csproj
- src/Microsoft.CodeAnalysis.ResxSourceGenerator/Microsoft.CodeAnalysis.ResxSourceGenerator.UnitTests/Microsoft.CodeAnalysis.ResxSourceGenerator.UnitTests.csproj
- src/NetAnalyzers/UnitTests/Microsoft.CodeAnalysis.NetAnalyzers.UnitTests.csproj
- src/PerformanceSensitiveAnalyzers/UnitTests/Microsoft.CodeAnalysis.PerformanceSensitiveAnalyzers.UnitTests.csproj
- src/PublicApiAnalyzers/UnitTests/Microsoft.CodeAnalysis.PublicApiAnalyzers.UnitTests.csproj
- src/Roslyn.Diagnostics.Analyzers/UnitTests/Roslyn.Diagnostics.Analyzers.UnitTests.csproj
- src/Test.Utilities/Test.Utilities.csproj
- src/Text.Analyzers/UnitTests/Text.Analyzers.UnitTests.csproj
- src/Tools/RulesetToEditorconfigConverter/Tests/RulesetToEditorconfigConverter.UnitTests.csproj
- src/Utilities.UnitTests/Analyzer.Utilities.UnitTests.csproj
- src/Utilities/Compiler/Lightup/IFunctionPointerInvocationOperationWrapper.cs
- src/Utilities/Compiler/Lightup/LightupHelpers.cs
- src/Utilities/Compiler/RulesetToEditorconfigConverter.cs
.NET Core 3.1 is out of support now.
It's also a pain for contributors working on Ubuntu as it seems 3.1 isn't supported in Ubuntu 22.04.
This change also (unintentionally) fixes https://github.com/dotnet/roslyn-analyzers/issues/6316 for me.
> Move tests to target .NET 7

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzer.cs
- src/NetAnalyzers/Microsoft.CodeAnalysis.NetAnalyzers.sarif
- src/NetAnalyzers/RulesMissingDocumentation.md
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzer.ObsoletedOSPlatformTests.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzerTests.GuardedCallsTests.cs
Backport https://github.com/dotnet/roslyn-analyzers/pull/6361 into .NET 7 release branch.
Issue: [.NET MAUI seeing lots of new CA1416 warnings](https://github.com/dotnet/roslyn-analyzers/issues/6158)
With https://github.com/dotnet/runtime/issues/68557 we added `ObsoletedOSPlatformAttribute` for annotating APIs that is Obsoleted but still works with a custom message for suggested alternative, then [added support for reporting new diagnostic with custom message in PCA](https://github.com/dotnet/roslyn-analyzers/pull/6082) which introduced one of the 2 bugs that fixed. The other bug was not known edge case scenario happening when a complex guard is used for calling an API that has annotations in the parent and the child API. 
The CA1416 Platform compatibility analyzer is included in SDK and …
> [release/7.0] Fix bugs found in MAUI repo

- src/Microsoft.CodeAnalysis.Analyzers/UnitTests/Microsoft.CodeAnalysis.Analyzers.UnitTests.csproj
- src/Microsoft.CodeAnalysis.BannedApiAnalyzers/UnitTests/Microsoft.CodeAnalysis.BannedApiAnalyzers.UnitTests.csproj
- src/Microsoft.CodeAnalysis.ResxSourceGenerator/Microsoft.CodeAnalysis.ResxSourceGenerator.UnitTests/Microsoft.CodeAnalysis.ResxSourceGenerator.UnitTests.csproj
- src/NetAnalyzers/UnitTests/Microsoft.CodeAnalysis.NetAnalyzers.UnitTests.csproj
- src/PerformanceSensitiveAnalyzers/UnitTests/Microsoft.CodeAnalysis.PerformanceSensitiveAnalyzers.UnitTests.csproj
- src/PublicApiAnalyzers/UnitTests/Microsoft.CodeAnalysis.PublicApiAnalyzers.UnitTests.csproj
- src/Roslyn.Diagnostics.Analyzers/UnitTests/Roslyn.Diagnostics.Analyzers.UnitTests.csproj
- src/Test.Utilities/Test.Utilities.csproj
- src/Text.Analyzers/UnitTests/Text.Analyzers.UnitTests.csproj
- src/Tools/RulesetToEditorconfigConverter/Tests/RulesetToEditorconfigConverter.UnitTests.csproj
- src/Utilities.UnitTests/Analyzer.Utilities.UnitTests.csproj
- src/Utilities/Compiler/Lightup/IFunctionPointerInvocationOperationWrapper.cs
- src/Utilities/Compiler/Lightup/LightupHelpers.cs
- src/Utilities/Compiler/RulesetToEditorconfigConverter.cs
Reverts dotnet/roslyn-analyzers#6364 to fix the build break in the repo
> Revert "Move tests to target .NET 7"

- src/Tools/GenerateAnalyzerNuspec/Program.cs
- src/Tools/GenerateDocumentationAndConfigFiles/Program.cs
- src/Tools/GenerateDocumentationAndConfigFiles/README.md
Fixes #6281
Prior implementation for `CodeAnalysisTreatWarningsAsErrors` passed `/warnaserror+:CAxxxx` to the compiler command line for each CA rule ID. This led to couple of issues:
1. All disabled by default CA warnings seem to get enabled as errors
2. Editorconfig/globalconfig based configuration of the enabled CA rules stops working.
The new implementation updates our globalconfig tooling to generate parallel globalconfigs with `_warnaserror` suffix, such that rules which would have had effective warning severity are set to error severity in the new globalconfig files. The targets/props that picks the appropriate globalconfig based on the `AnalysisLevel` property now chooses the file with `_warnaserror` suffix if user has enabled code analysis warnings to be treated as errors.
Another …
> Re-implement CodeAnalysisTreatWarningsAsErrors with globalconfig files

- src/Microsoft.CodeAnalysis.Analyzers/Core/ImmutableObjectMethodAnalyzer.cs
- src/Microsoft.CodeAnalysis.Analyzers/UnitTests/UseReturnValueFromImmutableObjectMethodTests.cs
> Fix RS1014 false positive discovered in roslyn

- src/Tools/GenerateDocumentationAndConfigFiles/Program.cs
- src/Tools/GenerateDocumentationAndConfigFiles/README.md
Fixes [AB#1726853](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1726853)
https://github.com/dotnet/roslyn-analyzers/pull/6427 re-implemented CodeAnalysisTreatWarningsAsErrors support using global config files instead of appending CA rule IDs to WarningsAsErrors and WarningsNotAsErrors properties. However, this new implementation only works as expected for `CodeAnalysisTreatWarningsAsErrors = true` case, but doesn't prevent escalating CA warnings to errors for `CodeAnalysisTreatWarningsAsErrors = false` and `TreatWarningsAsErrors = true` case. I am restoring the WarningsNotAsErrors logic deleted from https://github.com/dotnet/roslyn-analyzers/pull/6427 to fix this case.
I am also planning to file a separate tracking issue in Roslyn to see if we can implement this whole …
> Fix regression in CodeAnalysisTreatWarningsAsErrors when set to false

- eng/Version.Details.xml
- eng/Versions.props
- src/Directory.Build.props
PVP flow is a method of flowing dependencies in source build that only overrides versions of packages that the repo has a declared dependency on in Version.Details.xml. This means that the package flow is closer to the Microsoft's way of building .NET.
To enable this for roslyn-analyzers, we just need to add dependencis on the packages that should be overridden in source build. In this case, it's the compiler toolset package, and the Microsoft.CodeAnalysis package. I also cleaned up the CodeAnalysisVersion property to match the package name, however, I generally avoided adding dependencies that do not participate in source build. For example, System.CommandLine is used only in tooling that is not included in SB. It may be worth adding these dependencies to make it easier to track and …
> Changes to support 'PVP flow' in source-build

- src/NetAnalyzers/Core/AnalyzerReleases.Unshipped.md
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/MicrosoftNetCoreAnalyzersResources.resx
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/DoNotCallEnumerableCastOrOfTypeWithIncompatibleTypesAnalyzer.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.cs.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.de.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.es.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.fr.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.it.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ja.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ko.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.pl.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.pt-BR.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ru.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.tr.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.zh-Hans.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.zh-Hant.xlf
- src/NetAnalyzers/Microsoft.CodeAnalysis.NetAnalyzers.md
- src/NetAnalyzers/Microsoft.CodeAnalysis.NetAnalyzers.sarif
- src/NetAnalyzers/RulesMissingDocumentation.md
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/DoNotCallEnumerableCastOrOfTypeWithIncompatibleTypesAnalyzerTests.cs
- src/Utilities/Compiler/DiagnosticCategoryAndIdRanges.txt
Warn if use of `Enumerable.Cast<T>` would always fail at runtime or `OfType<T>()` would provably result in an empty sequence, because we can see that the input type in the sequence will never be the specified type.
RuleId: CA2019
Category: Reliability
related: https://github.com/dotnet/roslyn-analyzers/issues/3608, https://github.com/dotnet/runtime/issues/33770
> New Analyzer: Warn when calling Enumerable.Cast<T>/OfType<T> with incompatible types 

- src/NetAnalyzers/Core/AnalyzerReleases.Unshipped.md
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/DoNotCallEnumerableCastOrOfTypeWithIncompatibleTypesAnalyzer.cs
- src/NetAnalyzers/Microsoft.CodeAnalysis.NetAnalyzers.md
- src/NetAnalyzers/Microsoft.CodeAnalysis.NetAnalyzers.sarif
- src/NetAnalyzers/RulesMissingDocumentation.md
CA2021 is failing the CI build of the [PR that updating dependencies in runtime](https://github.com/dotnet/runtime/pull/80916), mostly on test projects. From failures we see several bugs that needs to fixed. As the analyzer is at warning level it could fail other repos too, so lowering the severity until the bugs are fixed CC @fowl2.
I will create an issue for the bugs shortly
> Lower the severity until bugs fixed

- src/Microsoft.CodeAnalysis.BannedApiAnalyzers/BannedApiAnalyzers.Help.md
- src/Microsoft.CodeAnalysis.BannedApiAnalyzers/Core/SymbolIsBannedAnalyzer.cs
- src/Microsoft.CodeAnalysis.BannedApiAnalyzers/UnitTests/SymbolIsBannedAnalyzerTests.cs
Hi, this is a PR to allow comment lines in the BannedApiAnalyzer's BannedSymbols.txt file.
Proposed format is:
```
T:MyNamespace.BannedClass
```
Internally at WiseTech Global, we use this to add comments to our banned symbols, giving some background information about why the particular symbol is banned and where to go for further information.
This is my first PR to this repo, so feedback is welcome.
Regards,
Mark
> BannedApiAnalyzer - allow comments in banned symbols file

- src/Common/Test/App.config
- src/Text.Analyzers/UnitTests/app.config
Fixes failure to run net472 tests in the IDE.
> Add missing binding redirects for Newtonsoft.Json

- src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/Maintainability/AvoidDeadConditionalCode_NullAnalysis.cs
- src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/Maintainability/AvoidDeadConditionalCode_ValueContentAnalysis.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PointsToAnalysis/DefaultPointsToValueGenerator.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAnalysis.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PointsToAnalysis/TrackedEntitiesBuilder.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/ValueContentAnalysis/ValueContentAnalysis.ValueContentDataFlowOperationVisitor.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/AnalysisEntity.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/AnalysisEntityDataFlowOperationVisitor.cs
Fixes #6453
While performing flow analysis for loops, we clear out the instance location for analysis entities when processing the back edges. This is primarily done because same operation when processed again might refer to a different runtime object/entity for a different loop iteration, and we have no way to known if any members accessed of this object point to the same runtime instance. Even though we were correctly setting the instance location for such entities to Unknown location on back edges, we were still continuining to track the analysis data for such entities. This led to multiple such distinct entities being considered identical and sharing the same flow analysis values, as seen in the bug repro case.
The fix here is to avoid tracking such child or instance member entities …
> Fix flow analysis to stop tracking entities which have unknown instance location

- docs/Analyzer Configuration.md
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/MicrosoftNetCoreAnalyzersResources.resx
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Performance/UseConcreteTypeAnalyzer.Collector.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Performance/UseConcreteTypeAnalyzer.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.cs.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.de.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.es.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.fr.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.it.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ja.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ko.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.pl.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.pt-BR.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ru.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.tr.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.zh-Hans.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.zh-Hant.xlf
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Performance/UseConcreteTypeTests.cs
- Add support to control the API surface the rule reports on using the normal api_surface annotation in .editorconfig. The rule defaults to 'private' only behavior.
- Add support to analyze properties.
- Skip analyzing interface types since that ends up being completely useless as there's nothing to recommend. So this saves some cycles.
- Reject analyzing partial method implementations earlier to save some
cycles.
- Fixes https://github.com/dotnet/roslyn-analyzers/issues/6452
- Fixes https://github.com/dotnet/roslyn-analyzers/issues/6440
- Fixes https://github.com/dotnet/roslyn-analyzers/issues/6451
- No longer recommends changing the method signature (either return
types or parameter types) for virtual and override methods.
- Now properly recognizes interpolated string expressions, …
> More work on CA1859

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Performance/DoNotGuardDictionaryRemoveByContainsKey.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Performance/DoNotGuardDictionaryRemoveByContainsKeyTests.cs
Only if `ContainsKey()` & `Remove()` are invoked on the **exact same field, property, parameter or local variable** will the CA1853 rule now kick in.
_Note that, as a result, if the methods are called using syntactically different but semantically equal references (e.g. 2 variables that have reference equality), the rule will not trigger._
Fixes #6377
> Fix CA1853 firing when another dictionary used for ContainsKey

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/SpecifyIFormatProvider.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/SpecifyIFormatProviderTests.cs
fixes #6217
- Add target method string as IFormatProviderOptionalRule parameter
- Update tests to cover new parameter
> Fix IFormatProviderOptionalRule Diagnostic message

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/SealInternalTypes.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/SealInternalTypesTests.cs
Backport #6278 into the .NET7 release branch
Issue: #6141 - CA1852 warns on generated Program for top-level statements
The CA1852 analyzer is hidden by default, but it is bulk configurable. Which means it is will be on if user choose to warn on all analyzers or on `Performance` category analyzers. Several customers asked about the porting in the issue #6141. For the customer who opened this PR they have all analyzers enabled with `TreatWarningsAsErrors` set to true in their project. So, they explicitly have to suppress this analyzer in order to compile. There is no workaround except suppressing the warning or upgrading to .NET 8 previews which is not desirable.  Accounting that top level statements are getting more and more popular the fix better to be serviced in 7.0.
No, but if we …
> [release/7.0.1xx] SealInternalTypes (CA1852): Don't warn for top-level type (#6278)

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/DoNotCallEnumerableCastOrOfTypeWithIncompatibleTypesAnalyzer.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/DoNotCallEnumerableCastOrOfTypeWithIncompatibleTypesAnalyzerTests.cs
Fix another case of #6457 where casting struct <-> interface would always flag.
> Fix CA2021 for casting interfaces from/to structs

- src/Microsoft.CodeAnalysis.Analyzers/Core/FixAnalyzers/FixerWithFixAllAnalyzer.cs
- src/Microsoft.CodeAnalysis.Analyzers/Microsoft.CodeAnalysis.Analyzers.sarif
Removes the Full Solution Analysis requirement from the following diagnostics:
* RS1010: Create code actions should have a unique EquivalenceKey for FixAll occurrences support
* RS1011: Use code actions that have a unique EquivalenceKey for FixAll occurrences support
* RS1016: Code fix providers should provide FixAll support
> Convert FixerWithFixAllAnalyzer to a symbol start/stop analyzer

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/MicrosoftNetCoreAnalyzersResources.resx
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Security/DoNotCallDangerousMethodsInDeserialization.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.cs.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.de.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.es.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.fr.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.it.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ja.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ko.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.pl.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.pt-BR.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ru.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.tr.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.zh-Hans.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.zh-Hant.xlf
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Security/DoNotCallDangerousMethodsInDeserializationTests.cs
Performance fix for [CA5360](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca5360): Stop tracking intermediate methods in CA5360 analysis. This seems to cause exponential increase in allocations and memory usage during analysis.
> Performance fix for CA5360 (Do not call dangerous methods in deserialization)

- src/Tools/GenerateDocumentationAndConfigFiles/Program.cs
Currently, we report an MSBuild warning when SDK NetAnalyzers version is higher than the referenced NuGet NetAnalyzers version. However, this seems to cause lot of annoyance if we haven't released the newer NuGet at the time newer SDK is released. This PR enhances this text by stating that this warning can be temporarily suppressed by setting '_SkipUpgradeNetAnalyzersNuGetWarning' property to 'true'.
> Enhance the text for NetAnalyzers upgrade warning

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/LoggerMessageDefineAnalyzer.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/LoggerMessageDefineTests.cs
fixes #5738
`AnalyzeInvocation` incorrectly set `argsIsArray = true` for every value of `paramsArgument`, so the analyzer did not work when a single argument was passed. We can accurately count the number of arguments whenever the value of `paramsArgument` is an array creation expression, implicit or otherwise.
Please let me know if I went overboard on the tests!
> Fix detection of single arguments for CA2017

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/UseExceptionThrowHelpers.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/UseExceptionThrowHelpersTests.cs
We were raising the diagnostic if any of the helpers on the type existed even if the specific one required didn't.
> Only report CA1512 if the specific helper required exists

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/InstantiateArgumentExceptionsCorrectly.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/InstantiateArgumentExceptionsCorrectlyTests.cs
InstantiateArgumentExceptionsCorrectlyAnalyzer is checking whether a parameter name exactly matches.  We recently decided our guidance is too strict here, and that it's reasonable for an ArgumentException ParameterName to be not just a parameter name but also inclusive of member access, e.g. "arg.Length", "arg[i]", etc.  This adds such a check to the analyzer to suppress diagnostics in such cases.
@terrajobst, @bartonjs, @tannergooding, @buyaa-n, this is what we talked about a few API reviews ago.
> Relax name validation in CA2208

- src/PublicApiAnalyzers/Core/Analyzers/DeclarePublicApiAnalyzer.Impl.cs
- src/PublicApiAnalyzers/Core/Analyzers/DeclarePublicApiAnalyzer.cs
Typing in roslyn shows this to be the highest allocation hitter.  This is because diagnostics will end up calling into this analyzer, which then rereads teh SourceText for these additional files, over and over again.
For example, this was typing just for just a few seconds:
> Cache the ApiData values we produce for an AdditionalText file.

- src/PublicApiAnalyzers/Core/Analyzers/DeclarePublicApiAnalyzer.Impl.cs
- src/PublicApiAnalyzers/Core/Analyzers/DeclarePublicApiAnalyzer.cs
About .6% when typing in roslyn.   Half is the arrays allocated for each line for .TrimStart, the other half are all the dictionary entries created over and over again as we merge apidata files.
> Reduce allocations more in public api analyzer

- src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/SymbolIsBannedInAnalyzersAnalyzer.cs
- src/Microsoft.CodeAnalysis.Analyzers/Core/Microsoft.CodeAnalysis.Analyzers.csproj
- src/Microsoft.CodeAnalysis.BannedApiAnalyzers/Core/DocumentationCommentIdParser.cs
- src/Microsoft.CodeAnalysis.BannedApiAnalyzers/Core/SymbolIsBannedAnalyzer.cs
- src/Microsoft.CodeAnalysis.BannedApiAnalyzers/Core/SymbolIsBannedAnalyzerBase.cs
The core problem here is that hte BannedSymbols analyzer starts with a top down walk that attempts to find the corresponding ISymbol for a symbol in the symbol tree.  This can be quite expensive as the compiler has to realize all the symbols downwards (in order to look up those names), including walking into symbols that might be enormous (consider large namespaces, or types with 10s of thousands of members).
This PR flips the general idea of hte banned-analyzer around.  Instead of upfront computing the list of banned symbols, we instead look for the *names* (and container names) specified in BannedSymbols.txt.  Then, as we're analyzing, *only* if we hit a real symbol with those names, do we attempt to them go map the banned-symbol line back to actual ISymbols, which we then compare the …
> Reduce excessive allocations in BannedSymbols analyzer.

- src/Text.Analyzers/Core/CodeAnalysisDictionary.cs
- src/Text.Analyzers/Core/IdentifiersShouldBeSpelledCorrectly.cs
Addresses the enormous amount of dictionary allocations performed on every compilation start:
> Improve performance of spell checking analyzer

- nuget/Microsoft.CodeAnalysis.ResxSourceGenerator/Microsoft.CodeAnalysis.ResxSourceGenerator.Package.csproj
- nuget/PerformanceSensitiveAnalyzers/Microsoft.CodeAnalysis.PerformanceSensitiveAnalyzers.Package.csproj
Fixes a failure to publish ResxSourceGenerator and PerformanceSensitiveAnalyzers to any consumable package feed.
> Publish packages

- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/CancellationTokenParametersMustComeLast.cs
- src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/CancellationTokenParametersMustComeLastTests.cs
- src/Utilities/Compiler/WellKnownTypeNames.cs
> Allow [CallerArgumnetExpressionAttribute] after CancellationToken

- src/Utilities/FlowAnalysis/BranchWithInfo.cs
Just happened to spot this suppression. Looks like the underlying analyzer bug was fixed so let's see if we can delete it.
> Remove unnecessary pragma suppression around ControlFlowConditionKind

- PostReleaseActivities.md
- eng/GenerateAnalyzerNuspec.targets
- src/Microsoft.CodeAnalysis.Analyzers/UnitTests/Microsoft.CodeAnalysis.Analyzers.UnitTests.csproj
- src/Microsoft.CodeAnalysis.BannedApiAnalyzers/UnitTests/Microsoft.CodeAnalysis.BannedApiAnalyzers.UnitTests.csproj
- src/Microsoft.CodeAnalysis.ResxSourceGenerator/Microsoft.CodeAnalysis.ResxSourceGenerator.UnitTests/Microsoft.CodeAnalysis.ResxSourceGenerator.UnitTests.csproj
- src/NetAnalyzers/UnitTests/Microsoft.CodeAnalysis.NetAnalyzers.UnitTests.csproj
- src/PerformanceSensitiveAnalyzers/UnitTests/Microsoft.CodeAnalysis.PerformanceSensitiveAnalyzers.UnitTests.csproj
- src/PublicApiAnalyzers/UnitTests/Microsoft.CodeAnalysis.PublicApiAnalyzers.UnitTests.csproj
- src/Roslyn.Diagnostics.Analyzers/UnitTests/Roslyn.Diagnostics.Analyzers.UnitTests.csproj
- src/Test.Utilities/Test.Utilities.csproj
- src/Text.Analyzers/UnitTests/Text.Analyzers.UnitTests.csproj
- src/Tools/GenerateAnalyzerNuspec/GenerateAnalyzerNuspec.csproj
- src/Tools/GenerateDocumentationAndConfigFiles/GenerateDocumentationAndConfigFiles.csproj
- src/Tools/GenerateDocumentationAndConfigFilesForBrokenRuntime/GenerateDocumentationAndConfigFilesForBrokenRuntime.csproj
- src/Tools/PerfDiff/PerfDiff.csproj
- src/Tools/ReleaseNotesUtil/ReleaseNotesUtil.csproj
- src/Tools/RulesetToEditorconfigConverter/Tests/RulesetToEditorconfigConverter.UnitTests.csproj
- src/Utilities.UnitTests/Analyzer.Utilities.UnitTests.csproj
- src/Utilities/Compiler/Extensions/.editorconfig
- src/Utilities/Compiler/Lightup/IFunctionPointerInvocationOperationWrapper.cs
- src/Utilities/Compiler/Lightup/LightupHelpers.cs
- src/Utilities/Compiler/RulesetToEditorconfigConverter.cs
Closes https://github.com/dotnet/roslyn-analyzers/issues/6490
> Move tests to target .NET 8

- src/Microsoft.CodeAnalysis.BannedApiAnalyzers/BannedApiAnalyzers.Help.md
- src/Microsoft.CodeAnalysis.BannedApiAnalyzers/Core/DocumentationCommentIdParser.cs
- src/Microsoft.CodeAnalysis.BannedApiAnalyzers/Core/SymbolIsBannedAnalyzerBase.cs
- src/Microsoft.CodeAnalysis.BannedApiAnalyzers/UnitTests/SymbolIsBannedAnalyzerTests.cs
The BannedApiAnalyzer refers to ["ID string format"](https://github.com/dotnet/csharpstandard/blob/standard-v6/standard/documentation-comments.md#d42-id-string-format) for reference on what symbols to ban. One of those symbols is Namespaces, but this is not supported. As this has been [requested before](https://github.com/dotnet/roslyn-analyzers/issues/2748) and is also something I ran into earlier today, it seems like a good fit to add to the project.
This will ban everything under namespace `A`, including child namespaces like `A.B` and `A.B.C`. Having an invocation like `new A.B.C.D()` will yield the error "The symbol 'A' is banned in this project":
```
N:A
```
I've chosen to report on the namespace of the symbol instead of the symbol itself for clarity. Reporting the symbol would …
> Support banning namespaces

- src/NetAnalyzers/Core/Microsoft.NetFramework.Analyzers/DoNotUseInsecureXSLTScriptExecution.cs
- src/NetAnalyzers/RulesMissingDocumentation.md
- src/NetAnalyzers/UnitTests/Microsoft.NetFramework.Analyzers/DoNotUseInsecureXSLTScriptExecutionXslCompiledTransformLoadInsecureConstructedSettingsTests.cs
- src/Test.Utilities/CSharpSecurityCodeFixVerifier`2.cs
> Support for target-typed new in Insecure XSLT script processing (CA3076)

- src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/Fixers/AnalyzerReleaseTrackingFix.cs
- src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/ReleaseTrackingHelper.cs
- src/Microsoft.CodeAnalysis.Analyzers/UnitTests/MetaAnalyzers/ReleaseTrackingAnalyzerTests.cs
> Added support markdown table headers in release tracking markdown files

- docs/Analyzer Configuration.md
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/Maintainability/AvoidUninstantiatedInternalClasses.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/SealInternalTypes.cs
- src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/Maintainability/AvoidUninstantiatedInternalClassesTests.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/SealInternalTypesTests.cs
- src/Utilities/Compiler/Options/EditorConfigOptionNames.cs
- Introduce the `ignore_internalsvisibleto` option to CA1812 and CA1852, enabling these rules to run even though an assembly has got InternalsVisibleTo definitions. The option defaults to `false` to maintain compatibility.
See https://github.com/dotnet/roslyn-analyzers/issues/5973
> Upgrade CA1812 and CA1852 to handle ivt

- src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/IdentifiersShouldNotContainUnderscoresTests.cs
- src/Utilities/Compiler/Extensions/ISymbolExtensions.cs
As discussed on "https://github.com/dotnet/roslyn/pull/68086" I also apply the code change here.
> Added support for multiple underscores as discards

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/MicrosoftNetCoreAnalyzersResources.resx
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.cs.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.de.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.es.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.fr.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.it.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ja.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ko.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.pl.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.pt-BR.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ru.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.tr.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.zh-Hans.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.zh-Hant.xlf
- src/NetAnalyzers/Microsoft.CodeAnalysis.NetAnalyzers.md
- src/NetAnalyzers/Microsoft.CodeAnalysis.NetAnalyzers.sarif
- src/NetAnalyzers/RulesMissingDocumentation.md
Updating messaging of CA1861 to apply the suggestion if the array argument is not mutated within the invoked method
Related to https://github.com/dotnet/runtime/pull/86229#issuecomment-1552360091 and https://github.com/dotnet/runtime/issues/86414
> Improve messaging of CA1861

- src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/AvoidMultipleEnumerationsTests.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzerTests.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/DetectPreviewFeatureUnitTests.Misc.cs
- src/Test.Utilities/AdditionalMetadataReferences.cs
Just minor cleanup, nothing more
> User proper reference assemblies of `net6.0` instead of self-crafted release candidate ones

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/AvoidConstArrays.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/AvoidConstArraysTests.cs
This PR excludes `static readonly` ReadOnlyCollections from triggering CA1861. Fixes #6629.
> Don't emit CA1861 for static ReadOnlyCollections

- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/UriParametersShouldNotBeStrings.cs
- src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/UriParametersShouldNotBeStringsTests.cs
Adds check for interface implementations when checking for string URI parameters, as these can be out of the user's control.
Fixes #6371
> Add check for interface implementations, CA1054

- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStatic.cs
- src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStaticTests.cs
The `MarkMembersAsStaticAnalyzer` currently checks if a method contains any instance reference operations. This PR adds an exclusion of the method itself, i.e. a recursive method, to that check.
Fixes #6540
> Emit CA1822 for recursive method.

- eng/Versions.props
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStatic.cs
- src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStaticTests.cs
Fixes https://github.com/dotnet/roslyn-analyzers/issues/6573
> Do not fire 'make member static' when a method references a primary constructor parameter.

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/AvoidConstArrays.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/AvoidConstArraysTests.cs
> Handle null initializer for array creation operation

- eng/Versions.props
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/OperatorOverloadsHaveNamedAlternates.cs
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/UseLiteralsWhereAppropriate.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/UseCancellationTokenThrowIfCancellationRequested.Fixer.cs
- src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/EnumsShouldHaveZeroValueTests.Fixer.cs
- src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/OperatorOverloadsHaveNamedAlternatesTests.Fixer.cs
- src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/OverrideEqualsOnOverloadingOperatorEqualsTests.Fixer.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/SealInternalTypesTests.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/UseSpanBasedStringConcatTests.cs
- src/NetAnalyzers/VisualBasic/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/BasicOverrideEqualsOnOverloadingOperatorEquals.vb
Fixes #6598
_Recommended to review ignoring whitespace differences_
- Move to latest Microsoft.CodeAnalysis package for unit tests
- Fix analyzers reporting non-local diagnostics
- Add comments to tests where `CodeFixTestBehaviors.SkipLocalDiagnosticCheck` cannot be removed
- Also fixed a code fixer relying on implicit tracking node functionality, which fails after moving to latest MS.CA bits.
> Fix analyzers/tests for non-local diagnostics

- src/Microsoft.CodeAnalysis.ResxSourceGenerator/Microsoft.CodeAnalysis.ResxSourceGenerator/AbstractResxGenerator.cs
I haven't seen the exception being surfaced as a diagnostic, but from reading the code, it seems possible.
> Prevent surfacing OperationCanceledException as diagnostic

- eng/Versions.props
- src/Test.Utilities/CSharpCodeFixVerifier`2+Test.cs
- src/Test.Utilities/VisualBasicCodeFixVerifier`2+Test.cs
* Update Microsoft.CodeAnalysis.Testing to 1.1.2-beta1.23322.1
* ~~Remove indirect reference to System.Drawing.Common~~ already handled by #6515
> Update test sdk

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Performance/UseConcreteTypeAnalyzer.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Performance/UseConcreteTypeTests.cs
Fixes #6659
Fixed #6565
Fixes #6687
Fixes #6704
> Fix a few bugs in CA1859.

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/InteropServices/UseValidPlatformString.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/InteropServices/UseValidPlatformStringTest.cs
We're adding support for the `net8.0-browser` TFM (see https://github.com/dotnet/runtime/issues/85333) and noticed the platform analyzer complains because we're using version 1.0 but there is no `IsBrowserVersionAtLeast()` method.
As far as I know we don't plan to add one (at least right now) which makes Browser a special case.
/cc @lewing @steveisok
> Remove error when targeting net8.0-browser1.0 TFM

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/AvoidConstArrays.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/AvoidConstArraysTests.cs
CA1861: `Avoid constant arrays as arguments` analyzer should not warn when the array creation has no array initializer.
Fixes https://github.com/dotnet/roslyn-analyzers/issues/6697
Related to https://github.com/dotnet/runtime/pull/87768#issuecomment-1602508045
> CA1861: Do not warn if not an array initializer.

- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/PropertiesShouldNotBeWriteOnly.cs
This ends up allocating `Location[]` here:
https://github.com/dotnet/roslyn-analyzers/blob/9653f963f44ab15d64e8131ed8240c249d3cb84d/src/Utilities/Compiler/Options/AnalyzerOptionsExtensions.cs#L34
and `MatchesConfiguredVisibility` might be generally slow. So we avoid calling it until we are about to issue a diagnostic.
In the trace I'm looking at currently, there is not so much allocations, but still an improvement.
> Improve PropertiesShouldNotBeWriteOnly performance

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/UseAsyncMethodInAsyncContext.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/UseAsyncMethodInAsyncContextTests.cs
- src/Utilities/Compiler/WellKnownTypeNames.cs
This PR adds exclusions for the `DbContext.Add()` and `DbContext.AddRange()` methods and fixes a false negative for `IDbContextFactory<DbContext>.CreateDbContext()` in the `UseAsyncMethodInAsyncContext` analyzer.
Fixes #6684.
> Don't emit CA1849 for DbContext methods

- src/PublicApiAnalyzers/Core/Analyzers/DeclarePublicApiAnalyzer.Impl.cs
On the profile I'm looking at, 11.4% of large object allocations are due to the ctor creation of the api map. There are two mitigations taken here:
1) Pre-size the dictionary as it's size is known. (I see over 6000 entries in this dictionary when in Roslyn.sln) 
2) Defer creation of the api map as it's not needed on many of the code paths where this object is created. For example, just typing inside a method appears to create several instances of this object, but I never see the api map dereferenced during that period.
> Reduce large memory allocations due to public api map construction.

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/SpecifyIFormatProvider.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/SpecifyIFormatProviderTests.cs
This PR fixes an issue where CA1305 is reported on nullable value types on any method invocation, when it should just be reporting on `ToString()` invocations. This was introduced by #6730.
Sorry about that!
Fixes #6745 and #6746
> Check method name for CA1305

- src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/Maintainability/AvoidDeadConditionalCode_NullAnalysis.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAnalysis.PointsToDataFlowOperationVisitor.cs
Fixes #6695
Fix predicated value flow in points to analysis to handle different types between the targetAnalysisEntity and different analysisEntity that shares the same location but has a different type. We use the conversion info between target type and analysis entity type to ensure the value can be flowed.
This change may likely fix other CA1508 false positives which involve conversions. I am going to try to add tests for such cases and see if they are fixed, and if so, add unit tests for them in this PR.
> Fix predicated analysis within points to analysis

- eng/Versions.props
- src/Test.Utilities/CSharpCodeFixVerifier`2+Test.cs
- src/Test.Utilities/VisualBasicCodeFixVerifier`2+Test.cs
Removes workarounds from #6711 which are no longer necessary.
> Update to Microsoft.CodeAnalysis.Testing 1.1.2-beta1.23357.1

- src/PublicApiAnalyzers/Core/Analyzers/DeclarePublicApiAnalyzer.Impl.cs
- src/PublicApiAnalyzers/UnitTests/DeclarePublicAPIAnalyzerTestsBase.cs
The delegate 'Invoke' signature defines the shape of the delegate, and is needed in teh public API file so that if it changes it is blocked.
> Include delegate 'Invoke' method in public API

- src/PublicApiAnalyzers/Core/Analyzers/DeclarePublicApiAnalyzer.Impl.cs
I wasn't able to reproduce the errors from Roslyn.sln in a unit testing configuration, so this is implementation-only.
> Do not report RS0041 or RS0057 for implicitly-declared symbols

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/UseStringEqualsOverStringCompare.cs
Since #6724 has been merged, this `pragma` directive can be removed.
> Remove unnecessary pragma

- src/Microsoft.CodeAnalysis.BannedApiAnalyzers/Core/SymbolIsBannedAnalyzer.cs
- src/Microsoft.CodeAnalysis.BannedApiAnalyzers/UnitTests/SymbolIsBannedAnalyzerTests.cs
This commit will filter out entries of banned symbols files that only contain a message and no declaration ID to prevent false RS0031.
Fixes #6633
> Prevent RS0031 for message only lines

- src/Microsoft.CodeAnalysis.BannedApiAnalyzers/Core/SymbolIsBannedAnalyzerBase.cs
- src/Microsoft.CodeAnalysis.BannedApiAnalyzers/UnitTests/SymbolIsBannedAnalyzerTests.cs
This PR changes the way the analyzer for RS0030 decides when attributes should be analyzed. It now also checks the `ContainerName`, because the `SymbolName` contains `.ctor` when trying to ban an attribute constructor.
Additionally, the symbol check is modified to allow method symbols that are constructors.
`AnalyzeAttributes` now also calls `VerifySymbol` for attribute constructors.
Fixes #6524
> RS0030: Support banning attribute constructors

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/PreferStringContainsOverIndexOf.Fixer.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/PreferStringContainsOverIndexOfAnalyzer.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/PreferStringContainsOverIndexOfTests.cs
Ran the new version against `dotnet/runtime` and found one new case:
[runtime/src/coreclr/tools/Common/Compiler/ProcessLinkerXmlBase.cs#L214](https://github.com/dotnet/runtime/blob/44c46e181a2a6f23a66f10924d8b7840150f18b7/src/coreclr/tools/Common/Compiler/ProcessLinkerXmlBase.cs#L214)
Also ran it against `dotnet/roslyn` -- found multiple `CA2249`, but most of them were already covered before this PR:
<details>
<summary>Paths</summary>
```
W:\roslyn\src\Compilers\Core\CodeAnalysisTest\Diagnostics\AnalysisContextInfoTests.cs(50,25): info CA2249: Use 'string.Contains' instead of 'string.IndexOf' to improve readability
W:\roslyn\src\Compilers\Core\MSBuildTask\CanonicalError.cs(273,17): info CA2249: Use 'string.Contains' instead of 'string.IndexOf' to improve readability …
```
> CA2249: Also trigger on `String.IndexOf() != -1`

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/InstantiateArgumentExceptionsCorrectly.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/InstantiateArgumentExceptionsCorrectlyTests.cs
This PR fixes a bug where diagnostics for all but the last arguments were not reported.
See also: https://github.com/dotnet/roslyn-analyzers/issues/6580#issuecomment-1637200714
I ran the analyzer against `dotnet/runtime` (no findings) and `dotnet/roslyn` (lots of CA2208, but none relate to the issue).
Fixes #6580
> CA2208: Find incorrect paramName in derived

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Performance/UseConcreteTypeAnalyzer.Collector.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Performance/UseConcreteTypeTests.cs
- The USeConcreteType analyzer didn't recognize array creation sequences which causes some analysis errors.
This fixes #6751
> Fix handling of array creation.

- src/NetAnalyzers/CSharp/Microsoft.NetCore.Analyzers/Performance/CSharpDoNotGuardDictionaryRemoveByContainsKeyFixer.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Performance/DoNotGuardDictionaryRemoveByContainsKeyTests.cs
- src/NetAnalyzers/VisualBasic/Microsoft.NetCore.Analyzers/Performance/BasicDoNotGuardDictionaryRemoveByContainsKey.vb
This PR will fix missing and incorrectly applied code fixes and adds additional tests to cover these cases.
The following has been changed:
1. Negated `dictionary.ContainsKey` calls now only report a diagnostic (added a wrong fix before). See `NegatedCondition_ReportsDiagnostic_CS` and `NegatedCondition_ReportsDiagnostic_VB`.
2. Additional statements in the if block now only report a diagnostic (added a wrong fix before). See `AdditionalStatements_ReportsDiagnostic_CS` and `AdditionalStatements_ReportsDiagnostic_VB`.
3. Fixer for single statement ifs in VB (did not work before). See `HasElseStatement_OffersFixer_VB`.
4. Add missing tests for VB, see `TriviaIsPreserved_VB` and `RemoveIsTheOnlyStatementInABlock_OffersFixer_VB`.
5. Remove `ConditionalExpressionSyntax` check for CS fixer as …
> CA1853: Fix incorrect code fixes

- src/Microsoft.CodeAnalysis.AnalyzerUtilities/PublicAPI.Unshipped.txt
- src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/Maintainability/AvoidDeadConditionalCode_NullAnalysis.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/CopyAnalysis/CopyAnalysis.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/CopyAnalysis/CopyAnalysisData.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAnalysis.PointsToAnalysisDomain.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAnalysis.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAnalysisData.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/TaintedDataAnalysis/TaintedDataAnalysis.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/TaintedDataAnalysis/TaintedDataAnalysisData.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/ValueContentAnalysis/ValueContentAnalysis.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/ValueContentAnalysis/ValueContentAnalysisData.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/AbstractIndex.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/AnalysisEntity.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/AnalysisEntityBasedPredicateAnalysisData.cs
Fixes #6616
We now ensure that setting an abstract value for an indexed access entity with any non-constant index clears out the existing value for entities that can overlap the indexed location
> Improve handling of indexed array access in flow analysis

- src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/OverrideEqualsOnOverloadingOperatorEqualsTests.cs
- src/NetAnalyzers/VisualBasic/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/BasicOverrideEqualsOnOverloadingOperatorEquals.vb
> Fix NRE in BasicOverrideEqualsOnOverloadingOperatorEqualsAnalyzer

- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/DisposeObjectsBeforeLosingScopeTests.cs
- src/Utilities/Compiler/Extensions/IMethodSymbolExtensions.cs
- src/Utilities/Compiler/Extensions/ITypeSymbolExtensions.cs
- src/Utilities/Compiler/WellKnownTypeNames.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/DisposeAnalysis/DisposeAnalysisHelper.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAnalysis.CorePointsToAnalysisDataDomain.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAnalysis.PointsToAnalysisDomain.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAnalysis.PointsToDataFlowOperationVisitor.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAnalysis.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAnalysisData.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs
We used to only track reference types and strings in PointsToAnalysis, which in turns leads to `ConfiguredAsyncDisposable` struct type returned from `TaskAsyncEnumerableExtensions.ConfigureAwait(this IAsyncDisposable, bool)` not being tracked, and hence the `await using` statement doesn't mark the original disposable object as being disposed.
Fixes #6765
Fixes #6512
> Track all disposable types in PointsToAnalysis

- src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/Maintainability/AvoidDeadConditionalCode_NullAnalysis.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs
Fixes #6048
`goto case DiscardPattern` had the required logic for setting the predicated value for the pattern value in true branch of the `is expression`, but it was also setting `predicateValueKind`, which is in turn used to identify redundant duplicate conditional checks. Latter is fixed by this change.
> Fix CA1508 false positive for pattern expressions

- src/NetAnalyzers/CSharp/Microsoft.NetCore.Analyzers/Performance/CSharpRecommendCaseInsensitiveStringComparisonFixer.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/MicrosoftNetCoreAnalyzersResources.resx
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Performance/RecommendCaseInsensitiveStringComparison.Analyzer.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Performance/RecommendCaseInsensitiveStringComparison.Fixer.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.cs.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.de.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.es.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.fr.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.it.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ja.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ko.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.pl.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.pt-BR.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ru.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.tr.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.zh-Hans.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.zh-Hant.xlf
- src/NetAnalyzers/Microsoft.CodeAnalysis.NetAnalyzers.md
- src/NetAnalyzers/Microsoft.CodeAnalysis.NetAnalyzers.sarif
- src/NetAnalyzers/RulesMissingDocumentation.md
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Performance/RecommendCaseInsensitiveStringComparison.Base.Tests.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Performance/RecommendCaseInsensitiveStringComparison.CSharp.Tests.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Performance/RecommendCaseInsensitiveStringComparison.VisualBasic.Tests.cs
- src/NetAnalyzers/VisualBasic/Microsoft.NetCore.Analyzers/Performance/BasicRecommendCaseInsensitiveStringComparisonFixer.vb
Fixes https://github.com/dotnet/runtime/issues/78607
Follow up of https://github.com/dotnet/runtime/issues/78606 
- Made sure it handles both `==`/`=` and `!=`/`<>` (C#/VB)
- Moved some code from the fixer to the analyzer and passed the result in the immutable dictionary (follow up of a suggestion by @Youssef1313)
- Added trivia support for both this new case and the original
> Recommend using Equals with StringComparison instead of string.ToLower() == otherString.ToLower()

- src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/Maintainability/AvoidDeadConditionalCode_NullAnalysis.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs
Fixes #5684
We were already performing escape analysis since #4113. However, we were not propertly resetting all the analysis data on encountering such escapes. In future, we can consider making the analysis more aggressive for such escapes by not resetting the entire analysis data on escapes, but instead just resetting the analysis data pertaining to capture variables and any points to locations reachable from these variables.
> Add conservative reset of analysis data in presence of escaped lambda and local function delegates

- eng/Version.Details.xml
This should hopefully address [compliance warnings](https://dev.azure.com/dnceng/internal/_componentGovernance/dotnet-roslyn-analyzers?_a=alerts&typeId=6265215&alerts-view-option=active) on the repo
See https://github.com/dotnet/source-build-reference-packages/pull/750 and https://github.com/dotnet/source-build-reference-packages/pull/747 for reference
> Move to latest source build reference packages

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzer.cs
Found with the new analyzer ~CA1865~ CA1868.
See #6767 and dotnet/runtime#85490.
> Remove guarded set add

- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/Maintainability/AvoidUnusedPrivateFields.cs
- src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/Maintainability/AvoidUnusedPrivateFieldsTests.cs
- src/Test.Utilities/AdditionalMetadataReferences.cs
- src/Utilities/Compiler/Extensions/ISymbolExtensions.cs
- src/Utilities/Compiler/WellKnownTypeNames.cs
> Avoid reporting CA1823 for inline arrays

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Performance/PreferDictionaryTryMethodsOverContainsKeyGuardAnalyzer.cs
- src/NetAnalyzers/RulesMissingDocumentation.md
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Performance/PreferDictionaryTryAddOverGuardedAddTests.cs
CA1864 now also triggers if the `value` argument passed to the `Add` method is a parameter.
Fixes #6824
> Include parameters for CA1864

- src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/Maintainability/AvoidDeadConditionalCode_NullAnalysis.cs
- src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/Maintainability/AvoidDeadConditionalCode_ValueContentAnalysis.cs
- src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/AvoidMultipleEnumerationsTests.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/CopyAnalysis/CopyAnalysis.CopyDataFlowOperationVisitor.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowAnalysis.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs
Fixes #5199
Fixes #5160
Fixes #4984
We already had implementation and option based support to perform exception path analysis to handle all operations that can potentially throw an exception, and hence need flow analysis data at the point of operation to be merged with analysis data at start of reachable catch blocks from that operation. However, we were only performing this analysis post pass when flow analysis is looking at exceptions data. Now we do it for all analysis as this is required for more accurate input analysis data at start of catch and finally blocks.
**NOTE:** Fixing this issue led to an assert firing in CodeAnalysis dataflow operation visitor for an existing unit test, which has also been fixed in this PR
> Perform exceptions path analysis for all flow analyses

- src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/RegisterActionAnalyzer.cs
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/TypeNamesShouldNotMatchNamespaces.cs
- src/Tools/GenerateAnalyzerNuspec/Program.cs
Closes #4520
Closes #4519
All these false positives have been fixed.
> Remove CA1508 pragma suppressions

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/UseAsyncMethodInAsyncContext.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/UseAsyncMethodInAsyncContextTests.cs
- src/Utilities/Compiler/WellKnownTypeNames.cs
fixes https://github.com/dotnet/efcore/issues/31431
Ignores DbSet.Add and DbSet.AddRange in CA1849 analyzer as well..
This currently generated a false positive if you call for example Add on a DbSet
```
myDbContext.Users.Add(new User("John Doe"));
```
> Don´t emit CA1849 when using DbSet.Add and DbSet.AddRange EntityFramework Methods

- azure-pipelines-microbuild.yml
Similar to the change we did in dotnet/runtime (https://github.com/dotnet/runtime/pull/90812), we need to temporarily switch the OneLocBuild MirrorBranch to point to the release/8.0.1xx branch to ensure all localization changes go there until we ship. This change will be reverted after we ship, so that we point to main again. We need to backport this to the [release/8.0.1xx](https://github.com/dotnet/roslyn-analyzers/tree/release/8.0.1xx) branch as well (like in https://github.com/dotnet/runtime/pull/90813).
@mavasani @sharwell @cristianosuzuki77 @buyaa-n @ericstj @ViktorHofer
> Change localization branch to release/8.0.1xx temporarily

- azure-pipelines-microbuild.yml
Backport of https://github.com/dotnet/roslyn-analyzers/pull/6890
Similar to the change we did in dotnet/runtime (https://github.com/dotnet/runtime/pull/90812), we need to temporarily switch the OneLocBuild MirrorBranch to point to the [release/8.0.1xx](https://github.com/dotnet/roslyn-analyzers/tree/release/8.0.1xx) branch to ensure all localization changes go there until we ship. This change will be reverted after we ship, so that we point to main again.
@mavasani @sharwell @cristianosuzuki77 @buyaa-n @ericstj @ViktorHofer
> [release/8.0.1xx] Change localization branch to release/8.0.1xx temporarily

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/MicrosoftNetCoreAnalyzersResources.resx
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/ProvideCorrectArgumentsToFormattingMethods.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.cs.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.de.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.es.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.fr.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.it.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ja.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ko.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.pl.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.pt-BR.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ru.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.tr.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.zh-Hans.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.zh-Hant.xlf
- src/NetAnalyzers/RulesMissingDocumentation.md
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/ProvideCorrectArgumentsToFormattingMethodsTests.cs
Fixes #6012 
See also https://github.com/dotnet/runtime/issues/90357
Prevents IndexOutOfRangeException, but also checks formats of non-formatting methods.
> Runtime90357 6012

- .github/workflows/backport.yml
Similar to [what we have in dotnet/runtime](https://github.com/dotnet/runtime/blob/main/.github/workflows/backport.yml#L15), I am enabling the bot functionality to automatically backport PRs from one branch to another by simply using the command:
```
/backport to <BranchName>
```
This will be helpful to backport PRs from main to 8.0. Example:
```
/backport to release/8.0.1xx
```
> Add backporting yml job

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/DoNotUseEnumerableMethodsOnIndexableCollectionsInsteadUseTheCollectionDirectly.cs
> Refactor CA1826 to read option only when needed and use SpecialType checks

- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/Maintainability/AvoidUninstantiatedInternalClasses.cs
Part of https://github.com/dotnet/roslyn-analyzers/issues/6301
I'm not marking this PR as a fix for #6301 as I think there may be a room for more performance improvements. This is only a quick pass.
> [Performance] Improve AvoidUninstantiatedInternalClasses performance

- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/PropertiesShouldNotBeWriteOnly.cs
- src/Utilities/Compiler/Extensions/ISymbolExtensions.cs
> Refactor PropertiesShouldNotBeWriteOnlyAnalyzer (CA1044)

- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/EnumShouldNotHaveDuplicatedValues.cs
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/EquatableAnalyzer.cs
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/ImplementIDisposableCorrectly.cs
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStatic.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/ModuleInitializerAttributeShouldNotBeUsedInLibraries.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Usage/ImplementGenericMathInterfacesCorrectly.cs
- src/NetAnalyzers/Core/Microsoft.NetFramework.Analyzers/MarkVerbHandlersWithValidateAntiforgeryTokenAnalyzer.cs
> Use direct cast instead of type checking when type is known

- src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/ValidateArgumentsOfPublicMethodsTests.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs
Fixes https://github.com/dotnet/roslyn-analyzers/issues/6755
@mavasani I have added very very minimal handling for binary patterns.
This doesn't handle declaration patterns, etc etc.
I can try to go further with the implementation whenever I get time again :)
I know my implementation might not be good enough. So, feel free if you wanted to close this PR and have a completely different fix.
> Add minimal binary pattern support for null checks in DFA

- src/NetAnalyzers/CSharp/Microsoft.NetCore.Analyzers/Runtime/CSharpUseSpanBasedStringConcat.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/UseSpanBasedStringConcat.cs
- src/NetAnalyzers/VisualBasic/Microsoft.NetCore.Analyzers/Runtime/BasicUseSpanBasedStringConcat.vb
There is no need to maintain `topMostConcatOperations` in a set. This can be a simple operation analyzer without operation block start/end actions.
This implementation should be more performant and also more simple.
> [Performance] Simplify UseSpanBasedStringConcat for better performance

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/SpecifyIFormatProvider.cs
> [Performance] Improve SpecifyIFormatProvider (CA1305) performance

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/InteropServices/UseValidPlatformString.cs
- src/Utilities/Compiler/Extensions/ISymbolExtensions.cs
> [Performance] Improve UseValidPlatformString (CA1418) performance

- src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/AnalysisEntityBasedPredicateAnalysisData.cs
Fixes #6929
Ensure that we do not perform any state updates to the dataflow CoreAnalysisData inside the loop for the method `ClearOverlappingAnalysisDataForIndexedEntity`. We instead collect the key-value pairs to be updated in the loop, and perform these updates after the loop.
I haven't been able to come up with a minimal repro case that reproduces this exception, but the loop for which exception was generated can no longer perform any state updates, so we can be quite certain the underlying exception can no longer be thrown.
> Avoid 'Collection was modified' InvalidOperationException

- NuGet.config
I am unsure how roslyn-analyzers works but it seems to be correctly pushing the nuget packages generated from main into the `dotnet9` feed. Example: The `Microsoft.CodeAnalysis.NetAnalyzers` package was correctly pushed to the `dotnet9` feed (see [here](https://dev.azure.com/dnceng/public/_artifacts/feed/dotnet9/NuGet/Microsoft.CodeAnalysis.NetAnalyzers/versions/9.0.0-preview.23463.2)) immediately after we merged this PR: https://github.com/dotnet/roslyn-analyzers/pull/6935
But just in case, and because it seems to be the proper change, I am adding the two missing feeds to `main`.
The old feeds are still there. I am unsure if we should remove them.
> Add dotnet9 and dotnet9-transport feeds

- src/NetAnalyzers/CSharp/Microsoft.NetCore.Analyzers/Performance/CSharpUseSearchValues.Fixer.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Performance/UseSearchValuesTests.cs
Fixed an edge-case code fixer issue where we would replace
```c#
new[] { (byte)'ÿ', (byte)'a', (byte)'e', (byte)'i', (byte)'o', (byte)'u' }
```
with
```c#
"ÿaeiou"u8
```
which is different (`"ÿ"u8` being two bytes).
I'm not sure this is a meaningful case anyone would actually hit, but we should still avoid changing the behavior in an unobvious way.
> Fix SearchValues fixer introducing slight changes for edge case inputs

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Performance/UseConcreteTypeAnalyzer.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Performance/UseConcreteTypeTests.cs
> Handle reference to non-source symbols in UseConcreteTypeAnalyzer

- src/NetAnalyzers/CSharp/Microsoft.NetCore.Analyzers/Performance/CSharpUseStringMethodCharOverloadWithSingleCharacters.Fixer.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Performance/UseStringMethodCharOverloadWithSingleCharactersTests.cs
- src/NetAnalyzers/VisualBasic/Microsoft.NetCore.Analyzers/Performance/BasicUseStringMethodCharOverloadWithSingleCharacters.Fixer.vb
> Preserve trivia when fixing CA1865

- src/Tools/GenerateDocumentationAndConfigFiles/Program.cs
Fixes design time builds and IDE code analysis for projects using ResxSourceGenerator and culture-specific resource files.
Review commit-by-commit recommended
> AddAllResxFilesAsAdditionalFiles depends on PrepareResourceNames

- src/PublicApiAnalyzers/Core/Analyzers/DeclarePublicApiAnalyzer.Impl.cs
- src/PublicApiAnalyzers/UnitTests/DeclarePublicAPIAnalyzerTestsBase.cs
Fixes #6759
Experimental items are shown in API files with a `[diagnosticId]` prefix, where `diagnosticId` is the ID provided to `ExperimentalAttribute`.
> Add support for ExperimentalAttribute

- src/NetAnalyzers/CSharp/Microsoft.NetCore.Analyzers/Resources/CSharpMarkAssembliesWithNeutralResourcesLanguage.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Resources/MarkAssembliesWithNeutralResourcesLanguage.cs
- src/NetAnalyzers/Microsoft.CodeAnalysis.NetAnalyzers.sarif
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Resources/MarkAssembliesWithNeutralResourcesLanguageTests.cs
- src/NetAnalyzers/VisualBasic/Microsoft.NetCore.Analyzers/Resources/BasicMarkAssembliesWithNeutralResourcesLanguage.vb
- src/Utilities/Compiler/Extensions/DiagnosticExtensions.cs
The intent of this change is two things:
1. Avoid analyzing more attributes if we already found a matching attribute.
2. Having this analyzer not be a compilation end analyzer.
@mavasani @sharwell Do you think it's worth changing this analyzer to not be non-compilation-end (which will make it available in IDE live diagnostics)?
Is there a better than what I did here?
> Write CA1824 as non-compilation-end

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Performance/AvoidSingleUseOfLocalJsonSerializerOptions.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Performance/AvoidSingleUseOfLocalJsonSerializerOptionsTests.cs
Fixes https://github.com/dotnet/roslyn-analyzers/issues/6957
> Fix false-flag of CompareExchange and re-usage with loops

- src/Microsoft.CodeAnalysis.ResxSourceGenerator/Microsoft.CodeAnalysis.ResxSourceGenerator.UnitTests/Verifiers/CSharpSourceGeneratorVerifier`1+Test.cs
> Adjust source generator verifier for broader usability

- eng/Versions.props
- src/Microsoft.CodeAnalysis.BannedApiAnalyzers/UnitTests/Microsoft.CodeAnalysis.BannedApiAnalyzers.UnitTests.csproj
- src/Microsoft.CodeAnalysis.BannedApiAnalyzers/UnitTests/RestrictedInternalsVisibleToAnalyzerTests.cs
- src/Microsoft.CodeAnalysis.BannedApiAnalyzers/UnitTests/SymbolIsBannedAnalyzerTests.cs
- src/PerformanceSensitiveAnalyzers/Core/ExplicitAllocationAnalyzer.cs
- src/PerformanceSensitiveAnalyzers/UnitTests/Microsoft.CodeAnalysis.PerformanceSensitiveAnalyzers.UnitTests.csproj
* Remove special case MicrosoftCodeAnalysisVersionForBannedApiAnalyzersTests
* Remove special case MicrosoftCodeAnalysisVersionForPerfSensitiveAnalyzersTests
> Update version used in tests

- eng/Versions.props
Reverts dotnet/roslyn-analyzers#7002
Stabilizing packages in roslyn-analyzers isn't required for the .NET 8 release.
> Revert "[release/8.0] Stabilize package versions for .NET 8"

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/UseAsyncMethodInAsyncContext.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/UseAsyncMethodInAsyncContextTests.cs
This PR ensures that referencing properties like `Task<T>.Result` and `ValueTask<T>.Result` in a `nameof` expression doesn't trigger CA1849.
Fixes #6993
> Don't emit CA1849 for nameof expressions

- eng/Versions.props
Allows testing fixers without an analyzer, e.g. when testing a diagnostic generated from an `ObsoleteAttribute`.
See dotnet/roslyn-sdk#1117 for more information.
> Update to Microsoft.CodeAnalysis.Testing 1.1.2-beta1.23509.1

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/AvoidConstArrays.Fixer.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/AvoidConstArraysTests.cs
The current implementation only considers the type's members when generating a name for the array. This PR extends the fixer to also consider method parameters and method locals.
Fixes https://github.com/dotnet/roslyn-analyzers/issues/6981
> Generate unique name for CA1861

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/SerializationRulesDiagnosticAnalyzer.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/MarkISerializableTypesWithSerializableTests.cs
> CA2237: Don't report diagnostic when ISerializable is inherited

- src/Tools/GenerateDocumentationAndConfigFiles/Program.cs
Addresses part of the problem reported in https://github.com/dotnet/roslyn-analyzers/issues/6878 by deleting the target that we have determined does not add enough value.
> Remove target that warns that user needs to upgrade to a newer SDK NetAnalyzers version

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/UseAsyncMethodInAsyncContext.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/UseAsyncMethodInAsyncContextTests.cs
- src/Utilities/Compiler/WellKnownTypeNames.cs
> Don't emit CA1849 for IDbContextFactory.CreateDbContext

- src/Microsoft.CodeAnalysis.Analyzers/CSharp/MetaAnalyzers/CSharpSymbolIsBannedInAnalyzersAnalyzer.cs
- src/Microsoft.CodeAnalysis.Analyzers/VisualBasic/BasicSymbolIsBannedInAnalyzersAnalyzer.vb
- src/Microsoft.CodeAnalysis.BannedApiAnalyzers/CSharp/CSharpSymbolIsBannedAnalyzer.cs
- src/Microsoft.CodeAnalysis.BannedApiAnalyzers/Core/SymbolIsBannedAnalyzerBase.cs
- src/Microsoft.CodeAnalysis.BannedApiAnalyzers/UnitTests/SymbolIsBannedAnalyzerTests.cs
- src/Microsoft.CodeAnalysis.BannedApiAnalyzers/VisualBasic/BasicSymbolIsBannedAnalyzer.vb
- src/Test.Utilities/CSharpCodeFixVerifier`2+Test.cs
Fixes #6841 
Note I've had to change `XUnitVerifier` to `DefaultVerifier` due to the following exception:
```
Error Message:
System.MissingMethodException : Method not found: 'Void Xunit.Sdk.EqualException..ctor(System.Object, System.Object)'.
Stack Trace:
at Microsoft.CodeAnalysis.Testing.Verifiers.EqualWithMessageException..ctor(Object expected, Object actual, String userMessage)
at Microsoft.CodeAnalysis.Testing.Verifiers.XUnitVerifier.Equal[T](T expected, T actual, String message) in /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Testing.Verifiers.XUnit/XUnitVerifier.cs:line 49
```
See https://github.com/dotnet/roslyn-sdk/issues/1099#issuecomment-1723487931
> BannedApiAnalyzers: Support banning base types

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/ProvideCorrectArgumentsToFormattingMethods.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/ProvideCorrectArgumentsToFormattingMethodsTests.cs
> CA2241: Non supported heuristically found format methods should not be checked.

- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/Maintainability/AvoidDeadConditionalCode.cs
- src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/Maintainability/AvoidDeadConditionalCode_ValueContentAnalysis.cs
> Don't emit CA1508 in Debug.Assert

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/AvoidConstArrays.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/AvoidConstArraysTests.cs
This PR modifies the `AvoidConstArraysAnalyzer` to not raise for attribute arguments.
Is there any possibility to use the `IAttributeOperation` API? Otherwise I am stuck using the current workaround to check for an attribute.
Fixes #7033
> Don't raise CA1861 in for attribute arguments

- azure-pipelines-microbuild.yml
Now that we shipped 8.0.1xx, we need to revert localization back to point to main. I already opened the [internal issue](https://ceapex.visualstudio.com/CEINTL/_workitems/edit/931170) for the loc team to track this request.
Here is the old PR that temporarily moved main to 8.0.1xx: https://github.com/dotnet/roslyn-analyzers/pull/6890/files
**Question**: This change [was also backported to the 8.0.1xx](https://github.com/dotnet/roslyn-analyzers/pull/6891) branch. Do I also need to revert the change in that branch, or can that one stay as is?
Edit: **Answer**: I need to backport it to release/8.0.2xx. I don't think I should backport it to 8.0.1xx, that branch won't be active again.
> Change localization back to main

- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/ParameterNamesShouldMatchBaseDeclaration.cs
- src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/ParameterNamesShouldMatchBaseDeclarationTests.cs
When implementing or overriding a method with a generic parameter, it often makes sense to deviate from the parameters name to make it more explicit. For example:
```csharp
public interface IService<TEntity>
{
void Update(TEntity entity);
}
public class User {}
public class UserService : IService<User>
{
public void Update(User user) {}
}
```
Implementing the method as `public void Update(User entity) {}` feels awkward.
> Suppress CA1725 for generic parameters

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/InstantiateArgumentExceptionsCorrectly.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/InstantiateArgumentExceptionsCorrectlyTests.cs
> fix(CA2208): false positive when message start with parameter name followed by punctuation

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/AvoidConstArrays.Fixer.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/AvoidConstArraysTests.cs
This PR adds support for invoking the fixer for the  `AvoidConstArrays` analyzer when in top-level statements.
Fixes #7111
> Create fix for CA1861 in top level statements

- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/EnumWithFlagsAttribute.cs
- src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/EnumWithFlagsAttributeTests.cs
> Fix CA1027 fires for simple aliases

- src/Microsoft.CodeAnalysis.Analyzers/Core/FixAnalyzers/FixerWithFixAllAnalyzer.Fixer.cs
- src/Microsoft.CodeAnalysis.Analyzers/Core/FixAnalyzers/FixerWithFixAllAnalyzer.cs
- src/Microsoft.CodeAnalysis.Analyzers/UnitTests/FixAnalyzers/FixerWithFixAllAnalyzerTests.Fixer.cs
- src/Microsoft.CodeAnalysis.Analyzers/UnitTests/FixAnalyzers/FixerWithFixAllAnalyzerTests.cs
- src/Utilities/Compiler/WellKnownTypeNames.cs
Fixes #5818
I've used the suggestion from @Youssef1313 to use the `ExportCodeFixProvider` attribute to decide whether to report RS1016 instead of looking at the base type of the code fix provider.
This change means that RS1016 will now _only_ report a diagnostic on a code fix provider that is exported.
I have also fixed up some of the VB.NET tests:
* The test `VisualBasic_VerifyFix_NonSealedTypeAsync` was skipped because of dotnet/roslyn#23410. That bug was fixed quite a while ago, so I've stopped skipping it and fixed the code so that it passes.
* Most of the other VB.NET tests in `FixerWithFixAllAnalyzerTests.Fixer.cs` weren't actually testing anything. The original source code did not produce RS1016, and the "fixed" code was the same as the original code.
> Use ExportCodeFixProviderAttribute to trigger RS1016

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Performance/PreferLengthCountIsEmptyOverAnyAnalyzer.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Performance/PreferLengthOverAnyTests.cs
> Suppress CA1860 when in expression tree

- eng/Versions.props
- src/Roslyn.Diagnostics.Analyzers/Core/AbstractDoNotCopyValue.cs
- src/Roslyn.Diagnostics.Analyzers/Core/RefKindEx.cs
- src/Roslyn.Diagnostics.Analyzers/UnitTests/DoNotCopyValueTests.cs
- src/Roslyn.Diagnostics.Analyzers/UnitTests/ImportingConstructorShouldBeObsoleteTests.cs
> Support RefKind.RefReadOnlyParameter in RS0042 (Do not copy value)

- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/DoNotRaiseExceptionsInUnexpectedLocations.cs
- src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/DoNotRaiseExceptionsInUnexpectedLocationsTests.cs
> CA1065: Consider explicit interface implementations of Equals, GetHashCode

- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/DoNotDeclareStaticMembersOnGenericTypes.cs
- src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/DoNotDeclareStaticMembersOnGenericTypesTests.cs
> Allow static virtual members in CA1000

- src/Microsoft.CodeAnalysis.Analyzers/Core/AnalyzerBannedSymbols.txt
Related to #7086
I looked into this scenario further and found the doc [Localizing Analyzers](https://github.com/dotnet/roslyn/blob/1b158968d85dfc7bce5baaf8795ada93e2e44527/docs/analyzers/Localizing%20Analyzers.md#using-localized-resources-in-analyzers). Basically, it appears that the pattern we want analyzer authors to use is to put culture-dependent formattable strings in a `.resx` file, and refer to those strings using [LocalizableResourceString](https://learn.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.localizableresourcestring?view=roslyn-dotnet-4.7.0).
It's possible that we will still want to introduce a public API to get the `CultureInfo` which is being used by the compiler, mentioned in https://github.com/dotnet/roslyn-analyzers/issues/7086#issuecomment-1907101557. But I …
> Adjust message for banned symbol CultureInfo.CurrentCulture

- src/Microsoft.CodeAnalysis.Analyzers/RulesMissingDocumentation.md
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/MicrosoftNetCoreAnalyzersResources.resx
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.cs.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.de.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.es.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.fr.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.it.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ja.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ko.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.pl.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.pt-BR.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.ru.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.tr.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.zh-Hans.xlf
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/xlf/MicrosoftNetCoreAnalyzersResources.zh-Hant.xlf
- src/NetAnalyzers/Microsoft.CodeAnalysis.NetAnalyzers.md
- src/NetAnalyzers/Microsoft.CodeAnalysis.NetAnalyzers.sarif
> Fix grammar for CA2262's description

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzer.cs
> In PlatformCompatiblityAnalyzer, set ObsoleteUrl based on child ObsoleteUrl

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/DoNotCallEnumerableCastOrOfTypeWithIncompatibleTypesAnalyzer.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/DoNotCallEnumerableCastOrOfTypeWithIncompatibleTypesAnalyzerTests.cs
Can't say I really understand this that well, but adds the test case and fixes #7153 without breaking anything else as far I can tell.
---- 
The code was previously using `ITypeSymbol` property `AllInterfaces` which says the seemly relevantly:
> // This is not quite the same as "all interfaces of which this type
> // is a proper subtype" 
However, I couldn't find any sort of "proper subtype" API. 
So this change sprinkles some `OriginalDefinition` calls around, and switches to using `DerivesFrom` - which calls `OriginalDefinition` on all the interface symbols before checking equality.
> fix CA2021 false positives

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/InteropServices/DynamicInterfaceCastableImplementation.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/InteropServices/DynamicInterfaceCastableImplementationTests.cs
> Don't report CA2257 on nested types

- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/DoNotRaiseExceptionsInUnexpectedLocations.cs
- src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/DoNotRaiseExceptionsInUnexpectedLocationsTests.cs
- src/Utilities/Compiler/WellKnownTypeNames.cs
> CA1065: Ignore System.Diagnostics.UnreachableException

- eng/Versions.props
- src/Roslyn.Diagnostics.Analyzers/Core/AbstractDoNotCopyValue.cs
- src/Roslyn.Diagnostics.Analyzers/UnitTests/DoNotCopyValueTests.cs
- src/Utilities/Compiler/Lightup/OperationKindEx.cs
This supports using a collection expression to initialize a non-copyable collection type.
> Support collection expressions for non-copyable analyzer

- src/NetAnalyzers/CSharp/Microsoft.NetCore.Analyzers/Performance/CSharpDoNotUseCountWhenAnyCanBeUsed.Fixer.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Performance/UseCountProperly.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Performance/DoNotUseCountWhenAnyCanBeUsedTests.Tests.cs
> Make CA1827 fire for 'is' patterns.

- src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/DiagnosticAnalyzerFieldsAnalyzer.cs
- src/Microsoft.CodeAnalysis.Analyzers/UnitTests/MetaAnalyzers/DoNotStorePerCompilationDataOntoFieldsRuleTests.cs
> Report RS1008 for ISymbol and IOperation fields

- src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/Maintainability/AvoidUnusedPrivateFieldsTests.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Performance/UseSearchValuesTests.cs
- src/PublicApiAnalyzers/UnitTests/DeclarePublicAPIAnalyzerTestsBase.cs
- src/Test.Utilities/AdditionalMetadataReferences.cs
> Remove temporary .NET 8 reference assemblies

- azure-pipelines-microbuild.yml
The task is not part of the other build steps.
Fixes CodeQL step broken in official builds since https://github.com/dotnet/roslyn-analyzers/pull/7096. Test run: https://dev.azure.com/dnceng/internal/_build/results?buildId=2397941&view=results
> Remove unnecessary install .NET task

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Usage/PreferGenericOverloads.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Usage/PreferGenericOverloadsTests.cs
> CA2263: Fix wrong fix for notnull constraints and fix crash on unbound generic types

- eng/Versions.props
Adds `ReferenceAssemblies.Net.Net90` needed for a few tests in https://github.com/dotnet/roslyn-analyzers/pull/6967.
> Update to Microsoft.CodeAnalysis.Testing 1.1.2-beta1.24168.2

- src/Roslyn.Diagnostics.Analyzers/Core/AbstractDoNotCopyValue.cs
- src/Roslyn.Diagnostics.Analyzers/UnitTests/DoNotCopyValueTests.cs
> Improve support for RefKind.RefReadOnlyParameter in RS0042 (Do not copy value)

- azure-pipelines-microbuild.yml
Validation build is at https://dev.azure.com/dnceng/internal/_build/results?buildId=2410326&view=results. (SBOM publishing failure warning pending. Should not be a blocker though.)
> Migrate to 1ES template migration for official builds and mark others accordingly

- azure-pipelines-microbuild.yml
Follow up on https://github.com/dotnet/roslyn-analyzers/pull/7253.
Currently official builds are getting stuck on CodeQL step: https://dnceng.visualstudio.com/internal/_build/results?buildId=2414766&view=results (interestingly, test run of https://github.com/dotnet/roslyn-analyzers/pull/7253 didn't get stuck, not sure why)
Test run of an official build of this PR: https://dnceng.visualstudio.com/internal/_build/results?buildId=2414884&view=results
This is like a change done in roslyn-sdk to resolve the same problem: https://github.com/dotnet/roslyn-sdk/pull/1152/commits/816cd02d2f99bde68614c6d833291b1a1fbbdff3
> Remove CodeQL tasks duplicating injected ones

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/AvoidUnreliableStreamRead.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/AvoidUnreliableStreamReadTests.cs
Fixes #7268.
I only excluded exact type matches of known reliable stream types (i.e. instances of `System.IO.MemoryStream` or `System.IO.UnmanagedMemoryStream`).
Let me know if we want to exclude child classes as well, but it seems based on the comment in the issue (https://github.com/dotnet/roslyn-analyzers/issues/7268#issuecomment-2021040159) that this could lead to false negatives.
We could detect more cases with flow analysis, but this would mean that the rule is disabled by default (AFAIK).
cc @buyaa-n @stephentoub
> CA2022: Do not flag well known reliable stream types

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/AvoidUnreliableStreamRead.cs
Follow-up from https://github.com/dotnet/roslyn-analyzers/pull/7269#discussion_r1540391779.
> CA2022: Specify IEqualityComparer when creating well known type set

- src/NetAnalyzers/CSharp/Microsoft.NetCore.Analyzers/Performance/CSharpUseSearchValues.Fixer.cs
- src/NetAnalyzers/CSharp/Microsoft.NetCore.Analyzers/Performance/CSharpUseSearchValues.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Performance/UseSearchValues.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Performance/UseSearchValuesTests.cs
- src/Utilities/Compiler/Analyzer.Utilities.projitems
- src/Utilities/Compiler/Lightup/ICollectionExpressionOperationWrapper.cs
- src/Utilities/Compiler/Lightup/OperationWrapperHelper.cs
Followup after #6898 to add recognition for collection expression patterns as well.
Currently, if you write something like
```c#
private static readonly char[] s_chars = new[] { 'a', 'e', 'i', 'o', 'u', 'A' };
public static int Test(ReadOnlySpan<char> s) => s.IndexOfAny(s_chars);
```
you will be offered two fixers: one to replace `s_chars` with `SearchValues.Create("aeiouA")`, and the other to replace the array creation with `['a', 'e', 'i', 'o', 'u', 'A']`.
If you accept the latter, you won't be offered the `SearchValues` fixer anymore since we don't recognize the pattern.
This PR adds recognition for patterns like
```c#
static readonly char[] s_chars = ['a', 'e', 'i', 'o', 'u', 'A'];
text.IndexOfAny(['a', 'e', 'i', 'o', 'u', 'A']);
text.IndexOfAny([(byte)'a', (byte)'e', (byte)'i', …
```
> Add CollectionExpression support to CA1870 (UseSearchValues)

- eng/Publishing.props
Fixes: https://github.com/dotnet/source-build/issues/4204
In the past we've required additional packages to be published to VMR location, during source-build. This was carried over with recent publishing work that modified VMR build to use regular arcade publishing infra - https://github.com/dotnet/source-build/issues/4204
With new changes in https://github.com/dotnet/installer/pull/19343 this is not needed anymore.
> Stop publishing of additional packages

- src/NetAnalyzers/CSharp/Microsoft.NetCore.Analyzers/Performance/CSharpUseSearchValues.cs
- src/Utilities/Compiler.CSharp/Analyzer.CSharp.Utilities.projitems
- src/Utilities/Compiler.CSharp/Lightup/SyntaxKindEx.cs
This appears to "resolve" the issue hit in https://github.com/dotnet/runtime/pull/100520 (failures after ingesting #7252)
The issue appears to be that this else block
https://github.com/dotnet/roslyn-analyzers/blob/e4d7ea6a967631713630cb1cf02efa7dfc35a8aa/src/NetAnalyzers/CSharp/Microsoft.NetCore.Analyzers/Performance/CSharpUseSearchValues.cs#L115-L120
is now being called with the [`@"\/"u8` expression](https://github.com/dotnet/runtime/blob/7def0b725852d55741262f43ed36ed501606f89f/src/libraries/Common/src/System/IO/PathInternal.Windows.cs#L58C71-L58C78).
While this condition will return `false` during the `IsConstantByteOrCharCollectionExpression` check, `semanticModel.GetOperation(expression)` intermittently fails when building `System.Formats.Tar` (consistently succeeds every second …
> Check for the CollectionExpression syntax kind early in UseSearchValuesAnalyzer

- azure-pipelines-microbuild.yml
Official build run: https://dnceng.visualstudio.com/internal/_build/results?buildId=2434167&view=results
> [8.0.1xx] Migrate official builds to 1ES template

- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/ImplementStandardExceptionConstructors.cs
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/AvoidMultipleEnumerations/AvoidMultipleEnumerationsHelpers.cs
- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/AvoidMultipleEnumerations/FlowAnalysis/GlobalFlowStateDictionaryAnalysis.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzer.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Security/SetHttpOnlyForHttpCookie.cs
- src/NetAnalyzers/Core/Microsoft.NetFramework.Analyzers/DoNotUseInsecureDtdProcessing.cs
- src/PerformanceSensitiveAnalyzers/PerformanceSensitiveAnalyzers.md
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/CopyAnalysis/SetCopyAbstractValuePredicateKind.cs
- src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/ParameterValidationAnalysis/ParameterValidationAnalysis.ParameterValidationDataFlowOperationVisitor.cs
- src/Utilities/Refactoring/AbstractRefactoringHelpers`3.cs
This is a small PR as requested in https://github.com/dotnet/roslyn-analyzers/pull/7226#issuecomment-2063873827.
> Fix some typos

- src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/CompareSymbolsCorrectlyAnalyzer.cs
- src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/Fixers/CompareSymbolsCorrectlyFix.cs
Fixes: https://github.com/dotnet/roslyn-analyzers/issues/4539
It turned out that despite `DiagnosticDescriptor` class is fully equatable, it isn't safe to compare instances in a codefix due to localized strings. For whatever reason all localizable strings in `diagnostic.Descriptor` are fixed strings while singleton descriptor instances in tha analyzer contain localizable resource strings, so the comparison could never succeed and thus fixes were not shown. I guess, this might be due to serialization-deserialization between devenv and roslyn OOP. To avoid that I made it so that diagnostics are now identified via `Rule` property, which is correctly passed between analyzer and a codefix provider. I've made a local setup where I verified, that this actually resolves the problem and the fix is …
> Avoid direct descriptor comparison, so the fix can be shown

- azure-pipelines-microbuild.yml
Adding a monthly run of the CI build to make sure all rel branches are buildable
> Monthly run of the CI build to make sure all rel branches are buildable

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/UseAsyncMethodInAsyncContext.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/UseAsyncMethodInAsyncContextTests.cs
- src/Utilities/Compiler/WellKnownTypeNames.cs
Affected analyzer: UseAsyncMethodInAsyncContext
Affected diagnostic IDs: [CA1849](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1849)
This PR suppresses CA1849 for calls to `SemaphoreSlim.Wait(0)`, `SemaphoreSlim.Wait(0, CancellationToken)`, `SemaphoreSlim.Wait(TimeSpan.Zero)` and `SemaphoreSlim.Wait(TimeSpan.Zero, CancellationToken)`.
Fixes #7271
> Prevent SemaphoreSlim.Wait(0) from triggering CA1849

- src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/Maintainability/AvoidUninstantiatedInternalClasses.cs
- src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/Maintainability/AvoidUninstantiatedInternalClassesTests.cs
Affected analyzer: AvoidUninstantiatedInternalClassesAnalyzer
Affected diagnostic ID: [CA1812](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1812)
This PR prevents an internal class which is instantiated via collection initializer to be marked as uninstantiated by the analyzer.
Fixes #7223
> Mark type as instantiated when used with a collection expression initializer

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/AvoidConstArrays.Fixer.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/AvoidConstArraysTests.cs
Affected analyzer: AvoidConstArraysAnalyzer
Affected diagnostic ID: [CA1861](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1861)
This PR ensures the `static readonly` field gets created when the code fix is applied.
Fixes #7216
> Generate field for const arrays in constructor declarations

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzer.cs
- src/NetAnalyzers/RulesMissingDocumentation.md
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzerTests.GuardedCallsTests.cs
Fixes issue @ManickaP encountered on https://github.com/dotnet/runtime/compare/main...ManickaP:runtime:quic-platform-guard?expand=1
Added unit test that reproes the issue
Repro:
```cs
[assembly: System.Runtime.Versioning.SupportedOSPlatform(""windows"")]
[assembly: System.Runtime.Versioning.SupportedOSPlatform(""linux"")]
[assembly: System.Runtime.Versioning.SupportedOSPlatform(""osx"")]
namespace System.Net.Quic;
public sealed partial class QuicConnection
{
[SupportedOSPlatformGuard("windows")]
[SupportedOSPlatformGuard("linux")]
[SupportedOSPlatformGuard("osx")]
public static bool IsSupported => false;
...
}
```
The Guard API used from another assembly, should not warn on `QuicConnection.IsSupported` invocation
```cs
namespace System.Net.Http;
internal sealed partial class …
```
> Do not warn when invoking APIs that has SupportedOSPlatformGuard attribute

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzer.cs
The NameAndParametersValid is executed for ALL methods in a class, independently of the methods being static and returning a boolean.
If you look carefully at the code, we have a || after a && therefore the NamedAndParametersValid is executed ALWAYS. This means that we are performing the check for EVEVERY method, rather than on those methods that are static and return a bool.
> Execute NameAndParametersValid only when needed.

- src/Test.Utilities/CSharpCodeFixVerifier`2.cs
- src/Test.Utilities/CSharpCodeRefactoringVerifier`1.cs
- src/Test.Utilities/CSharpSecurityCodeFixVerifier`2.cs
Adds [StringSyntax("C#-test")] to verifier classes to enable syntax highlighting for embedded C# code in visual studio.
Before:
After:
> Highlight C# code in unit tests

- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/DisposableFieldsShouldBeDisposedTests.cs
- src/Utilities/Compiler/Extensions/IMethodSymbolExtensions.cs
Follow-up to #6976
This PR fixes up CA2213 implementation to handle the following use case:
```cs
using System;
using System.Threading.Tasks;
class A : IAsyncDisposable
{
private readonly object disposedValueLock = new object();
private bool disposedValue;
private readonly Inner innerA;
public A() 
{
innerA = new Inner();
}
protected virtual async ValueTask DisposeCoreAsync()
{
lock (disposedValueLock)
{
if (disposedValue)
{
return;
}
disposedValue = true;
}
await innerA.DisposeAsync().ConfigureAwait(false);
}
public ValueTask DisposeAsync()
{
return default(ValueTask);
}
}
class B : A
{
private readonly object disposedValueLock = new object();
private bool disposedValue;
// Newly, we want to test that no diagnostic is reported on this line.
private readonly Inner innerB;  /* …
```
> CA2213: Handle overriden `DisposeCoreAsync` / `DisposeAsyncCore`

- azure-pipelines-microbuild.yml
Same as last year: https://github.com/dotnet/roslyn-analyzers/pull/6890
We need to temporarily switch the OneLocBuild MirrorBranch to point to the release/9.0.1xx branch to ensure all localization changes go there until we ship. This change will be reverted after we ship, so that we point to main again. We need to backport this to the [release/9.0.1xx](https://github.com/dotnet/roslyn-analyzers/tree/release/9.0.1xx) branch as well.
@mavasani @sharwell @cristianosuzuki77 @buyaa-n @ericstj @ViktorHofer
> Change localization branch to release/9.0.1xx temporarily

- eng/Versions.props
- src/NetAnalyzers/Microsoft.CodeAnalysis.NetAnalyzers.sarif
Similar to last year: https://github.com/dotnet/roslyn-analyzers/pull/6883/
> Bump main to 10.0

- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Security/DataSetDataTableInWebSerializableObjectGraphTests.cs
- src/Test.Utilities/CSharpCodeFixVerifier`2+Test.cs
- src/Test.Utilities/CSharpSecurityCodeFixVerifier`2+Test.cs
Workaround to address the failure in the official builds:
```
/mnt/vss/_work/1/s/src/Test.Utilities/CSharpSecurityCodeFixVerifier`2+Test.cs(24,21): error SYSLIB0014: 'ServicePointManager' is obsolete: 'WebRequest, HttpWebRequest, ServicePoint, and WebClient are obsolete. Use HttpClient instead. Settings on ServicePointManager no longer affect SslStream or HttpClient.' (https://aka.ms/dotnet-warnings/SYSLIB0014) [/mnt/vss/_work/1/s/src/Test.Utilities/Test.Utilities.csproj]
/mnt/vss/_work/1/s/src/Test.Utilities/CSharpSecurityCodeFixVerifier`2+Test.cs(29,21): error SYSLIB0014: 'ServicePointManager' is obsolete: 'WebRequest, HttpWebRequest, ServicePoint, and WebClient are obsolete. Use HttpClient instead. Settings on ServicePointManager no longer affect SslStream or HttpClient.' …
```
> Temporarily disable pragma SYSLIB0014 from CSharp CodeFix Verifiers

- src/NetAnalyzers/Core/AnalyzerReleases.Shipped.md
- src/NetAnalyzers/Core/AnalyzerReleases.Unshipped.md
Manually backported of https://github.com/dotnet/roslyn-analyzers/pull/7396 to release/9.0.1xx
Update AnalyzerReleases file to reflect new analyzers for .NET9 release same as in https://github.com/dotnet/roslyn-analyzers/pull/6940
CC @carlossanlop @jeffhandley
> [release/9.0.1xx]  Update AnalyzerReleases file to reflect new analyzers for .NET9 release

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/SpecifyIFormatProvider.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/SpecifyIFormatProviderTests.cs
Affected analyzer: SpecifyIFormatProviderAnalyzer
Affected diagnostic IDs: [CA1305](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1305)
This PR improves nullable support for CA1305. So far only nullable number types were analyzed, this is now extended to all nullables.
> Improve CA1305 for nullable types

- eng/GenerateAnalyzerNuspec.targets
- src/Roslyn.Diagnostics.Analyzers/CSharp/AnalyzerReleases.Unshipped.md
- src/Roslyn.Diagnostics.Analyzers/CSharp/CSharpDoNotUseDebugAssertForInterpolatedStrings.cs
- src/Roslyn.Diagnostics.Analyzers/CSharp/CSharpDoNotUseDebugAssertForInterpolatedStringsFixer.cs
- src/Roslyn.Diagnostics.Analyzers/Core/RoslynDiagnosticIds.cs
- src/Roslyn.Diagnostics.Analyzers/Core/RoslynDiagnosticsAnalyzersResources.resx
- src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.cs.xlf
- src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.de.xlf
- src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.es.xlf
- src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.fr.xlf
- src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.it.xlf
- src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.ja.xlf
- src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.ko.xlf
- src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.pl.xlf
- src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.pt-BR.xlf
- src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.ru.xlf
- src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.tr.xlf
- src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.zh-Hans.xlf
- src/Roslyn.Diagnostics.Analyzers/Core/xlf/RoslynDiagnosticsAnalyzersResources.zh-Hant.xlf
- src/Roslyn.Diagnostics.Analyzers/Roslyn.Diagnostics.Analyzers.md
- src/Roslyn.Diagnostics.Analyzers/Roslyn.Diagnostics.Analyzers.sarif
- src/Roslyn.Diagnostics.Analyzers/RulesMissingDocumentation.md
- src/Roslyn.Diagnostics.Analyzers/UnitTests/CSharpDoNotUseDebugAssertForInterpolatedStringsTests.cs
- src/Tools/GenerateDocumentationAndConfigFiles/Program.cs
- src/Utilities/Compiler/WellKnownTypeNames.cs
As @jaredpar found in https://github.com/dotnet/roslyn/pull/75163, interpolated strings in `Debug.Assert` can consume a surprising amount of memory. On modern .NET, this is fine; `Debug.Assert` has an interpolated string handler that will avoid the allocations if the assert isn't triggered. However, on our framework tests, this can be very bad and OOM our tests. So, this analyzer looks for cases where interpolated strings are passed to `Debug.Assert`, and recommends moving over to `RoslynDebug.Assert` instead, which is an interpolated string handler on all platforms. Note that I only did C# support, as there's no equivalent handler API for VB.
> Add an analyzer for Debug.Assert

- src/Microsoft.CodeAnalysis.Analyzers/Core/AnalyzerReleases.Unshipped.md
- src/Microsoft.CodeAnalysis.Analyzers/Core/CodeAnalysisDiagnosticsResources.resx
- src/Microsoft.CodeAnalysis.Analyzers/Core/DiagnosticIds.cs
- src/Microsoft.CodeAnalysis.Analyzers/Core/ImplementationIsObsoleteAnalyzer.cs
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.cs.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.de.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.es.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.fr.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.it.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.ja.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.ko.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.pl.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.pt-BR.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.ru.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.tr.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.zh-Hans.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.zh-Hant.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Microsoft.CodeAnalysis.Analyzers.md
- src/Microsoft.CodeAnalysis.Analyzers/Microsoft.CodeAnalysis.Analyzers.sarif
- src/Microsoft.CodeAnalysis.Analyzers/RulesMissingDocumentation.md
- src/Microsoft.CodeAnalysis.Analyzers/UnitTests/ImplementationIsObsoleteAnalyzerTests.cs
We're officially marking `ISourceGenerator` as deprecated, but we can't actually deprecate the interface, because it's used in several APIs like AnalyzerFileReference. So instead, we just add an analyzer to indicate that the interface should not be implemented. I've made this more general so we can do this with more interfaces in the future if necessary, based the implementation on InternalImplementationOnlyAnalyzer.
> Add new analyzer for deprecating implementing an interface

- src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/AnalysisEntity.cs
Rename or qualify `field` references in property accessors to avoid conflict with [`field` keyword](https://github.com/dotnet/csharplang/blob/main/proposals/field-keyword.md) in C# compiler preview.
Fixes https://github.com/dotnet/roslyn-analyzers/issues/7429
> Update field references

- src/NetAnalyzers/CSharp/Microsoft.NetCore.Analyzers/Performance/CSharpPreferHashDataOverComputeHash.Fixer.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Performance/PreferHashDataOverComputeHashTests.cs
fixes https://github.com/dotnet/roslyn-analyzers/issues/7320
@buyaa-n
> Fix CA1850 Fixer not accounting for toplevel syntax nodes

- src/Tools/Scripts/CopyAllResourceStrings.ps1
The last `| ForEach-Object { [System ... }` was not actually being included in the previous line. The `\`` will cause it to be included
> Fixed line break issue

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/DoNotCallEnumerableCastOrOfTypeWithIncompatibleTypesAnalyzer.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/DoNotCallEnumerableCastOrOfTypeWithIncompatibleTypesAnalyzerTests.cs
Fix for #7357.
#7183 changed the `CastWillAlwaysFail(ITypeSymbol castFrom, ITypeSymbol castTo)` to work with `castFrom.OriginalDefinition`/`castTo.OriginalDefinition`, eliding the generic type information in order to fix issues with interfaces, but that appears to have broken the check for class types. This reverts just the class type case to use the `castFrom`/`castTo` types passed in instead of the `.OriginalDefinition`. I'm not sure I quite understand why that's the only place this matters, but I tried a few variations with `struct`s and `interface`s and couldn't get any other false positives.
> Fix CA2021 false positive for generic class types

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/DoNotCallEnumerableCastOrOfTypeWithIncompatibleTypesAnalyzer.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/DoNotCallEnumerableCastOrOfTypeWithIncompatibleTypesAnalyzerTests.cs
Backport of #7488
Fix for #7357.
#7183 changed the `CastWillAlwaysFail(ITypeSymbol castFrom, ITypeSymbol castTo)` to work with `castFrom.OriginalDefinition`/`castTo.OriginalDefinition`, eliding the generic type information in order to fix issues with interfaces, but that appears to have broken the check for class types. This reverts just the class type case to use the `castFrom`/`castTo` types passed in instead of the `.OriginalDefinition`. I'm not sure I quite understand why that's the only place this matters, but I tried a few variations with `struct`s and `interface`s and couldn't get any other false positives.
> [Backport] Fix CA2021 false positive for generic class types

- src/Microsoft.CodeAnalysis.Analyzers/Core/AnalyzerReleases.Unshipped.md
- src/Microsoft.CodeAnalysis.Analyzers/Core/CodeAnalysisDiagnosticsResources.resx
- src/Microsoft.CodeAnalysis.Analyzers/Core/DiagnosticIds.cs
- src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/DoNotUseFileTypesForAnalyzersOrGenerators.cs
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.cs.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.de.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.es.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.fr.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.it.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.ja.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.ko.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.pl.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.pt-BR.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.ru.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.tr.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.zh-Hans.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Core/xlf/CodeAnalysisDiagnosticsResources.zh-Hant.xlf
- src/Microsoft.CodeAnalysis.Analyzers/Microsoft.CodeAnalysis.Analyzers.md
- src/Microsoft.CodeAnalysis.Analyzers/Microsoft.CodeAnalysis.Analyzers.sarif
- src/Microsoft.CodeAnalysis.Analyzers/RulesMissingDocumentation.md
- src/Microsoft.CodeAnalysis.Analyzers/UnitTests/MetaAnalyzers/DoNotUseFileLocalTypesForAnalyzersOrGeneratorsTests.cs
- src/NetAnalyzers/RulesMissingDocumentation.md
Inspired by https://github.com/dotnet/roslyn/discussions/76355. `file` types can cause errors on .NET Framework hosts, and we should just prevent these from being used. The purpose of `file` types is to not be visible outside the current file, and the purpose of analyzers is to be loaded by some other plugin system. These goals are mutually exclusive.
> Error when users use a `file` type for things we need to load

- PostReleaseActivities.md
The old instructions had an obsolete script that was not collecting all the changes between releases. Sometimes it was not collecting any.
I generated these release notes using these instructions:
- https://github.com/dotnet/roslyn-analyzers/releases/tag/7.0.3
- https://github.com/dotnet/roslyn-analyzers/releases/tag/7.0.4
- https://github.com/dotnet/roslyn-analyzers/releases/tag/8.0.0
- https://github.com/dotnet/roslyn-analyzers/releases/tag/9.0.0
> Update release notes instructions

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzer.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzerTests.GuardedCallsTests.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzerTests.cs
- src/Utilities/Compiler/Options/MSBuildPropertyOptionNames.cs
> Ensure that PlatformCompatibilityAnalyzer better handles various TFMs

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzer.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/InteropServices/PlatformCompatibilityAnalyzerTests.cs
This is follow up to https://github.com/dotnet/roslyn-analyzers/pull/7542 which ensures that our checks of `build_property.TargetFrameworkVersion` support no leading `v`, the same as the SDK allows.
> Trim leading v from TargetFrameworkVersion

- src/NetAnalyzers/CSharp/Microsoft.CodeAnalysis.CSharp.NetAnalyzers.csproj
- src/NetAnalyzers/VisualBasic/Microsoft.CodeAnalysis.VisualBasic.NetAnalyzers.vbproj
Follow-up on https://github.com/dotnet/roslyn-analyzers/commit/8bfe8b84962ceb734510a7524da27dc8d09f61e2
Partially unblocks https://github.com/dotnet/sdk/pull/47100
> Fix two more cases where the live CodeAnalysis version isn't used

- src/NetAnalyzers/CSharp/Microsoft.NetCore.Analyzers/Performance/CSharpUseStringMethodCharOverloadWithSingleCharacters.Fixer.cs
- src/NetAnalyzers/VisualBasic/Microsoft.NetCore.Analyzers/Performance/BasicUseStringMethodCharOverloadWithSingleCharacters.Fixer.vb
Fixes https://github.com/dotnet/roslyn-analyzers/issues/7588
The issue here is that we remove the implicit conversions that allowed `SyntaxList<SyntaxNode>` to convert to something like `SyntaxList<ArgumentSyntax>`.  Updating the code to just make a strongly typed list in the first place now.
> React to breaking api change

- global.json
Updated `xcopy-msbuild` in `global.json` to the latest available version on dotnet-eng
Updated vs to the [latest available version](https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-notes-v17.13)
I am raising this as I made the change in [aspnetcore](https://github.com/dotnet/aspnetcore) via https://github.com/dotnet/aspnetcore/pull/60666 and spotted this repository was using an older version of 17.x
> Update xcopy-msbuild and vs to latest available version

- src/PerformanceTests/Tests/PerformanceTests.csproj
This fixes build on FreeBSD as it started to have a RID since .NET 8
Suggested in https://github.com/dotnet/source-build/issues/5035#issuecomment-2794935476
> Switch the PerformanceTests project to net8.0

- eng/Version.Details.xml
- eng/Versions.props
- src/Tools/GenerateDocumentationAndConfigFilesForBrokenRuntime/GenerateDocumentationAndConfigFilesForBrokenRuntime.csproj
A direct dependency on System.Composition is not needed and actually causes issues when building a dev version of source build in the VMR:
```
/repos/dotnet/src/roslyn-analyzers/src/Tools/GenerateDocumentationAndConfigFilesForBrokenRuntime/GenerateDocumentationAndConfigFilesForBrokenRuntime.csproj error NU1605: Warning As Error: Detected package downgrade: System.Composition from 10.0.0-preview.4.25174.9 to 10.0.0-dev. Reference the package directly from the project to select a different version. 
GenerateDocumentationAndConfigFilesForBrokenRuntime -> Microsoft.CodeAnalysis 4.14.0-3.25179.1 -> System.Composition (>= 10.0.0-preview.4.25174.9) 
GenerateDocumentationAndConfigFilesForBrokenRuntime -> System.Composition (>= 10.0.0-dev) [/repos/dotnet/src/roslyn-analyzers/RoslynAnalyzers.sln] …
```
> Remove direct dependency on System.Composition

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/UseStringEqualsOverStringCompare.Fixer.cs
- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/UseStringEqualsOverStringCompare.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/UseStringEqualsOverStringCompareTests.cs
fixes https://github.com/dotnet/roslyn-analyzers/issues/6498
> CA2251: support for string.CompareOrdinal

- src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/AvoidConstArrays.cs
- src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/AvoidConstArraysTests.cs
The analyzer now ignores allocations of constant arrays in static properties and fields, as they are already only allocated once.
Fixes #7365
> Ignore inline static members, CA1861
